### ISSUE TITLE
"ssl network error" thrown during non-blocking sys.ssl.Socket handshake when compiled with -debug and -D HXCPP_M64 on Windows

### ISSUE THREAD

**Issue by joshtynjala** [HaxeFoundation/hxcpp#1033]
### Overview:

Example code:

```haxe
import haxe.Timer;
import haxe.io.Error;

class Main {
	static function main() {
		var socket = new sys.ssl.Socket();
		try {
			socket.setBlocking(false);
			socket.connect(new sys.net.Host("haxe.org"), 443);
		}
		catch (e:Dynamic) {}
		function tryHandshake():Void {
			var result = sys.net.Socket.select(null, [socket], null, 0);
			if (result.write[0] != socket) {
				Timer.delay(tryHandshake, 16);
				return;
			}
			try {
				socket.handshake();
			}
			catch (e:Error)
			{
				switch (e)
				{
					case Error.Blocked:
						Timer.delay(tryHandshake, 16);
					case Error.Custom(Error.Blocked):
						Timer.delay(tryHandshake, 16);
					default:
						trace("handshake failed 1: " + e);
				}
				return;
			}
			catch (e:Dynamic)
			{
				trace("handshake failed 2: " + e);
				return;
			}
			trace("handshake succeeded");
		}
		Timer.delay(tryHandshake, 16);
	}
}
```

Compile command:

```sh
haxe -cp src -main Main -debug -cpp out -D HXCPP_M64
```

If you remove one of `-debug` or `-D HXCPP_M64` (or both), the handshake completes successfully. If the socket is blocking, the handshake completes successfully.

I confirmed that it works correctly with all combinations on macOS.

### System info:

Haxe 4.2.5
hxcpp 4.2.1
Windows 11 Pro 22H2

**Comment by joshtynjala** [comment]
I tried updating to mbedtls-2.28.2 by checking out PR #1026, but, unfortunately, the bug still reproduces by throwing "ssl network error".

**Comment by joshtynjala** [comment]
It looks like this "ssl network error" is thrown by hxcpp (the `block_error` method in _SSL.cpp_) here:

https://github.com/HaxeFoundation/hxcpp/blob/3028724/src/hx/libs/ssl/SSL.cpp#L185-L194

I added this line for debugging purposes to see which value is returned by `WSAGetLastError`:

```cpp
printf("WSAGetLastError: %i\n", err);
```

Apparently, the value of `err` is `0`, which is odd.

**Comment by joshtynjala** [comment]
Now, this is interesting:

I tried adding a some code...

```cpp
if (r == -1) {
	printf("*** net_read: %i, %i\n", r, WSAGetLastError());
}
```

...immediately after the call to `recv` in the `net_read` method of _SSL.cpp_:

https://github.com/HaxeFoundation/hxcpp/blob/3028724/src/hx/libs/ssl/SSL.cpp#L237

It gives me this output:

```
*** net_read: -1, 10035
```

If I add move that code after the call to `hx::ExitGCFreeZone()` in the same method, I get this output instead:

```sh
*** net_read: -1, 0
```

So the code returned by `WSAGetLastError()` is getting lost before it is actually needed in `block_error`. 10035 is `WSAEWOULDBLOCK` — one of the values in `block_error` that should be allowed!

Is that enough investigation to allow someone who knows C++ better than I do to fix this bug?

**Comment by joshtynjala** [comment]
joshtynjala/hxcpp@1aafee5 is my attempt to implement a blocking check in similar manner to: HaxeFoundation/hashlink@a8cbcc5b9948c3d83c2a9944edaab8f4abb6da54

I can create a PR for this branch, or I can create a PR for my other branch from the previous comment. Please let me know.

**Comment by tobil4sk** [comment]
The solution with the static variable may cause problems when using multiple threads.

According to [the documentation](https://mbed-tls.readthedocs.io/projects/api/en/latest/api/file/ssl_8h/#_CPPv418mbedtls_ssl_send_t) for the `mbedtls_ssl_send_t` and `mbedtls_ssl_recv_t` callback types (i.e. net_write and net_read):
> If performing non-blocking I/O, MBEDTLS_ERR_SSL_WANT_WRITE must be returned when the operation would block.

and `MBEDTLS_ERR_SSL_WANT_READ` for the other callback. So the second patch seems like the correct solution to me.

**Comment by joshtynjala** [comment]
My client tried the second patch in their full app, and they reported that it worked well.

I created pull request #1036
