### ISSUE TITLE
PCRE2 requires C99 support

### ISSUE THREAD

**Issue by tobil4sk** [HaxeFoundation/hxcpp#1041]
This is from Lime's github actions android builds:

```
hxcpp/4,3,2/project/thirdparty/pcre2-10.42/src/pcre2_script_run.c:109:1: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
 for (int i = 0; i < FULL_MAPSIZE; i++) require_map[i] = 0;
 ^
note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
```

Seems like the new version of pcre from #1037 doesn't compile with older c standards.

It looks like this is why this commit was necessary? 27210f2160c1138cfde433ff2f384383928afa0d @hughsando 

Maybe we can set the flag only for the pcre sources? Otherwise, it requires adding the c99/c11 flag to the remaining toolchains.

**Comment by player-03** [comment]
I tried to build on my own machine. When I used android-toolchain-gcc.xml I got this error, but android-toolchain-clang.xml succeeded.

**Comment by hughsando** [comment]
-std=c99 on the toolchain breaks some other c code (SDL) .  I think -std=gnu99 might be best for all gcc based toolchains (android - others too?) without breaking anything.  Or -std=c99 on the PCRE flags only.  Not sure if windows will like this or not.

**Comment by player-03** [comment]
Adding the flag to the toolchain produces a huge number of "valid for C/ObjC but not for C++" warnings when compiling other libraries. Let's try the PCRE-specific approach.

**Comment by tobil4sk** [comment]
> Not sure if windows will like this or not

MSVC doesn't recognise the `-std=c99` flag, however, we don't need anything there anyway because the default MSVC C standard seems to support the for loop declaration.

I used the MSVC_VER to limit the usage to prevent it from being passed to msvc: #1042.

Could you see if the android build works with this patch in #1042? @player-03 

> Adding the flag to the toolchain produces a huge number of "valid for C/ObjC but not for C++"

If it's added to the toolchain, it should be added as a `cflag` so that it's only added to c source files. Perhaps you added it as a `cppflag` by mistake?

**Comment by Galactic00** [comment]
Having this same issue did you ever figure it out?

**Comment by tobil4sk** [comment]
> Having this same issue did you ever figure it out?

This is fixed in the git version of hxcpp but there hasn't been a new release to haxelib yet. You can install from git using:
```
haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
```

**Comment by Galactic00** [comment]
thanks but I already tried that. I specified more at https://github.com/openfl/lime/pull/1682
