### ISSUE TITLE
`__hxcpp_parse_int` parsing Hexadecimal string returns the wrong value

### ISSUE THREAD

**Issue by Paracosm-Daemon** [HaxeFoundation/hxcpp#1052]
I recently noticed this when I was working on a new feature for a mod I'm working on. Whenever entering any hex value, i.e `0xFF000000`, or `0xFF00FFFF`, or any hex value like that, it gives the same translucent white color, with a value of 2147483647 which is the limit for signed 32 bit integers.

I'm unsure why this happens; but my first assumptions are that it roots from commit d204bca99ddd51ba3ebcaa35643054512b31defa as I do not remember having these issues with the function before this commit, as replacing StdLibs.cpp with the file from b8248a719f45a1c3989f3d6c998c863724d18925 seems to have no issues.

To further reinforce the point above, using StdLibs.cpp from b8248a719f45a1c3989f3d6c998c863724d18925 returned the correct values for both colors I stated above as examples.

Here's what happens when trying to parse "0xFF000000" (`var color:String = "0xFF000000"`) and "0xFF00FFFF", with the int value itself and the parsed string:

![image](https://user-images.githubusercontent.com/98495978/234418197-814098e4-d66a-467b-b23d-8c53038ff16c.png)

Via commit b8248a719f45a1c3989f3d6c998c863724d18925:
0xFF000000
![image](https://user-images.githubusercontent.com/98495978/234422359-30eec98c-eb65-4700-8b43-4767bc83118c.png)
0xFF00FFFF
![image](https://user-images.githubusercontent.com/98495978/234421591-d5bdc4a6-d4e8-446c-b256-bba46615e62e.png)

Via commit d204bca99ddd51ba3ebcaa35643054512b31defa:
0xFF000000
![image](https://user-images.githubusercontent.com/98495978/234418308-533142f0-8681-4eb0-a4ec-a0dd8f285c9a.png)
0xFF00FFFF
![image](https://user-images.githubusercontent.com/98495978/234423875-69bba1be-8972-4a78-b69d-8cc1c0d2067e.png)

This shows that commit b8248a719f45a1c3989f3d6c998c863724d18925 prints the correct value but commits d204bca99ddd51ba3ebcaa35643054512b31defa and higher return 2147483647. I'm not the most well-versed in C++, so I cannot figure out why this happens myself, but I hope this is enough information to figure out and fix this issue.

Any help would be greatly appreciated.

**Comment by Aurel300** [comment]
@tobil4sk I think the `strtoul` (parse *unsigned* long) was there purposefully. From the [documentation for `strtol`](https://cplusplus.com/reference/cstdlib/strtol/):

> If the value read is out of the range of representable values by a long int, the function returns `LONG_MAX` or `LONG_MIN` (defined in [`<climits>`](https://cplusplus.com/climits)), and [`errno`](https://cplusplus.com/errno) is set to `ERANGE`.

**Comment by tobil4sk** [comment]
> @tobil4sk I think the strtoul (parse unsigned long) was there purposefully.

Yes, that makes sense. I guess the code from https://github.com/HaxeFoundation/hxcpp/commit/d204bca99ddd51ba3ebcaa35643054512b31defa will need to be amended to still manually check for the minus sign like it did before and use `strtoul`.

It means that hex and denary behaviour for overflows will be different again, but I guess keeping it as it was in older versions of hxcpp is probably better here.
