### ISSUE TITLE
Document how the C++ compilation process works

### ISSUE THREAD

**Issue by kud1ing** [HaxeFoundation/hxcpp#106]
This was send over here from https://github.com/HaxeFoundation/haxe/issues/3368

I can not seem to find documentation how the C++ backend compilation process works.
- on a Mac g++ is used. what do you need to do to call clang++?
- is it possible to find out how the C++ files are compiled, without using `haxe`? Maybe by using the generated XML file? I am thinking of tweaking the generated C++ files and using e.g. Xcode to compile, once the files are generated by Haxe.

**Comment by thomasuster** [comment]
Hey @kud1ing. I bet if you just edit the tool-chain file for the platform it should work. hxcpp/toolchain/mac-toolchain.xml look for g++ and try swapping for clang++. I think the best documentation for the build process right now is the source code. Try tweaking hxcpp/tools/hxcpp/BuildTool.hx and putting traces in that. For feature requests and/or support try the google group and IRC channel. http://haxe.org/community/community-support.html

**Comment by martinfinke** [comment]
Hey there @kud1ing. In recent Xcode versions, `g++` actually just calls `clang++`. Running `g++ -v` should confirm this with output like: `Apple LLVM version 6.0 (clang-600.0.57)`.

When I run `haxe` to compile something in the Terminal, it outputs all calls to `g++`. They have a lot of flags, but it should help you gain insight on what's going on.

[Running `haxe` with the `-no-compilation` flag](http://old.haxe.org/manual/tips_and_tricks) should only produce the .h/.cpp files without compiling them. You can then maybe compile them using Xcode, but I haven't tried this. I recommend this link, I found it recently and it cleared up a lot for me.

**Comment by hughsando** [comment]
There are quite a few docs in the 'docs' directory now.
