### ISSUE TITLE
wasm is not working with hxcpp

### ISSUE THREAD

**Issue by JonnycatMeow** [HaxeFoundation/hxcpp#1075]
i was trying to build this friday night funkin mod with emscripten but then i got an error when it was trying to compile. please can you fix it and i tried looking into one of the errors https://stackoverflow.com/questions/22197030/what-is-an-undeclared-identifier-error-and-how-do-i-fix-it
![Screen Shot 2023-11-19 at 8 53 21 AM](https://github.com/HaxeFoundation/hxcpp/assets/107599365/308864a8-709a-4f4f-b397-78d8d25d69da)

**Comment by Simn** [comment]
Please seek help in the FNF community.

**Comment by JonnycatMeow** [comment]
its not a "fnf community" thing its a hxcpp thing

**Comment by http-80** [comment]
It's related to https://github.com/HaxeFoundation/hxcpp/issues/867
