### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [HaxeFoundation/hxcpp#110]
I would like to point out that identifiers like "[```CppInt32__```](https://github.com/HaxeFoundation/hxcpp/blob/a74bfd4b4bddc1d4f0d5665ebcedde78e8cb8905/include/hxcpp.h#L182)" and "[```__Mark```](https://github.com/HaxeFoundation/hxcpp/blob/6cd0afab07142774dfe54d74e2427aa55e157daf/include/hx/Object.h#L72)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by hughsando** [comment]
I'm closing this one now - I will deal with any practical issues as they come up.
