### ISSUE TITLE
Magic metadata (@:headerCode) doesn't output for Abstract implementations.

### ISSUE THREAD

**Issue by jonathanhardie** [HaxeFoundation/hxcpp#114]
I have an abstract wrapping an extern type, which requires certain library headers included in the XXX_Impl_.h file.  Unfortunately it seems none of the magic metadata types generate any code for abstract implementations.  Latest git versions of hxcpp and haxe.

**Comment by underscorediscovery** [comment]
I think I also have this problem with `extern` classes.

**Comment by hughsando** [comment]
I have fixed the headerCode issue
@underscorediscovery, Extern classes are declared externally, so no headerCode is generated.  It should respect the '@:include' meta though.  Or are you taking about buildXml meta or some other meta.

**Comment by hughsando** [comment]
I'm closing this one since the abstracts are fixed. @underscorediscovery, if you want to open a new issue with an example of what you want from extern, please do.

**Comment by underscorediscovery** [comment]
I'll see if I can find the example, but I think what I needed was resolved at the time thanks.
