### ISSUE TITLE
Compilation makes Windows Defender think it's a virus

### ISSUE THREAD

**Issue by Danya20072019** [HaxeFoundation/hxcpp#1141]
When I compile the application, Windows Defender reports a virus and the application cannot continue to run.
It detects ```Trojan:Win32/Wacatac.B!ml```

In VirusTotal:

![image](https://github.com/user-attachments/assets/76d84512-5933-4214-8fd4-f1a424479310)

I really don't know how to solve this problem.

Here is my Haxelib Versions (I use these for application):
```Haxe: 4.3.6```
```HxCpp: 4.3.55```
```Lime: 8.1.3```
```OpenFl: 9.3.1```
```Flixel: 5.8.0```

**Comment by Danya20072019** [comment]
So I resolve this problem

**Comment by moxie-coder** [comment]
> So I resolve this problem

can you say how you solved it for others with the same issue?
