### ISSUE TITLE
Error when compiling via git. [Unknown compiler option "asmExe"]

### ISSUE THREAD

**Issue by sillycodergirl** [HaxeFoundation/hxcpp#1142]
Hello

I updated my hxcpp to git, and then it started giving the following error:
`Unknown compiler option "asmExe"`

The issue was fixed when i swapped of git and to 4.3.2 and after comparing the files for any "asmExe" mention, there was no mention of asmExe but in git there was.

![image](https://github.com/user-attachments/assets/4bb84e61-f787-44a5-988f-1051a549d237)
![image](https://github.com/user-attachments/assets/346d96e3-7c11-4d40-a110-50559e0feede)

**Comment by hughsando** [comment]
After updating from git, sometimes you need to recompile the 'hxcpp.n' file by running "haxe compile.hxml" in the tools/hxcpp directory.  I have a mechanism to alert the programmer to this, which I have activated for this change.
