### ISSUE TITLE
Cross-compiler support

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/hxcpp#115]
What would be needed to add cross-compiler toolchains?
I've been able to cross compile from Linux to iOs by overriding the CC, CXX, HXCPP_AR and HXCPP_RANLIB env vars. However there are still some defines (e.g. HXCPP_LINUX) that get added automatically. What would be the best way to tackle this? I can provide a patch when I get it working.

Also - is adding new toolchains through haxelib already working?

**Comment by jcward** [comment]
@waneck - it's been a few months, any updates on the status of cross compiling?

**Comment by hughsando** [comment]
I'm going to close this one now, but happy to discuss details if someone wants to try something again.
