### ISSUE TITLE
#define IMMIX_ALLOC_SIZE_SHIFT 6, but should be 8?

### ISSUE THREAD

**Issue by jerry1aa** [HaxeFoundation/hxcpp#1155]
#define IMMIX_ALLOC_SIZE_SHIFT 6
and in immix.cpp
#define IMMIX_ALLOC_SIZE_MASK 0x000fff00

Then, the following code uses these two values to calculate size.
size = (header & IMMIX_ALLOC_SIZE_MASK) >> IMMIX_ALLOC_SIZE_SHIFT;
From this code, It seems 0x000fff00 shift right should be 8.
So, IMMIX_ALLOC_SIZE_SHIFT is should be 8?

**Comment by hughsando** [comment]
The last 2 bits should be 0, since allocations are always on a 4-byte boundary.
Space in the header is at a premium, so can't afford to have 2 bits sitting around doing nothing.
