### ISSUE TITLE
Inconsistent method call semantics through getter of extern class

### ISSUE THREAD

**Issue by cbatson** [HaxeFoundation/hxcpp#116]
Given this definition:

	extern class Dummy
	{
		static var getter(get, never) : Dummy;
		function method() : Void;
	}

(A) A usage of the form

	Dummy.getter.method();

results in this generated C++:

	::Dummy_obj::get_getter()->__Field(HX_CSTRING("method"),true)();

(B) A usage of the form

	var d = Dummy.getter;
	d.method();

results in this generated C++:

	Dummy d = ::Dummy_obj::get_getter();
	d->method();

If the definition of `Dummy` is well-formed, I would expect both (A) and (B) to generate semantically equivalent code output.

Hint: Adding `static function get_getter() : Dummy` to the definition of `Dummy` leads to semantically equivalent generated code.

**Comment by hughsando** [comment]
This seems to be working now.  Is this solved for you?
