### ISSUE TITLE
Executing something after main()

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#121]
I have a problem trying to run the same code in both C++ and Flash/JS.
I found that what I actually want to do is either to start the C++ window event loop BEFORE or AFTER the main() function has been executed, in order to get the same behavior on all platforms. Is there a way to be able to trigger code execution at this time ?

PS : I'm using a standard Haxe setup, without NME tool, so I'm compiling with `-main MyGame`, not generating an NME Application etc.

**Comment by hughsando** [comment]
Can we use the answer "There is a macro for that" and close this one?

**Comment by ncannasse** [comment]
Not exactly, but I'll review that when I work on haxe "main loop"
