### ISSUE TITLE
No viable conversion from 'hx::AnyCast' to 'Dynamic'

### ISSUE THREAD

**Issue by dpeek** [HaxeFoundation/hxcpp#124]
When compiling with `haxe:development` and `hxcpp:master` I'm getting the following error:

```
Error: ./src/cpp/Lib.cpp:49:11: error: no viable conversion from 'hx::AnyCast' to 'Dynamic'
                Dynamic _g = ::__hxcpp_cast_get_proc_address(lib,(prim + HX_CSTRING("__prime")),quietFail);             HX_STACK_VAR(_g,"_g");
                        ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Because the `AnyCast` returned by this RTTI helper in `StdLibs.h`:

```
inline hx::AnyCast __hxcpp_cast_get_proc_address(String inLib, String inPrim,bool inQuietFail=false)
{
   return hx::AnyCast(__hxcpp_get_proc_address(inLib,inPrim,false,inQuietFail));
}
```

Can't be converted to `Dynamic`. The call is generated by this line in `cpp.Lib._loadPrime`:

```
var factory:Function< RawConstPointer<Char> -> RawPointer<Object> > = getProcAddress(lib, prim + "__prime", quietFail);
```

I've got the latest from Haxe and Hxcpp, and I've rebuilt the libs without problem. Still, it's possible that something is out of sync :)

**Comment by hughsando** [comment]
I think this is working now.  If you have a specific case that is not working you can reopen the issue.
