### ISSUE TITLE
val_iter_fields inconsistent between Neko and Cpp - breaking

### ISSUE THREAD

**Issue by PDeveloper** [HaxeFoundation/hxcpp#125]
`val_iter_fields(v, haxe_iter_object, l);`
gets passed a function to iterate:
`void haxe_iter_object(value val, field f, void *state)`

on Neko, val will be the value of the current field that it's iterating on.
on Cpp, `val == v`, and `value _v = val_field(val, val_id(val_string(val_field_name(f))));` is the value of the current field that it's iterating on.

So on Neko, the function gets passed the current field value, while on Cpp, the function gets passed the object it's iterating on.

**Comment by hughsando** [comment]
Should be fixed. Thanks for reporting.

**Comment by kevinresol** [comment]
Does this mean now cpp follow neko? i.e. the iterator function receives the field value instead of the object itself?

**Comment by hughsando** [comment]
Yes it does, but I guess there could be an issue here if you do not know
which version of the hxcpp runtime your ndll is connected to.
I think I will add a new function (val_iter_field_val) which is consistent
with neko, and return the old function to its original meaning (different
on hxcpp and neko).

**Comment by kevinresol** [comment]
Why would you want a function to be inconsistent between hxcpp and neko? Is it just for backward compatibility?
 
Could the problem be solved by some compile time version check (such as the dependencies version in haxelib.json)?

8c1f1b56716ce3d9605ed28a0dcaebd3d257f6be, does `val_iter_field_vals` work on neko?

**Comment by hughsando** [comment]
I'm not sure if anyone is actually using this, so maybe I could just reuse
the name.  But lets say there is a library implementer that is using the
old version on cpp and expects a certain behaviour.
And a developer is using the library.  The developer upgrades haxe and now
the code crashes.
Basically, the old version is now deprecated, no ones old code is going to
crash and everyone new code will work on neko too.
To keep the function name and change the return value, the application code
would need to know the intention of the library developer - not sure if
this is possible.
I could possibly just remove the old cffi function and the library
developer would get a compile error, fix the problem and move forward, and
still no crashes.
