### ISSUE TITLE
SIMD support

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#126]
I'm not sure how much @hughsando have been thinking about adding SIMD support, but that would be interesting to have.

Today Mozilla has released SIMD.js which is an API that will get JIT'ed with SIMD instructions.

https://hacks.mozilla.org/2014/10/introducing-simd-js/

I think we could follow the same API in Haxe/C++ so it does produce SIMD instructions that gets compiled. 

For GCC : https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html
For MSVC : http://msdn.microsoft.com/en-us/library/708ya3be(v=vs.90).aspx

**Comment by hughsando** [comment]
I'm closing this one now.  I think the native tools are at a point where this can be developed as part of a haxelib and then added to hxcpp if appropriate.  The only thing that might be needed is a 128-bit aligned GC alloc.  I can look at adding this if there is sufficient interest.
