### ISSUE TITLE
Multiplication assignment(*=) and Addition assignment(+=) do not work for lime's typed arrays

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#136]
These operators don't work correctly on hxcpp, as they causes compile time errors on Visual C++.

// mRawData is lime's Float32Array
mRawData[offset]        += deltaX;
...
mRawData[Std.int(offset + i*ELEMENTS_PER_VERTEX)] *= factor;

https://github.com/vroad/starling-openfl/commit/a44bc99e97801b3310bd8140678d947bdcb186ff

**Comment by vroad** [comment]
This code will also cause error C2679 on VS2013.
```
package ;

class SomeClass implements ArrayAccess<Float>
{
    @:noCompletion private var __arr:Array<Float>;
    public function new()
    {
    }
    
    @:keep public inline function __get(pos:Int):Float
    {
        return __arr[pos];
    }
    
    @:keep public function __set(pos:Int, v:Float):Float
    {
        return __arr[pos] = v;
    }
}

class Main 
{
	
	static function main() 
	{
	    var val:SomeClass = new SomeClass();
        val[0] = 2.0;
        val[0] *= 3.0;
        trace(val[0]);
	}
	
}
```

**Comment by Simn** [comment]
Thanks, I can reproduce the error with that.

**Comment by Simn** [comment]
@hughsando: Should this work? I'm not sure about the implications of `implements ArrayAccess<Float>` and how it relates to `__get` and `__set` for hxcpp.
