### ISSUE TITLE
__unsafe_get slower than get

### ISSUE THREAD

**Issue by eliasku** [HaxeFoundation/hxcpp#145]
you can see code here: https://github.com/eliasku/horror/blob/master/tests/benchmarks/HxcppArrayBenchmark.hx

```
Benchmark.hx:26: [Benchmark] Node-array read : 0.7629394531 ms
Benchmark.hx:26: [Benchmark] Node-array read unsafe : 3.946065903 ms
Benchmark.hx:26: [Benchmark] Int-array read : 0.0009536743164 ms
Benchmark.hx:26: [Benchmark] Int-array read unsafe : 0.0009536743164 ms
```
See, problem only when getting Object (Array<::Dynamic> is produced), not primitive type which Array<int> is used.

I think this cuz of missing StaticCast<Node> in generated cpp when using __unsafe_get:
this `::_HxcppArrayBenchmark::Node node = this->array->__get(i).StaticCast< ::_HxcppArrayBenchmark::Node >();` faster than this `::_HxcppArrayBenchmark::Node node = this->array->__unsafe_get(i);`

I don't know why. Please explain or help :)

**Comment by Simn** [comment]
@eliasku: Your benchmark is no longer available, can you upload it again?

**Comment by eliasku** [comment]
I've updated the link: https://github.com/eliasku/horror/blob/master/tests/benchmarks/HxcppArrayBenchmark.hx

**Comment by Simn** [comment]
@hughsando: Should we add `function __unsafe_get(i:Int):T;` to Array.hx (only for cpp) so we get proper types in the AST?

```
[Var _g5(274):_Main.Node]
	[Call:_Main.Node]
		[Field:i : Int -> _Main.Node]
			[Local _g3(272):Array<_Main.Node>]
			[FInstance:i : Int -> _Main.Node]
				Array<_Main.Node>
				__unsafe_get
		[Local _g4(273):Int]
```

This is much better than the `untyped` version which has FDynamic fields and some unknown types because of that.

**Comment by Simn** [comment]
By the way, what's the reason for using `::Dynamic` for all non-numeric/String/interface types?

**Comment by underscorediscovery** [comment]
This looks like a good direction Simn
