### ISSUE TITLE
hxcpp : -D static_link not working for android target

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/hxcpp#147]
Even when passing -D static_link to haxe / hxcpp a .so is generated on the android target.

Test.hx
```haxe
class Test{
	public static function main() : Void{
		trace("hello");
	}
}
```

build.hxml:
```
-main Test
-cpp lib
-D static_link
-D android
```

**Comment by wighawag** [comment]
any idea?

**Comment by hughsando** [comment]
This should be fixed now.  Use static_link if you want to create a library, or exe_link if you want to create and executable.

**Comment by wighawag** [comment]
cool, tested and it works. thanks
