### ISSUE TITLE
Isn't mscv typo of msvc?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#153]
https://github.com/HaxeFoundation/hxcpp/blob/467c894520a67be9c1af8a8d59a0c6d16b4046c1/toolchain/msvc-toolchain.xml
https://github.com/HaxeFoundation/hxcpp/blob/532041fabd4903a440b4991f634336d5d25c7818/tools/hxcpp/Setup.hx

**Comment by Simn** [comment]
Microsoft curriculum vitae!

Sure looks like a typo.
