### ISSUE TITLE
Definition of Class in global namespace conflicts with Apple definition

### ISSUE THREAD

**Issue by cbatson** [HaxeFoundation/hxcpp#155]
The definition of `Class` in the global namespace (in `hxcpp.h` and `Class.h`) conflicts with a global definition of the same name in Apple's `objc.h` which is widely included by Apple framework headers for iOS:

``` c
/// An opaque type that represents an Objective-C class.
typedef struct objc_class *Class;
```

This makes it quite challenging to use `hxcpp.h` and an iOS header in the same source file.  It's possible, but cumbersome, to work around this by segregating iOS and hxcpp code into separate source files.

Ideally hxcpp will not define `Class` in the global namespace.  I have briefly explored this option, but I'd need to spend much more time in the compiler code, as generating the correct reference in all cases appears to be non-trivial.

See also https://github.com/HaxeFoundation/hxcpp/pull/151 for an aborted attempt at a different workaround.

**Comment by hughsando** [comment]
This should be fixed now.  If you use the latest haxe compiler, you can also use ```-D file_extension="mm"``` to generate objc++ code.
