### ISSUE TITLE
Android Performance Down

### ISSUE THREAD

**Issue by starburst997** [HaxeFoundation/hxcpp#156]
I am not sure why, but since this commit https://github.com/HaxeFoundation/hxcpp/commit/5a309697f1fe803053f2ad930a899ff595227671 my game (using OpenFL and Nape) has been having some stuttering / lag spikes that makes it unplayable on a Android HTC Desire HD (2010) whereas it was running at a silky smooth 60 FPS before. Using hxcpp version 3.1.39 or using GIT with the commit just before everything is fine.

**Comment by starburst997** [comment]
Ttried the git version, this is definitely a major improvement and seems on par with 3.1.39. Thanks!

**Comment by Simn** [comment]
(I got scared there for a second...)
