### ISSUE TITLE
function StringTools.startsWith / endsWith has substr() in it...

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#161]
@hughsando 
I strictly do not understand all the string magic underneath, but I have a feeling that it can end up with subotpimal performances for runtime lookups and extra unwanted allocations.

Can you schedule a fact checking pass and instruct me as the flow, here ?

Thanks !

**Comment by hughsando** [comment]
Yep, that looks sub-optimal.  Substr will allocate a string.  The fix would be to add these function to the hxStrring.h as native function and use 'untyped' to access them.

**Comment by delahee** [comment]
Ok can you please schedule it ?

No need to hurry but I know for sure that i wil waste many time and that
you will rewrite my patch anyway :D

Bisous !

2015-01-19 11:23 GMT+01:00 Hugh Sanderson <notifications@github.com>:

> Yep, that looks sub-optimal. Substr will allocate a string. The fix would
> be to add these function to the hxStrring.h as native function and use
> 'untyped' to access them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxcpp/issues/161#issuecomment-70472299>
> .
>



-- 
David Elahee

**Comment by hughsando** [comment]
Managed to fix it with pure haxe code in the haxe compiler StringTools.hx.

**Comment by delahee** [comment]
Nice thank you.
Le 21 janv. 2015 06:51, "Hugh Sanderson" <notifications@github.com> a écrit
:
