### ISSUE TITLE
HXCPP_API_LEVEL confusion

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#163]
Hi Hugh,

What is the source of the API level for hxcpp?
@waneck and I were discussing it, we understand the purpose of the define. 

This define allows newer haxe generated code (i.e git haxe) to run against prior versions of hxcpp (i.e 3.1.39 will still work against it).

At least, that seems to be the goal?

Now the question is, what is the value from?
"313" is ambiguous because of haxe 3.1.3 aligned with hxcpp 3.1.39,
Currently hxcpp is at 3.1.48, does that make the `HXCPP_API_LEVEL=314` ?

i.e to determine the correct API level automatically, 
the haxelib.json version can be used like this:

 `ver.replace('.','').substr(0,3)` ?

Or is this misguided, and it comes from elsewhere?

**Comment by hughsando** [comment]
The haxe compiler defines this symbol, and hxcpp must be able to deal with it.
The value will be incremented as I add features to gencpp.ml and therefore bound to a git commit, and is unrelated to the haxelib.json version.  This allows anyone using any release or any "overnight" version of haxe to work with the latest hxcpp, regardless of how Nicolas or anyone else decides to name the particular version.
The latest change was to change type of the last parameter passed to the "__Field" function.  The new compiler creates code that is not compatible with old versions of hxcpp.  However, I maintain that the latest version of hxcpp should work with all practical versions of haxe to avoid "version hell", so simultaneous with the breaking change, I bump the hxcpp_api_level, and then switch on this in hxcpp.
You can consider the resemblance to the haxe version coincidental, although I will bump it to 32x if I need to make a change after 3.2 release.
You can get the value directly from the compiler via this PrintHxcppApi.hx script:
```
import haxe.macro.Context;
class PrintHxcppApi
{
   macro public static function getApiVersion() return  Context.makeExpr( Context.definedValue("hxcpp_api_level"), Context.currentPos() );

   public static function main() Sys.println( getApiVersion() );
}
```

and then:
```haxe -main PrintHxcppApi.hx --interp```

Which will be linked to the particular verison of haxe, as desired.

**Comment by underscorediscovery** [comment]
Thanks @hughsando, that clarifies the details on how it works, but it still means that the `haxe compiler define` of the symbol needs to be set - _does the haxe compiler set this itself_ in newer versions (newer than 3.1.3)? For example, without the *build* toolchain (i.e flow, lime) setting that value to something, it appears to arrive as 0/blank in the HXCPP build side - is this expected?

If haxe compiler is defining the value according to itself, then we/the user does not have to set anything for it at all - right?

**Comment by hughsando** [comment]
Yes, if you think of it as the "version of haxe generated code", and you do
not use haxe generated code, then it does not matter what you set it to.
If you somehow interact directly with the hxcpp "Object" class (say, by
including hxcpp.h), then you will need to match the value with the users
code.  "Directly" does not mean cffi, because this isolates the
implementation details.

**Comment by underscorediscovery** [comment]
Back again!

I think there is still a problem with this define, there is [this PR](https://github.com/HaxeFoundation/haxe/pull/3813) that exposes one issue, but this only affects builds from haxe.

Take for example the following use cases which are common:
extensions/build.xml
lime/project/build.xml => ndll
snow/project/build.xml => ndll

** Problem 1: **

To build these, the regular run tool is used, the following steps occur:

- `haxelib run hxcpp build.xml`
- `HXCPP_API_LEVEL=0` on c++ files
- **there is no haxe compiler step**, haxe cannot define this value for hxcpp builds!
- user app builds regularly, from haxe, `HXCPP_API_LEVEL=313`
- user app using the ndll get's linker errors from missing symbols in hxcpp headers

Problem 2:
The details of the HXCPP_API_LEVEL are embedded in the ndll/library
- `haxelib run hxcpp build.xml -Dhxcpp_api_level=313`
- user app builds with the define from haxe, all is well
- user on haxe 3.1.3 release links against ndll/library, what now?

Does this mean libraries will require a separate prebuilt binary for every api level change to maintain backward compatibility? Does it mean that the person building an extension/library must know the api level _from the haxe compiler_ when not using it at all?

I think the flag is a good way to have new builds work against older haxe, but it breaks the other way around.  To have an entire framework (like waxe, snow, lime etc) require the end user to have every dependency before they can use the _end_ product of the builds is not an option. I also don't think that per-api level binaries is a good idea either...

cc @waneck

**Comment by underscorediscovery** [comment]
**You can disregard the above.** 
I think.

After working through it a bit and trying from blank slate, it does appear that whatever was happening is not what I thought. It seems (as @jgranick has reminded me) that the defines reside in haxe application land code specifically and as long as the application code has the right define (automatically from haxe) things are fine.

I tested again, and it worked, so the 2+ reports I got from it and my own multiple times running into `PropertyAccess` and `paccDynamic` linker or compiler errors were false flags.

**Comment by Simn** [comment]
For what it's worth I'm currently getting this when compiling the Haxe cpp unit tests with the `-D analyzer` being removed from compile-each.hxml:

```
./src/Reflect.cpp(477) : error C2664: 'Dynamic hx::Object::__Field(const String &,hx::PropertyAccess)' : cannot convert argument 2 from 'Dynamic' to 'hx::PropertyAccess'
        No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
```

**Comment by hughsando** [comment]
There was a bit of a problem related to case, which you may have been seeing.
The haxe-generated build.xml has upper-case HXCPP_API_LEVEL, and the haxe command defines the lower-case version.  Which means you could not later use the generated build.xml without haxe.
This has been fixed now to respect the define first, and fallback the the build.xml one if required.
But still, should not matter unless you are using generated code.

@Simn, I think the issues was fixed then the __cpp__ calls were not put in tmp variables.

**Comment by underscorediscovery** [comment]
Was that fixed directly in the repos? And if so can I close this PR I sent when I found that to be the case?

https://github.com/HaxeFoundation/haxe/pull/3813

**Comment by hughsando** [comment]
Yes, I took a slightly different approach to allow haxe to take priority,
with fallback to build.xml.  Close this if you are happy with:
https://github.com/HaxeFoundation/hxcpp/commit/672d5a62f25bd810993f18583e44a2eb8e24c60d

**Comment by underscorediscovery** [comment]
I'm happy with that if it fixes the issue :+1:
