### ISSUE TITLE
The run script catches unrelated errors, and prints that HXCPP should be rebuilt

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#164]
I just ran into an issue, where HXCPP was having an error, since it expected (like normal) a stack of files to compile, but for the particular target, there actually were no files to speak of:

https://github.com/HaxeFoundation/hxcpp/commit/2444f40e5d15d56191b1e1fe42d4b0092237bf36

This is resolved, but I noticed that on release versions of HXCPP, instead of having an error out from the tools, it instead prompted that it was a dev version of HXCPP, and needed to be rebuilt. I believe this may be due to how the errors are being caught in the run script.

I'm not sure how you would like to handle this, but it could lead to red herrings when actually another problem is going on within otherwise normal tools. This problem is solved, but there could be some other scenario where we run into an error with the tools.

Thanks and have a great day :smile:

**Comment by Justinfront** [comment]
Glad Joshua posted this. This is indeed very very confusing, and the fact that I could not get it rebuilding ended up leading to further fustration.

**Comment by underscorediscovery** [comment]
It also errors if you do something in a @:buildXML or build.xml that it doesn't like,

```xml
<target id="haxe"> 
 <vflag name="-compilerflag" />
</target>
```

This throws errors about a development version of hxcpp (on stable releases):
The error is unrelated, `value` is required for vflag (that could be fixed, but the problem remains)
 
```xml
<target id="haxe"> 
 <vflag name="-compilerflag" value="" />
</target>
```

**Comment by hughsando** [comment]
So I think this should be fixed - there is no "catch" in the run.n script
any more.  Maybe something needs updating.  Try with setenv HXCPP_VERBOSE
to see if you get any better information.
