### ISSUE TITLE
Socket.select on Windows

### ISSUE THREAD

**Issue by mbrezu** [HaxeFoundation/hxcpp#165]
Hello,

I have some code where `Socket.select` returns a socket in the 'read' list, but then reading from the socket with `socket.input.readBytes` returns 0. Same code works fine if compiled for the neko platform (socket is not returned in the 'read' list).

The socket is non-blocking and has a timeout of 2 seconds.

The code in question is called from https://github.com/mbrezu/napetest/blob/master/Source/me/mbrezu/hxmp/Utils.hx, line 81.

`haxelib list` returns:

```
actuate: 1.7.5 1.8.0 [1.8.1]
HIDE: [0.4.7]
hxcpp: 3.1.39 [3.1.48]
lime-tools: [1.5.7]
lime: 1.0.1 2.0.4 2.0.5 [2.0.6]
nape: [2.0.16]
node-webkit: [1.0.7]
openfl-samples: 1.3.0 2.2.0 [2.2.1]
openfl: 2.0.1 2.2.1 2.2.3 [2.2.4]
```

Thanks,
Miron

**Comment by hughsando** [comment]
There does not seem to be much difference between the neko and the cpp implementation.
Is it possible that the first read gets some bytes (but not all), then it goes again - without the select - and gets 0 byes the second time?  Or does it get no bytes at all after the select.

**Comment by mbrezu** [comment]
The sequence I consider broken is: 1) call select, get a socket ready for reading and then immediately 2) read from the socket and get 0 bytes. On neko, select doesn't seem to return the socket as 'ready to read' if nothing can be read from it.

**Comment by hughsando** [comment]
This socket code has changed quite a bit, so I'm going to close this one.
