### ISSUE TITLE
FPHelper for cpp

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#166]
Now that `haxe.io.FPHelper` has been merged, it would be good to review cpp implementation to see if more performances can be added there.

**Comment by ncannasse** [comment]
PS : we need this to ensure thread safety as well (there should be not need for a static helper)

**Comment by hughsando** [comment]
So this should be optimised now, but I think the doubleToI64 should take an optional buffer:
```
public static function doubleToI64( v : Float, ?buffer:Int64 ) : Int64  {
   ....
   var i64 = buffer==null ? tmpI64 : buffer;
```
Not only will this add optional (if you care about it) thread safety, but also reuse-safety:
```
var result = doubleToI64( d0, new Int64() ) + doubleToI64( d1, new Int64() ) + ....
```
Plus other recycling patterns, while also working in the "easy to write" case.

**Comment by ncannasse** [comment]
@hughsando the problem is that on platforms that have native int64 basic type, this will create a null boxing around the int64. I think it's better to add native (immutable) int64 to hxcpp here.

**Comment by hughsando** [comment]
Yes, that would be a better idea.
I'm still struggling with the requirements with Dynamic.
For example, adding an Int + a Dynamic, where the Dynamic is Int64 should
give an Int64 Dynamic - or only if the result is big enough.  And then, can
you use this Dynamic as an Index into an Array, and then I need to upgrade
the Array length to Int64?  Or throw "Out of Bounds", or silently truncate
the bits.  Maybe this has performance implications (on Arm?) or maybe it is
a good idea.

As an "Object", the Int64 fits well with Dynamic, but as a value, it needs
special treatment.  And it also invalidates the way I do Dynamic
arithmetic, which is to "just upgrade to double (float64)", which will
become inaccurate.

The actual storage does not seem too hard.
