### ISSUE TITLE
Thread not switching back

### ISSUE THREAD

**Issue by juakob** [HaxeFoundation/hxcpp#171]
When you run an infinite loop or a blocking function the active threads never switches between the other threads.

OpenFl example, the code runs fine in neko but it get stuck, unresponsive on cpp(windows) in the infinite loop
		package;
		#if cpp
		import cpp.vm.Thread;
		#elseif neko
		import neko.vm.Thread;
		#end
		import openfl.display.Sprite;

		class ThreadTest extends Sprite
		{

			public function new() 
			{
				super();
				Thread.create(infinitLoop);
				Thread.create(infinitLoop2);
			}
			
			function infinitLoop():Void
			{
				var counter:Int=0;
				while (true)
				{
					++counter;
				}
			}
			function infinitLoop2() 
			{
				var s = new sys.net.Socket();
					s.connect(new sys.net.Host("localhost"),5000);
				while (true)
				{
					s.input.readLine();
				}
			}
			
		}

**Comment by R32** [comment]
maybe the current main thread is exiting

**Comment by juakob** [comment]
Hi R32, I don't think the problem is that the main thread exits because the OpenFL app gets unresponsive.
Still I thought about what you said so I made an example without using openfl

        static function main() 
	{
		//Thread.create(infinitLoop);
          //Thread.create(infinitLoop2);
		 while (true)
		 {
			
		 }
	}
	static function infinitLoop():Void
        {
            var counter:Int=0;
            while (true)
            {
                ++counter;
            }
        }
       static function infinitLoop2() 
        {
            var s = new sys.net.Socket();
                s.bind(new sys.net.Host("localhost"),5000);
            while (true)
            {
                s.input.readLine();
            }
			
        }

And it runs as expected, so the problem must be in the interactions of the threads inside OpenFl. I know now that the second thread dosen't even runs once, because I made the mistake of using connect instead of bind.
So probably the error is inside OpenFL, so I will submit the issue to OpenFl.

Thank you R32,

**Comment by juakob** [comment]
Pleas close the issue

**Comment by hughsando** [comment]
There can actually be an issue with the code as written.  If one thread does not make a Gc call (eg, "new", or one of the system-blocking calls, like "bind", "readLine" etc), then the other threads can stall waiting to the thread to "check in".
Generally, it should be safe to sit in any of the blocking calls, but not "while(true) ;".  To make this safe, you need to either call "Gc.enterGCFreeZone", then do all you non-allocating calls, and then call Gc.exitGCFreeZone", or periodically call Gc.safePoint from within your loop.
If it is one of the system blocking calls that creates the problem, then this is a bug.

**Comment by juakob** [comment]
Thank you hughsando, as you said the problem disappears when I call Gc.safePoint in OpenFl in the while(true) loop. 
My other problem whit a blocking function was solved by using Gc.enterGCFreeZone and exit zone. 

Im using hxudp(https://github.com/andyli/hxudp), it implements the UDP protocol for haxe( UdpSocket is not currently implemented for cpp) using .ndll. The lib offers a  recive()  function to read data that arrives. When I run it in a thread inside OpenFl the app just stops working, but after adding the Gc methods the app continues working.

Thank you again hughsando, after discovering that UdpSocket was not implemented in cpp and that I couldn't run infinite threads inside OpenFl, I was a little down. 
But you made my day =)

**Comment by hughsando** [comment]
Great!
I would suggest Calling "Sys.sleep(0.010)" inside your while loop if you
can afford to (if you are just waiting to exit, not processing characters)
- this will reduce the CPU usage significantly and it also has the
enter/exit stuff built-in.
You need to take some care with the enter/exit blocking - allocate your
buffers before entering gc blocking, and exit it before you throw
exceptions - the Std.ndll code does quite a bit of this.  Passing ints and
floats to cffi will also generate gc events, so you really need to do the
enter/exit inside the c code.  If you compile with debug, there are some
extra checks for mismatched enter/exit calls which might be helpful.

Hugh

**Comment by juakob** [comment]
Thank you Hugh for the inside info. I'm going to work more with threads, they give you a lot of extra power, specially in modern CPUs. So all the information that you give me is really valuable.

Thanks 
Joaquin
