### ISSUE TITLE
Invalid token at start of a preprocessor expression (osx)

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/hxcpp#172]
Trying the master branch of hxcpp, and am getting this error when I try to build for C++ target on a mac:

    xcrun --sdk macosx10.9 clang++ -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/ben/Dev/hxcpp/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL= -x c++ -frtti ./src/sys/net/_Socket/SocketOutput.cpp -oobj/darwin64/7a49fabf_SocketOutput.o
    Error: In file included from ./src/sys/net/_Socket/SocketOutput.cpp:1:
    /Users/ben/Dev/hxcpp/include/hxcpp.h:208:22: error: invalid token at start of a preprocessor expression
    #if (HXCPP_API_LEVEL >= 313)
                         ^
    1 error generated.

**Comment by hughsando** [comment]
This error usually indicates that the hxcpp.n file from a development build is out of date.
try running "haxe compile.hxml" from the hxcpp tools/hxcpp directory first.

**Comment by bendmorris** [comment]
Thanks, that solved it.
