### ISSUE TITLE
Compile issues with latest version of hxcpp/haxe on mac and ios

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/hxcpp#174]
I've installed a development version of Haxe and hxcpp, rebuilt hxcpp.n, and run "lime rebuild hxcpp mac" and "lime rebuild hxcpp ios" followed by "lime rebuild mac -Dlegacy -clean" and "lime rebuild ios -Dlegacy -clean". Hopefully I didn't miss a step there.

I'm getting different compiler errors on each platform:

## Desktop

xcrun --sdk macosx10.9 clang++ -Iinclude -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/ben/Dev/hxcpp/include -DHX_MACOS -m64 -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-format-extra-args -Wno-bool-conversion -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=313 -x c++ -frtti ./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp -oobj/darwin64/47df8cdc_BitmapDataTextureLoader.o
Error: ./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp:140:20: error: no member named '_v2' in namespace 'spinehaxe::platform::openfl'; did you mean '::openfl::_v2'?
                tmp = hx::TCast< openfl::_v2::display::BitmapData >::cast(page->rendererObject);
                                 ^~~~~~~~~~~
                                 ::openfl::_v2
include/spinehaxe/platform/openfl/BitmapDataTexture.h:12:26: note: '::openfl::_v2' declared here
HX_DECLARE_CLASS3(openfl,_v2,display,IBitmapDrawable)
                         ^
/Users/ben/Dev/hxcpp/include/hx/Macros.h:448:80: note: expanded from macro 'HX_DECLARE_CLASS3'
#define HX_DECLARE_CLASS3(ns3,ns2,ns1,klass) namespace ns3 { HX_DECLARE_CLASS2(ns2,ns1,klass) }
                                                                               ^
/Users/ben/Dev/hxcpp/include/hx/Macros.h:447:52: note: expanded from macro 'HX_DECLARE_CLASS2'
#define HX_DECLARE_CLASS2(ns2,ns1,klass) namespace ns2 { HX_DECLARE_CLASS1(ns1,klass) }
                                                   ^
1 error generated.

This comes from the following function (page.rendererObject is a Dynamic):

    public function unloadPage (page:AtlasPage) : Void {
        cast(page.rendererObject, BitmapData).dispose();
    }

If I comment out the cast, the build finishes successfully.

## iOS

Error: ./src/spinepop/SpinePop.cpp:1502:60: error: no member named 'paccNever' in namespace 'hx'
                if (HX_FIELD_EQ(inName,"skin") ) { if (inCallProp != hx::paccNever) return set_skin(inValue);skin=inValue.Cast< ::String >(); return inValue; }

Here's the Haxe function which generated this:

    public var skin(default, set):String;
    function set_skin(skin:String) {
        if (skin != this.skin) {
            skeleton.skinName = skin;
            skeleton.setToSetupPose();
        }
        return this.skin = skin;
    }

**Comment by bendmorris** [comment]
Android, similar issue as desktop:

Error: ./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp: In member function 'virtual Void spinehaxe::platform::openfl::BitmapDataTextureLoader_obj::unloadPage(spinehaxe::atlas::AtlasPage)':
./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp:140: error: '_v2' is not a member of 'spinehaxe::platform::openfl'
./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp:140: error: '_v2' is not a member of 'spinehaxe::platform::openfl'
./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp:140: error: template argument 1 is invalid

**Comment by hughsando** [comment]
So the cast bugs could be from some new way cast is handled - I will look
into it.  The IOS bug looks a little bit like it is finding the wrong
version of hxcpp, or somehow missing the HXCPP_API_LEVEL define.  If you
can show the compiler command, that would help.

**Comment by hughsando** [comment]
I have put a fix in for the TCast issue. Did not manage to reproduce the issue, but it looks like it is to do with 2 different "openfl" pacakges/namespaces - and the fix look reasonable.  Let me know if this fixes the issue.

**Comment by bendmorris** [comment]
That did indeed fix the cast issue, thank you.

Tried rebuilding everything for iOS but no difference. Here's the command that's generating the error, with -DHXCPP_API_LEVEL=0 for some reason:

xcrun --sdk iphoneos7.1 clang++ -Iinclude -c -stdlib=libc++ -O2 -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk -miphoneos-version-min=5.0 -fobjc-arc -DOBJC_ARC -Wno-parentheses -Wno-null-dereference -Wno-unused-value -Wno-bool-conversion -fno-stack-protector -DIPHONE=IPHONE -DIPHONEOS=IPHONEOS -DSTATIC_LINK -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -I/Users/ben/Dev/hxcpp/include -fexceptions -fstrict-aliasing -x c++ ./src/spinehaxe/platform/openfl/BitmapDataTextureLoader.cpp -oobj/iphoneos-c11-v7/cf449eba_BitmapDataTextureLoader.o

**Comment by hughsando** [comment]
The problem is certainly that the HXCPP_API_LEVEL is not being set, so we can work backwards from there.
This is running lime/openfl right? Going back one step, can you see the "haxelib run hxcpp ...." command, or the "haxe ..." command?  The haxelib command should have "-Dhxcpp_api_level" in it somewhere.
I actually write the api level the build.xml file, and might be able the use this better.

**Comment by bendmorris** [comment]
That's right, this is openfl/lime. Looks like -Dhxcpp_api_level is not set:

haxe Build.hxml -D HXCPP_ARMV7 -cpp build/Release-iphoneos-v7
cd build/Release-iphoneos-v7; export HXCPP_NO_COLOR=1; haxelib run hxcpp Build.xml -Dios -Diphone -DHXCPP_ARMV7 -DHXCPP_CPP11  -DHXCPP_CLANG -DOBJC_ARC  -Dtools="2.1.1" -Dguest="1" -Dlime_legacy="1" -Dnative="1" -Dhardware="1" -DhaxeJSON="1" -Dopenfl_native="1" -Dlime_native="1"

**Comment by hughsando** [comment]
Well the problem seems to be with lime here using its own flags.  I guess there is a reason for this - not sure.  Maybe it has already been fixed in lime?
Anyhow, I will see if I can make better use of the value in the build.xml file.

**Comment by bendmorris** [comment]
Did some digging and found a linked Lime issue (https://github.com/openfl/lime/issues/323) which has been resolved recently. I'll give this a shot. It looks like hxcpp is working as intended. Thanks!
