### ISSUE TITLE
Enable hx_set_loader on platforms other than Android and Windows RT

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#176]
I'm currently using fork of hxcpp only for setting dynamic function loader for ndlls. Could you remove these #if defined, or add #if defined of other platforms?
https://github.com/vroad/hxcpp/commit/0ad5ce941028e14274d8a29f8d5c69951ac4e6c4

**Comment by hughsando** [comment]
Seems a bit mean to not let the other platforms do this!
