### ISSUE TITLE
@: cppHeaderInclude/cppFileInclude relative injection

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#179]
As discussed, being able to include "local" cpp code without resorting to haxelibs, buildXML or putting large quantities of cpp code inside of the `@:cppFileCode` or `untyped __cpp` would be great.

(_exact semantics for below might be incorrect_)

```haxe
@:include('./nativeclass.h') //A
@:nativeCode('./nativeclass.cpp') //B
class NonExternClass {
   public static function func2() {
      return untyped __cpp__('my::nativefunc2()');
   }
}

@:include('./nativeclass.h') //C
extern class NativeClass {
   @:native('my::nativefunc1')
    function func1(ex:Int);
}
```

The folder would then look like:
```
/ex/NativeClass.hx
/ex/nativeclass.h
/ex/nativeclass.cpp
```

**Comment by hughsando** [comment]
@:Include should now work with native code and you can specify the native implementation file for externs with @:source("./filename.cpp").
Also, @:cppInclude and @:headerInclude will inject "#include" statements into the implementation and header files.
