### ISSUE TITLE
resource file cpp

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#181]
it was already partially discussed but we need a more advanced solution than what the ticket was asking.

We have issue because the __resource_.cpp file is too big, when we do 24MB of resource (split among any number of files...) of overall data, it goes to 128 MB of .cpp in one array. this is mainly withthe haxe.Resource API.

Problem is the situation is frequent in prototype phases and even for large projects.

When filees get so big the android compiler is not able to generate anything and goes segfault crunching 2GB of RAM.

The solution is to trim the output as much as possible (spaces, pack by 4bytes which is faster anyway) AND split the resources across several files so that one file does not get over 120MB.

We bypass the bug by using only the openfl resource system but it is really a showstopper for someone not using openfl wanting to embed one or several texture atlases summing more thant 24 MB during prototyping phases (a little cubemap easily goes that big...)...and even at release !

Thanks !

**Comment by ncannasse** [comment]
I agree we should allow huge resources in binary format. @hughsando anything that can be done here ?

**Comment by hughsando** [comment]
For crazy-big files, source code might not be the right way to go.  Not too
sure if I can generate the linkable-data directly.  Could maybe do one .cpp
per resource file, which might be nice for caching objs too.

**Comment by delahee** [comment]
Problem is that for 2d 3d data 32mb is "not that big" so in prototyping and
alpha phases it occurs frequently to us :)

**Comment by hughsando** [comment]
Embedding 32 M in an exe is not a great solution - there is no way to
remove the data from RAM, and you need to do a full recompile + package to
update the data, rather than a file-copy.  Don't see many other workflows
doing this.  Are you saying it would also be in a single file, so no
benefit from multiple cpp files?

**Comment by jgranick** [comment]
I've seen a lot of people who want a static EXE solution, embedding  
resources is a key way to make sure that you can keep everything all in  
one file, instead of spreading into a directory

**Comment by hughsando** [comment]
I understand this, but you can't expect a 2Gig exe to work on a 32 bit
system. Having a single exe is "nice" to a point - but you don't see
call-of-duty shipped as self-contained exe.  So there is some practical
limit to how much can/should be put in.  I'm trying to understand what
limits we have and should anticipate from an engineering point of view.

**Comment by hughsando** [comment]
I have put each resource in its own cpp file, and compressed the ascii a bit.  Don't really want to do 32bits because of endian issues.
If you are going to have single big files, this wont help much,  but should solve the problem otherwise.

**Comment by delahee** [comment]
No we have a collection of textures plus sound summing to 32mb...it is not
ideal but for prototyping, it is fairly frequent. Feel free to close but I
have the feeling any 3d guy will encounter this situation :)

**Comment by delahee** [comment]
Thanks !
