### ISSUE TITLE
Document the defines

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#182]
There's several defines in hxcpp build system that are mostly undocumented. I find myself searching for the web and finding some Hugh personal projects hxml to discover new flags that I didn't knew about :)

I think that hxcpp is now stable enough so that we can+should document the defines that users are supposed to use. That can be for 64 bit vs 32 bit build, static linking, creating dynamic library, XP compatibility, etc etc etc

I know that's a significant amount of work but I'm sure that will save you some time afterwards when people can directly answer "RTFM" to people asking such questions on [haxe].

I think the best place for them would be on http://haxe.org/manual/target-cpp.html

**Comment by kevinresol** [comment]
+1 for documentations

**Comment by martinfinke** [comment]
Yes this would be very good! +1

**Comment by fzzr-** [comment]
:+1:

**Comment by hughsando** [comment]
There are some docs there now.
