### ISSUE TITLE
Escape sequence not working when "no_console" (Windows - ConEmu)

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/hxcpp#183]
Hi Hugh

I am experimenting with a color Logger for Windows target. Since cmd.exe is not compatible with ANSI, I am using ConEmu. I see that hxcpp's Log.hx already use coloring and it works fine.  For OpenFL/NME I had to set 
 setenv name="SHOW_CONSOLE" value="1" 
in the XML
, which unsets "no_console", to make it work.  

When not setting SHOW_CONSOLE,  looks like cmd.exe is converting the Escape character (to an arrow character) before arriving to ConEmu. 

Do you think there is a workaround or is it something that is a limitation of the Windows system?
Anyway, I think we can just use SHOW_CONSOLE for the debug version.  

Also, hopefully there is a Flashdevelop implementation on the way (https://github.com/fdorg/flashdevelop/issues/530)
(BTW, I have attached a ConEmu link to FlashDevelop's Toolbar by adding a line in Toolbar.xml)

Thanks!

EDIT: removed brackets in setenv name="SHOW_CONSOLE" value="1" to show in this post.
I have checked that the arrow means that the input is not processed at all, so it may be a ConEmu issue

**Comment by thomasuster** [comment]
@madrazo Have you been able to narrow down if it's a conemu issue or not?

**Comment by madrazo** [comment]
Hi. I tried to test on Console 2 but I was unable to configure it using ansicon as shell.

**Comment by hughsando** [comment]
Hi,  Is this still an issue?
With no_console current logic will use "WinMain" to create a console-less window, then attempt to attach to the launching console via "AttachConsole" (in StdLibs.cpp) - if indeed there is a launching window.
This allows you to create an app that works with or without a window.
I guess this is messing with your colouring characters.
You might be able to make some changes in "__hxcpp_stdlibs_boot" to get what you want.

**Comment by madrazo** [comment]
I have not tried this lately but it was fine just using no_console. I will give a look and reponen If necessary. Thank you ver much.
