### ISSUE TITLE
Is val_fun_nargs not giving the corrent number of arguments?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxcpp#184]
Seems `val_fun_nargs(v)` on cpp is returning some arbitrary number. I am sure `v` is a function as I used `switch (val_type(v)) case valtFunction:` on it. 

On neko it works fine.

Edit: I think it is returning `-1` and screwed things up

**Comment by thomasuster** [comment]
Hey @kevinresol . I'm  new to CFFI, I got a hello world up and running. And I was also able to call val_fun_nargs(v) but only for functions with a known number of arguments. Would you mind modifying the following to demonstrate your problem? https://github.com/thomasuster/haxe-cpp-hello-world

**Comment by hughsando** [comment]
There was an issue when inline-closures were usesd, rather than function names or function variables (as in Thomas' example).  I have fixed this in the haxe compiler - not sure it it will make it into 3.2.

**Comment by kevinresol** [comment]
Thanks @hughsando for the info. Just to clarify, my use case was passing a inline-closure wrapped in an object to cpp, i.e.:

```haxe
var cppFunc = Lib.load("someFunc",1);
cppFunc({myFunc:function(i) trace(i)});
```

and I iterate the object in cpp, when I encounter the `myFunc` field, I pass it to `val_fun_nargs` and it returns `-1` to me.

**Comment by hughsando** [comment]
This will be broken until the change makes it through haxe.
Meanwhile, you might be able to re-write your code with a "real" function:
class ABC {
function realFunc(i:int) trace(i);
function runCpp()
{
   ...
   cppFunc({myFunc:realFunc})
}

**Comment by kevinresol** [comment]
Ok I will try that later, thanks!

**Comment by thomasuster** [comment]
@kevinresol If your issue is resolved please close. Otherwise please close and reopen in haxe github referencing this issue. https://github.com/HaxeFoundation/haxe/issues
