### ISSUE TITLE
StructData.mValue is never marked, and always gets collected

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#190]
StructData::__Mark is never called, and after looking into the marking process, it seems as though StructData should be allocated with NewObjContainer, rather than NewObjAlloc.

https://github.com/HaxeFoundation/hxcpp/blob/14e6ed07c4ac0479e6a13bb17d238b4b6f723ed5/src/Dynamic.cpp#L163

**Comment by hughsando** [comment]
Nice catch, thanks.
