### ISSUE TITLE
Primitive not found

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxcpp#213]
With latest haxe build and dev version hxcpp, I got an `Primitve not found` error when using `Lib.load`.

Details:
```
haxelib git lua https://github.com/kevinresol/hx-lua
lime rebuild lua windows
```

Haxe:
```haxe
var lua = new Lua();
```

I am not sure what's going on, what can I do to obtain more debug info?

**Comment by hughsando** [comment]
you can set the environment variable HXCPP_LOAD_DEBUG to get more info about what it is doing.

**Comment by kevinresol** [comment]
I am not sure, but the problem solved somehow. Maybe I have rebuilt the ndll with latest hxcpp...
