### ISSUE TITLE
val_string crashes on neko when you pass null value

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#217]
While cpp doesn't.
api_val_string checks if the value is string, but doesn't check if the value is null.
api_val_string thinks that the value is an object if the value is not a string, but that will cause the app to crash if null value is given.

val_to_buffer calls api_val_string internally so it also crashes when null value is given.
https://github.com/HaxeFoundation/hxcpp/blob/master/include/hx/CFFILoader.h#L221

**Comment by hughsando** [comment]
I have added some checking to val_string.
The cffi usage was unclear about how values and buffers can interact.  I have gone over it and tried to separate the neko api, where you use val_buffer to build up strings, and the c++ api where you get direct access to a byte-array.  The later usage is not really going to work on neko.
To compensate, I have added a 'CffiBytes' struct that uses the basic primitives to get byte-access to a haxe.io.Bytes structure.  Hopefully this will now be clearer how this can be used.
I have also added test/cffi to show some use-cases.
