### ISSUE TITLE
error: no viable conversion from 'hx::Null<bool>' to 'bool'

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [HaxeFoundation/hxcpp#218]
While everything is fine under android and ubuntu linux, I get this compile error when trying to compile for mac os x:

```
> lime test mac -Dv2
...
Error: ./src/ru/stablex/Assets.cpp:71:7: error: no viable conversion from 'hx::Null<bool>' to 'bool'
        bool tmp1 = useCache;           HX_STACK_VAR(tmp1,"tmp1");
             ^      ~~~~~~~~
/usr/lib/haxe/lib/hxcpp/git/include/null.h:164:11: note: candidate function
   inline operator Dynamic();
```

I tried hxcpp from git and the newest version (3.2.81).
I remember having this error for android and linux and at that time it was solved by using hxcpp from git, but under mac it is not.

**Comment by underscorediscovery** [comment]
I am having a similar looking error @hughsando , on OSX.

```
error: no viable conversion from 'bool' to 'Void' (aka 'null')
                                                        return _g->bouncing = false;
                                                               ^~~~~~~~~~~~~~~~~~~~
/Users/sven/dev/haxelib/hxcpp/3,2,102/include/null.h:65:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'bool' to 'const null &' for 1st argument
class null
      ^
1 error generated.
```

This is from the latest release, `3.2.102`.

I'm going backward in version to see where it introduced (as it was working before I ran haxelib update hxcpp) and then weirdly, none of my previous installed versions are working. I also tried my existing hxcpp git version, and then updated and tried that too.

- 3.2.27 - the oldest 3.2 I have, not working at all on hx::ArrayBase stuff
- 3.2.81 - same error as above, bool/null
- 3.2.94 - same error as above, bool/null
- git updated (5865090e38) - hxtelemetry pull from jcward, same error as above, bool/null
- git originally (4065a573e5) - "emscripten compile fix", ArrayBase errors.

The code was working before, and I did clean builds and such, so it's pretty weird.
I also didn't change my build environment between builds, I just said haxelib update hxcpp.

The build lists `-DHXCPP_API_LEVEL=321`

I'm not worried about older versions but 3.2.102 isn't working on the latest version with the above error.
`g++ -v`:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

I'll restart my machine and delete all the things and try again as well.

**Comment by underscorediscovery** [comment]
Actually, discard the above - it's an error from a local inline function, which seems like a code generation error (i'll file a separate issue for that).

**Comment by skylerparr** [comment]
Running git version and getting the same issue. Is there a temporary patch that could be applied to this?

**Comment by hughsando** [comment]
skylerparr - are you trying the git version of haxe, or just hxcpp?  it look like this inline-case has been fixed in haxe.

**Comment by skylerparr** [comment]
I'm using the git version of hxcpp. Release version of haxe. I see where you're going at with this.

**Comment by hughsando** [comment]
I think this should be working now.
