### ISSUE TITLE
Problems converting from Neko `Float`

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#219]
I have issues using CFFI to read a field from a class, compiling with Neko.

The Haxe type is `Float`, but fails the `val_is_float` check. Since I created the object using `new Rectangle (0, 0, 50, 50);`, it appears to be using Neko `Int` values instead of floats.

`val_float` will crash. `val_number` will always return 0, but not crash. This works:

```cpp
if (val_is_float) data = val_float (field);
else if (val_is_int) data = val_int (field);
```

When I see Neko2.h, it seems the idea of `val_number` is to automatically handle these conditions. I just wanted to raise this issue in case CFFI was supposed to have a helper method to handle this problem with Neko

**Comment by jgranick** [comment]
I'm sorry, I was misdiagnosing the issue. I was accidentally using `printf ("%d\n");` instead of `printf ("%f\n");`, the Neko Int/Float difference is quirky, but `val_number` handles it

**Comment by hughsando** [comment]
Cool.  You could commit a test to hxcpp/tests/cffi to make sure if you like.
