### ISSUE TITLE
Build failing on latest xcode 8.3 

### ISSUE THREAD

**Issue by fserb** [HaxeFoundation/hxcpp#229]
When I try to compile an OpenFL target to ios -ipad, it failes after running libtool with:
```
xcrun --sdk iphoneos8.3 libtool -o libApplicationMain.iphoneos-v7.a [...]
cp build/Release-iphoneos-v7/nullApplicationMain.iphoneos-v7.a ../lib/armv7/libApplicationMain.a
cp: build/Release-iphoneos-v7/nullApplicationMain.iphoneos-v7.a: No such file or directory
```

Not sure where this "null" is coming from.

**Comment by fserb** [comment]
I forced copy the file, to skip this step, then I got that some files present on the Lime templates were not copied properly (xassets files). I manually copyed them too. Then finally I got:
```
 Undefined symbols for architecture armv7:
 "_null_register_prims", referenced from:
     _main in Main.o
ld: symbol(s) not found for architecture armv7
```
I've tried this with stock openfl examples (PiratePig) and got the same outcome.
It looks like a hxcpp thing and not a lime thing, but I may be wrong.

**Comment by hughsando** [comment]
This looks like a lime issue - Main.mm is generated by the lime templates
so if this file mentions "null_register_prims" then the problem is
something to do with the template system.

**Comment by fserb** [comment]
Oh, I thought that because things were not being copied and being in a weird state it could be something wthi hxcpp not being happy with the latest xcode. Sorry for that.
I created a bug on lime side.
Thanks, Hugh.
