### ISSUE TITLE
Faster Std.int

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#231]
See this issue:

https://github.com/openfl/openfl/issues/660#issuecomment-101462872

**Comment by jcward** [comment]
FYI, code in question is [StdLibs.cpp::__int__](https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/StdLibs.cpp#L366-L377).

Wait a second, if the [Std.hx API](http://api.haxe.org/Std.html#int) states the behavior is unspecified outside the signed `Int32` range, so is there a need for range checking? And why handle `__int64` -- Std.int is supposed to return `Int`?  Perhaps hxcpp internally relies on this 64-bit handling, maybe `Std.int` should get less strict (and faster) implementation?

**Comment by hughsando** [comment]
I'm quite happy to use a faster implementation - as long as it passes the
unit tests, which is the only real specification I have been working off.
I also think there will be a nice gain from inlining - the haxe def, and
the hxcpp implementations.

**Comment by hughsando** [comment]
I have added "NativeMath", with
idiv - integer division
castInt - basically "(int)f"
fastInt - the bitwise twiddle from the openfl post.
These should be nice additions.
