### ISSUE TITLE
rounding when using Std.string()

### ISSUE THREAD

**Issue by elliott5** [HaxeFoundation/hxcpp#238]
The haxe (and tardisgo) program at https://github.com/tardisgo/tardisgo-samples/tree/master/go-as-haxe-lib-examples/math

For cpp produces the output:

Main.hx:7: Go 'math' and 'strconv' standard library trivial example

Main.hx:16: The next valid floating point value after 2.0 towards 3.0 is (Go): 2.0000000000000004

Main.hx:18: The next valid floating point value after 2.0 towards 1.0 is (Go): 1.9999999999999998

Main.hx:22: The next valid floating point value after 2.0 towards 3.0 is (Haxe): 2

Main.hx:24: The next valid floating point value after 2.0 towards 1.0 is (Haxe): 2

**Comment by hughsando** [comment]
Try using cpp.Lib.setFloatFormat to something like "%.18f"

**Comment by elliott5** [comment]
Thank you Hugh, I was not aware of cpp.Lib.setFloatFormat.
I will probably use "%.18g" within tardisgo as it will mean that doubles with large exponents will not produce very long string representations.
The question for you is whether the default print format for Haxe Float should change to show the full precision as it does on the other Haxe targets (except C#, which Cauê is looking at), rather than use the C++ default of only 6 digits of precision.
