### ISSUE TITLE
Compiler switch to disable hxcpp debugging 

### ISSUE THREAD

**Issue by andreashanft** [HaxeFoundation/hxcpp#244]
In our game we experience a huge performance impact between a release and a debug build running on a device (just do give some numbers: 60 vs 40 fps). Because of this we only run release versions for testing which make crash hunting harder. The performance drop seems to be caused by the hxcpp debugger. As such an option to disable it when compiling a debug build would be awesome! :)

**Comment by delahee** [comment]
In our engine we just tag worst offenders func with the @:noDebug Metadata,
like vertex transfer and particle processing, it is usually sufficient, if
it's not enough in Cpp you can modify your toolchain.xml to select debug
info injected.

**Comment by hughsando** [comment]
Instead of adding  -debug, you can add just the bits you need.  Eg, null
pointer check and debug link.  There is a post on Gamehaxe.com about this.

**Comment by thomasuster** [comment]
```
<haxedef name="HXCPP_DEBUG_LINK" if="debug" />
<haxedef name="HXCPP_STACK_TRACE" if="debug" />
<haxedef name="HXCPP_STACK_LINE" if="debug" />
<haxedef name="HXCPP_CHECK_POINTER" if="debug" />
```

**Comment by hughsando** [comment]
I think I can close this one.  Feel free to ask questions on the google group if you have any more questions.
