### ISSUE TITLE
hxcpp creates invalid C++ code in 3.2 compiler for interface extending interface

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#246]
Not sure exactly what the minimal code construct to reproduce this is, but the following is pretty minimal and it reproduces the problem:

```
class Data
{
}

interface IBase
{
    function updateData(data : Dynamic) : Void;
}

class Base implements IBase
{
    public function updateData(inData : Data) : Void
    {
    }
}

interface ISub extends IBase
{
}

class Foo extends Base implements ISub
{
    public static function main()
    {
    }
}
```

Put the above into a file Foo.hx, then compile:

<pre>
bji/bug_demo$ haxe -cpp Foo-cpp -main Foo
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.2" -Dhxcpp_api_level="321" -I"" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/share/haxe/std/"
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/ISub.cpp -oobj/linux64/469a59a9_ISub.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Std.cpp -oobj/linux64/469a59a9_Std.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/__boot__.cpp -oobj/linux64/469a59a9___boot__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/IBase.cpp -oobj/linux64/469a59a9_IBase.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/__files__.cpp -oobj/linux64/469a59a9___files__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Base.cpp -oobj/linux64/469a59a9_Base.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Foo.cpp -oobj/linux64/469a59a9_Foo.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Data.cpp -oobj/linux64/469a59a9_Data.o
Error: In file included from /usr/lib/haxe/lib/hxcpp/3,2,102/include/hxcpp.h:254:0,
                 from ./src/Foo.cpp:1:
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Object.h: In instantiation of 'void hx::ObjectPtr<O>::CastPtr(hx::Object*, bool) [with OBJ_ = Data_obj]':
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Object.h:199:40:   required from 'hx::ObjectPtr<O>::ObjectPtr(const hx::ObjectPtr<SOURCE_>&) [with SOURCE_ = hx::Object; OBJ_ = Data_obj]'
include/ISub.h:35:3:   required from 'Void ISub_delegate_<IMPL>::updateData(Dynamic) [with IMPL = Foo_obj; Void = null]'
./src/Foo.cpp:113:1:   required from here
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Object.h:173:15: error: cannot dynamic_cast 'inPtr->hx::Object::__GetRealObject()' (of type 'class hx::Object*') to type 'class Data_obj*' (target is not pointer or reference to complete type)
          mPtr = dynamic_cast<OBJ_ *>(inPtr->__GetRealObject());
               ^
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Object.h:175:57: error: invalid use of incomplete type 'class Data_obj'
             mPtr = (Ptr)inPtr->__ToInterface(typeid(Obj));
                                                         ^
In file included from /usr/lib/haxe/lib/hxcpp/3,2,102/include/hxcpp.h:250:0,
                 from ./src/Foo.cpp:1:
include/Base.h:12:19: error: forward declaration of 'class Data_obj'
 HX_DECLARE_CLASS0(Data)
                   ^
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Macros.h:530:8: note: in definition of macro 'HX_DECLARE_CLASS0'
  class klass##_obj; \
        ^
Error: Build failed
bji/bug_demo$ 
</pre>

The problem appears to be the fact that the generated header file for ISub includes delegate functions which invoke dynamic_cast on the Data type without actually including a definition of the Data type (missing includes?  Something else?).

**Comment by bjitivo** [comment]
Note also that there is a signature difference in the IBase updateData function and the Base implementation thereof.  The compilation error does not happen if IBase's updateData is changed to take a Data type as its argument.

I don't know if the difference in declared interface signature between IBase and Base is even valid haxe code; but the compiler accepts it.

For what it's worth, when targeting neko output, Foo.hx compiles and runs without error.

**Comment by Simn** [comment]
Are you saying this is a regression from 3.1.3?

**Comment by bjitivo** [comment]
Yes.

**Comment by bjitivo** [comment]
Although, in case it wasn't clear: I'm not certain what the language semantics surrounding re-declaration of an interface function in a sub-interface with a more specific argument type than in the parent interface; if it were me, I would disallow this, I think it's inherently flawed to allow it.  But the compiler used to allow it, and the front end still allows it, it's only the C++ back end that emits code that fails to compile.

My recommendation would be to either decide that changing function signatures in sub-interfaces is valid and consider this a bug to be fixed in the hxcpp back-end, or declaring such a language construct as being invalid and properly catching it and flagging the appropriate error in the front-end.  The latter would be potentially a "breaking change", in that it would make some code that used to be legal haxe now illegal.

**Comment by bjitivo** [comment]
Er I guess I mis-described the problem in my most recent comment; it's not a sub-interface that changes the signature of an interface function, it's the implementing class.  But either way, I don't think the compiler should allow function signatures to be changed in this way.  Allowing this means that a function may be passed an argument that isn't even the type of argument that it declared that it accepted, which seems wrong.

**Comment by bjitivo** [comment]
Just to add some more detail, here is an example of code that demonstrates the problem I most recently described:

```
class Data
{
    public var value : String;

    public function new()
    {
        value = "Hello, world!";
    }
}

interface IBase
{
    function updateData(data : Dynamic) : Void;
}

class Base implements IBase
{
    public function updateData(inData : Data) : Void
    {
        trace("inData is: " + inData.value);
    }
}

interface ISub extends IBase
{
}

class Foo extends Base implements ISub
{
    public static function main()
    {
        var ib : IBase = new Foo();

        ib.updateData(7);
    }

    public function new()
    {
    }
}
```

Here, the updateData function in class Base is expecting a Data object, declares that it accepts only such a type, and operates on that type.  But because the compiler allows IBase to declare the accepted argument as Dynamic, code can pass a value in that doesn't match what the implementation of the interface actually expects.

The results:

haxe 3.1.3 compiler, hxcpp back-end: Segmentation fault (core dumped)
haxe 3.1.3 compiler, neko back-end: Uncaught exception - Segmentation fault
haxe 3.2 compiler, hxcpp back-end: hxcpp produces bad C++ code that won't compile
haxe 3.2 compiler, neko back-end: Uncaught exception - Segmentation fault

I think the correct thing is for the compiler to issue an error about incompatible function signatures in updateData between IBase and Base.

**Comment by hughsando** [comment]
I would tend to agree this should be caught at the haxe stage.

**Comment by bjitivo** [comment]
If Simon agrees, I will open an issue on the haxe compiler and close this one.  Thanks.

**Comment by Simn** [comment]
Function arguments are contravariant so this indeed shouldn't be allowed (if I understood correctly).

**Comment by bjitivo** [comment]
Closing, as this is now tracked in HaxeFoundation/haxe issue 4378:

https://github.com/HaxeFoundation/haxe/issues/4378
