### ISSUE TITLE
hxcpp creates invalid C++ code in 3.2 compiler for interface using @:nativeGen

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#247]
Here is some example code to demonstrate the problem:

```
@:nativeGen
interface IBase
{
}

class Foo implements IBase
{
    public static function main()
    {
    }
}
```

Put this into a file Foo.hx, then compile:

<pre>
bji/bug_demo$ haxe -cpp Foo-cpp -main Foo
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.2" -Dhxcpp_api_level="321" -I"" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/share/haxe/std/"
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Std.cpp -oobj/linux64/469a59a9_Std.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/__resources__.cpp -oobj/linux64/469a59a9___resources__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/__files__.cpp -oobj/linux64/469a59a9___files__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/Foo.cpp -oobj/linux64/469a59a9_Foo.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/IBase.cpp -oobj/linux64/469a59a9_IBase.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/3,2,102/include -x c++ -frtti -Wno-invalid-offsetof ./src/__boot__.cpp -oobj/linux64/469a59a9___boot__.o
Error: In file included from /usr/lib/haxe/lib/hxcpp/3,2,102/include/hxcpp.h:250:0,
                 from ./src/__boot__.cpp:1:
include/Foo.h:12:19: error: conflicting declaration 'typedef class hx::ObjectPtr<IBase_obj> IBase'
 HX_DECLARE_CLASS0(IBase)
                   ^
/usr/lib/haxe/lib/hxcpp/3,2,102/include/hx/Macros.h:531:37: note: in definition of macro 'HX_DECLARE_CLASS0'
  typedef hx::ObjectPtr<klass##_obj> klass;
                                     ^
In file included from include/Foo.h:9:0,
                 from ./src/__boot__.cpp:7:
include/IBase.h:11:31: error: 'class IBase' has a previous declaration as 'class IBase'
 class HXCPP_CLASS_ATTRIBUTES  IBase{
                               ^
Error: Build failed
bji/bug_demo$ 
</pre>

**Comment by hughsando** [comment]
There are probably still some issues, depending on how you want to use these things.  For example, the native interface implemented by a hxcpp object will not hold a GC reference.  Also, whether the header file should include "hxcpp.h" or not.
But, this code should now work:
```
@:nativeGen
interface IBase
{
   public function base() : Int;
}

class User
{
  @:unreflective
  public static function run(base:IBase )
  {
     trace( base.base() );
  }
}

class Test implements IBase
{
   public function new() { }

   public static function main()
   {
      var t = new Test();
      User.run(cast t);
   }


   public function base() : Int
   {
      trace("Base!");
      return 5;
   }
}
```

**Comment by hughsando** [comment]
I am closing this 3.2 interface issue - basically given up on nativeGen for 3.2.
3.3 has some new stuff, that may require a discussion of its own.
