### ISSUE TITLE
NekoAPI does not convert string encoding correctly

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/hxcpp#25]
api_val_wstring copies UTF-8 string to UTF-16 string.
https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/nekoapi/NekoAPI.cpp#L210
api_alloc_wstring_len copies UTF-16 string to UTF-8 string.
https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/nekoapi/NekoAPI.cpp#L259
They does not convert string encoding correctly.

**Comment by hughsando** [comment]
This should be fixed now.
