### ISSUE TITLE
Memory leak in process_run

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#250]
Would be fairly rare as it only happens on errors, but still seems worth reporting.

In short, the memory allocated for `argv` and `p` does not get freed on the following early returns:

https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/std/Process.cpp#L168
https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/std/Process.cpp#L172

**Comment by ncannasse** [comment]
@james4k could you also open an issue for Neko ? https://github.com/HaxeFoundation/neko/blob/master/libs/std/process.c
