### ISSUE TITLE
hxcpp for haxe 3.2 does not implement Reflect.setField properly for static fields

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#251]
Sample code:

```
class Statics
{
    public static var one : String = "one";
    public static var two : String = "one";
    public static var three : String = "one";
}


class Foo
{
    public static function main()
    {
        Reflect.setField(Statics, "two", "two");
        Reflect.setField(Statics, "three", "three");

        trace("Statics.one is " + Statics.one);
        trace("Statics.two is " + Statics.two);
        trace("Statics.three is " + Statics.three);
    }
}
```

Expected results:

<pre>
Foo.hx:17: Statics.one is one
Foo.hx:18: Statics.two is two
Foo.hx:19: Statics.three is three
</pre>

Results for:

- Haxe 3.1.3, neko target: expected results
- Haxe 3.1.3, hxcpp target: expected results
- Haxe 3.2, neko target: expected results
- Haxe 3.2, hxcpp target: invalid results:
<pre>
Foo.hx:17: Statics.one is one
Foo.hx:18: Statics.two is one
Foo.hx:19: Statics.three is one
</pre>

In Haxe 3.2, the hxcpp backend is not actually doing the Reflect.setField as expected.

**Comment by hughsando** [comment]
This looks like a pretty nasty bug - I think it would only show up if you had no member variables, only static.
I have made the fix in haxe developement branch, but I think we are going to need to get a patch release out.

**Comment by bjitivo** [comment]
Oh hey thanks, I actually have a fix locally too, I was going to submit a pull request today.  I'm sure your fix is better though so I will await your change.

For your info, my fix was to change the "has_set_static_field" "function" (or whatever you call them in ocaml) to set its "reflect_fields" variable the same as "has_get_static_field" does.

**Comment by bjitivo** [comment]
Oh I see your change is the exact same thing.  Sweet.
