### ISSUE TITLE
LGPL

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#253]
Hello,

It seems that while hxcpp is licensed with a BSD-style license, it isn't clear that LGPL code exists as well. [1] It is also not very clear from reading the Haxe licensing page [2], unless you are aware pieces of the Neko runtime are used for other targets.

Do iOS developers have issues here?

I would like to see either an increase in clarity on this, or to relicense these portions of Neko to hxcpp's license if possible.

[1] https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/std/File.cpp
[2] http://haxe.org/foundation/open-source.html#std-library-license

**Comment by hughsando** [comment]
I need to remove that license.  There is nothing in the hxcpp runtime that requires GPL or even LGPL - the original code has removed this requirement.  Sorry for the confusion.
