### ISSUE TITLE
hxcpp compatibility with haxe versions

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hxcpp#257]
Hugh, I notice that newer versions of hxcpp is compatible with older versions of haxe. So I guess this is intentional, right?
Do you have a minimal version of haxe want to support?
I'm just thinking of to expand the TravisCI build matrix to test for different haxe versions.

**Comment by hughsando** [comment]
Hey.  I know this is an old issue, but I would like to maintain compatibility - probably 1 version, or about a year.  Do you have any thoughts on having a 3.2.1 test set running against the git hxcpp?
