### ISSUE TITLE
Bad C++ produced for Null<haxe.Int64> constructs

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#267]
Probably this is a general problem with abstract types and Null<>, but I've only bothered to reproduce it with haxe.Int64.  Example:

```
class Foo
{
    public static function main()
    {
        var a : Null<haxe.Int64> = haxe.Int64.ofInt(1);
        var b : Null<haxe.Int64> = haxe.Int64.ofInt(1);

        var c = haxe.Int64.sub(a, b);
    }
}
```

<pre>
bji/bug_demo$ haxe -cpp Foo-cpp -main Foo
...
Error: ./src/Foo.cpp: In static member function 'static Void Foo_obj::main()':
./src/Foo.cpp:40:28: error: 'class Dynamic' has no member named 'get'
   cpp::Int64Struct c = ((a.get()) - (b.get()));  HX_STACK_VAR(c,"c");
                            ^
./src/Foo.cpp:40:40: error: 'class Dynamic' has no member named 'get'
   cpp::Int64Struct c = ((a.get()) - (b.get()));  HX_STACK_VAR(c,"c");
</pre>

**Comment by hughsando** [comment]
I think this is a general problem with ``Null<Struct<T> >```.  May need a
haxe compiler fix to sort out.

**Comment by hughsando** [comment]
I reworked the way Int64 externs are done, and this should be fixed now.
