### ISSUE TITLE
HXCPP_VISIT_ALLOCS and static_link

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [HaxeFoundation/hxcpp#269]
I was trying to make a more complex app with a hxcpp project compiled to a library based on [ExampleMain.cpp](https://github.com/HaxeFoundation/hxcpp/blob/master/src/ExampleMain.cpp).

I had the problem that, whenever I copied an object the "mPtr" member of the copy gets set to 0.

After trying around a lot, I found that the build command in the commands of [ExampleMain.cpp](https://github.com/HaxeFoundation/hxcpp/blob/master/src/ExampleMain.cpp) needed to have "-DHXCPP_VISIT_ALLOCS" added, and  the problem would be solved.

What is the reason for this?
Also, I think the comment in ExampleMain.cpp should be updated.

Edit: I am on linux64 using hxcpp form haxelib and haxe 3.2.0

**Comment by hughsando** [comment]
I think the difference between this ExampleMain and code the uses ".mPtr" is that this ExampleMain does not include "hxcpp.h".  As soon as you include this file, you need to ensure that the compilation flags match the flags the were used when the library was generated.
Particularly, you will also need the HXCPP_API_LEVEL.  I will have a think about how to make this easier to manage.
