### ISSUE TITLE
haxe 3.2 compiler fails to compile Map with object type as key

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#273]
Example code:

```
class Foo
{
    public static function main()
    {
        new Map<Foo, Int>();
    }
}
```
<pre>
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.2" -Dhxcpp_api_level=
"321" -I"/home/bji/bug_demo/" -I"" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/sha
re/haxe/std/"
ESC[33;1mg++ESC[0m ESC[0m-IincludeESC[0m ESC[0m-cESC[0m ESC[0m-fvisibility=hidde
nESC[0m ESC[0m-O2ESC[0m ESC[0m-fpicESC[0m ESC[0m-fPICESC[0m ESC[1m-DHX_LINUXESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[1m-DHXCPP_VISIT_ALLOCSESC[0m ESC[1m-DHXCPP_API_LEVEL=321ESC[0m ESC[0m-m64ESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[0m-I/usr/lib/haxe/lib/hxcpp/3,2,102/includeESC[0m ESC[0m-xESC[0m ESC[0mc++ESC[0m ESC[0m-frttiESC[0m 
ESC[0m-Wno-invalid-offsetofESC[0m ESC[33m./src/haxe/ds/ESC[33;1mObjectMap.cppESC[0m ESC[0m-oobj/linux64/f2cbc6b9_ObjectMap.oESC[0m
ESC[33;1mg++ESC[0m ESC[0m-IincludeESC[0m ESC[0m-cESC[0m ESC[0m-fvisibility=hiddenESC[0m ESC[0m-O2ESC[0m ESC[0m-fpicESC[0m ESC[0m-fPICESC[0m ESC[1m-DHX_LINUXESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[1m-DHXCPP_VISIT_ALLOCSESC[0m ESC[1m-DHXCPP_API_LEVEL=321ESC[0m ESC[0m-m64ESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[0m-I/usr/lib/haxe/lib/hxcpp/3,2,102/includeESC[0m ESC[0m-xESC[0m ESC[0mc++ESC[0m ESC[0m-frttiESC[0m 
ESC[0m-Wno-invalid-offsetofESC[0m ESC[33m./src/ESC[33;1m__boot__.cppESC[0m ESC[0m-oobj/linux64/469a59a9___boot__.oESC[0m
ESC[33;1mg++ESC[0m ESC[0m-IincludeESC[0m ESC[0m-cESC[0m ESC[0m-fvisibility=hiddenESC[0m ESC[0m-O2ESC[0m ESC[0m-fpicESC[0m ESC[0m-fPICESC[0m ESC[1m-DHX_LINUXESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[1m-DHXCPP_VISIT_ALLOCSESC[0m ESC[1m-DHXCPP_API_LEVEL=321ESC[0m ESC[0m-m64ESC[0m ESC[1m-DHXCPP_M64ESC[0m ESC[0m-I/usr/lib/haxe/lib/hxcpp/3,2,102/includeESC[0m ESC[0m-xESC[0m ESC[0mc++ESC[0m ESC[0m-frttiESC[0m 
ESC[0m-Wno-invalid-offsetofESC[0m ESC[33m./src/ESC[33;1mFoo.cppESC[0m ESC[0m-oobj/linux64/469a59a9_Foo.oESC[0m
ESC[31mESC[1mError:ESC[0m ESC[1mIn file included from ./src/__boot__.cpp:4:0:
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, null)':
include/haxe/ds/ObjectMap.h:39:66: error: 'h' was not declared in this scope
   inline void set(Dynamic key, ::null value) { __object_hash_set(h,key,value); }
                                                                  ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, bool)':
include/haxe/ds/ObjectMap.h:40:64: error: 'h' was not declared in this scope
   inline void set(Dynamic key, bool value) { __object_hash_set(h,key,value); }
                                                                ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, char)':
include/haxe/ds/ObjectMap.h:41:68: error: 'h' was not declared in this scope
   inline void set(Dynamic key, char value) { __object_hash_set_int(h,key,value); }
                                                                    ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, unsigned char)':
include/haxe/ds/ObjectMap.h:42:77: error: 'h' was not declared in this scope
   inline void set(Dynamic key, unsigned char value) { __object_hash_set_int(h,key,value); }
                                                                             ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, signed char)':
include/haxe/ds/ObjectMap.h:43:75: error: 'h' was not declared in this scope
   inline void set(Dynamic key, signed char value) { __object_hash_set_int(h,key,value); }
                                                                           ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, short int)':
include/haxe/ds/ObjectMap.h:44:69: error: 'h' was not declared in this scope
   inline void set(Dynamic key, short value) { __object_hash_set_int(h,key,value); }
                                                                     ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, short unsigned int)':
include/haxe/ds/ObjectMap.h:45:78: error: 'h' was not declared in this scope
   inline void set(Dynamic key, unsigned short value) { __object_hash_set_int(h,key,value); }
                                                                              ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, int)':
include/haxe/ds/ObjectMap.h:46:67: error: 'h' was not declared in this scope
   inline void set(Dynamic key, int value) { __object_hash_set_int(h,key,value); }
                                                                   ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, unsigned int)':
include/haxe/ds/ObjectMap.h:47:76: error: 'h' was not declared in this scope
   inline void set(Dynamic key, unsigned int value) { __object_hash_set_int(h,key,value); }
                                                                            ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, float)':
include/haxe/ds/ObjectMap.h:48:71: error: 'h' was not declared in this scope
   inline void set(Dynamic key, float value) { __object_hash_set_float(h,key,value); }
                                                                       ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, double)':
include/haxe/ds/ObjectMap.h:49:72: error: 'h' was not declared in this scope
   inline void set(Dynamic key, double value) { __object_hash_set_float(h,key,value); }
                                                                        ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, String)':
include/haxe/ds/ObjectMap.h:50:75: error: 'h' was not declared in this scope
   inline void set(Dynamic key, ::String value) { __object_hash_set_string(h,key,value); }
                                                                           ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, const cpp::Struct<T, S>&)':
include/haxe/ds/ObjectMap.h:54:84: error: 'h' was not declared in this scope
   inline void set(Dynamic key, const ::cpp::Struct<V,H> &value) {__object_hash_set(h,key,value); }
                                                                                    ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, const cpp::Function<T>&)':
include/haxe/ds/ObjectMap.h:56:84: error: 'h' was not declared in this scope
   inline void set(Dynamic key, const ::cpp::Function<V> &value) {__object_hash_set(h,key,(Dynamic)value ); }
                                                                                    ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, const cpp::Pointer<T>&)':
include/haxe/ds/ObjectMap.h:56:84: error: 'h' was not declared in this scope
   inline void set(Dynamic key, const ::cpp::Function<V> &value) {__object_hash_set(h,key,(Dynamic)value ); }
                                                                                    ^
include/haxe/ds/ObjectMap.h: In member function 'void haxe::ds::ObjectMap_obj::set(Dynamic, const cpp::Pointer<T>&)':
include/haxe/ds/ObjectMap.h:58:83: error: 'h' was not declared in this scope
   inline void set(Dynamic key, const ::cpp::Pointer<V> &value) {__object_hash_set(h,key,(Dynamic)value ); }
                                                                                   ^ESC[0m
Error: Build failed
</pre>

**Comment by thomasuster** [comment]
This would make a great unit test.

**Comment by bjitivo** [comment]
You know, I'm starting to suspect my local config, as I'm having a time compiling any code using any map type, even explicit map types like haxe.ds.StringMap ...

**Comment by bjitivo** [comment]
Hm, I looked at the latest source for the haxe standard libraries on HaxeFoundation/haxe, and apparently https://github.com/HaxeFoundation/haxe/commit/7ff9b212782c1224c5c6a93d0a8a784badb836c0#diff-d7908e86fdb9aaf1cb1388c378400c7d brought in a change that looks like it might address this.

Am I to believe that the stock Haxe 3.2 release doesn't work with the newest hxcpp haxelib, the one that I get when I do "haxelib install hxcpp"?

**Comment by bjitivo** [comment]
OK so yeah I made the same @:ifFeature changes to all of the map classes in my local version of the haxe 3.2 standard library, and now things work.

So I guess it is true that stock Haxe 3.2 doesn't actually work with stock hxcpp.  Is anybody steering this ship?  It feels like it's drifting ...

**Comment by thomasuster** [comment]
I'm not sure, but what I meant was if you fork HXCPP, and create a test with the code you have above in the test suite, then when you push your commit travis should fail on your fork. If it doesn't fail then it's something local.

**Comment by thomasuster** [comment]
There actually is a test for ObjectMap, so I think maybe you're having a local problem.

https://github.com/HaxeFoundation/hxcpp/blob/master/test/haxe/TestObjectHash.hx

**Comment by thomasuster** [comment]
Actually I take that back, the travis script is using latest haxe in the .travis script.

**Comment by Simn** [comment]
@waneck: This might be something for the 3.2.1 branch: https://github.com/HaxeFoundation/haxe/commit/7ff9b212782c1224c5c6a93d0a8a784badb836c0#diff-d7908e86fdb9aaf1cb1388c378400c7d

**Comment by ncannasse** [comment]
@bjitivo the issue was detected after 3.2 release and to my knowledge is related to DCE in case you use a Map without any code actually using any StringMap. I don't think it's related to HxCPP library. It has been fixed on GIT and we expect to release a 3.2.1 in the following weeks along with some other bugfixes. Hope that helps

**Comment by bjitivo** [comment]
As far as not being related to hxcpp, I would like to note that the same code compiles fine for JS and Neko.  The bug may be in the front end and it's just hxcpp that is structured in such a way to be affected by it.

**Comment by Simn** [comment]
This issue has been addressed.
