### ISSUE TITLE
Cannot convert 'null' to 'hx::Object *'

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#274]
I've been using CFFI prime a bit, and have noticed this error occur when building.

I believe that a null value in the code does not convert to the hx::Object* type, so if you have an "o" in the signature, but pass a null, there is a compile error. Do we just need a conversion added to hx::Object?

**Comment by hughsando** [comment]
Null converts to any pointer now, so this should be fixed.
