### ISSUE TITLE
cpp.Pointer issues with Map and anonymous objects

### ISSUE THREAD

**Issue by KeyMaster-** [HaxeFoundation/hxcpp#276]
I've been making native bindings for cpp classes and I've run into two problems when using the `::cpp::Pointer<T>` class:
- Using any cpp.Pointer type as the key type for maps results in `.get` and `.exists` calls not working (at least those are the ones I've tested).
- When I have an anonymous object with a field of the cpp.Pointer type and try to use `==` on it, the build fails due to the use of the overloaded operator being ambiguous.

I've created an isolated test case that demonstrates this, the files all go into one folder:
(_You'll have to replace `/Users/tschmidt/dev/code/haxe/cppPointerTest/` with your path to the project folder in files.xml and Test.hx_)

Main.hx
```
package ;

class Main {
    public static function main() {
        var t = Test.create();
        trace(t);

        var map = new Map<Test, Int>();
        map.set(t, 5);
        trace(map);
        trace(map.exists(t)); // Returns false

        var anon:Anon = {
            t:t
        }
        trace(anon);
        // The following will fail during the build
        // trace(anon.t == t);
    }
}

typedef Anon = {
    t:Test
}
```

Test.hx
```
@:buildXml('<include name="/Users/tschmidt/dev/code/haxe/cppPointerTest/files.xml" />')
@:include('./Test.h')
@:native('::cpp::Pointer<Test>')
extern class Test {
    public static inline function create():Test {
        return cast untyped __cpp__('::cpp::Pointer<Test>(new Test())');
    }

    @:native('get_raw()->val')
    var val:Int;
}
```

Test.h
```
class Test {
    public:
        Test() {
            val = 0;
        }
        
        int val;
};
```

files.xml
```
<xml>
    <files id="cppPointerTest">
        <compilerflag value="-I/Users/tschmidt/dev/code/haxe/cppPointerTest"/>
    </files>

    <files id="haxe">
        <compilerflag value="-I/Users/tschmidt/dev/code/haxe/cppPointerTest"/>
    </files>

    <files id="__main__">
        <compilerflag value="-I/Users/tschmidt/dev/code/haxe/cppPointerTest"/>
    </files>

    <target id="haxe">
        <files id="cppPointerTest"/>
    </target>
</xml>
```

build.hxml
```
-main Main
-cpp cpp/
-cmd cpp/Main
```

**Comment by hughsando** [comment]
The map one is failing I think because it is wrapping the pointer in a
Dynamic and then comparing the Dynamics, which will fail because of
different wrappings.  I think this is going to need a new type of map, like
a ```PointerMap<T,V>```.

The operator== should not be too hard to fix.

**Comment by hughsando** [comment]
There is no plan to support cpp.Pointer as keys to maps.
The best way of doing this at the moment is with a String representation of the pointer, which should act like a unique key.
