### ISSUE TITLE
Cannot return null HxString using CFFIPrime

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#278]
The following code is crashing on OS X:

```cpp
const char* path = 0;
return HxString (path);
```

I've tried other combinations -- the only thing that works is passing an empty string (like `HxString (0, 0)`) but I cannot get a null string to pass without a crash

**Comment by jgranick** [comment]
For the moment, I've had to replace my `return HxString` values with `return path ? alloc_string (path) : alloc_null ();` to work around the issue, the headers probably need something similar somewhere?

**Comment by hughsando** [comment]
Should be fixed by https://github.com/HaxeFoundation/hxcpp/commit/c2e08141437b8682c0b759075207ee7eae28a93f
