### ISSUE TITLE
Cannot rebuild hxcpp on Mac OSX

### ISSUE THREAD

**Issue by Hasufel** [HaxeFoundation/hxcpp#279]
Hi,
when trying to rebuild hxcpp from source on Mac OSX with a `neko build.n clean`
I'm getting
```
haxelib run hxcpp Build.xml clean -DHXCPP_CLEAN_ONLY
Error: Could not find build target "std"
#### Error cleaning
```
and same goes with (specifying or not specifying mac) `neko build.n`:
```
Error: Could not find build target "std"
#### Error building neko -Dmac -DHXCPP_M64 
```
Any help would be appreciated! Thank you.

**Comment by hughsando** [comment]
Have you tried rebuilding the hxcpp.n and build.n scripts?
This is done by running haxe in the tools/hxcpp and tools/build directories.

**Comment by Hasufel** [comment]
Hi Hugh, thx! That did the trick. Maybe add this to the instructions? Thanks again!
