### ISSUE TITLE
Comparing object to integer zero

### ISSUE THREAD

**Issue by maxless** [HaxeFoundation/hxcpp#28]
Comparing object to a numeric zero equals to true in case of HXCPP. The same thing produces false in Neko target.

```
class Test
{
  public function new()
    {}


  public static function main()
    {
      var o: Dynamic = { test: 1 };
      trace(o == 0);
    }
}
```

On Neko:
```
Test.hx:10: false
```

On c++:
```
Test.hx:10: true
```

C++ version can be traced to the following lines in Object.h:
```
   virtual int __ToInt() const { return 0; }
   virtual double __ToDouble() const { return 0.0; } // this one but the one above is probably used for something
```

IMHO it's better to have the same code produce the same result in both Neko and HXCPP. Maybe this can be changed to return a NaN? Or to produce an exception?

**Comment by hughsando** [comment]
Thanks for the report - should be fixed now.
