### ISSUE TITLE
HTTP Request doesn't work for CPP

### ISSUE THREAD

**Issue by smks** [HaxeFoundation/hxcpp#290]
package;

	import cpp.Lib;
	import haxe.Http;

	class Main 
	{
		static private var http:haxe.Http;
		
		static function main() 
		{
			makeHttpRequest();
		}
		
		static private function makeHttpRequest() 
		{
			var url:String = 'http://jsonplaceholder.typicode.com/posts/1';
			
			http = new Http(url);
		
			trace("making request to " + url);
			
			http.onData = function(status) {
				trace('received success response');
				trace(status);
			};
			
			http.onError = function(status) {
				trace('received error response');
				trace(status);
			};
			
			http.onStatus = function(status) {
				trace('received different status');
				trace(status);
			};

            http.request(false);
			
			Sys.sleep(3);
			
			trace(http.responseData);
		}
		
	}

**Comment by thomasuster** [comment]
I doubt this would fix it, but it's a good practive to call .request after setting your callbacks.

**Comment by hughsando** [comment]
Seems to work for me - maybe a firewall or DNS issue?
Also, you do not need the sleep, the http request will block until it completes.

**Comment by smks** [comment]
Yeah it works. Turned off firewall :|
