### ISSUE TITLE
VS2015 Compiler error c2208 compiling any luxe project

### ISSUE THREAD

**Issue by mrcdk** [HaxeFoundation/hxcpp#295]
I can't compile any luxe project using the latest hxcpp release because it throws this error:

```
include\phoenix/Camera.h(51) : error C2208: 'double' : no members defined using this type
include\phoenix/Camera.h(52) : error C2208: 'double' : no members defined using this type
```

These are the two lines referenced by the error:
```
        Float near;
        Float far;
``` 

The full `Camera.h` is here http://pastebin.com/Gp4HJyUp

I can compile just fine any OpenFL project and hxcpp, Lime and snow libraries.

This commit is the one that triggers the error https://github.com/HaxeFoundation/hxcpp/commit/55fc6eae8cf99d7c1efc1955af2faade482441c3

**Comment by hughsando** [comment]
I stopped including windows.h in the haxe files - I think this should fix the problem.

**Comment by mrcdk** [comment]
Yes, that fixed the issue, thanks :smile:
