### ISSUE TITLE
Hard crash with latest HXCPP related to array null checks

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/hxcpp#296]
This code:

```Haxe
var a = new Array<Array<Int>> ();
a.push (null);
var b = (a[0] != null);
```

Should reproduce the error. The third line will result in a hard crash without any haxe-level exceptions thrown.

Seems related to this change maybe?

https://github.com/HaxeFoundation/hxcpp/commit/67d9fb716afb5ea851728f91eff15f0dbae6e36c

**Comment by jcward** [comment]
Interesting, so the outer array type should be nullable (`Array<Int>`), while the inner array type should be simple (`Int`). And you think maybe the POD (plain old data) detection logic maybe got confused?

@hughsando - ooh, is this commit related to my inquiries into `Map<Int>` requiring a dynamic cast / request for POD accessor? Looks tasty.

**Comment by larsiusprime** [comment]
@hughsando Cool, thanks :) Should I switch to hxcpp dev for now or will you put out a quick patch to the haxelib version?

**Comment by thomasuster** [comment]
Builds are automatic. You can download version here. http://nmehost.com/hxcpp/
```
haxelib install ~/Downloads/hxcpp-3.2.178.zip
```

**Comment by larsiusprime** [comment]
Ah cool, thanks :)

**Comment by hughsando** [comment]
I will do a release in the next day or two - might look to sort out some vs2015 issues first.
