### ISSUE TITLE
Autogenerated Visual C++ project for debuging?

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#302]
We have found a crash and hang on the hxcpp Garbage Collector using openfl 3.3.6 and hxcpp 3.2.171.
We were able to pinpoint the faulting code to GCInternal.cpp inside the BlockData::init() method.
Before trying to create a simple case to reproduce the error (the bug only happens under heavy memory usage in our project) I was wondering if there was some way to debug the C++ generated code.

I was under the impression than with old NME an automatically generated project was created for this, but I can be wrong. Is this option available?

**Comment by james4k** [comment]
Don't necessarily need a project. Attach to the process, use JIT debugging, or start the debugger from a command prompt `devenv program.exe` (need the PATH setup with vsvars32.bat or whatever).

**Comment by james4k** [comment]
You might be interested in #303

**Comment by ex** [comment]
Thank! I'm planning to create a project manually, adding the required flags. 
Regarding the other bug, I'll comment there.
