### ISSUE TITLE
GC Error on Android with Debug

### ISSUE THREAD

**Issue by francoisvn** [HaxeFoundation/hxcpp#312]
When I compile for Android with debug on and create a new thread, I get the following error: `Critical Error: Allocating from a GC-free thread`. I am using OpenFL, but I believe the issue is with hxcpp (hence this issue), although I could be wrong.

I traced the error back to `Immix.cpp` and it seems like an assert-like check that is failing. I'm not very familiar with the hxcpp code base, so I figured it would be easier to report the issue and see if perhaps someone more familiar can quickly identify the cause.

Workaround: if I give g++ the flag `-UHXCPP_DEBUG` to basically turn off debug just for hxcpp, then the issue disappears. For now I selectively give this flag via `~/.hxcpp_config.xml`

There is also this related issue in OpenFL, which I believe is just this underlying issue manifesting: https://github.com/openfl/openfl/issues/707

**Comment by hughsando** [comment]
This fix was put in shortly after the 3.2.180 release:
https://github.com/HaxeFoundation/hxcpp/commit/dc950dbe0ac379494695fc3ca592b3b3e600f63f

You could try the git version, or a version from http://nmehost.com/hxcpp/ and see if this fixes your issue.

**Comment by thomasuster** [comment]
For nmehost download http://nmehost.com/releases/hxcpp/hxcpp-3.2.186.zip
Then do
```haxelib install ~/Downloads/hxcpp-3.2.186.zip```

**Comment by francoisvn** [comment]
I finally got time to try 3.2.186. It seems to fix the issue I raised, but now it has a "hard" stall sometimes (previously it was a crash). This _could_ be due to a concurrency issue somewhere else in my project (it's always hard to say), but it seems to be happening when there is only the main thread and not when I spawn off a worker thread.

This happens on Android, but not Linux native. My instinct tells me it's probably something in the GC stalling, but it's super difficult to say.

**Comment by francoisvn** [comment]
I tried build 3.2.188 now and it seems like it works, so there must have been a bug introduced between 180 and 186 that was fixed between 186 and 188. Not sure if it it worth mentioning and/or if it warrants a look, but I thought I'd mention it

Keep up the good work devs :)

**Comment by thomasuster** [comment]
Sweet, if your issue is resolved please close.
