### ISSUE TITLE
hxcpp libz linking problems

### ISSUE THREAD

**Issue by d1ss** [HaxeFoundation/hxcpp#313]
I'm trying to use haxe-created static library in our cross-platform game engine. I compiled the lib for both ios and android but have several issues when linking it. As the haxe-created lib requires it's own libz, std and regex, I link them to my ios project. My project also uses libz (from iPhoneIos sdk) so I get conflicts in runtime - libpng presumably refers the libz stuff from haxe's libz and it leads to bugs. Ok, on ios this can be fixed by changing the linking order in Xcode (system libz must be linked first) but it seems to be a very insecure solution.

On android I just get many "multiple definition of ..." for symbols defined both in system's libz and haxe's libz.
How should I link it all together)?

I use -D static_link in my target's hxml.
MacOS 10.11, hxcpp 3,2,180, Haxe Compiler 3.2.0, NekoVM 2.0.0

**Comment by thomasuster** [comment]
Do you ever get an android error that says ```has unexpected e_machine: 3```?

**Comment by d1ss** [comment]
No, just linker's multiple definition errors

**Comment by hughsando** [comment]
I have added an optional define, "-D HXCPP_LINK_NO_ZLIB".  If you provide this to the haxe command line and import "hxcpp.StaticZlib", you can and must provide your own version of zlib when linking your final application.

**Comment by d1ss** [comment]
Hi Hugh

Thank you for fixing this, it works for me!
