### ISSUE TITLE
hxcpp fails to generate compilable code with semi-complex interface property hierarchy

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#314]
This fails with the current top-of-trunk hxcpp (@ ff2fa80).

I narrowed it down to this simple test case.  It's possible that a simpler interface hierarchy could also cause this bug, but this was the simplest case I could find.

```
class Foo implements SubInterface
{
    public var property(get, never) : Bool;

    public function get_property() : Bool
    {
        return false;
    }

    public static function main()
    {
    }
}


interface SubInterface extends IntermediateInterface
{
}


interface IntermediateInterface extends SuperInterface extends RootInterface
{

}


interface SuperInterface
{
    var property(get, never) : Bool;
}


interface RootInterface
{
}
```

<pre>
bji/bug_demo$ haxe -cpp Foo-cpp -main Foo
haxelib run hxcpp Build.xml haxe -Dhaxe3="1" -Dhaxe_ver="3.201" -Dhxcpp_api_level="321" -I"" -I"/usr/share/haxe/std/cpp/_std/" -I"/usr/share/haxe/std/"
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/Std.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_Std.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/Foo.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_Foo.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/IntermediateInterface.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_IntermediateInterface.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/RootInterface.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_RootInterface.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/SubInterface.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_SubInterface.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/__boot__.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9___boot__.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/SuperInterface.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9_SuperInterface.o
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/usr/lib/haxe/lib/hxcpp/git/include -x c++ -frtti -Wno-invalid-offsetof ./src/__files__.cpp -o/home/bji/bug_demo/Foo-cpp/obj/linux64/469a59a9___files__.o
Error: ./src/Foo.cpp: In member function 'Foo_obj::operator SubInterface_obj*()':
./src/Foo.cpp:46:55: error: cannot allocate an object of abstract type 'SubInterface_delegate_<Foo_obj>'
  { return new ::SubInterface_delegate_< Foo_obj >(this); }
                                                       ^
In file included from include/Foo.h:9:0,
                 from ./src/Foo.cpp:4:
include/SubInterface.h:27:7: note:   because the following virtual functions are pure within 'SubInterface_delegate_<Foo_obj>':
 class SubInterface_delegate_ : public SubInterface_obj
       ^
In file included from include/SubInterface.h:9:0,
                 from include/Foo.h:9,
                 from ./src/Foo.cpp:4:
include/IntermediateInterface.h:24:16: note:    virtual bool IntermediateInterface_obj::get_property()
   virtual bool get_property( )=0;
                ^
include/IntermediateInterface.h:25:17: note:    virtual Dynamic IntermediateInterface_obj::get_property_dyn()
 virtual Dynamic get_property_dyn()=0;
                 ^
Error: Build failed
</pre>

**Comment by thomasuster** [comment]
If you're feeling extra awesome, you could also add this as a test case in the haxe test. 

https://github.com/HaxeFoundation/hxcpp/tree/master/test/haxe

Maybe test/haxe/compile/TestComplexIntercace.hx

**Comment by thomasuster** [comment]
Does this work in other haxe targets? 
```interface IntermediateInterface extends SuperInterface extends RootInterface```

**Comment by bjitivo** [comment]
Works fine for neko and js targets.  Haven't tried others.

**Comment by bjitivo** [comment]
To be honest, I don't understand why gencpp.ml generates _dyn() functions for interface properties.  Shouldn't a runtime reference to an interface function get the implementation _dyn() function, not the interface _dyn() function?  It would seem to me that interfaces never need _dyn() functions to be generated for properties.

**Comment by hughsando** [comment]
Re:_dyn on interfaces.  The implementation does come from the implementing object - but without a vtable entry on the interface it must look up the function by name (as it did in 3.1).
You can restore this behaviour with "-D dynamic_interface_closures"

**Comment by bjitivo** [comment]
I tried the -D dynamic_interface_closures option and it didn't prevent this bug from occurring.  So the issue is still a problem for us.  Thanks.

**Comment by hughsando** [comment]
The " -D dynamic_interface_closures" is only to cut down the virtual functions that may be considered " unnecessary and wasteful" if you are not concerned about speed in the ```var func = iobj.doSomething;``` case.

However, I recently made a commit https://github.com/HaxeFoundation/haxe/commit/55529ebebc13de3b0a004a3472d646b4d5eb40ab and this test case now appears to compile ok.

**Comment by hughsando** [comment]
The interface implementation has completely changed for haxe 3.3, and this seems to be working now, so I'm going to close this one.
