### ISSUE TITLE
<flag value="-stdlib=libstdc++" unless="HXCPP_GCC" /> breaks on Lion

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/hxcpp#32]
please revert or find alternative for change

https://github.com/HaxeFoundation/hxcpp/commit/d0fc29ba319e9aab9eda4d2afa8de381a50c9fb2#diff-15e66de6f57c543a27161a3adbc163ab

Since on Lion for atleast two users it breaks compile, it results in the following compile error.

cc1plus: error: unrecognized command line option "-stdlib=libstdc++"

If I comment out line 15 in mac-toolchain.xml eg:
flag value="-stdlib=libstdc++" unless="HXCPP_GCC"
( see googlecode submitted bug for clarity ) 

code will now compile this was verified by another user who following my instruction and was able to use the c++ target.

The user with problems suggested we could look at Travis for mac to avoid these regression issues, but the link only seems to have 10.8.  

http://docs.travis-ci.com/user/osx-ci-environment/

But maybe we can run over how travis works at wwx and I can do tests on each new hxcpp release if that is possible I have not read up on what exactly Travis is just seem to hear a lot about it.

( just reported on googlecode as well but just realized that repository is probably dead now http://code.google.com/p/hxcpp/issues/detail?id=268 )

**Comment by hughsando** [comment]
I think the config provides the solution.  Closing this one now.
