### ISSUE TITLE
Controlling how much time is spent in the GC

### ISSUE THREAD

**Issue by tanis2000** [HaxeFoundation/hxcpp#326]
Hi!

Is there a way to tell hxcpp how much time the GC should spend doing its work when it kicks in?
The reason is that I noticed that some libraries that I use make a heavy use of temporary variables and when the GC kicks in, it takes quite some time to collect and dispose them. That way, the simulation I'm running has some stuttering every time the GC starts doing its job. 

I suppose that the reason is that it kicks in at, let's say every 200ms and it takes something like 300ms to collect the garbage and in the meanwhile the rendering loop of the simulation is loosing cycles thus leading to a visual effect of the animation stuttering.

It would be nice if there was a way to tell the GC to pause what it's doing after a set amount of time so that I can give more time to the simulation and less to the GC itself.

Thanks!

**Comment by hughsando** [comment]
The pause time is related to the number of "live" objects you have.
The pause frequency is related to the amount of memory allocated and the amount of "working memory" you have.  So to improve things, you can:
1. Reduce the number of live objects you have.  This usually involves avoiding caching large amounts of data such as XML, or not using object pools.
2. Decrease the amount you allocate.  This can be tricky - but sometimes it can be something simple that is cause most of the problems.  See the hxtelemetry project some some hints in this direction.
3. Increase the working memory.  This wont decrease the pause time (stutter), but will improve the fraction of the time spent collecting.  You can paste in some code from https://github.com/HaxeFoundation/haxe/commit/9c9ab92895b781c1cb14fd83389782c162632df3 to setMinimumFreeSpace bigger.
300ms sounds like a very long time for collection, so I think point 1 might be be most interesting.

You can un-comment the "PROFILE_COLLECT" define in src/hx/gc/Immix.cpp to see some of the times.

**Comment by tanis2000** [comment]
Thanks Hugh, they're all good suggestions.

I've already done some optimizations. I increased the working memory and that surely helped. Of course now the problem shifted to when there are too many objects allocated.

In my case I'm using object pools and it's a good fight to whether use it or not as there are pros and cons both way.

I enabled PROFILE_COLLECT and the times aren't as bad as they were before, but with a lot of moving objects it starts to show that stuttering effect.

I'm pasting the latest times from the profiler of hxcpp as a reference:

```
Collect time total=4.51ms =0.2% sync=0.00, mark=2.15, large=0.48, block=1.78
Collect time total=42.21ms =2.0% sync=0.00, mark=39.32, large=0.36, block=2.21
Collect time total=17.79ms =1.5% sync=0.00, mark=15.48, large=0.00, block=2.07
Collect time total=19.71ms =1.7% sync=0.00, mark=17.16, large=0.00, block=2.31
Collect time total=27.56ms =2.3% sync=0.00, mark=25.06, large=0.00, block=2.26
Collect time total=8.17ms =0.7% sync=0.00, mark=5.65, large=0.00, block=2.27
Collect time total=27.22ms =2.3% sync=0.00, mark=24.66, large=0.00, block=2.33
Collect time total=31.52ms =2.6% sync=0.00, mark=28.60, large=0.00, block=2.64
Collect time total=25.50ms =2.2% sync=0.00, mark=22.90, large=0.00, block=2.24
Collect time total=33.90ms =2.8% sync=0.00, mark=31.06, large=0.00, block=2.63
Collect time total=25.58ms =2.2% sync=0.00, mark=23.16, large=0.00, block=2.18
Collect time total=34.01ms =2.8% sync=0.00, mark=31.26, large=0.00, block=2.52
Collect time total=27.41ms =2.3% sync=0.00, mark=24.79, large=0.00, block=2.38
Collect time total=29.46ms =2.5% sync=0.00, mark=26.97, large=0.00, block=2.24
Collect time total=23.04ms =1.9% sync=0.00, mark=20.48, large=0.00, block=2.32
Collect time total=34.95ms =2.9% sync=0.00, mark=29.91, large=0.00, block=4.82
Collect time total=34.44ms =2.8% sync=0.00, mark=31.55, large=0.00, block=2.60
Collect time total=30.56ms =2.6% sync=0.00, mark=27.78, large=0.00, block=2.49
Collect time total=26.11ms =2.2% sync=0.00, mark=23.54, large=0.00, block=2.33
Collect time total=34.41ms =2.9% sync=0.00, mark=31.55, large=0.00, block=2.58
Collect time total=8.29ms =0.7% sync=0.00, mark=5.67, large=0.00, block=2.38
Collect time total=27.92ms =2.3% sync=0.00, mark=25.25, large=0.00, block=2.43
Collect time total=25.70ms =2.2% sync=0.00, mark=23.28, large=0.00, block=2.18
Collect time total=10.52ms =0.9% sync=0.00, mark=7.62, large=0.00, block=2.61
Collect time total=24.36ms =2.0% sync=0.00, mark=21.70, large=0.00, block=2.42
```

Time, percentage and sync are self explanatory, but can you help me with the meaning of mark, large and block?

Cheers!

**Comment by thomasuster** [comment]
I found a decent way to optimize this was doing CPU profile on mac of your app (Launch your game, open empty xcode, open instruments, attach CPU profiler to running app). If you're getting frame stutter even on mac you should see the frameTime spike every time there is a collection. If you highlight this region it should give you the % of time it's spent iterating over certain objects. If you look at this for multiple GC collect regions you should see the pools your app is spending most of it's time marking. hxScout should also be able to track this, but I haven't tested it.
