### ISSUE TITLE
Linux cross-compile to windows, bad register name in GxRegCapture.cpp

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/hxcpp#331]
@jobs-git @hughsando - trying to test the cross-compiling merged in #304, I get the following error:

```
>haxe -D windows -main Main -cpp out
...
i686-w64-mingw32-g++ -D_CRT_SECURE_NO_DEPRECATE -DHX_UNDEFINE_H -c -O2 -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -DHX_WINDOWS -DHXCPP_M64 -I/home/jward/dev/hxcpp/include -x c++ -frtti /home/jward/dev/hxcpp/src/hx/gc/GcRegCapture.cpp -o/home/jward/dev/haxe_test/out/obj/mingw64/254d3248_GcRegCapture.o
Error: /tmp/ccIRALUv.s: Assembler messages:
/tmp/ccIRALUv.s:14: Error: bad register name `%rbx'
/tmp/ccIRALUv.s:18: Error: bad register name `%rbp'
/tmp/ccIRALUv.s:22: Error: bad register name `%r12'
/tmp/ccIRALUv.s:31: Error: bad register name `%r13'
/tmp/ccIRALUv.s:35: Error: bad register name `%r14'
/tmp/ccIRALUv.s:43: Error: bad register name `%r15'
Error: Build failed
```

It seems there are `asm('mov %%rbx')` commands in GcRegCapture, but it looks like they should be protected in the else clause of:

      #if !defined(__GNUC__)

Is (should?) `__GNUC__` being properly undefined for the windows compile?

**Comment by jobs-git** [comment]
-DHXCPP_M64, you are trying to cross-compile 64-bit its not yet supported, could you try 32bit cross-compilation?

**Comment by jcward** [comment]
haxe -D windows -D HXCPP_M32 -main Main -cpp out

Ok, that worked for my hello world test. Now to try cross-compiling a larger project. :)
