### ISSUE TITLE
Looks like cpp.vm.Gc.enable(false) does not actually do anything, again

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/hxcpp#337]
Hi. I am trying to disable Gc collect for some moments but  sgInternalEnable is not used.
It is the same issue as in https://github.com/HaxeFoundation/hxcpp/issues/26

Thanks!

**Comment by underscorediscovery** [comment]
I keep wishing for it too, but there is also more control over the collection window with the memory sizes recently added. You might be able to start with that in the mean time.

**Comment by hughsando** [comment]
What version of hxcpp are you using?
sgInternalEnable should be working.  It will still try do a collect if it would mean crashing otherwise.

**Comment by madrazo** [comment]
Sorry. I got confused because when searching "sgInternalEnable" in here it just showed the InternalEnableGC function. Thanks!

**Comment by underscorediscovery** [comment]
I'll note i've yet to try the disable flag since recent GC pushes on haxelib release, I didn't intend to add confusion. If it's working that's great!
