### ISSUE TITLE
Null function pointer is a hard crash (not caught by debugger)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/hxcpp#338]
```
    var func:Void->Void = null;
    func(); // Should throw, but hard crashes
```
Results in hard runtime crash:
```
Called from Main::main Main.hx line 24
Error : Null Function Pointer
```
Even with [HaxeFoundation/hxcpp-debugger](https://github.com/HaxeFoundation/hxcpp-debugger) attached. Ideally the debugger would catch this.

**Comment by hughsando** [comment]
This is thrown like a "normal" exception, which can be caught:
```
    try
    {
       var func:Dynamic = null;
       func(1);
    }
    catch(e:Dynamic)
    {
      trace("Error " + e);
    }
```
Can't remember the exact reasoning, but this is how neko works.
I will put in a special hook for the debugger so it can stop in this case.

**Comment by ncannasse** [comment]
In neko there is no "fatal error". Only exceptions. so you can for instance catch and report all errors without having access to the console. That's the same for JS or Java for example. Should we not allow the debugger to stop on exceptions (at the place they're raised)?

**Comment by hughsando** [comment]
I guess we need to separate the logic-errors (null function) from the expected exception ( stream.readLine()) or else the noise level might be too high.
