### ISSUE TITLE
mingw cross-compile to Windows, libwinpthread-1.dll is missing

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/hxcpp#339]
@jobs-git @hughsando I'm trying to cross-compile from Linux to Windows a CLI tool, and when I attempt to run the .exe on Windows, I get the error message:

- The program can't start because libwinpthread-1.dll is missing from your computer.

Looking around the web, it seems I may need to statically link this library in, but I'm not sure of the hxcpp arguments to do that. Is it possible? I tried adding `-D static_link` and it didn't help. My command line I'm using is:

```
haxe -cp src -main Main -cpp bin/windows -D windows -D HXCPP_M32 -D static_link
```

Thanks for any ideas.

**Comment by jobs-git** [comment]
Make sure you also got the complete headers and binaries for Mingw

Fedora:
     sudo yum install mingw32 mingw32-gcc-c++ mingw32-headers mingw32-crt mingw-winpthreads mingw32-cpp mingw32-filesystem

Ubuntu
    sudo apt-get install mingw-w64

If this has been completed already, the `libwinpthread-1` is automatically copied by Hxcpp to your project compile directory, try to copy it and place the file to your bin directory.

`bin` directory is unique for every project, so the best way for hxcpp to resolve this is to copy dependencies into project compile directory.

**Comment by jcward** [comment]
Ah, I see that both `Main.exe` and `libwinpthread-1.dll` file are delivered to my `bin/windows` output directory. So you're saying that I can deliver them together? I suppose that's workable for many cases.

But are there are no options to statically link the `libwinpthread-1.dll` into the output `Main.exe` so the result is a single executable file?

**Comment by jobs-git** [comment]
You could deliver them together. `libwinpthread-1.dll` should be were the `Main.exe` file is.

Static linking for `libwinpthread-1.dll` is not possible, until of course Mingw developers creates a fully static libwinpthread-1, but, unfortunately only a dynamic libwinpthread exists.

**Comment by jcward** [comment]
Ok, thanks for the info.
