### ISSUE TITLE
LD34 build fails in hxcpp only (js, neko, swf work)

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/hxcpp#340]
hxcpp doesn't like something about the syntax of my LD34 entry. There's some hackish stuff, admittedly (assigning closure functions to statics to make them accessible to other classes) as I built from scratch and refactored on-the-fly, but if it compiles into JS, SWF, and neko, I'd think it should work in hxcpp.

ld34 project: https://github.com/jcward/ld34

compile with any of:

`openfl test flash`
`openfl test html5`
`openfl test linux`

cpp first error: 
```
g++ -Iinclude -c -fvisibility=hidden -O2 -fpic -fPIC -DHX_LINUX -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -m64 -DHXCPP_M64 -I/home/jward/dev/hxcpp/include -x c++ -frtti -Wno-invalid-offsetof ./src/Game.cpp -o/home/jward/dev/ld34/Export/linux64/cpp/obj/obj/linux64/57588eaa_Game.o
Error: ./src/Game.cpp: In member function ‘Void Game_obj::__construct(openfl::display::Shape, openfl::display::Sprite, openfl::display::BitmapData, Float, Float, Float, Float, Float, openfl::display::BitmapData)’:
./src/Game.cpp:333:39: error: expected primary-expression before ‘,’ token
  HX_BEGIN_LOCAL_FUNC_S32(hx::LocalFunc,_Function_1_1,Float,W,Array< Float >,map_x,Array< Float >,bmy,::openfl::display::BitmapData,map,Float,W2,Float,H2,Float,SC,::openfl::media::Sound,death,::openfl::media::Sound,squeek,Array< int >,tap_state,Array< Float >,rotate,Array< Float >,dr,Array< Float >,bmx,::openfl::geom::Matrix,m,Float,H,Array< bool >,win,::openfl::display::BitmapData,bd,Array< Float >,bmr,Array< int >,growth,::openfl::media::Sound,bubbles,::openfl::display::Sprite,cont,Array< Float >,map_y,::Player,p,Array< Float >,acc,::openfl::display::Sprite,overlay,::openfl::media::Sound,success,Array< bool >,dead,::openfl::display::Shape,clear,Float,px_screen,Float,py_screen,Array< ::Dynamic >,powerups,Array< ::Dynamic >,sparks)
                                       ^
./src/Game.cpp:333:40: error: ‘_Function_1_1’ was not declared in this scope
  HX_BEGIN_LOCAL_FUNC_S32(hx::LocalFunc,_Function_1_1,Float,W,Array< Float >,map_x,Array< Float >,bmy,::openfl::display::BitmapData,map,Float,W2,Float,H2,Float,SC,::openfl::media::Sound,death,::openfl::media::Sound,squeek,Array< int >,tap_state,Array< Float >,rotate,Array< Float >,dr,Array< Float >,bmx,::openfl::geom::Matrix,m,Float,H,Array< bool >,win,::openfl::display::BitmapData,bd,Array< Float >,bmr,Array< int >,growth,::openfl::media::Sound,bubbles,::openfl::display::Sprite,cont,Array< Float >,map_y,::Player,p,Array< Float >,acc,::openfl::display::Sprite,overlay,::openfl::media::Sound,success,Array< bool >,dead,::openfl::display::Shape,clear,Float,px_screen,Float,py_screen,Array< ::Dynamic >,powerups,Array< ::Dynamic >,sparks)
...
etc
etc
```

I assume this is an hxcpp issue, @hughsando, but feel free to move this elsewhere.

**Comment by hughsando** [comment]
Yeah, way to many local variable captures for hxcpp.
Moving some of the local variables into member variables should solve the problem.
Not sure what the best solution is, since there could always be n+1 local captures.

**Comment by ncannasse** [comment]
@hughsando maybe use a specially generated tmp struct when there's more than X captures ?

**Comment by hughsando** [comment]
I could generate the code from the haxe compiler, rather than using
macros, but this would get messy.
The temp struct might keep some variables from being collected if two or
more closures operated on and intersection of variables, also tricky to
control the  scope of variables within the function, but I think it is the
best solution - mainly because it will be more efficient - having one
struct of variables, rather than many one-element arrays.
This might be a job for the core compiler, since I think it is applicable
to many targets.

Hugh

**Comment by ncannasse** [comment]
what about using only a structure for parameter passing ? You can then immediately move them into locals in function body. This should retain the current behavior for GC

**Comment by ncannasse** [comment]
Ah but if it's a closure it requires scanning the struct.

**Comment by ncannasse** [comment]
PS : I'm doing something similar in genSWF9

**Comment by jcward** [comment]
I'm sorry I keep breaking things. ;) I don't understand the details of the problem, but if it's hairy, a friendly error message about "too many local variables, move some to member variables" could be helpful in the short term.

Like I said, this is the result of messy, fast prototyping and refactoring for a timed game jam -- hopefully not typical use. I haven't had this problem in the actual products (hxscout and vscode-hxcpp-debug) I'm working on.

**Comment by hughsando** [comment]
I think 'typical' depends on your background - this a very javascript/ocaml
way of writing classes, so may come up against this depending on who is
using haxe.  I would like the solution to be in hxcpp, rather than in
gencpp.ml since I can change it more easily, but this means that any
compiler errors are going to get delayed until the actual c++ compile is
started.

**Comment by fullofcaffeine** [comment]
This hasn't affected me yet, but I'm curious, did we decide on a path to take here or does it still need to be discussed?

**Comment by hughsando** [comment]
There have been changes to the haxe compiler to remove the need for "return blocks", and this may have fixed this issue.  Hxcpp has also increased the number of capture vars for closures to easily handle this case, so this should now work.

**Comment by delahee** [comment]
@hughsando Sorry to bugger but maybe you could put a unit test on this one ?
