### ISSUE TITLE
Crashes on versions greater than 3.2.102

### ISSUE THREAD

**Issue by EduardoLopes** [HaxeFoundation/hxcpp#341]
On the snowkit chat, lot's of people have reported crashes when trying to build for native targets. What fix it is downgrade to hxcpp 3.2.102, the problem happens on windows, mac and linux, but for some reason, there's people who don't have any problem with latest versions.

I can't provide a way to reproduce the crash, but i have some [debug info](https://gist.github.com/EduardoLopes/b70bed027d03bb1b2f89) i got from a [luxe empty project](https://github.com/underscorediscovery/luxe/tree/master/samples/empty), the crash happens seconds after running (i'm using lubuntu 14.04 if that helps).

I have tried to run the hxcpp tests for `3.2.102` and `3.2.193` versions, but i'm on a 32 bits system, and i guess i'll need some help to run those tests in a 32 bits system.

Edit: [This is a log](http://pastebin.com/cGci3aqs) from a machine running Windows 10 having the same issue

**Comment by ncannasse** [comment]
It if's easily reproducible, you could bisect against hxcpp git to locate the offending commit, I'm sure that would help @hughsando

**Comment by EduardoLopes** [comment]
I started to compile from each commit since https://github.com/HaxeFoundation/hxcpp/commit/7a4ff7c6de2a2613787902936460e0dc14ad61c8. This is one commit before *Start on Gc code refactor*. It don't give me any error or crashes. 

Then i tried the commit when the GC code refactor started https://github.com/HaxeFoundation/hxcpp/commit/69ccf6f7c1f087793f42b28ffa170d5d180e4fd8, and i couldn't even compile it ([erro](https://gist.github.com/EduardoLopes/2a0a0228df0c5df162bf#file-debug-hxcpp-commit-69ccf6f7c1f087793f42b28ffa170d5d180e4fd8-md)).

Then i tried https://github.com/HaxeFoundation/hxcpp/commit/55fc6eae8cf99d7c1efc1955af2faade482441c3 commit, from here, it started to show a recurrent error involving `MarkAllocUnchecked` for all the next commits: [debug](https://gist.github.com/EduardoLopes/2a0a0228df0c5df162bf#file-debug-hxcpp-commit-55fc6eae8cf99d7c1efc1955af2faade482441c3-md). The program crashes after run it as well.

Then i tried lot's of others commits and got the same error as before, till the last commit in the history, here's the debug info: [debug](https://gist.github.com/EduardoLopes/2a0a0228df0c5df162bf#file-debug-hxcpp-commit-1c1283c6316be915e211c600fd5eb79e2f710e60-md)

I'm on Lubuntu 14.04 32 bits. HXCPP was compiled for each commit i have tried and the cache feature was not set. I cleaned up the luxe project bin folder each time i tried a different commit.

Hope this will help.

**Comment by hughsando** [comment]
There was a significant change in the GC implementation, so it is not a great surprise when things first started going wrong.
I tried a simple luxe project, an it seemed to work ok - for as long as I tried it.
So what I really need is a way to reproduce the problem.
Is the system memory showing a leak, or is the memory usage pretty small when you get the crash?

One thing you can try is changing Immix.cpp and set MAX_MARK_THREADS=1 at the top.
If this fixes the crash, then I know where to look.

Similarly, there is code in MarkObjectAllocUnchecked to call pushObj instead of marking recursively.  If you make this always recursive, then it eliminates some possible errors, like:  ```if ( true ||  block==__inCtx->block)```.

These changes can help isolate the sub-system where the problem might lie.  Also, they will make the collection more deterministic and give better stack dumps.

**Comment by underscorediscovery** [comment]
I've also been trying to reproduce this more deterministically, the thread mark count should help. I should have more time this coming week to dig into it as well, but much appreciate Eduardo and the others in the community digging as well.

**Comment by madrazo** [comment]
Maybe it is related: I had a crash when using function parameters with same name as class variables (It was incorrect anyway but it may be a clue). Changing names solved it.

Also looks like Gc.compact crashes some times. Furthermore, parsing XML has an issue when using telemetry (may be related to the creation of Dynamic objects?).

**Comment by EduardoLopes** [comment]
The memory is ok.

I tried the two suggestions, none seems to work and i got the exactly same debug error.

**Comment by EduardoLopes** [comment]
i forgot to run the backtrack command, here's the debug info when trying the `if ( true || block==__inCtx->block)` sugestion https://gist.github.com/EduardoLopes/6b9850a7af6fc9babb2f

**Comment by underscorediscovery** [comment]
@EduardoLopes and others
if testing against release, you can define HXCPP_DEBUG_LINK to have debug info in release.
Have you tried latest (3.2.203) from nmehost?
http://nmehost.com/hxcpp/

**Comment by EduardoLopes** [comment]
Just tried it and i got the same error. [Here's](https://gist.github.com/EduardoLopes/c3327dab819d15bed21e) the debug info just in case.

**Comment by hughsando** [comment]
Thanks for the debug - I can reproduce it easily with debug on.
