### ISSUE TITLE
Windows problem: fatal error C1061: compiler limit: blocks nested too deeply

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/hxcpp#343]
I triggered this issue with a string switch I am generating which had lots of cases:

cl.exe -Iinclude -nologo -O2 /WX- /fp:precise -DHX_WINDOWS -D_USING_V140_SDK71_ -GR -FS -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,2,193/include -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -DHX_WIN_MAIN -wd4996 -MT ./src/haxe/io/_Float32Array/Float32Array_Impl_.cpp -FoC:...
*fatal error C1061: compiler limit: blocks nested too deeply*

For what I have seen here:
http://www.openfl.org/archive/community/bugs/fatal-error-c1061-cpp-windows-target/

It is due to hxcpp is generating if else chains, for each case in that switch, which creates nested blocks because "else if" is just a else nesting an if.
I think that this issue should be fixed here at the hxcpp generation level.
A possible solution would be creating a function changing each if else with plain ifs which returned that function in each branch.
Also it could limit stuff using a switch with string length before checking each string.

Switch looks like that:
```
switch (name) {
	case 'V', 'B', 'C', 'S', 'I', 'L', 'J':
	case "all.rt.GenericListIterator": c0(c);
        case "all.rt.StdioInputStream": c2(c);
        // hundreds of cases
```

**Comment by hughsando** [comment]
Yes - tricky one.  If I switch on length first, then I would potentially need to duplicate some code blocks - which is possible. Other options include the good-old "goto", and switching on the hash of the string.
Meanwhile, maybe a Map<String, something> could solve the problem.

**Comment by hughsando** [comment]
The fix for this will likely come from haxe changes, so I'm joining this to this issue:
https://github.com/HaxeFoundation/haxe/issues/4865
