### ISSUE TITLE
Wrong data passed to finalizers expecting Pointer<T>

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/hxcpp#345]
When creating a finalizer for a native object, the Pointer<NativeObject> gets wrapped in a PointerData, which is passed to the finalizer instead of the Pointer<NativeObject>.

A hack to get around this is possible.  By exposing PointerData's mValue pointer to the finalizer using:
```
@:cppFileCode("namespace hx{ class PointerData : public hx::Object { public: void *mValue; };}")
```
a line can be inserted at the beginning of the finalizer to get the pointer data into the expected location:
```
untyped __cpp__('{0} = (::native::NativeObject *)((hx::PointerData *){0})->mValue', variable.ptr);
```
I don't know if the compiler should be inserting similar code, or if the hxcpp's garbage collector should be passing the correct data, but something seems to be incomplete here.

**Comment by hughsando** [comment]
hxcpp does not really know about externally allocated pointers, and does not keep track of references to the pointers for collection/finalization.
Not exactly sure what you are trying to do here, but typically, the pointer would be stored as a member is some class.  You would put the finalizer on this class, and then the class would delete the native object.
If you are storing the class in more than one haxe class, then you could use some kind of reference counting, or a haxe wrapper class.  The "alloc_abstract" code is basically a simple haxe object with a finalizer that frees the data.

**Comment by ckentgeorge** [comment]
I'm wrapping a native extern with an abstract.  In nearly every way, this has worked beautifully, but because the Pointer get's wrapped in PointerData, I have to cheat, as mentioned above, to get the passed Pointer<NativeVariable> actually pointing to the correct thing.  Following is an actual excerpt of my working code.

```
@:cppFileCode("namespace hx{ class PointerData : public hx::Object { public: void *mValue; };}")

abstract Variable(Pointer<NativeVariable>) from Pointer<NativeVariable> to Pointer<NativeVariable>
{
   public inline function new(name:String)
   {
      this = NativeVariable.create(name);
      Gc.setFinalizer(this, Function.fromStaticFunction(Variable.destroy));
   }

   @:void private static function destroy(variable:Pointer<NativeVariable>):Void
   {
      untyped __cpp__('{0} = (::kiwi::Variable *)((hx::PointerData *){0})->mValue', variable.ptr);
      variable.destroy();
   }

   ...
}

@:structAccess
@:include("kiwi.h")
@:analyzer(no_simplification)
@:native("::kiwi::Variable")
extern class NativeVariable
{
   @:native("new ::kiwi::Variable")
   public static function create(name:String):Pointer<NativeVariable>;

   ...
}
```

**Comment by hughsando** [comment]
I can across something similar.  The key point is that finalizers can only be set in "Objects", and the argument  to destroy should be a "Dynamic". You have to be careful here that the  Gc.setFinalizer does not create a temporary dynamic to wrap your Pointer, then set the finalizer on that.  Because in this case, the temp will go out of scope in the very next collection.
To use finalizers with native pointers, you really need to set it on an owning "Object" - ie, something that gets allocated with GC.
