### ISSUE TITLE
Invalid compressed data for hxcpp-3.2.205/lib/Mac64/libzlib.a

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/hxcpp#346]
I used haxelib to upgrade all libs 
and got a message to update hxcpp to 3.2.205

download went as planned but at the end of the install I got this message 

```
...
  Created lib/Mac64/
  Install lib/Mac64/libmysql5.a
  Install lib/Mac64/libregexp.a
  Install lib/Mac64/libsqlite.a
  Install lib/Mac64/libstd.a
  Install lib/Mac64/libzlib.a
Invalid compressed data for hxcpp-3.2.205/lib/Mac64/libzlib.a
```

and further upgrading of the libs stopped.

Was not really looking to upgrade hxcpp, so I ran `haxelib upgrade` again
and got 
```
Set hxcpp to version 3.2.205 [y/n/a] ? y
Library hxcpp current version is now 3.2.205
```
 and this time it finished upgrading

**Comment by mikedotalmond** [comment]
I also saw version 3.2.205 available on haxelib, but the download was stopped by Avast! (on windows) because it thinks the file is suspicious... Hmm. Also, the latest changes don't have a version number in the Changes.md - it looks like the most recent release should still be 3.2.193

**Comment by pizzamakesgames** [comment]
Can confirm the issue. Gotta manually install 3.2.193 until this is fixed.

**Comment by hughsando** [comment]
I re-uploaded it and it seems to work now.

**Comment by MatthijsKamstra** [comment]
its seems to work, but not exactly as it should:
after I update just now...
previous bug was not present, but I got this:
```
...
  Created tools/run/
  Install tools/run/compile.hxml
  Install tools/run/RunMain.hx
  Current version is now 3.2.205
Done
std@sys_file_type
```
and the upgrade of haxelib stopped

I ran it again and no problems (the rest of the libs are upgraded)

**Comment by hughsando** [comment]
That is a bit odd.  But I think it was probably haxelib crashing on the
first bad file, and leaving something in a bad state, which seems to be
resolved by the second upgrade.
If everything is working now, I think we should just move on, and hopefully
this is the last we will see of this issue.

On Thu, Dec 31, 2015 at 11:42 PM, Matthijs Kamstra <notifications@github.com
