### ISSUE TITLE
Library hxcpp version 3.2.205 does not have a run script Build halted with errors.

### ISSUE THREAD

**Issue by smks** [HaxeFoundation/hxcpp#347]
Library hxcpp version 3.2.205 does not have a run script
Build halted with errors.

**Comment by smks** [comment]
Sorted.

hxcpp: 3.2.102 3.2.171 3.2.180 3.2.193 [3.2.205] 3.2.94

> haxelib set hxcpp
Version : 3.2.94
Library hxcpp current version is now 3.2.94

**Comment by RealyUniqueName** [comment]
Downgrading to previous version does not solve this issue for the latest one :)
I've faced this issue too. 
Ubunut 15.04 x64
