### ISSUE TITLE
HXCPP_GC_MOVING defined by default

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#349]
Are there plans to enable the moving collector by default?

If so, are there known issues that need to be addressed before that happens, or is it waiting for a certain release/milestone, or something else?

I hesitate to use HXCPP_GC_MOVING knowing how few real projects likely use it since it is not the default or in any documentation.

**Comment by hughsando** [comment]
This is a bit tricky.  I don't have any outstanding bugs logged against this feature, but then again, I'm aware that this has not been properly tested in enough environments.  I'm not sure how to break this deadlock.

**Comment by james4k** [comment]
I understand that. Certainly a tricky situation.

What do you think about calling upon the community to test it on their projects? Do you think it is ready for wider testing?

**Comment by thomasuster** [comment]
I recommend asking developers to test a specific branch. Then once enough :+1: are given rebase & merge to master.

**Comment by ex** [comment]
We are using this flag in our ongoing project, without it the GC slowdown passing 1GB of memory is really bad.

**Comment by larsiusprime** [comment]
Happy to test it. What's required?

**Comment by Simn** [comment]
`-D HXCPP_GC_MOVING` I'd guess.

**Comment by larsiusprime** [comment]
Does it require a specific branch or just latest hxcpp release?

**Comment by Simn** [comment]
It's probably only available/usable in the current git versions.

**Comment by hughsando** [comment]
3.2.205 (current haxelib) with haxe define -D HXCPP_GC_MOVING should do the
trick.
You can also set -D HXCPP_GC_DEBUG_LEVEL=4 if you want some extra debug.

**Comment by underscorediscovery** [comment]
I've been testing quite a bit and ran into some crashes I reported to Hugh prior to 3.2.205. 
I'll try and keep it enabled as much as it doesn't impede my day to day work and report as well.

**Comment by ex** [comment]
I added a related issue: #366

**Comment by ex** [comment]
We are still having crashes in our current project with HXCPP_GC_MOVING, HXCPP_M64 and HXCPP_GC_BIG_BLOCKS when we use Gc.compact().
The crash is very random and I don't have a test case right now.

**Comment by james4k** [comment]
Looked at this some more, and the main issue here seems to be the need to pin memory if you store an hxcpp allocated address in some unmanaged memory with CFFI or whatever else.

Right now there does not seem to be a way to pin memory, but even when that is in place, or maybe the rules around memory and FFI change in some other way, probably not feasible to enable this by default for some time, until projects are aware of these rules.
