### ISSUE TITLE
Const qualifier error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#352]
The following used to work, but now I'm getting an error:

```
function onSample( buf : cpp.Pointer<cpp.Float32>, len : Int ) {
  var data : haxe.io.BytesData = [];
  cpp.NativeArray.setUnmanagedData(data, buf.reinterpret(), len<<2);
  foo( haxe.io.Float32Array.fromBytes(haxe.io.Bytes.ofData(data)) );
}
```

It says `cannot convert argument 1 from const unsigned char * to void *`

**Comment by ncannasse** [comment]
PS: also, is there any reason you have cpp.UInt8 and haxe.io.BytesData.Unsigned_char__ ?

**Comment by Simn** [comment]
I caused this, but I'm not sure if it's actually my fault because the AST looks alright. See https://github.com/HaxeFoundation/haxe/pull/4746#issuecomment-168160319

**Comment by ncannasse** [comment]
@hughsando any insight?
