### ISSUE TITLE
Extra keywords

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#353]
I've hit into an error since my project was using `__leave` identifier, it's a reserved keywords in MSVC toolchain. Consider also adding __try and __finally, according to 
https://msdn.microsoft.com/en-us/library/9xtt5hxz.aspx

**Comment by ncannasse** [comment]
As well as __except

**Comment by ncannasse** [comment]
A full list of MSVC C++ keywords is available here https://msdn.microsoft.com/en-us/library/2e6a4at9.aspx

**Comment by hughsando** [comment]
Technically, I think double-underbars are possibly reserved for the c++
compiler.  So maybe just anything starting with double-underbar.

**Comment by delahee** [comment]
agreed __ are indeed reserved for c compiler.

2016-01-04 16:33 GMT+01:00 Hugh Sanderson <notifications@github.com>:

> Technically, I think double-underbars are possibly reserved for the c++
> compiler. So maybe just anything starting with double-underbar.
>
> On Mon, Jan 4, 2016 at 11:01 PM, Nicolas Cannasse <
> notifications@github.com>
> wrote:
>
> > A full list of MSVC C++ keywords is available here
> > https://msdn.microsoft.com/en-us/library/2e6a4at9.aspx
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/HaxeFoundation/hxcpp/issues/353#issuecomment-168699863>
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxcpp/issues/353#issuecomment-168707998>
> .
>



-- 
David Elahee

**Comment by ncannasse** [comment]
Well, we are writing Haxe code, not C++, and as far as I know __ are not reserved for Haxe compiler so genCPP should handle them gracefully :)

**Comment by nadako** [comment]
Somewhat related: https://github.com/HaxeFoundation/haxe/issues/4462

**Comment by delahee** [comment]
Ok I reformulate. I agree with Nicolas, this class of problem has tricked users a lot a struggle  when switching target, we should find a global solution.

@hughsando you talked of a command or something to have cpp code namespaced as a whole.  I cannot see anything there : http://haxe.org/manual/compiler-usage-flags.html

Is there something related somewhere ?

**Comment by underscorediscovery** [comment]
We just ran info [far](https://en.wikipedia.org/wiki/Far_pointer) being a reserved keyword too.

I have no idea how the same unchanged code has been compiling all this time (probably vs2015) - but in VS2015, hxcpp 3.2.205, haxe 3.2.1 `var far:Float;` generates `Float far` and you get `error C2208: 'double': no members defined using this type` from the far usage error.

**Comment by delahee** [comment]
erf...

2016-01-07 23:44 GMT+01:00 Sven Bergström <notifications@github.com>:

> We just ran info far <https://en.wikipedia.org/wiki/Far_pointer> being a
> reserved keyword too.
>
> I have no idea how the same unchanged code has been compiling all this
> time (probably vs2015) - but in VS2015, hxcpp 3.2.205, haxe 3.2.1 var
> far:Float; generates Float far and you get error C2208: 'double': no
> members defined using this type from the far usage error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxcpp/issues/353#issuecomment-169830979>
> .
>



-- 
David Elahee

**Comment by hughsando** [comment]
I have remapped all unknown double-underbar methods (had to keep some special hxcpp ones for legacy reasons).  I have also remapped near and far, although I could not replicate the error.
