### ISSUE TITLE
Invalid generation for local function

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#354]
The following class fails to compile with -cpp:
`https://github.com/ncannasse/heaps/blob/master/h2d/comp/Value.hx`

The offending code is the following:

```haxe
text.input.onPush = function(e1) {
			text.active = true;
			if( text.hasClass(":focus") )
				return;
                        ....
```

This will generate a normal return while it should generate a `return null()`, this trigger a compilation error in the generated CPP. It might be because this closure contains another closure, I'm not sure what's special here.

**Comment by ncannasse** [comment]
The generated cpp code
```cpp
	Void run(::hxd::Event e1){
		HX_STACK_FRAME("*","_Function_1_2",0x5200ed38,"*._Function_1_2 (h2d/comp/Value.hx:25)","h2d/comp/Value.hx",25,0x07847e98)
		HX_STACK_ARG(e1,"e1")
		{
			HX_STACK_LINE(26)
			_g->text->active = true;
			HX_STACK_LINE(27)
			if ((_g->text->hasClass(HX_HCSTRING(":focus","\x5e","\x4d","\x3c","\x35")))){
				HX_STACK_LINE(28)
				return;
			}
```

**Comment by ncannasse** [comment]
Getting the same error for h2d/comp/Input, maybe only occur for closures declared in constructor?

**Comment by ncannasse** [comment]
@hughsando up ? :)

**Comment by hughsando** [comment]
Yes, seems easy enough to reproduce with:
```
class Test
{
   public function new()
   {
     var closure = function() { return; };
   }
   public static function main() new Test();
}
```
