### ISSUE TITLE
Repeated `alloc_root` and matching `free_root` can result in a crash

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#355]
I am not 100% sure what causes this issue, but when performing multiple `alloc_root` and `free_root` calls quickly, the application can crash within this logic:

```cpp
   if (root->mPrev)
      root->mPrev->mNext = root->mNext;
   if (root->mNext)
      root->mNext->mPrev = root->mPrev;
```

For example, this tends to produce a problem:

```cpp
Bytes bytes;

if (true) {
    
    bytes = Bytes (path);
    
}
```

The `Bytes (const char* path)` constructor ends up creating a root in order to prevent garbage collection on the byte buffer, even if it is resized (which can cause collection and subsequent problems).

The `~Bytes` finalizer calls `free_root` if the root was defined. I think that when enough values are removed quickly enough, there may become a case where `mPrev` or `mNext` exists, but `mPrev->mNext` or `mNext->mPrev` is a null pointer and crashes.

It seems to happen most when stack variables are cleaned up. Not sure if this is a threading issue either?

**Comment by hughsando** [comment]
Yes - that code does not look thread safe.  It also looks pretty out-of-date.  Not even sure why the root list is maintained anymore, I'm sure I can simplify it - just need to get some kind of test together.
