### ISSUE TITLE
GC-related crash

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#356]
Reproducing a crash in a fairly simple program that only happens with `/O2` on Windows. Have not tested on other platforms.

Not quite sure what it is happening, but it looks potentially like another register needs capturing?

https://github.com/james4k/hxcpp-issue-356

**Comment by james4k** [comment]
Also, I don't think the randomly sized arrays are relevant. Originally, I was trying to cause fragmentation while attempting to create a unit test for https://github.com/HaxeFoundation/hxcpp/issues/357.

**Comment by hughsando** [comment]
It is possible some register may be hiding, but I cold not reproduce it.
It might have something subtle to do with the version of haxe I'm using - I'll have to check it out on a clean machine.

**Comment by james4k** [comment]
Hmm. I tried again and had trouble reproducing until I got it again by forcing -O2 in a debug build, since that is what I was primarily looking at yesterday. This is with Haxe 3.2.1 and git version of hxcpp.

```diff
diff --git a/toolchain/msvc-toolchain.xml b/toolchain/msvc-toolchain.xml
index 9a3c6db..a59b643 100644
--- a/toolchain/msvc-toolchain.xml
+++ b/toolchain/msvc-toolchain.xml
@@ -39,7 +39,7 @@

 <compiler id="MSVC" exe="cl.exe" if="windows">
   <flag value="-nologo"/>
-  <flag value="-Od" if="debug"/>
+  <flag value="-O2" if="debug"/>
   <!-- -O2 is back ! -->
   <flag value="-O2" unless="debug"/>
```

Originally, it happened in release builds as well, but perhaps that was before reduction of the repro' case.

**Comment by hughsando** [comment]
I can now reproduce this easily enough - thanks.  I think the problem is that these functions pass the value by reference, and it is a reference to some return value which is somewhere ever-so-slightly down the stack.
I can extend the stack scan by a bit, or maybe not pass the value by reference.  I will have to think about it.

**Comment by hughsando** [comment]
I have put in a fix which fixes things in this case - maybe some calls we completely inline confusing my stack calculations.
I'm not 100% sure, but it seems to fix the problem.

**Comment by james4k** [comment]
Hmm, I'm still having trouble deciphering what is going on. I kind of wish I came across this issue in real code so we could have further confirmation, but I feel that your fix at least reduces the likelihood of such a problem.

Thanks for taking a look.
