### ISSUE TITLE
HXCPP_GC_MOVING and adjusting sWeakRefs

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#357]
While testing HXCPP_GC_MOVING on some existing code, I encountered a crash related to weak references. After investigating, it looks like the pointers in the sWeakRefs array may not be updated when the objects move.

After looking at the AdjustPointers function, I then put the following code at the end of the function:

```
for(int i=0;i<hx::sWeakRefs.size(); i++)
{
   hx::WeakRef *ref = hx::sWeakRefs[i];
   if ( ((unsigned int *)ref)[-1] == IMMIX_OBJECT_HAS_MOVED )
   {
      hx::sWeakRefs[i] = ((hx::WeakRef **)ref)[0];
   }
}
```

It seems to solve the issue with the project I am testing with, but not confident on the correctness.

**Comment by madrazo** [comment]
Hi.
I have tried this with my "XML parsing" demo which crashes when telemetry is enabled.
( https://github.com/HaxeFoundation/hxcpp/issues/333 )
However, it crashes faster. In the 6th time instead of the 9th.
https://github.com/madrazo/telemetryTest
Thanks.

**Comment by madrazo** [comment]
Sorry, that was without using -DHXCPP_GC_MOVING. With GC Moving it crashes in the 9th as before.

**Comment by hughsando** [comment]
Yes, this is pretty much what was needed.  There was also something with weak keys that needed fixing.  Please close this issue if it is working for you now,

**Comment by james4k** [comment]
Great! Thanks, Hugh.
