### ISSUE TITLE
[Android] Gcc major issue with cpp.vm.Gc.run( true )

### ISSUE THREAD

**Issue by kiroukou** [HaxeFoundation/hxcpp#362]
Hi,

We have tracked down a major issue with hxcpp on Android target (not windows nor linux).
The problem has been isolated , but definitly not understandable for us.

On the **first** cpp.vm.Gc.run( true ) call, there's something really wierd occuring, that corrupt current data.

```
class Test {
	static function main(){
		trace("-- Start");
		for( i in 0...2 ){
			trace("-- init");
			var b = haxe.io.Bytes.alloc( 265000 );
			for( i in 0...b.length )
				b.set(i,i%256);
			trace("sha1="+haxe.crypto.Sha1.make(b).toHex());
			trace("-- run GC");
			cpp.vm.Gc.run( true );
			trace("sha1="+haxe.crypto.Sha1.make(b).toHex());
		}
	}
}
```
*On all (tested) platforms except Android :*
The output is the same, both times.

*On Android target:*
The **first** loop gives a different result, while the second iteration output a valid equal output.

The different ways we found to be bug free are : 
 - run once cpp.vm.Gc.run( true ); at the very begining of the app
 - _enabling DCE_ !  We usually set _-dce no_  and in that configuration the bug occurs. with _-dce std_  no problem occurs.
 - move back to hxcpp 3.2.102

Here is  a sample project
[cpp_gc.zip](https://github.com/HaxeFoundation/hxcpp/files/90141/cpp_gc.zip)

_Tested with haxe nightly and yesterday hxcpp git version,  compiled from Linux and Windows ENV._

**Comment by hughsando** [comment]
Are you using an android ui framework, or just running on the device directly?

**Comment by kiroukou** [comment]
We run it on device directly. (and we tested 2 different devices  tablet & phone)

**Comment by hughsando** [comment]
There was an issue with calling Gc.run directly in android.  I should have fixed it when I was going some other gc stuff with:
https://github.com/HaxeFoundation/hxcpp/commit/edaf985b18b7dfea88d85739a424a6622f576a07#diff-d65d8d6bc1df27143ddfbcbdfc543657L3946
Let me know if this solves the problem.

**Comment by hughsando** [comment]
I think this should be fixed.
