### ISSUE TITLE
Conversation of typedef to string don't keep field definition order

### ISSUE THREAD

**Issue by hammeron-art** [HaxeFoundation/hxcpp#363]
Typedef to string conversation don't shows fields in the same order as the definition of the type.
Also they are formated like a Map but something like the actual declaration of a typedef would be better for this case.
```haxe
typedef CustomType = {
	var a:Int;
	var b:Int;
	var c:Int;
	var d:Int;
}

class Main {
	
	static function main() {
		var object:CustomType = {
			a: 0,
			b: 1,
			c: 2,
			d: 3,
		}
	// Cpp: { d => 3, b => 1, c => 2, a => 0}
	// Javascript: { a : 0, b : 1, c : 2, d : 3 }
        trace(Std.string(object));
	}
	
}
```

**Comment by Simn** [comment]
The field order of the run-time type is not enforced by Haxe. The exact printing result is unspecified as well, it only guarantees that there's the key and the value with some symbol(s) between them. You shouldn't rely on the string signature of anonymous structure types.
