### ISSUE TITLE
hxcpp renames some variables which makes them inaccessible to the debugger

### ISSUE THREAD

**Issue by bji** [HaxeFoundation/hxcpp#365]
If you name a variable "tmpXXX", where XXX is some number that is low enough to conflict with the "fake" locals that hxcpp generates into the C++ code, then hxpp will rename the variable to not conflict with its temporaries.

This means that when a user tries to use the debugger to inspect the value of their variable, they will get the value of the temporary that hxcpp generated instead of their actual variable (which now has a different name).

It's fairly easy to demonstrate by taking some code which generates some tmp variables, then changing that code to introduce a new local variable with a name that conflicts with one of the generated tmp variables, then looking at the subsequently generated C++ source code.

**Comment by Simn** [comment]
We can't really guarantee that variable names are preserved in the general case. The same can happen without temp vars if you manually cause a "clash":

```haxe
class Main {
	static function main() {
		var a = 0;
		if (Math.random() > 0.5) {
			var a = 1; // renamed to a1
			trace(a);
		}
	}
}
```

We could address this for temp vars via https://github.com/HaxeFoundation/haxe/issues/4462 but that's only a solution-by-convention as well.

**Comment by bji** [comment]
You could generate hxcpp temporaries using a prefix that either is a) impossible to conflict with user defined variables, or b) is very unlikely to conflict.

For example:

tmp1___hxcpp_generated
tmp2___hxcpp_generated

I can't imagine anyone ever using those variable names in their source code.  You could even document that these variable names are not allowed in haxe and the compiler could check for them and issue an error.

But tmp1, tmp2, etc ... those are all too likely to be declared in user code.

**Comment by Simn** [comment]
Yes we can change it, I just have to make up my mind about what exactly to use instead.

**Comment by bji** [comment]
I see your point about local variables that haxe allows to shadow other local variables (which actually is a bad language feature in my opinion, but apparently the cat's already out of the bag on this one).

Just checked the source.  I realize that there is already a facility in the hxcpp generated output that could handle this, it's just not being used properly.

hxcpp is generating lines like:

HX_STACK_VAR(tmp9,"tmp9");

This tells the debugger that there is a local variable called "tmp9" in the haxe world and that it is represented in the C++ code as tmp9.

This macro just needs to properly identify the haxe language name for the variable.  Right now it's always just emitting the temporary name, even when that temporary name is a remapping of a haxe variable name.

**Comment by bji** [comment]
If you don't want to address this right away, that's cool ... here at TiVo we're actually partnering with a local college to assign some work to some computer science students as a senior project.  We decided to set them loose on improving the hxcpp debugger's handling of lines with multiple expressions, which it currently does not handle well.  We can potentially add making the variable name mapping work correctly too.

**Comment by Simn** [comment]
To avoid some confusion: The temp vars we're talking about are not "created by hxcpp". They are created by the compiler and become a normal part of the typed AST. The C++ code generator does not have any information other than that variable name. In other words there is no "mapping" to speak of.

It all comes down to changing this line: https://github.com/HaxeFoundation/haxe/blob/development/analyzer.ml#L1093

There are a few other places where "tmp" is used, but this is the main one. I can change this right now, but obviously that would only affect the current git version straight away.

**Comment by Simn** [comment]
I have changed it to `_hx_tmp` now. Does that work for you?

**Comment by hughsando** [comment]
As you say, we have lost the original name by the time we get to hxcpp.
There are also some issues with the shadow variable and the temp variables.
If there was just a map somewhere from the AST variableId to its original
name (with some 'None' optional name in the case of introduced variables)
then I could put the original names in the macro.  Shadowing would then
work under the original name, and I can skip the registering of temp
variables, which should make the code a bit nicer to read.

**Comment by Simn** [comment]
We could store the original name as some metadata on `v_meta` if you think that's worthwhile.

**Comment by hughsando** [comment]
Something like that should do the trick.

**Comment by Simn** [comment]
[Done](https://github.com/HaxeFoundation/haxe/commit/84641bf4c63064f0422b1a4dc0bb2f8bc89210a1), is that sufficient or do we have to do anything else?

**Comment by Simn** [comment]
I suppose we are done here.

**Comment by hughsando** [comment]
I'm just reopening this because I need to address the whole variable name thing in cppast.

**Comment by hughsando** [comment]
New cppast should handle this correctly now.
