### ISSUE TITLE
Can't download version 3.2.205 from haxelib

### ISSUE THREAD

**Issue by soyyo5159** [HaxeFoundation/hxcpp#375]
The hxcpp latest version (3.2.205) is currently unavailable to download from lib.haxe.org

**Comment by Simn** [comment]
Works fine for me. Did you try via the website and the haxelib command line?

Either way this is not an issue for hxcpp.

**Comment by soyyo5159** [comment]
I've tried doing both... Could it be that the South America mirror is not working? What can I do to solve this problem? Where should I ask?
Thanks a lot

**Comment by Simn** [comment]
We had routing issues from SA before but I thought that was no longer a problem. Does downloading Haxe from http://haxe.org/download/ work?

**Comment by soyyo5159** [comment]
@Simn yes, that works fine (without using proxy).
I just could download hxcpp using http://hidemyass.com/ so I think it has to do with my location.

**Comment by Simn** [comment]
That's quite peculiar, but I think we should chalk it up as a temporary routing issue. Let me know if this still doesn't work tomorrow, though I'm not sure what we can do about it.

**Comment by soyyo5159** [comment]
Ok, I'll do that... Thanks!

**Comment by soyyo5159** [comment]
I turns out it was my antivirus blocking the download URL after a false positive. Sorry for taking your time and thanks for the responses.

**Comment by soyyo5159** [comment]
Just reported the false positive (it was Avast)

**Comment by Simn** [comment]
Alright, thanks!
