### ISSUE TITLE
Don't pass null() into optional parameters

### ISSUE THREAD

**Issue by tienery** [HaxeFoundation/hxcpp#377]
I have an instance in my code where the following extern:

    @:native("sf::CircleShape") public static function create(radius:Float, ?pointCount:UInt = 30):CircleShape;

And the implementation:

    var circle = CircleShape.create(50);

Generates the following code in output:

    sf::CircleShape& tmp7 = sf::CircleShape((int)50,null());

Which gives unwanted results. This supposedly is caused by the fact that I'm using an extern class instead of a normal Haxe class, but it would be nice if it also applied to externs as well if at all possible.

**Comment by hughsando** [comment]
This is a bit tricky because the haxe idea of optional parameter is
different to the c++ idea.  hxcpp does not see the "=30", it requires the
function to implement this logic.  This way, it works with dynamic, eg
```var func = Circle.create;  func(1); // will get radius 30```
A similar thing happens in Java - where they use the "@:overload" meta to
define 2 functions (create taking one param, create taking 2 params).  I
wonder if exactly the same thing would work here.
Otherwise, I may be able to handle default args on native functions
differently.

**Comment by tienery** [comment]
Well, the implementation as seen in SFML is that the parameter defaults to 30 if none is given. http://www.sfml-dev.org/documentation/2.3.2/classsf_1_1CircleShape.php

So perhaps instead of passing null, just assume that it is optional and let the compiler throw an error otherwise. I personally think that would be a safer option, up to you.

**Comment by Simn** [comment]
We should make extern distinctions between `@:nativeGen` and `@:hxGen`, with the former being the default and not padding nulls. That requires a core typer change though.

**Comment by ncannasse** [comment]
This kind of C++ polymorphism might interest @waneck as well

**Comment by Simn** [comment]
Note to self: Don't forget about optional argument skipping.

Note to Nicolas: Can we get rid of that feature for Haxe 4?

**Comment by nadako** [comment]
So far I have exactly one case where I found argument skipping useful: `haxe.Json.stringify(obj, "  ")`.

**Comment by ncannasse** [comment]
I'll have to check what kind of impact it has on my codebase to evaluate how practical it is. I agree it would simply things in the compiler as well as allow better error reporting

**Comment by hughsando** [comment]
Would @:overload be better?  This would push the default value ('30') back
into the c++ header code, rather than hardwired (and possibly different)
int the haxe extern wrapper.

**Comment by Simn** [comment]
Default values on externs should have no effect other than self-documentation, right?

**Comment by ncannasse** [comment]
@Simn, yes, but I'm not sure what is the status of null padding with extern code. We maybe want at some point these externs to be actual Haxe code (it is already possible on some platforms), which might then require null padding; I agree with @hughsando that overload is the best choice here

**Comment by Simn** [comment]
That's why I said we should make the distinction of `@:nativeGen` and `@:hxGen` for extern, which is what @waneck does for Java/C# as well.

**Comment by tienery** [comment]
Not sure if it's related or not, but since you mention using @:overload, there is also a weird issue resulting from not passing anything into an optional parameter where the function in question in its C++ form has overloads.

The `sf::RenderWindow::draw` function has two overloads, and if I pass just one object (something to render) into the first parameter of the function, it errors out saying you can't use the second overloaded function signature despite the fact that the type of the first parameter doesn't match the second overload, which is really odd.

Here is an example of that:

![img](http://i.imgur.com/sl5qgZU.png)

It does not seem to matter if you denote an optional parameter with `?` or not, the same error occurs.

**Comment by hughsando** [comment]
I'm combining this issue with https://github.com/HaxeFoundation/haxe/issues/3955 since this fix will come from changes to the haxe compiler.

I the case were you can't represent the default value in haxe (eg, Renderstates &) then the overload option is certainly what you are after, since it will work efficiently and well.
