### ISSUE TITLE
Neko.dll sometimes mess with hxcpp programs...

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#381]
Ok that is first class weirdness.

I compile  a simple hxcpp program that invokes Sys.getCwd.
I run the program.
On some configurations, the neko.dll version of Sys.getCwd will get loaded and provoke a hard crash.

This impeach all System / File access for this kind of program...weirdly it "sometimes" works if i get back to haxe 3.0.x according to hxcpp version uses.

I don't expect a real closure but I leave this ticket here for the record.

**Comment by delahee** [comment]
If I remove neko after compile and remove all neko.dll files from all paths, my hxcpp program will not run with : 
```
Called from cpp.Lib::load C:\Workspace\motionTools\haxeNightly\std/cpp/Lib.hx line 34
Error : Could not load module regexp@regexp_new_options__2
```

...getting weirder..maybe related to dce no..still diggin

**Comment by delahee** [comment]
@hughsando  

If I reduce to a simple code : 
```
import cpp.Lib;
class Main {
	static function main() 	{
		trace(Sys.getCwd());
	}	
}
```

And compile and then remove neko.dll, error is now : 
```
Called from cpp.Lib::load C:\Workspace\motionTools\haxeNightly\std/cpp/Lib.hx line 34
Error : Could not load module std@get_cwd__0
```
So I manually copied what was in "bin\Windows" from hxcpp redistribution...and it magically works...

Hey Hugh, don't you think this is a bit weird, because from how i see it, we are relying on a non predictable load order here...or maybe something wasn't done correctly along the way...

I let you 'close' if the case seems too far fetched to you but I really feel there is a bit of luck/hazard somewhere lurking...

Sorry for the noise.

**Comment by hughsando** [comment]
If you set HXCPP_LOAD_DEBUG environment variable, you should see exactly
what is going on.
Might be that you need to rebuild the dlls that go with the github version,
via some of the instructions  on https://github.com/haxefoundation/hxcpp

**Comment by delahee** [comment]
I had fully rebuilt them...
Should'nt Std.dll be copied along the output .exe ( it wasnot ) ? Or are we relying in standard dll order ?

**Comment by hughsando** [comment]
It is not generally copied, so all exe can the refer to the single dll.
Nme and openfl copy the dlls to allow for moving the output to new machines.
You may also like to consider static-linking these libraries, which is
similar but better than copying the dlls to the exe directory.

**Comment by delahee** [comment]
hmm. In my case i'll static link but as a Haxe ecosystem wide issue. Then we have still a tiny problem...I elaborate.

ref https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586(v=vs.85).aspx

If dll is not copied, then we relied on standard dll order...which states that dlls's will come fetched from $PATH which will most likely "randomy" drop NEKO before where the hxcpp dll are ( I don't even get how they can be fetched )...

So at best on windows it's a coin flip if dynamic library fetch one dll or another...

I suggest raw hxcpp builds in dynamic links ensure that it behaves correctly and to me it seems copying dll in the exe path is the only way to achieve this since we hardly control $PATH order...

Maybe I missed something but I do think I am not out of my mind, amirite ?

**Comment by Simn** [comment]
I guess this is no longer an issue now that hxcpp library handling has been reworked.
