### ISSUE TITLE
How to pass callback to native gen

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#382]
Hi!

for example  :

```
int 	av_lockmgr_register (int(*cb)(void **mutex, enum AVLockOp op))
```

What type should I declare in the haxe .hx ? There seems to be a cpp.Function<???,ABI>...but it doesn't look like it's the thing to use..

Can you put a sample/test in the hxcpp  test suit so that I can understand how to proceed ? 

Thanks !

**Comment by hughsando** [comment]
The "void **" in a function signature does not leave a lot or room for using haxe-compatible types.
So you must use "cpp.RawPointer", and in doing so, you must also use "unreflective", since raw pointers can't be passed through dynamic reflection.  This example should do the trick:
```
import cpp.RawPointer;
import cpp.Pointer;

typedef VoidStarStar =  RawPointer< RawPointer<cpp.Void> >;

extern class LockManager
{
   @:native("av_lockmgr_register")
   public static function register( callback:cpp.Callable<VoidStarStar->Int->Int>) : Int;
}


@:cppFileCode('

int av_lockmgr_register (int(*cb)(void **mutex, int op))
{
   printf("Register !\\n");
   void *mutex = 0;
   int result = cb(&mutex, 1);
   printf("Got %p = %d\\n", mutex, result);
   return 0;
}

')
class Test
{
   @:unreflective
   public static function myHander(ptr:VoidStarStar, op:Int) : Int
   {
      trace("op = " + op);
      var x = 1;
      var cppPointer = Pointer.fromRaw(ptr);
      // Not sure what you want here ...
      cppPointer.ref = cast cpp.Pointer.addressOf(x);
      return 4;
   }

   public static function main()
   {
      LockManager.register( cpp.Function.fromStaticFunction(myHander) );
   }
}
```

What you  actually put into the mutex is another story (address of x is just an example).

**Comment by delahee** [comment]
okidoki the RawPointer thing seems interesting, I'll check out if it can solve moar of my problems. Thanks !
