### ISSUE TITLE
cpp.Pointer / setUnmanagedData does not seem to work...Const vengeance...

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#387]
Hi bro!

setUnmanagedData does not seem to work on my windows box...As a workaround I'll go untyped but If I can do without it, i'll give it a shot :)

If you would be kind enough to add this file ( hxcpp\git\test\native\tests ) to your tests ( and fix the issue in the same run, if you please ) : 

```
package tests;

class TestNativeArray extends haxe.unit.TestCase {
	public function testPtrToArray(){
		var o : cpp.UInt8 = 16;
		var	ptr : cpp.Pointer<cpp.UInt8> = cpp.Pointer.addressOf( o );
		var arr : Array<cpp.UInt8> = [];
		cpp.NativeArray.setUnmanagedData(arr, ptr, 1);
		assertTrue(arr[0]==16);
	}
}
```

The problems seems to come from 
```
::cpp::Pointer< ::cpp::UInt8 > ptr = ::cpp::Pointer< ::cpp::UInt8 >(::cpp::Pointer_obj::addressOf(o));		
Array< ::cpp::UInt8 > arr = Array_obj< ::cpp::UInt8 >::__new();		
 const ::cpp::UInt8 *  _hx_tmp = ptr->get_raw();		
arr->setUnmanagedData(_hx_tmp,(int)1);
```

the " const ::cpp::UInt8 *  _hx_tmp = ptr->get_raw();" seems to be a bug or something?

See ya !

**Comment by hughsando** [comment]
Yes, It should not be const.  I think the problem is that RawPointer
extends ConstRawPointer (so you can use it in the same places), but can't
override the type "raw" in haxe.   I think I need to add a constRaw
property, and not implement (non-const) raw in ConstRawPointer.

**Comment by delahee** [comment]
I have sent a fix ( https://github.com/HaxeFoundation/haxe/pull/4905 ) 
it is not done the elegant way but it works. I'll send the test along when you are happy with the thing.

**Comment by hughsando** [comment]
".raw" now always returns the non-const version.  Bit easier to deal with I think.
