### ISSUE TITLE
Cppia: Wrong float compare

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/hxcpp#390]
The following code:

``` haxe
class Main {

  static function main() {
    var stamp = Date.now().getTime();
    Sys.sleep(1);
    trace(stamp < Date.now().getTime());
  }

}
```

Traces `false` when running through cppia

**Comment by hughsando** [comment]
This seems to be working - not sure if anything has changed.
It is using dynamic compare because the compiler thinks now().getTime() is dynamic (cppast should fix this, but its not in cppia yet).  But still, the dynamic compare should work.

**Comment by waneck** [comment]
I'll try it with latest hxcpp and report back! Thanks!
