### ISSUE TITLE
hxcpp sometime generate strange include statement

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#394]
```
@:native("AVCodecContext") 
@:include('linc_ffmpeg.h')
extern class AVCodecContext { 
	var blabla : AVMediaType;
	...goes on...
}

static function foo(ctx:cpp.Pointer<AVCodecContext>) {
		
}
```

I don't know why but when I call foo(somePointer), hxcpp generates
```<linc_ffmpeg.h>``` in the Main file header
instead of
``` 
"linc_ffmpeg.h" 
```

It happens more often if I use cpp.Struct s
I think there is a bad inclusion code generation somewhere.

This bug prevents me to use Pointer/Struct in many places, I kind of think it's a showstopper because it stops me very often and I cannot really isolate a case...I'l try though...

**Comment by delahee** [comment]
Apparently this is a frequent behaviour but "sometime" when I use type from an "external" class in a haxe located class, it triggers a C compiler error preventing many use cases. I'll dig it in.

**Comment by hughsando** [comment]
If you want to include a file relative to the haxe class, you must start the include with "./" like @:include("./linc_ffmpeg.h").
Otherwise, you need to use Build.xml to inject an include path, possibly with some environment variable ( ${ENV}  syntax).

**Comment by delahee** [comment]
ok i'll dig around that.

**Comment by hughsando** [comment]
Can I close this one?

**Comment by delahee** [comment]
Let's close, I'll reopen if need be, thanks.

2016-04-25 3:39 GMT+02:00 Hugh Sanderson <notifications@github.com>:

> Can I close this one?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxcpp/issues/394#issuecomment-214087902>
>



-- 
David Elahee
