### ISSUE TITLE
Link error, missing empty file? [haxe 3.3]

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#397]
Ok so I'm not so sure what is happening
the log https://travis-ci.org/ianharrigan/hxWidgets/jobs/116498059
at the very end:
```
 - Running command: g++ -o Main -rdynamic -m64 @/home/travis/build/ianharrigan/hxWidgets/samples/00-Showcase/bin/obj/linux64/all_objs -lpthread -ldl -lwx_gtk2u_gl-3.0 -L/usr/lib/x86_64-linux-gnu -pthread  -lwx_gtk2u_xrc-3.0 -lwx_gtk2u_html-3.0 -lwx_gtk2u_qa-3.0 -lwx_gtk2u_adv-3.0 -lwx_gtk2u_core-3.0 -lwx_baseu_xml-3.0 -lwx_baseu_net-3.0 -lwx_baseu-3.0  -ldl

g++: error: : No such file or directory

g++: error: : No such file or directory
```

The same thing happens for me on my machine,
going into bin (`haxe -cpp bin`) and doing the link call manually works.

I saw some commits at haxe about the executablePath/systemPath, could be related? (although the c++ files compile without issue so maybe not)

**Comment by hughsando** [comment]
Have not looked properly at this, but my guess is that the obj list file /home/travis/build/ianharrigan/hxWidgets/samples/00-Showcase/bin/obj/linux64/all_objs contains some relative paths, rather than absolute.
There is some logic to get this right, but maybe one of the xml injection commands is missing something, or some meta for adding cpp file is not quite right.

**Comment by ibilon** [comment]
Yes it contains lines like `"obj/linux64/ae7b103b_String.o"`.

I'll look into the generated build xml, thanks.

**Comment by ibilon** [comment]
I dumped it, (added to a `:buildXml` metadata)
http://pastebin.com/v04CA0Mk

I guess the empty lib tag don't help.

**Comment by ibilon** [comment]
Found out the error (the one in the edit) is caused by `-Dsource-header="Generated by haxe"`,
fixed it by adding `haxe.macro.Compiler.define("source-header", "GeneratedByHaxe");`
(after reading https://github.com/openfl/lime/issues/537)

So it works for me, I'm keeping this open in case that's something that need to be fixed in hxcpp,
otherwise feel free to close.

**Comment by hughsando** [comment]
This looks to me like a haxelib error, and I think it's been fixed - although I don't do enough linux to tell.
Do you know which version of haxelib you are using, and does upgrading fix the problem?

**Comment by ibilon** [comment]
I tried on a recent version of haxelib and the problem is not there.
