### ISSUE TITLE
sys_exe_path returns the path of the parent exe on Linux

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/hxcpp#398]
When working on https://github.com/HaxeFoundation/haxe/issues/3401, I found that on Linux, if the hxcpp compiled binary (`exe`) is run by another process, say neko (calling `new Process("exe", []))`, `sys_exe_path` will return the path of the parent process instead of itself's.

Is it a platform limitation?

**Comment by hughsando** [comment]
Could you please retest? I only use the "_" env as a last resort now.

**Comment by andyli** [comment]
I confirm it works as expected now. Thanks!
