### ISSUE TITLE
Deploy build somewhere, so it can be downloaded

### ISSUE THREAD

**Issue by back2dos** [HaxeFoundation/hxcpp#400]
I've recently set up my CI to build hxcpp for the dev version of Haxe because of [an issue I was having](https://github.com/HaxeFoundation/haxe/issues/4967) and it led me to wonder whether it wouldn't be more practical to just deploy the builds made in hxcpp's CI somewhere, so that you can use them with wget + haxelib local. It feels rather wasteful to have to rebuild hxcpp every time I build on travis. 

What do you think @andyli?

**Comment by andyli** [comment]
In fact Hugh has his own CI setup and put the packages in his site here:
http://nmehost.com/hxcpp/

Best,
Andy

**Comment by Simn** [comment]
I wanted to ask about that because the last version there is from more than two weeks ago.

**Comment by back2dos** [comment]
Oh, ok, good to know. Still, I would much appreciate if it were current and also if the latest version were available under a defined url.

**Comment by hughsando** [comment]
My build server needs a restart.

**Comment by back2dos** [comment]
@hughsando Say, would it be possible to have some link point to the latest zip?

**Comment by hughsando** [comment]
Like  you mean something like "nmehost/hxcpp/latest.zip" that changes with
the times?

**Comment by back2dos** [comment]
Yep, exactly. I want to be able to download it from CI and I'd rather not
have to parse the HTML to do it :D

**Comment by hughsando** [comment]
Also, I'm hoping to remove the binaries from hxcpp distro very soon, so the
point may become moot since the github download will then be best.

**Comment by back2dos** [comment]
What do you mean by github download?

**Comment by hughsando** [comment]
I guess checkout depth 1.  Not sure what is the fastest.

**Comment by back2dos** [comment]
Ok, let me reexplain my situation.

On Travis, when I want to use the dev version of Haxe, I need the dev version of hxcpp too. To build it there, I do not only need to check out hxcpp, but also install gcc-multilib and g++-multilib and to rebuild it. All that to then run some tests on a lib that has barely 1000 lines of code.

To me it seems like a rather crass waste of resources, even more so given that all that is practically unneccessary, given that this project has a CI in place that [builds the binary I need](https://github.com/HaxeFoundation/hxcpp/blob/master/.travis.yml#L23) every time there is an update. All that's left to do is to zip it and upload it somewhere, and I for one would be happy.

**Comment by hughsando** [comment]
So do you want to do some compiling or not?  If you have gcc installed, it
should not be much drama, if you don't, what sort of testing are you
after?  There is cppia, but I do not think you are talking about this.

**Comment by back2dos** [comment]
I have unit tests running on Travis running against the latest state of Haxe's develop, on all compiler targets (granted, I forgot cppia but I will look into that). For it to work, I had to integrate the latest state of hxcpp for obvious reasons. What I currently do is haxelib git hxcpp and then build it. Before that, I need to install more dependencies to compile it, namely the ones I mentioned. Without them, it failed, but maybe there is a simpler way. Since this [repo uses them too](https://github.com/HaxeFoundation/hxcpp/blob/master/.travis.yml#L9), I would assume there's no real way around it. 

My issue now is that *every time* I push any of my libs that uses this setup, this whole machinery is run. Both gcc-multilib and g++-multilib are installed, hxcpp is checked out and then built and then I can compile and run my tests. And once the session is finished, all of that state is thrown away, because that's how Travis works. To me, this seems utterly silly, because every time anyone pushes here, that very state (i.e. the binary lying next to the sources it was built from) is also created on Travis and all I really want is that it be shrink-wrapped in a zip and uploaded to some public url, where I can just download it from, instead of senselessly burning Travis' resources to replicate it over and over again. Unless I am missing something, it should be a trivial thing to do and it would shave of a substantial amount of time needed to run the tests, i.e. close to 50% or 2 minutes - the time difference I get between stable and dev while building a simple library against all targets, which also involves installing haxe, neko, mono and what not.

Another advantage of this would also be that if the build here gets broken, then the zip with the last compiling state is still available and all the dependent builds remain unaffected. Which is exactly as it is for Haxe itself.

Does that clarify what I am after?

**Comment by hughsando** [comment]
I understand most of this.  Downloading to some extent may invalidate the
test if hxcpp is in flux - time between a commit and a when the zip can be
downloaded.
This is normally not a big issue, but there are a lot of changes going on
at the moment, especially if you are testing the the haxe compiler changes.
I think most of the time (May - February)  you could build against the
haxelib version of hxcpp.

I think there is probably more you can do to optimize the cpp compile
time.  I assume that you do actually want to compile some cpp code, and
that you have g++ installed, but not multilib.  So you could just build the
libs + arch you need (skipping 4 different versions of mysql should help).
I'm currently working on eliminating these pre-compiled binaries, so using
the git version will be pretty much the same.

Not that I'm saying a latest.zip is a bad idea, but ultimate I don't think
it is going to save much (if any) time.

**Comment by hughsando** [comment]
For example, instead of building all architectures you could build in the
project directory:
neko build.n ndll-linux-m64
depending on your system.  This should give a 4x speeup.  Skipping
mysql/sqlite would help a bit too.
As I say, this will only be this way for a little while longer.

**Comment by back2dos** [comment]
Hmmm, I must really be doing a horrible job at explaining myself. Never mind then, I will find my own solution ;)

**Comment by hughsando** [comment]
Could be that the "Travis Way" runs counter to something deep in your sole.

**Comment by back2dos** [comment]
I am pretty sure that that assessment fits your stance far better than mine ;)

Automated deployment is considered a best practice in CI, which is why Travis has a feature for it. The fact that Haxe has it doesn't seem to be the end of the world, and I for one appreciate the fact that I don't have to rebuild Haxe every time I want to run my tests on Travis. Having fast builds is also considered a best practice in CI. This is a trivial change to make, that will yield significant improvements without forcing builds to rely on any additional assumptions to be faster. In the time wasted with this discussion I could have set up a mirror and done it there and had I expected such resistance, that's what I would have done in the first place. I just thought this is a no-brainer and it would be in everyone's interest, but evidently I have been wrong. I will solve this in my little corner and then everyone will have it their way \o/

**Comment by hughsando** [comment]
The hxcpp and haxe need to be a matched pair.  If you are using bleeding-edge haxe, you need bleeding-edge hxcpp.  If you are using a "named" version of haxe, then the haxelib version of hxcpp should be sufficient. If you are doing something different, I guess something can be done although it will introduce some time-dependency on the correctness of the results.
Anyhow, the change I was alluding to is now in:
https://github.com/HaxeFoundation/haxe/commit/bd6315d6baf0b5f8c2f155d4f8ec18c737425ecd
so maybe the point may be moot.

**Comment by back2dos** [comment]
Ok, at the risk of wasting some more time, let me explain again, because I
still get the feeling you do not understand what I am saying.

What I want is to build with the bleeding-edge version of Haxe together
with the bleeding-edge version of hxcpp.

Now, let's examine how I get to use the bleeding-edge version of Haxe: when
someone pushes on to the Haxe repo, a build is made to run the tests on,
and if they pass, it is zipped and uploaded to builds.haxe.org . When I use
the `development` Haxe version on Travis, then that is just what I get. Not
having to build it all again in my CI seems nothing but practical to me.

Similarly, every time a new state is pushed onto the hxcpp repo, a build is
made on Travis:
https://github.com/HaxeFoundation/hxcpp/blob/master/.travis.yml#L52
And that is exactly the binary form of the bleeding-edge version I want.
There is no way for me to build a version that is any more current than
that one. It is the very version I obtain when I build the HEAD of hxcpp on
Travis. Which is why I consider it absolutely pointless and want to stop
wasting resources doing that.

I know nothing about nmehost, its particular CI or your hxcpp distribution
workflow and I certainly have no intention of suggesting how you should go
about it. All I want is that a few more steps be added to the .travis.yml
to deploy the build artifacts that get produced anyway.

I hope I'm being at least somewhat clear now.

**Comment by hughsando** [comment]
Yes, I understand where you are coming from.
But this is the sort of thing that is happening:
At 7:59pm, I put a new feature into hxcpp - say add a class to the header.
At 8:00pm, I commit the change to haxe that uses/requires this class.
At 8:30pm, the hxcpp nmehost version goes live.
At some time the "overnight" version of haxe goes live.

If you try to use the 8:15 overnight version of haxe with the 8:15 nmehost
version of hxcpp you may or may not get it working.
And especially if you respond immediately to a 8:00pm haxe change.

The only way to be sure is to use a version of haxe <= version of hxcpp,
and to this end I suggest using any version of haxe with the latest version
of hxcpp.

Now I know there are practical issues with this, particularly since you
can't use the cpp compiler cache or anything on travis.
But I think this issue i now solved, since you do not need to pre-build
libraries on hxcpp anymore.  The procedure is:
Setup haxelib dev from:
https://github.com/HaxeFoundation/hxcpp/archive/master.zip
Rebuild the "hxcpp.n" script from tools/hxcpp (takes about 1 second)

The github zip is much smaller than the nmehost zips, so I think you will
see a win in both running time and removal of race conditions.

Also, I do intend to link the "latest" on nmehost - just not there yet.
 Meanwhile there is also this view of the files:
http://nmehost.com/releases/hxcpp/  but as I say, I don't think CI will
need it.
