### ISSUE TITLE
Could not find dependencies error

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#402]
If you try https://github.com/HaxeFoundation/haxe/pull/5017 and replace in test/misc/eventLoop.hx the `#if neko` by `#if sys` in order to add a Sleep before the end of the thread, compilation with latest haxe + hxcpp fails at linking time with the following error:

`Error: Could not find dependencies: [ /Build.xml, /Build.xml ]`

Reason is unknown to me.

**Comment by hughsando** [comment]
This seems to be working with the 'sys' in the haxe repo test.  Can I close this now?
