### ISSUE TITLE
Cppia host classes can't reach overridden script functions without Reflect

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/hxcpp#423]
This has been a problem for a long time, but I failed to create a test case the first time I tried.

For the purpose of this test case, everything here is located in "D:/haxe" on my computer.

```haxe
@:build(cpp.cppia.HostClasses.include())
class Test
{
	public static function main()
	{
		var source = sys.io.File.getContent("D:\\haxe\\MyScript.cppia");
		untyped __global__.__scriptable_load_cppia(source);
	}

	public static function callScript()
	{
		var myScriptClass = Type.resolveClass("MyScript");
		
		var s:Script = cast Type.createInstance(myScriptClass, []);
		
		//calls base function (Script)
		s.init();
		
		//calls implementation (MyScript)
		Reflect.callMethod(s, Reflect.field(s, "init"), []);
	}
}
```

```haxe
class Script
{
	public function init()
	{
		trace("init called in Script.");
	}
}
```

```haxe
#if cppia
class MyScript extends Script
{
	public static function main()
	{
		Test.callScript();
	}
	
	override public function init()
	{
		trace("init called in MyScript.");
	}
}
#end
```

Compile host
`haxe -main Test.hx -cpp host -D scriptable -D dce=no -D dll_export=D:/haxe/export/export_classes.info`

Compile script
`haxe -main MyScript.hx --macro cpp.cppia.HostClasses.exclude() -D dce=no -D cppia -cpp MyScript.cppia -cp export`

**Comment by hughsando** [comment]
Thanks for the concise error report.  This one is pretty fundamental to cppia - I had "over optimised" the functions calls in this case.
