### ISSUE TITLE
NDK path problem

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxcpp#424]
I am using Mac and my android NDK is installed through brew. Brew puts the ndk in a path like `/usr/local/Cellar/android-ndk/r11b`. And hxcpp is unable to recognize the folder because it expects a folder name starting with `"android-ndk-r"` ([code](https://github.com/HaxeFoundation/hxcpp/blob/8101cfe55d502f1c50f13b0c63531331db6810c9/tools/hxcpp/Setup.hx#L21))

My current workaround is to create a symlink named `android-ndk-r11b` that points the the above mentioned path.

**Comment by kevinresol** [comment]
It may be better to read the version from the `Pkg.Revision` field in the `source.properties` file inside the ndk folder.
For example, for my particular ndk version, the value of `Pkg.Revision` is `11.1.2683735`

**Comment by hughsando** [comment]
Other distros do not seem to have this file in them.  I have adjusted the regexp for now - see if that works.
