### ISSUE TITLE
Uncaught exception - Invalid operation (+) building android with haxe+hxcpp master

### ISSUE THREAD

**Issue by soywiz** [HaxeFoundation/hxcpp#428]
**Uncaught exception - Invalid operation (+)**

```
C:\projects\hxcpp\project>git pull
Already up-to-date.

C:\projects\hxcpp\project>haxe -version
3.3.0 (git build development @ a65a5ad)

C:\projects\hxcpp\project>neko build.n android
neko run.n Build.xml -Dandroid -Dstatic_link C:/projects/hxcpp/project/
Called from neko.vm.Thread::$statics line 1
Called from RunMain::main line 99
Called from RunMain::executeHxcpp line 93
Called from neko.vm.Loader::loadModule line 132
Called from sys.io.Process::$statics line 1
Called from BuildTool::main line 1257
Called from BuildTool::$init line 29
Called from BuildTool::new line 155
Called from BuildTool::include line 1689
Called from BuildTool::parseXML line 1581
Called from Setup::setup line 215
Called from Setup::setupAndroidNdk line 291
Uncaught exception - Invalid operation (+)
#### Error building neko -Dandroid -Dstatic_link
```

**Comment by soywiz** [comment]
I have tracked down the problem. It seems that ndkVersion=null.

This line returns null: Setup.getNdkVersion( defines.get("ANDROID_NDK_ROOT") );

It seems that I don't have `ANDROID_NDK_ROOT` environment variable.

(I have found the -v switch)

```
Reading HXCPP config: c:\Users\Carlos\.hxcpp_config.xml
No specified toolchain

 - Parsing include: C:/projects/hxcpp/toolchain/setup.xml
 - Parsing include: c:\Users\Carlos\.hxcpp_config.xml (section "vars")
 - Parsing include: C:/projects/hxcpp/toolchain/finish-setup.xml
 - Parsing makefile: Build.xml
 - Parsing include: C:/projects/hxcpp/build-tool/BuildCommon.xml
 - Parsing include: C:/projects/hxcpp/toolchain/haxe-target.xml
 - Parsing include: C:/projects/hxcpp/project/libs/std/Build.xml
 - Parsing include: C:/projects/hxcpp/project/libs/zlib/Build.xml
 - Parsing include: C:/projects/hxcpp/project/libs/regexp/Build.xml
 - Parsing include: C:/projects/hxcpp/project/libs/mysql/Build.xml
 - Parsing include: C:/projects/hxcpp/project/libs/sqlite/Build.xml
 - Parsing include: C:/projects/hxcpp/toolchain/android-toolchain.xml

Using Android NDK root: C:\Development\Android NDK
Detected Android NDK rnull
```

It would be great to print a descriptive error in that case.

I have checked which android ndk installs lime (lime setup android). It downloads "android-ndk-r8b-windows.zip". So I have added "set NDKV8="c:\Development\Android NDK" because it cannot autodetect which ndk I'm using otherwise because the directory doesn't match android-ndk-\d+.

**Comment by hughsando** [comment]
Is this a new error?  I have just been messing with the android ndk regexp and that may have broken things.
When it unzips, do you get a directory inside "Android NDK", like "android-ndk-r8b" , or does it so straight into the files like "platforms"

**Comment by hughsando** [comment]
I have put a fix in - I think there was a stray "*" in the regexp which
caused to to match against "roid".
I am not sure why it did not pick up the version from the NDKV variable - I
think it should avoid the regexp in this case.

**Comment by soywiz** [comment]
I didn't had the NDKV\d+ env variable (installing with lime setup android) (I added it manually). Don't know why. But it would be great if it provides some info about not being able to determine which version are you using.

Folder of the ndk was `C:\Development\Android NDK`

Searched for NDKV in file contents:
```
Searching 15676 files for "NDKV"

0 matches
```

It unzips straight to root:

![android_ndk_folder](https://cloud.githubusercontent.com/assets/570848/14630682/7f73d616-060f-11e6-8ea1-f4d8c554e402.JPG)

```
C:\dev\ConsoleZ>haxe -version
3.3.0 (git build development @ a65a5ad)

C:\dev\ConsoleZ>lime -version

 ___
/\_ \    __
\//\ \  /\_\    ___ ___      __
  \ \ \ \/\ \ /' __` __`\  /'__`\
   \_\ \_\ \ \/\ \/\ \/\ \/\  __/
   /\____\\ \_\ \_\ \_\ \_\ \____\
   \/____/ \/_/\/_/\/_/\/_/\/____/

Lime Command-Line Tools (2.9.1)
Use lime setup to configure platforms or lime help for more commands
```

**Comment by hughsando** [comment]
I need to know the ndk version because google moves the paths around inside, and I need to work out what I need to include and from in which sub directory.
When you download from google and unzip normally, you get a folder called something like "android-ndk-r8a" (up to version 11 now).  So I guess lime is unzipping itself or somehow skips the one folder level that normally matches the zip name.
Hxcpp kind of assumes you might accumulate many of these directories over time, so the naming convention seems as good as any.
Maybe lime has always done this, and my changes stopped this from working somehow.
My preferred solution would be for lime the call the folder the same as the zip, and I can work it out from there.

**Comment by hughsando** [comment]
This issue is quite old - I am assuming lime is working ok with hxcpp now. Please reopen it if you hare having issues.
