### ISSUE TITLE
cpp.Pointer requires a defined type / Breaks externs

### ISSUE THREAD

**Issue by PDeveloper** [HaxeFoundation/hxcpp#432]
Revision: 4a6b30ab4872219950cc57a229dd37a1c44711c7
Date: 13/4/2016 9:06:06 AM

In this revision, this was added:
https://github.com/HaxeFoundation/hxcpp/blob/a66838a08d18129080dcb486de81de411ff2ebc0/include/cpp/Pointer.h#L150

This causes issues when compiling libraries that contain forward declared types, specifically snowkit/linc_sdl#8
Removing that one line allowed me to compile my project. In SDL sources, SDL_Window is defined as `typedef struct SDL_Window SDL_Window;` in `include/SDL_video.h`
SDL_Window is given a concrete definition ONLY in internals that shouldn't be used from the public API.

I would argue that requiring the `sizeof()` of a type breaks pointers, because of cases like the above, which in my view aren't all too uncommon.

**Comment by PDeveloper** [comment]
Currently exploring alternatives to using ::cpp::Pointer in linc_sdl, perhaps this would be a better solution!

**Comment by PDeveloper** [comment]
Changing to use a cpp.RawPointer fixes things! Sorry for the disturbance! (Hadn't noticed cpp.RawPointer before :) )

**Comment by Simn** [comment]
I'm still a bit curious what exactly changed here and what the difference between Pointer and RawPointer is. That might be worth documenting?

**Comment by PDeveloper** [comment]
As far as I know, a RawPointer is a straight up C++ pointer `Type* type_p;`

The change here is that `SDL_Window` wasn't a complete type from the headers, and `::cpp::Pointer<T>` does a `sizeof(T)`, causing it to fail (expectedly).

**Comment by hughsando** [comment]
I think I can remove the sizeof from the  header.  You are right that it is an unnecessary restriction.
The difference between raw and cpp.Pointer is that the latter wraps the pointer in a struct to allow it to be passed Dynamically.

**Comment by PDeveloper** [comment]
Yep, changing to a RawPointer causes more issues relating to Dynamic!

Should I pull request or can you do a small commit for this? :)
