### ISSUE TITLE
Error: Could not find include file "/usr/lib/haxe/lib/hxcpp/3,2,205/src/hx/libs/regexp/Build.xml"

### ISSUE THREAD

**Issue by mboussaa** [HaxeFoundation/hxcpp#437]
Error: Could not find include file "/usr/lib/haxe/lib/hxcpp/3,2,205/src/hx/libs/regexp/Build.xml"
when try to run cpp tests in hxmath
haxe test_cpp.hxml

**Comment by hughsando** [comment]
Looks like you are using the git version of haxe, with an old version of hxcpp.
You will need to use the git version of hxcpp in this case.
