### ISSUE TITLE
Null<Float> performance. 

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/hxcpp#439]
I noticed this while benchmarking performance of `Null<Float>`, consider:

```haxe
import cpp.Lib;

class Main {
    private static inline var COUNT = 100000000;
    private static inline var ITERATIONS = 3;
	static function main() {
        var start:Float = Sys.time();
        
		for (a in 0...ITERATIONS) {
            for (b in 0...COUNT) {
                var f:Float = 100;
                f = f * 100 / 100;
            }
        }
        var end:Float = Sys.time();
        trace("took: " + (end - start) + "s");
        

        var start:Float = Sys.time();
		for (a in 0...ITERATIONS) {
            for (b in 0...COUNT) {
                var f:Null<Float> = 100;
                f = f * 100 / 100;
            }
        }
        var end:Float = Sys.time();
        trace("took: " + (end - start) + "s");
    }
}
```

The results i got were:
```
Main.hx:19: took: 0.245000839233398s
Main.hx:30: took: 9.47200012207031s
```

So about a factor of 50. This isnt really a bug, and its also not of real concern as its 300 million operations, which is pretty high, however, i thought id leave this here anyways just in case there is some obvious optimisation to be had. Apparently the C# target uses a stack allocated struct - i havent even looked into the C++ to see what hxcpp is generating yet. 

Ian

**Comment by ncannasse** [comment]
That seems perfectly regular. Usually when using a nullable value, every access needs a null check, but more importantly every assignment will perform an allocation.

I guess in some cases, when the variable does not leave the function scope, it could be replaced by a float struct. I think you need a GC pointer in other cases, for instance `Array<Null<Float>>`

**Comment by ianharrigan** [comment]
Right, fair enough. I figured it wasnt that "strange" esp. as i was throwing 300,000,000 loops at it, but wasnt sure it should have been quite that high. As you say you can improve drastically by cutting down on operations (less allocations i guess) or by not assigning results (ie, `f+1` is hugely faster than `f=f+1`). 

So ill close this then, i just wasnt 100% if there was something obvious to look at so figured id mention (i didnt try any other targets either to be fair)
