### ISSUE TITLE
Calling `.ptr` on a function returned Pointer creates wrong temp var

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#440]
We've got these small helper functions we use to get the correct pointer
```haxe
private var menuBarRef(get, null):Pointer<WxMenuBar>;
private inline function get_menuBarRef():Pointer<WxMenuBar> {
    return Pointer.fromRaw(untyped __cpp__("(wxMenuBar*)(_ref->get_raw())"));
}
```

and use it like this
```haxe
public function append(menu:Menu, title:String) {
    menuBarRef.ptr.append(menu.menuRef, title);
}
```

but that doesn't work because `menuBarRef.ptr` gets put into a variable
```c++
HXLINE(  20)		 ::wxMenuBar* _hx_tmp = (wxMenuBar*)(_ref->get_raw());
HXDLIN(  20)		 ::wxMenuBar _hx_tmp1 = ( ( ::wxMenuBar)(::cpp::Pointer_obj::fromRaw(_hx_tmp)->ptr) );
HXDLIN(  20)		 ::wxMenu* _hx_tmp2 = (wxMenu*)(_ref->get_raw());
HXDLIN(  20)		::cpp::Pointer<  ::wxMenu > _hx_tmp3 = ::cpp::Pointer_obj::fromRaw(_hx_tmp2);
HXDLIN(  20)		_hx_tmp1->Append(_hx_tmp3,title.__s);
```
(second line)
and wxWidgets classes cannot be copied.

Doing it in two steps
```haxe
public function append(menu:Menu, title:String) {
    var mbr:Pointer<WxMenuBar> = menuBarRef;
    mbr.ptr.append(menu.menuRef, title);
}
```

generates a correct code
```c++
HXLINE(  20)		 ::wxMenuBar* _hx_tmp = (wxMenuBar*)(_ref->get_raw());
HXDLIN(  20)		HX_VARI( ::cpp::Pointer<  ::wxMenuBar >,mbr) = ::cpp::Pointer_obj::fromRaw(_hx_tmp);
HXLINE(  21)		 ::wxMenu* _hx_tmp1 = (wxMenu*)(_ref->get_raw());
HXDLIN(  21)		::cpp::Pointer<  ::wxMenu > _hx_tmp2 = ::cpp::Pointer_obj::fromRaw(_hx_tmp1);
HXDLIN(  21)		mbr->ptr->Append(_hx_tmp2,title.__s);
```

Anything hxcpp can do about that?
Should always be safe to create `x*` variables, but not `x`,
also avoid copy.

**Comment by ibilon** [comment]
Not having `menuBarRef` (the helper function) inline doesn't help.

Still get this with the one line call
```c++
::wxMenuBar _hx_tmp = this->get_menuBarRef()->ptr;
```

And this in two steps
```c++
HX_VARI( ::cpp::Pointer<  ::wxMenuBar >,mbr) = this->get_menuBarRef();
```

**Comment by hughsando** [comment]
You could try putting the " @:analyzer(no_simplification)" meta on the "ptr" member of cpp.ConstPointer.
I'm not sure if this is the right meta anymore, I'll have to ask @Simn.  I really need some way of saying "never put this value in a temp".

I think one cause of this problem is the ```__cpp__``` code, which confuses the analyzer.  It must be pessimistic about what can go on inside this function.  The officially best way is to replace these cpp calls with static functions with @:native overrides, like:
```
@:extern @:native("wx_helper_ref_to_menu")
static inline function refToMenu(ref:WxMenuRef) : Pointer<WxMenuBar> return null;
```
then
```
private  function get_menuBarRef():Pointer<WxMenuBar> return refToMenu(_ref);
```
You would then need a way of getting this helper into the file - possibly via an include or @:cppFileCode

**Comment by delahee** [comment]
erg, this one....I stumbled on this one way too many times,  I got used to
it and it is not a good thing.

If I may join the whine, I badly want a RGB on this one ( Really Global
Solution ).

Thanks!! <3 <3



2016-05-02 8:10 GMT+02:00 Hugh Sanderson <notifications@github.com>:

> You could try putting the " @:analyzer(no_simplification)" meta on the
> "ptr" member of cpp.ConstPointer.
> I'm not sure if this is the right meta anymore, I'll have to ask @Simn
> <https://github.com/Simn>. I really need some way of saying "never put
> this value in a temp".
>
> I think one cause of this problem is the __cpp__ code, which confuses the
> analyzer. It must be pessimistic about what can go on inside this function.
> The officially best way is to replace these cpp calls with static functions
> with @:native overrides, like:
>
> @:extern @:native("wx_helper_ref_to_menu")
> static inline function refToMenu(ref:WxMenuRef) : Pointer<WxMenuBar> return null;
>
> then
>
> private  function get_menuBarRef():Pointer<WxMenuBar> return refToMenu(_ref);
>
> You would then need a way of getting this helper into the file - possibly
> via an include or @:cppFileCode
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/HaxeFoundation/hxcpp/issues/440#issuecomment-216112540>
>



-- 
David Elahee

**Comment by Simn** [comment]
> You could try putting the " @:analyzer(no_simplification)" meta on the "ptr" member of cpp.ConstPointer.
> I'm not sure if this is the right meta anymore, I'll have to ask @Simn. I really need some way of saying "never put this value in a temp".

I'll have to check that, chances are I forgot about it when rewriting the analyzer. I don't particularly like having to do that though, it can easily bring back blocks-as-values and other horrible things.

**Comment by hughsando** [comment]
I'm actually happy to have a different meta, which should not cause any trouble.
What is needed is "never use a temp on this TField access".  The ".ptr" member can only be used as a built-in member.  You can leave it up to the developer to ensure that "(some complicated expression).ptr" does not violate any ordering etc.

**Comment by hughsando** [comment]
I have changed the haxe code to tell it that Pointer.ptr returns a cpp.Referece, which it actually does.  So any temp variable should be correctly typed.  I had to use the "typedef hack" like "Null" does - ironically, had @Simn not complained about how bad a hack it was, I would not have thought of it.

I could not really get your code into a testable state, but this small example now correctly used a temp:
```
import cpp.Pointer;

@:structAccess
extern class ExternStruct
{
   public var x:Int;

   @:native("new ExternStruct")
   public static function create(x:Int) : Pointer<ExternStruct>;

   public function someFunc(p:ExternStruct) : Void { }
}

@:headerCode("
struct ExternStruct
{
   ExternStruct(int inX) : x(inX) { }
   void someFunc(ExternStruct &s) { s.x=99; }
   int x;
};
")
class Test
{
   public static function main()
   {
      var e = ExternStruct.create(1);
      e.ptr.someFunc(e.ref);
      trace(e.ptr.x);
   }
}
```

**Comment by ibilon** [comment]
> I'll have to check that, chances are I forgot about it when rewriting the analyzer. I don't particularly like having to do that though, it can easily bring back blocks-as-values and other horrible things.

Yeah `@:analyzer(no_simplification)` didn't do anything,
but several members of ConstPointer use that meta, maybe worth investigating the consequences.

Your commit has fixed the original issue, but looks like it broke structAccess.
In the code you made if you add `trace(e.ref.x);` then `error: base operand of ‘->’ has non-pointer type ‘ExternStruct’`,
but if you do `var t = e.ref; trace(t.x);` if works.

**Comment by ibilon** [comment]
(hope that I don't sound like I'm never happy ^^)

your latest commit fixes structAccess, but also seems to force it,
`error: invalid initialization of reference of type ‘wxRadioButton&’ from expression of type ‘wxRadioButton*’`
it puts a `Pointer<WxRadioButton>.ptr` in a `wxRadioButton&`,
also mean that can't call functions `error: base operand of ‘->’ has non-pointer type ‘wxRadioButton’` for `_hx_tmp1->Create` (_hx_tmp1 is the wxRadioButton&)

**Comment by hughsando** [comment]
Yep - I need to do a typedef hack for .ptr as well, which should solve to porblem properly.

**Comment by hughsando** [comment]
Do you have a repo I can test against?

**Comment by ibilon** [comment]
There's https://github.com/ianharrigan/hxWidgets/tree/feature/haxe-3.3,
the `feature/haxe-3.3` branch, go to `samples/00-Showcase` and `haxe build.hxml`,
though you need wxWidgets 3 on your computer, a bit heavy just for a test, sorry.

**Comment by hughsando** [comment]
I have not actually tested your code, but I have made sure that Pointer.ptr and Pointer.ref can be used in temp vars, so hopefully this does the trick.

**Comment by ibilon** [comment]
Yeah it did, works now, thanks.
