### ISSUE TITLE
extern enum abstact with @:unreflective create reflection access in user class

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#441]
I've got an extern enum represented like this
```haxe
@:unreflective
@:enum extern abstract SystemMetric(SystemMetricImpl) {
    @:native("wxSYS_MOUSE_BUTTONS")      var MOUSE_BUTTONS;
}
@:include("wx/settings.h")
@:unreflective
@:native("wxSystemMetric")
extern class SystemMetricImpl {
}
```

and when I use it in a normal haxe class, c++ compilation fails with
```
./src/views/panels/SystemMetricsPanel.cpp: In function ‘Dynamic views::panels::__SystemMetricsPanel_objaddMetric(hx::Object*, const Dynamic&, const Dynamic&, const Dynamic&)’:
/home/ibilon/Code/Haxelibs/hxcpp/include/hx/Macros.h:445:58: error: conversion from ‘const Dynamic’ to ‘wxSystemMetric’ is ambiguous
       ret reinterpret_cast<class *>(inObj)->func(arg_list); return  ::Dynamic(); \
                                                          ^
/home/ibilon/Code/Haxelibs/hxcpp/include/hx/Macros.h:495:11: note: in expansion of macro ‘HX_DEFINE_DYNAMIC_FUNC’
           HX_DEFINE_DYNAMIC_FUNC(class,3,func,ret,HX_ARR_LIST3,HX_DYNAMIC_ARG_LIST3,HX_ARG_LIST3)
           ^
./src/views/panels/SystemMetricsPanel.cpp:132:1: note: in expansion of macro ‘HX_DEFINE_DYNAMIC_FUNC3’
 HX_DEFINE_DYNAMIC_FUNC3(SystemMetricsPanel_obj,addMetric,(void))
```
and force me to add `@:unreflective` to the using class.

Since the enum is extern and unreflective, shouldn't that prevent reflection when it's used too?

**Comment by hughsando** [comment]
You should be able to use use @:unreflective on the members that use the type as a parameter or return value, rather than the whole class.  But you are right, hxcpp should be able to do this for you.

You might also like to consider using ```@:native("cpp::Struct<wxSystemMetric>")``` for the implementation, which will wrap the enum in a light struct that does allow reflection.
You would have to check how this affects you usage of this item - eg, passing it as an "int" to something.

**Comment by hughsando** [comment]
I added a test to show how native enums can be used reflectively by changing the "@:native" meta.
https://github.com/HaxeFoundation/hxcpp/blob/8eeeee784cca9a271c023030d56e3f6db426076c/test/native/tests/TestNativeEnum.hx

**Comment by ibilon** [comment]
The fix works,
and the `cpp::Struct<wxSystemMetric, cpp::EnumHandler>` works great too.

Thanks!
