### ISSUE TITLE
BuildTool creates invalid paths

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/hxcpp#446]
Because of this line in PathManager: https://github.com/HaxeFoundation/hxcpp/blob/master/tools/hxcpp/PathManager.hx#L219

I get invalid paths trying to be created on a fresh windows install when trying to run `neko build.n`. Its creating paths like `c://abc/xyz`, ie, with two `/` before the drive. This then makes the create dir bomb out. I patched it locally by simply removing the ` + "/"` and all seemed fine - build completed successfully.

**Comment by hughsando** [comment]
thanks
