### ISSUE TITLE
Lib and Math link errors in windows

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/hxcpp#450]
Im using latest git version of hxcpp and after updating (and cleaning the project bin dir), i started getting this:

```
 - Link : Main-debug.exe
   Creating library Main-debug.lib and object Main-debug.exp
fbebc09c_Lib.obj : error LNK2011: precompiled object not linked in; image may not run
86800261_Math.obj : error LNK2011: precompiled object not linked in; image may not run
Main-debug.exe : fatal error LNK1120: 2 unresolved externals
```

Seems Lib and Math are causing linker errors. Any thoughts? 

Cheers,
Ian

**Comment by hughsando** [comment]
I will have a look a bit later, but one thing to try is to rebuild the hxcpp.n by compiling in the tools/hxcpp directory.

**Comment by hughsando** [comment]
Just had a quick go, and it seems to work.  Can you check the "all_objs" for the reference, like:
obj/msvc19-debugxp/__pch/runtime/hxcpp.obj
in
cpp/obj/msvc19-debugxp/all_objs

I can bump the code to force a rebuild of hxcpp.n if that helps.

**Comment by ianharrigan** [comment]
Ill try again in a bit... Im pretty sure i rebuilt all the tools, etc. But ill sanity check that. One thing i have noticed is the first compile links correctly, its subsequent builds that show this linker error. If i delete the two .obj files in question then it links again correctly. 

Ill pull and rebuild everything shortly just to sanity check.

Cheers,
Ian

**Comment by hughsando** [comment]
Yes - i can reproduce it with a second compile - thanks for the tip.

**Comment by ianharrigan** [comment]
Great. Works fine now. Thanks for the quick fix.
