### ISSUE TITLE
Modulo operation performance

### ISSUE THREAD

**Issue by troyc** [HaxeFoundation/hxcpp#455]
I was messing around with some simple benchmarks and noticed that this benchmark took 15s to complete in hxcpp, but only 3s in native C++:

Haxe:
```
	var foo:Int = 1;
	for (x in 0...1000000000)
	{
		foo *= 7;
		foo %= 337;
	}
```

C++
```
	int foo = 1;
	for (int x = 0; x < 1000000000; x++)
	{
		foo *= 7;
		foo %= 337;
	}
```

The source code calls hx::ModEq(foo,(int)337) which in turn calls doublemod (which calls fmod), converting both parameters to double. Is this something that should be optimized?

**Comment by hughsando** [comment]
Yes, I should add cpp.NativeMath.imod, like I did for cpp.NativeMath.idiv
It is too hard to build this into the standard "%" / "%=" operator - mainly
because of Dynamic access and then fact that Haxe has some very specific
rules about mod to do with rounding and negative numbers and zero

**Comment by troyc** [comment]
What are the differences between Haxe and C++ for modding integers? It seems the same as far as I can tell.

**Comment by hughsando** [comment]
Mainly how %0 works.  trace(1%0) gives NAN.

**Comment by hughsando** [comment]
In 3.3rc, this code runs as fast as your native example:
```
   using cpp.NativeMath;

       var foo:Int = 1;
       for (x in 0...1000000000)
       {
           foo *= 7;
           foo = foo.imod(337);
       }
```
Slightly more verbose, but it gets around some thing in the specification that I really don't feel like messing with.

**Comment by troyc** [comment]
Thanks, but how do I actually use that? I get `Type not found : cpp.NativeMath` on hxcpp version 3.3.49

**Comment by hughsando** [comment]
You need the haxe 3.3 rc release, or copy that one file (std/cpp/NativeMath.hx) into your own project.
