### ISSUE TITLE
Regression in comparison String != Dynamic

### ISSUE THREAD

**Issue by ntrf** [HaxeFoundation/hxcpp#459]
version 3.3.47 introcuced regression in this code:

```
package ;

class Test {
	static function main() {
		var a : Dynamic = null;
		var b : String = "!";
		
		var c : Bool = (a == b);
		var d : Bool = (a != b);
		
		trace('"!" == null  is  $c');
		trace('"!" != null  is  $d');
		
		var e : Bool = (b == a);
		var f : Bool = (b != a);
		
		trace('null == "!"  is  $e');
		trace('null != "!"  is  $f');
	}
}
```

The expected result given by both Js backend and hxcpp version 3.2.205 is:

```
Test.hx:11: "!" == null  is  false
Test.hx:12: "!" != null  is  true
Test.hx:17: null == "!"  is  false
Test.hx:18: null != "!"  is  true
```

Instead results are:
```
Test.hx:11: "!" == null  is  false
Test.hx:12: "!" != null  is  false
Test.hx:17: null == "!"  is  false
Test.hx:18: null != "!"  is  false
```

Regression intrioduced in [commit a2f443fb68](https://github.com/HaxeFoundation/hxcpp/commit/a2f443fb68bb1c5fca2b896e7322dcea91cddcc9#diff-3d757d5bfa07fb55818adae89db8ac3fL113), where operator != was reimplemented with wrong condition `return mPtr && ((String)(*this) != inRHS);` instead of correct `return !mPtr || ((String)(*this) != inRHS);`. Notice how `||` gets replaced by `&&`.

Other operators might have similar behaviour changes.

**Comment by thomasuster** [comment]
@ntrf Any chance you could add a test to https://github.com/HaxeFoundation/hxcpp/tree/master/test/haxe ?
