### ISSUE TITLE
GC crash with latest Haxe 3.3.0 RC and latest hxcpp

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#460]
I was testing my project with latest versions of Haxe 3.3.0 RC night build and the current version of hxcpp on github and found a crash on the GC:
````
Editor.exe!hx::MarkContext::Process() Line 1343	C++
Editor.exe!GlobalAllocator::ThreadLoop(int inId) Line 3046	C++
Editor.exe!GlobalAllocator::SThreadLoop(void * inInfo) Line 3069	C++

````
Attaching image of the line of crash: the pointer is invalid.
Unfortunately I can't create a simple test case right now.
[EDIT]: forgot to mention the same project runs fine with Haxe 3.2.1 (or the crash is very rare)

**Comment by ex** [comment]
![hxcppgc](https://cloud.githubusercontent.com/assets/99072/15550694/50ba7cd2-2278-11e6-9913-ecbf30616f72.png)

**Comment by hughsando** [comment]
If you define HXCPP_GC_DEBUG_LEVEL to 1 2 or 3 it should be easier to track what is going on.

**Comment by ex** [comment]
I tested again with HXCPP_GC_DEBUG_LEVEL = 3, the crash happened in another part:
![hxcpp2](https://cloud.githubusercontent.com/assets/99072/15558643/135cdec4-22a1-11e6-9011-394bbb823d8b.png)
Previously to the crash there was this output in the console:
````

Blocks 24552 = 1571328 k
Blocks 24583 = 1573312 k
Blocks 24614 = 1575296 k
Blocks 24645 = 1577280 k
Blocks 24676 = 1579264 k
Blocks 24707 = 1581248 k
Blocks 24738 = 1583232 k
Blocks 24769 = 1585216 k
Blocks 24800 = 1587200 k
Blocks 24831 = 1589184 k
Blocks 24862 = 1591168 k
Blocks 24893 = 1593152 k
Blocks 24924 = 1595136 k
Blocks 24955 = 1597120 k
Blocks 24986 = 1599104 k
Blocks 25017 = 1601088 k
Blocks 25048 = 1603072 k
Blocks 25079 = 1605056 k
Blocks 25110 = 1607040 k
...
Blocks 25141 = 1609024 k
Blocks 25172 = 1611008 k
Blocks 25203 = 1612992 k
Blocks 25234 = 1614976 k
Blocks 25265 = 1616960 k
Blocks 25296 = 1618944 k
Blocks 25327 = 1620928 k
Blocks 25358 = 1622912 k
Blocks 25389 = 1624896 k
Blocks 25420 = 1626880 k
Blocks 25451 = 1628864 k
Blocks 25482 = 1630848 k
Blocks 25513 = 1632832 k
Blocks 25544 = 1634816 k
Blocks 25575 = 1636800 k
Blocks 25606 = 1638784 k
Blocks 25637 = 1640768 k
Blocks 25668 = 1642752 k
Blocks 25699 = 1644736 k
Blocks 25730 = 1646720 k
...
Blocks 25761 = 1648704 k
Blocks 25792 = 1650688 k
Blocks 25823 = 1652672 k
Blocks 25854 = 1654656 k
Blocks 25885 = 1656640 k
Blocks 25916 = 1658624 k
Blocks 25947 = 1660608 k
Blocks 25978 = 1662592 k
Blocks 26009 = 1664576 k
Blocks 26040 = 1666560 k
Collect time total=257.88ms =0.4% sync=0.00, mark=216.19, large(240-150)=0.24, block=39.16
...
...
Total memory : 1693224960
Total rows   : 758242048
Total bytes  : 400947280
Large size   : 14044828
Empty blocks : 6469 (24.8%)
Fragged blocks : 18219 (70.0%)
Fragged score : 139.958180
Filled       : 0.528785
Try to release 84 groups, reduce 1693224960 to 1516484048
After defrag---
 Total memory : 1552122880d
 Total rows   : 430768768
 Empty blocks : 17231 (72.2%)
 Fragged blocks : 25 (0.1%)
 Released groups : 67
Collect time total=1205.04ms =1.4% sync=0.00, mark=227.06, large(168-150)=0.02, block=224.09
````
Also the complete call stack is:
````
Editor.exe!hx::MarkObjectAllocUnchecked(hx::Object * inPtr, hx::MarkContext * __inCtx) Line 1510	C++
Editor.exe!com::engine::game::SWorldActor_obj::__Mark(hx::MarkContext * __inCtx) Line 1063	C++
Editor.exe!com::engine::display::Animation_obj::__Mark(hx::MarkContext * __inCtx) Line 1461	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!openfl::_legacy::display::DisplayObjectContainer_obj::__Mark(hx::MarkContext * __inCtx) Line 903	C++
Editor.exe!hx::Hash<hx::TDynamicElement<double,0> >::__Mark(hx::MarkContext * __inCtx) Line 596	C++
Editor.exe!com::engine::iso::ISO_DepthBuffer_obj::__Mark(hx::MarkContext * __inCtx) Line 265	C++
Editor.exe!com::engine::iso::ISO_BaseActor_obj::__Mark(hx::MarkContext * __inCtx) Line 296	C++
Editor.exe!com::engine::display::Animation_obj::__Mark(hx::MarkContext * __inCtx) Line 1461	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!openfl::_legacy::display::DisplayObjectContainer_obj::__Mark(hx::MarkContext * __inCtx) Line 903	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!openfl::_legacy::display::DisplayObjectContainer_obj::__Mark(hx::MarkContext * __inCtx) Line 903	C++
Editor.exe!openfl::_legacy::display::DisplayObject_obj::__Mark(hx::MarkContext * __inCtx) Line 1245	C++
Editor.exe!com::engine::utils::TintInterval_obj::__Mark(hx::MarkContext * __inCtx) Line 234	C++
Editor.exe!com::game::demoIso::PlayerIso_obj::__Mark(hx::MarkContext * __inCtx) Line 12290	C++
Editor.exe!com::game::demoIso::ai::GSector_obj::__Mark(hx::MarkContext * __inCtx) Line 649	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!hx::MarkObjectArray(hx::Object * * inPtr, int inLength, hx::MarkContext * __inCtx) Line 1563	C++
Editor.exe!Array_obj<Dynamic>::__Mark(hx::MarkContext * __inCtx) Line 453	C++
Editor.exe!com::game::demoIso::ai::GSectorManager_obj::__Mark(hx::MarkContext * __inCtx) Line 846	C++
Editor.exe!com::game::demoIso::enemies::BaseAICommander_obj::__Mark(hx::MarkContext * __inCtx) Line 529	C++
Editor.exe!com::game::demoIso::WorldIso_obj::__Mark(hx::MarkContext * __inCtx) Line 2665	C++
Editor.exe!com::game::gui::GuiGame_obj::__Mark(hx::MarkContext * __inCtx) Line 794	C++
Editor.exe!com::engine::display::Animation_obj::__Mark(hx::MarkContext * __inCtx) Line 1476	C++
Editor.exe!openfl::_legacy::display::DisplayObject_obj::__Mark(hx::MarkContext * __inCtx) Line 1245	C++
Editor.exe!com::game::demoIso::enemies::utils::GEnemiesDebugTool_obj::__Mark(hx::MarkContext * __inCtx) Line 498	C++
Editor.exe!com::game::demoIso::GameIso_obj::__Mark(hx::MarkContext * __inCtx) Line 1862	C++
Editor.exe!com::game::demoIso::GameIso_obj_sMarkStatics(hx::MarkContext * __inCtx) Line 2366	C++
Editor.exe!hx::MarkClassStatics(hx::MarkContext * __inCtx) Line 339	C++
Editor.exe!GlobalAllocator::MarkAll() Line 3196	C++
Editor.exe!GlobalAllocator::Collect(bool inMajor, bool inForceCompact, bool inLocked) Line 3317	C++
Editor.exe!GlobalAllocator::GetFreeBlock(int inRequiredBytes, hx::ImmixAllocator * inAlloc) Line 2491	C++
Editor.exe!LocalAllocator::CallAlloc(int inSize, unsigned int inObjectFlags) Line 3998	C++
Editor.exe!Dynamic::Dynamic(double inVal) Line 352	C++
Editor.exe!alloc_float(double arg1) Line 273	C++
Editor.exe!ExternalPrimitive::__Run(const Array<Dynamic> & inArgs) Line 187	C++
Editor.exe!Dynamic::operator()(const Dynamic & inArg0, const Dynamic & inArg1, const Dynamic & inArg2, const Dynamic & inArg3, const Dynamic & inArg4, const Dynamic & inArg5) Line 567	C++
Editor.exe!openfl::_legacy::Lib_obj::create(Dynamic onLoaded, int width, int height, hx::Null<double> __o_frameRate, hx::Null<int> __o_color, hx::Null<int> __o_flags, String __o_title, hx::ObjectPtr<openfl::_legacy::display::BitmapData_obj> icon, hx::ObjectPtr<hx::Class_obj> stageClass) Line 289	C++
Editor.exe!ApplicationMain_obj::main() Line 164	C++
Editor.exe!main(int argc, char * * argv) Line 86	C++
````

**Comment by ex** [comment]
The tests cases on #366 are crashing, they are in the same repo. https://github.com/ex/haxe/tree/master/gc
There are two cases in one file controlled by a define at line 14 of Main.hx

**Comment by ex** [comment]
Additionally activating HXCPP_SINGLE_THREADED_APP is just hanging the GC on Collect

**Comment by hughsando** [comment]
The call stack looks reasonable.  I'm guessing that the GC moved some blocks and something had a pointer which was not updated.  It then overwrote some data, which caused a crash at the next collect.
I'm not really sure what has changes, except that far fewer temp variables are generated, and maybe this means the marking is missing something.
It appears you have quite a big project here, so I'm not really sure to go about tracking this down.
I guess I will have to try to make some kind of stress test.

**Comment by ex** [comment]
@hughsando thanks for your time checking this issue.
I myself would also try to get a reproducible case, I was trying some simple cases and it didn't crashed, we need to go hard in the resource and memory usage for this to happen.
Yes, I think we must be pushing the limits of hxcpp right now :D. 
A bit offtopic but I raised issue #474 , if a big project like ours come out without a proper mention of you it would feel kind of sad, unless that is what you really want. Not sure if I can change credits at this stage however.

**Comment by hughsando** [comment]
I think there is no obligation to mention me by name - I will not be sad.
It is enough to know that it is useful on a big project.
Also off topic, have you tried running it against nme rather than opengl legacy?  Or do you need js support?

**Comment by ex** [comment]
@hughsando I started using Haxe when nme was the only option, it worked great but we never really pushed the limits. After some mobile projects we changed to openfl and things got pretty unstable, and unfortunately we are now stuck in an outdated legacy version of openfl with many changes to support additional platforms. @madrazo is part of my team and has tested current nme and found some issues like the audio not working and similar performance to legacy openfl (testing right now our project failed to compile using nme for x64 windows but it can be our fault).

Having JS support was great in theory, but in practice the generated JS is still too much for mobile targets to handle and so so we have a separated JS engine for web games. Maybe web assembly can change all this but is still in the future.

So right now my only big concern is to achieve 60+ FPS on C++ targets. 
I was considering kha and heaps but they are very different and I suspect they are also bound to the hxcpp GC performance limitations (not incremental and memory fragmentation over long runs with many objects).

**Comment by james4k** [comment]
The crashes I've seen have all been to do with pointers that are stored in unmanaged memory, and so the GC cannot adjust them when the objects move. I don't know much about nme or openfl legacy, but I suspect it is a problem there.

It might be a good idea to add a debug flag to detect this case that would do something like:
1. Always keep old memory when moving, which are filled with a recognizable pattern of bytes. Or maybe a flag is left in the alloc header.
2. Probably in the same place as HXCPP_GC_CHECK_POINTER, check for the recognizable pattern and/or the flag in the alloc header.

If this is the case for you, the only thing you can really do right now is manage a table of objects to handles in hxcpp memory, and store an index into that table in unmanaged memory. Or avoid these kind of references entirely.

**Comment by ex** [comment]
@james4k the crashes only happen on Haxe 3.3.0, it seems 3.2.1 its fine. The problem of not using HXCPP_GC_MOVING is that performance suffered a lot once the memory consumption goes near 2 GB, at least when I tested this time ago.

**Comment by hughsando** [comment]
Yes, I would expect similar performance between openfl legacy and nme, since the code is very similar.  The main reasons why I suggest nme is that it is still actively being developed, the source code is less spread out and I am pretty familiar with it, so generally I would have a better chance of guessing what is going wrong.  I'm also happy to investigate performance issues in it.
There is nothing in the gc or hash code that depends directly on the haxe-version define.
The main difference is the VirtualArray (for ```Array<Dynamic>```) code, and ```cpp::Variant``` - I will check both of these for moving safety.
I could possibly maintain a map of moved-pointers and add a check to this in GC_CHECK_POINTER, which should help locate as early as possible when a moved pointer is accessed.  This is probably the next step if you have a "reasonably" repeatable crash.

**Comment by hughsando** [comment]
I added an option to move more often, and in combination with the "spam collects" option, I think I have seen a crash.  It looks like it may have missed marking a local variable, or perhaps moved something while it was partially constructed.  The way variables are initialized and constructed is a bit different from 3.2.1 - I can put this back and see if that solves something too.

**Comment by ex** [comment]
@hughsando glad to hear that you can reproduce a crash, and yes, it is in our top priority list to port all our engine to Haxe 3.3 and nme. The better C++ code generation alone is too much to ignore.

**Comment by hughsando** [comment]
I found 2 issues.
1 - finalizers we not moving their object, this would have been on all versions of hxcpp
2 - VirtualArrays we not being moved correctly - this is 3.3 issue.

Hopefully this fixes your issue.

**Comment by ex** [comment]
@hughsando thank you very much for this!
we are currently in crunch mode for our deadline so it will take a bit before I could test this but I'm more that eager to start testing your latest changes.

**Comment by ex** [comment]
@hughsando applying your fixes to our game I could not reproduce the crash! :D 
In the past the crash in the GC and the crash with the vector array happened after some minutes but today I tested it almost one hour without issues; just because this is a random issue I'm leaving a build in a separate PC to run all day, also to collect memory usage statistics.
Thank you very much for your hard work.

**Comment by hughsando** [comment]
Sweet.

On Tue, Jul 26, 2016 at 5:28 AM, Laurens Rodriguez <notifications@github.com
