### ISSUE TITLE
hxcpp.DebugStdio(true) replacement

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#461]
Is there any replacement for hxcpp.DebugStdio(true)?
I was reading this old post: http://gamehaxe.com/2012/09/14/hxcpp-built-in-debugging/ and I was wondering if I can force Visual Studio to stop the debugger from haxe using this line.
I didn't found the class in current implementation.

**Comment by Gama11** [comment]
Did you find a solution?

**Comment by ex** [comment]
Not exactly, I think it would be good to have this behavior again, but in the meantime I'm just attaching the process to Visual Studio C++ and opening the corresponding C++ generated file in the compilation (inside cpp/obj) and putting a breakpoint there, is not ideal but new 3.3.0 hxcpp C++ generator makes things more easy to follow.
