### ISSUE TITLE
How to unset abstract value on neko? free_abstract doesn't work on neko.

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#475]
I've tried using `free_abstract `on neko, but this didn't work on neko.
It would be nice if I can unset abstract value on neko in the same way. I can avoid dangling pointer issues with this.
For example, this would be useful when you are referencing the same abstract value from multiple C++ classes with `AutoGCRoot`. This will allow you to destroy C++ object manually, and check if it's still alive.

Doc says that on neko you can unset abstract value by directly modifying struct value ( `val_kind(v) = NULL;` ), but I think it's impossible to do this from hxCFFI.

http://nekovm.org/doc/ffi

**Comment by hughsando** [comment]
I added some code to the Neko CFFI version - see if this works for you.

**Comment by vroad** [comment]
Thanks, i'll see if that works.

**Comment by vroad** [comment]
It's working, but it seems that it's not allowed to free root value on neko... Application crashes after I delete an AutoGCRoot because of heap corruption, even though this works fine on cpp and cs. I created a issue for this.

https://github.com/HaxeFoundation/neko/issues/138

 Maybe I have to think of mehod that doesn't need AutoGCRoot.
