### ISSUE TITLE
Crashes on 3.3.0 RC1 using NativeArray interface

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#476]
I'm getting many crashes after updating to latest version. I have an array class that implements ArrayAccess and uses NativeArray unsafe get and set to maintain pools of objects. 
It was working fine with 3.2.1 (or at least without crashes, I didn't really dig inside the memory operations), but now is crashing with invalid pointer errors.
Does something changed with this interface in the new version? 
I'll try to get a simple test case.

**Comment by hughsando** [comment]
A simple case would be good.  A snippet of the generated code could also help.

**Comment by ex** [comment]
I think this was fixed in https://github.com/HaxeFoundation/hxcpp/commit/995a980d6b21676e399c760277cd8313501284e2 testing a little more before closing it.
