### ISSUE TITLE
How to only transpile to cpp code?

### ISSUE THREAD

**Issue by willstdueswissen** [HaxeFoundation/hxcpp#477]
How to only transpile haxe code to cpp?
If i run haxe -main Main -cpp ./build it's automatic compile the cpp files.
I dislike it.
Can i fix it with a flag?

**Comment by Gama11** [comment]
You can use `-D no-compilation`, see `haxe --help-defines`:

```
no-compilation            : Disable final compilation for Cs, Cpp and Java
```

**Comment by willstdueswissen** [comment]
Wow very nice :+1: 
Thanks.
