### ISSUE TITLE
HxString does not call alloc_string when it's constructed, making it impossible to return C string on stack

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#479]
How can I return temporary string correctly then? I don't want to use global variable just to return temporary string.

https://github.com/openfl/lime/blob/0bcd8d46eee75eb8ea5f310e8d2270dd67ca9253/project/src/graphics/opengl/OpenGLBindings.cpp#L855

This code may cause the app to read from invalid pointer, as it allocates CFFI string with `alloc_string` AFTER local variable `char buf[1024]` is destroyed. I also think that we shouldn't use fixed sized buffer for returning error log, though that's another issue.

I could workaround this by making return type `value` instead of `HxString`, but this will also change function signature. CFFIPrime refuses to load C++ functions with different type signature, so you should change return type of functions to `Dynamic` from `String`. But I want to use `String` for return type as well...

I think HxString should have constructor that allows you to set CFFI string allocated with `alloc_string`.

**Comment by hughsando** [comment]
Yes, I'm thinking the pointer should always be converted on input, and
never when converted to value.

**Comment by hughsando** [comment]
but then it needs a double allocation on neko, so I'll have to think about
it...

**Comment by vroad** [comment]
I added third parameter named "allocated" to handle this situation.
This would allocate CFFI string only when it's not already there. I'm not sure about neko-specific issue.

https://github.com/vroad/hxcpp/commit/f89cdd64ad97e1b59cbbbb3b00417d0422ff66c1

I reverted this for now as it loses compatibility with original hxcpp. And this still does not allow you to allocate string directly from wchar_t. Is that okay?

**Comment by hughsando** [comment]
The structure needs to match the cpp struct layout so it can be used without conversion.
When used with cpp, the ```__s``` fields needs to be a gc copy of the actual data - adding this will solve your problem.  And it does not need to go to a value, like it does for neko.
On neko, you would ideally cache it as a 'neko_value' which requires an allocation.  But you need to be able to use the same ndll for both targets, which means you need to do stuff at runtime, not compile time.
So I think adding a optional (but on by default) conversion from the constructor char * to a "gc string pointer" (new cffi api function).  On neko, this is just a copy (using gc memory), on cpp it is the final result.  Then neko will finally convert to value by allocating another string.
This does 1 extra copy on neko, but you would end up with something like this is you  were to use a "std::string".
If converting from a wchar_t, ```__s``` should be a utf8 representation.
