### ISSUE TITLE
Hxcpp looks for libraries in wrong location

### ISSUE THREAD

**Issue by rknonchalance** [HaxeFoundation/hxcpp#484]
Good afternoon! I'm a novice developer that just revisited Haxe since I tried it along with Lime/OpenFL/Haxeflixel last year. I retried it now with HaxeDevelop as my IDE, but I encountered a tiny error on the version of hxcpp I downloaded month (if it's already fixed now please say so :)). When I attempt to compile to Windows using hxcpp, it tries to find the libraries at:
hxcpp/src/hx/libs
but the libraries used are now currently under:
project/libs
I simply moved them to make them work but it's a bit odd it hasn't been changed yet.

**Comment by hughsando** [comment]
Currently, with hxcpp 3.3.49+, there is library code under both these
locations.
When you compile with haxe 3.3rc, it will use the code under src/hx/libs
When you use haxe 3.2.1, it should use the code under projects/libs.
Perhaps there is something I have not accounted for with flashdevelop, or
perhaps you need to update the haxelib version of hxcpp.

**Comment by rknonchalance** [comment]
Ah I see. I forgot to mention using Haxe 3.3.0-rc1 along with hxcpp. It works fine without issues so far, thanks.
