### ISSUE TITLE
scripts evaluation doesn't throw exceptions for unknown variables on Haxe 3.3

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hxcpp#489]
The following code returns `null` on target CPP but should throw an exception since the variables are not declared.
```haxe
var program = new hscript.Parser().parseString("foo-bar");
var result = new hscript.Interp().execute(program);
haxe.Log.trace("RESULT=" + result);
```

Neko, Flash, Python  throw an exception like:
```
Called from hscript.Interp::execute line 207
Called from hscript.Interp::exprReturn line 211
Called from hscript.Interp::exprReturn line 212
Called from hscript.Interp::initOps line 78
Called from hscript.Interp::expr line 284
Called from hscript.Interp::resolve line 264
Uncaught exception - EUnknownVariable(foo)
```

Tested with hscript 2.0.7, haxe 3.3.0-rc1, hxcpp 3.3.49

When testing with Haxe 3.2.1 the CPP target works as expected.

**Comment by hughsando** [comment]
Closed by https://github.com/HaxeFoundation/haxe/commit/25b62c2bc66eb5177ef01f2fd671b270ff1f4c61
