### ISSUE TITLE
Strange memory consumption behavior using HXCPP_GC_MOVING

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#490]
The graphic below is a cyclic run test of the loading and unloading of all the levels in our current game project. the OFF and 3.3 runs are using github versions of Haxe and hxcpp. Similar behavior can be seen using Haxe 3.2.1 as graphic shows. (Memory is on Y-axis on MB and level runs on X-axis)

![memory](https://cloud.githubusercontent.com/assets/99072/17114323/fd5d1316-5273-11e6-9d3f-15e48ce2bc85.png)

As you can see, using HXCPP_GC_MOVING has the advantage of using less memory (at least in Haxe 3.2.1, the different memory pattern usage between 3.2.1 and 3.3 can be due to Haxe 3.3 game code not being exactly the same due to a possible hxcpp bug building pooling classes that I disabled to run the tests.)

As time passes the memory ramps up with big steps consuming more and more memory on long runs. The version without usin HXCPP_GC_MOVING has a regular pattern but uses more memory from the beginning.

**Comment by hughsando** [comment]
So if I understand this correctly, the non-moving case (OFF) uses a constant 2000MB of memory - presumably this is fragmented and slower, but sufficient to run the app.
The moving case appears to be leaking, or at least thinks is needs more memory as you churn though reloading the level over and over.
I think the clue here might be the spike down before it returns to a higher level.  Here it looks like it is releasing blocks - but maybe something has not taken this into account.
How are you measuring the MB used?
If you could try removing the code in Immix.cpp that sets "releaseGroups" to anything other than 0, that would help me track down this problem.

**Comment by ex** [comment]
Hi @hughsando : yes, the non-moving version uses a semi constant 2 GB of memory, they start the same however using 1.3 GB of RAM. We are using the moving flag because during development our game level editor used to need near the double of memory than the game only version and it was crashing or it was too slow to be used on PCs with 4 GB of RAM. also, we tested at that time that the game was faster using the moving flag, but after that we went through many rounds of memory optimizations, we need to check again.

Regarding of how memory was measured, we are just using the system reported value: "tasklist /FI".
We were trying to use the MEM_INFO_USAGE, MEM_INFO_RESERVED, etc with memInfo, but these values were not giving us the total amount used by the application, I think if we added two of them we could get an approximate value but it was very unreliable so we ended with the system value. I'd like to have a flag to get the total amount of all the memory buffers allocated by the GC at any time.

I tested again using releaseGroups=1, the behavior is the same, but it seems the spikes happens after more time but in the end they leak more that the one with releaseGroups=0

![gc2](https://cloud.githubusercontent.com/assets/99072/17153426/565c2b4a-5342-11e6-9e39-394efcadd555.png)

**Comment by hughsando** [comment]
I have just made a few changes to do with defragmentation.  One was to pay more attention to how well each row was filled, and detect fragmentation better that way.  Another was to "borrow" some empty blocks when compacting to give the fragmented data somewhere to go.  These borrowed blocks can then be released after compacting.  Lastly was to calculate the working size from the defragmented size, rather than the fragmented size. 
The changes allow a much better upper bound on the required data.
The downside is that these defragmentation passes can generate quite large pause times for large data.
I am interested to know if these changes help you.

**Comment by ex** [comment]
@hughsando glad to know, let me test this in our project and I'll come back to you soon. Many thanks!

**Comment by thomasuster** [comment]
@ex How are you generating this graph?

**Comment by ex** [comment]
@thomasuster I'm just leaving a special build of our game to run for hours, the special build just loads and unloads all the levels of our game cyclically. Whenever a level is loaded we use the command "tasklist /FI" to get the whole game memory consumption and log it to a file. After that I just regex the file for the memory logs and put that into a google sheet for the graphic.

**Comment by ex** [comment]
@hughsando there is something weird going with my test using the latest versions of Haxe and hxcpp. Without moving (RED): memory just keeps going up (it crashed after reaching memory system limit). With moving enabled (ORANGE): I can see it consuming less memory but still too much memory, compared with previous version (BLUE).

A big difference is that we are using now NME for this test. Until I can recompile our project with latest Haxe and openfl legacy I can not say for sure if this is a problem in Haxe or our version of NME.

![mem001](https://cloud.githubusercontent.com/assets/99072/20774181/3649be04-b723-11e6-92ba-57ba11c38e23.png)

**Comment by hughsando** [comment]
Looks pretty leaky.  Is should run some stress allocations on nme.

**Comment by ex** [comment]
@hughsando unfortunately this seems to be a NME issue, I'm still processing more test runs but what I have at hand show that just changing our target from OpenFL to NME causes the leaky behavior.

**Comment by hughsando** [comment]
I ran some tests creating/releasing display objects (including bitmap
render), text and cacheAsBitmap and it did not seem to leak like this.
I'm thinking it is just one component I need to isolate.  Maybe a
weak-callback event listener or something like that?
Any ideas on the types of nme operations you are doing would help me create
a better stress test.

**Comment by hughsando** [comment]
I did not check audio - does this test include audio?

**Comment by ex** [comment]
@hughsando yes this test loads audio

**Comment by thomasuster** [comment]
@ex Can you try narrowing down the asset type to just be audio, or just textures, etc?

**Comment by ex** [comment]
@thomasuster yep! I'll disable the audio and test again. @madrazo is suspecting the TextField

**Comment by ex** [comment]
@thomasuster @hughsando we found the problem with the leak in our code, I'm very sorry about the false alarm. I'll try again the tests with our fixed code.

**Comment by ex** [comment]
@hughsando great news! the last version seems to be consuming less memory when using the MOVING flag. I could not test for frame performance drops but we are going to test this as soon as we are free, currently we are a bit busy.
![moving](https://cloud.githubusercontent.com/assets/99072/21161398/6908827a-c156-11e6-992a-392c8d786c98.png)

**Comment by hughsando** [comment]
I'll close this issue.  We can start a new one if there is more to talk about.
