### ISSUE TITLE
Haxelib does not look for hxcpp in local repositories

### ISSUE THREAD

**Issue by desttinghim** [HaxeFoundation/hxcpp#495]
I'm not sure where to report this, but haxelib will not look for hxcpp in a local repository. Instead, it will always look for hxcpp in the global haxelib repository.

Replication instructions:
First:
```
haxelib remove hxcpp #do this outside of a folder with a local repo
mkdir test
```
Then create [these files](https://gist.github.com/desttinghim/c96d28d79d476607a133fa4ce084e041) inside that folder. Finally, run these commands:
```
haxelib newrepo
haxelib install all
haxe build.hxml
```
And you will get a build error telling you hxcpp is not installed.

I think this has to do with it being a target instead of a standard library. If this is not the right place to report this error, please tell me and I'll open the issue in the correct place.

**Comment by hughsando** [comment]
Is the problem that "install all" does not include hxcpp?  I guess it could
check for a "-cpp" target.  You could also add "-lib hxcpp" to the hxml to
work around this.

Another problem with a truly local repo is that haxe first changes
directory to the same directory as the generated build.xml file (the one
you specify with -cpp xxx) before running haxelib. This would confuse a
relative path.

**Comment by desttinghim** [comment]
That is not the error. hxcpp will be installed from the `haxelib instal all` command if you have cpp as a target. 

Your second point is right on the money though! That explains why the global hxcpp directory is being used instead of the local one. Looks like this is would have to be a feature request on haxelib instead of here.
