### ISSUE TITLE
Rebuilding Android fails with backslashes in HXCPP_COMPILE_CACHE path

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/hxcpp#499]
With this, `neko.n build.n windows` works just fine:

``` xml
<set name="HXCPP_COMPILE_CACHE" value="C:\Users\Jens\.hxcpp_cache" />
```

But `neko build.n android` does not:

```
neko run.n Build.xml -Dandroid -Dstatic_link C:/HaxeToolkit/haxe/lib/hxcpp/git/project/
 clean C:/HaxeToolkit/haxe/lib/hxcpp/git/lib/Android/libstd.a
 - Link : C:/HaxeToolkit/haxe/lib/hxcpp/git/lib/Android/libstd.a
arm-linux-androideabi-ar: C:UsersJens.hxcpp_cache/std/79/21820a2112ebe2982535c06ade927c.obj: No such file or directory
Error: error running arm-linux-androideabi-ar -cr C:/HaxeToolkit/haxe/lib/hxcpp/git/lib/Android/libstd.a @obj/android-stat/all_objs
#### Error building neko -Dandroid -Dstatic_link
```

The path with missing backslashes in "no such file or directory" got me to try forward slashes, which fixes the issue (well, sort of, crashes with something else later on).

Using latest hxcpp (87193e6), Neko 2.1.0 and Haxe 3.3.0@87193e6.

**Comment by hughsando** [comment]
looks like the all_objs file needs escaping of backslashes in arm-linux-androideabi-ar
I have had issues with needing/need not to have quotes in these files.  I guess this is another version of this bug.
