### ISSUE TITLE
Cannot build binaries for Android

### ISSUE THREAD

**Issue by Tiago-Ling** [HaxeFoundation/hxcpp#501]
Haxe version: haxe-3.3.0-rc1-dev-f769ed1-win
Hxcpp version: Latest commit 3896d66

When using the command `neko build.n android` the build fail with the following error:
http://hastebin.com/sivaxuzapu.tex

This is on a fresh installation and after successfully building the tools ( `/hxcpp/tools` and `/build` directories). Building for windows works without any problem.

**Comment by Gama11** [comment]
I had the same error a few days ago. Then it just disappeared out of the blue, I haven't changed anything relevant that I know of.

**Comment by hughsando** [comment]
I wonder if something is running out of processors.
It looks like hxcpp is not printing out the command line for the process
creation error.
If you compile  -D HXCPP_VERBOSE you should see this line, which might give
extra clues.

**Comment by Tiago-Ling** [comment]
Here is the output with -DHXCPP_VERBOSE (didn't copied everything because windows command prompt):
http://hastebin.com/mapakoqete.tex

**Comment by hughsando** [comment]
Do you have this directory?

C:\Development\Android
NDK/toolchains/arm-linux-androideabi-4.4.3/prebuilt/windows/bin

It says it is assuming the ndk is version r8, but perhaps its not, and it
has a different directory layout.

I will see if I can make it work out-of-the-box with android studio.

**Comment by Tiago-Ling** [comment]
Yes, it has the folder `C:\Development\Android NDK\toolchains\arm-linux-androideabi-4.4.3\prebuilt\windows\bin` with the following files inside:
![image](https://cloud.githubusercontent.com/assets/1617118/18005372/f5762d94-6b6f-11e6-9dd0-588fda45a9e3.png)

Before attempting to build i've reinstalled all of the android-related stuff through `openfl setup android` command. I'm on OpenFL `3.6.1` and Lime `2.9.1`, could this be related somehow?

**Comment by hughsando** [comment]
Ok, so it is trying to link the 64 bit version with "aarch64..." and can't find the command - or there is something funky with the call.  It's odd that it can compile fine, but not link.

I think the clue might be:
- Adding path: C:\Development\Android NDK/toolchains/aarch64-linux-android-/prebuilt/windows/bin

Note that the there is a "-" after aarch64-linux-android, but no build number.  This must be something to do with android studio, which I will have to look at.

**Comment by Tiago-Ling** [comment]
Just tested building Android binaries with latest Haxe + Hxcpp from git on Mac OSX 10.11.5 and it worked normally. Cannot test this on windows currently, but will do as soon as i can.

**Comment by madrazo** [comment]
Hi. I got this error on windows when first building hxcpp (I have the latest Android Studio, ndk r13, hxcpp git, haxe nightly)

 - Link : libApplicationMain.so
arm-linux-androideabi-g++: error: C:\dev\androidndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9/libgcc.a: No such file or directory

The directory is now named 4.9.x instead of 4.9 (C:\dev\androidndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x)

I see that this is the TOOLCHAIN_VERSION in android-toolchain.xml

**Comment by madrazo** [comment]
Sorry, the flag -DNDKV12 solved it

**Comment by madrazo** [comment]
Hi. just to report that I have sent 2 PR that solve this issue with ndk r13 and r13b linking. https://github.com/HaxeFoundation/hxcpp/issues/529
Thanks!
