### ISSUE TITLE
Array<haxe.ds.Vector> does not allow [][] access

### ISSUE THREAD

**Issue by velochy** [HaxeFoundation/hxcpp#520]
I have a bunch of matrices stored as`Array<Vector<Float>>`. When I try accessing them with [i][j] syntax, compiler fails with: 

> error: invalid initialization of non-const reference of type ‘Array<double>&’ from an rvalue of type ‘Array<double>’
>  HXLINE(  10)  ::haxe::Log_obj::trace(( (Float)(_hx_array_unsafe_get(av->__get((int)0).StaticCast< ::Array< Float > >(),(int)0)) ),hx::SourceInfo(HX_("VectorBug.hx",4d,5d,55,37),10,HX_("VectorBug",11,46,3a,19),HX_("main",39,38,56,48)));

What follows is a minimal example which gives this error (NB! without the trace, the access is optimized out).

```
package;
import haxe.ds.Vector;
class VectorBug {

    public static function main ():Void {
           var av = new Array<Vector<Float>>();
           av.push(new Vector(1));
          av[0][0] = 0.0;
          trace(av[0][0]);
    }
}
```

**Comment by hughsando** [comment]
What versions are you using?
This may have been fixed - I'm testing overnight versions of haxe and hxcpp.

**Comment by velochy** [comment]
3.3.49, i.e. the version up in Haxelib, not github master.
If that test snippet compiles with the new version, I think it is safe to assume it is fixed :)

**Comment by hughsando** [comment]
Seems good now.
