### ISSUE TITLE
Android/iOS: crashing when Bytes getFloat from unaligned data

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/hxcpp#522]
Hi. I am investigating a crash when calling

var bytes:haxe.io.Bytes = nme.Assets.getBytes( filename ); 
 bytes.getFloat( position ); //crash here

which should call hxcpp's __hxcpp_memory_get_float
It works OK on Windows with 64 bit flag.

**Comment by madrazo** [comment]
The error is
A/libc: Fatal signal 7 (SIGBUS) at 0x666fb769 (code=1), thread 5560 (Thread-4070)

and some googling points to a data alignment issue.

**Comment by madrazo** [comment]
Defining HXCPP_ALIGN_FLOAT (in hxcpp.h) solved the issue

**Comment by madrazo** [comment]
This flag sets also HXCPP_ALIGN_ALLOC in GC.h, but in a small test I see that the framerate was a little lower, so, I am just setting it for the function I need (__hxcpp_align_get_float32). Next time, I'll try to align data in the binary files. 

I'm thinking on adding alignment check, maybe just for -debug, ( http://stackoverflow.com/questions/1898153/how-to-determine-if-memory-is-aligned-testing-for-alignment-not-aligning ) to match http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0491c/Babfcgfc.html

**Comment by hughsando** [comment]
Which device was this on?  I wonder if it is on all devices.  I have a few
I can test on.

**Comment by madrazo** [comment]
It was in a Galaxy Tab 3, but also happens on iOS, on an iPod 5th. My floats are unaligned on the binary file.

**Comment by Yanrishatum** [comment]
Can confirm for Galaxy Tab 3 and 2 other android devices (can't say exact models, though). I've got this error during PocketKingdom development and thought it's problem on a ARM processor side, so just rewrote all of the save-system to use only Int32 and Float.

**Comment by codeservice** [comment]
I can confirm issue on IOS. When I load binary 3ds file for parsing, getFloat crash

**Comment by codeservice** [comment]
In addition the same code works fine in windows 32, Mac, android 6 nexus 7
Crash only on IOS (XCode 8) ByteArray->readFloat->untyped __global__.__hxcpp_memory_get_float(b, position);

**Comment by madrazo** [comment]
Hi. I don't think that https://github.com/HaxeFoundation/hxcpp/blob/4d71d1c7c32915db4b6672d4436bbe8e3a4108b1/include/hx/GC.h#L16
is needed for arm, Android/iOS. May be set on a different flag? Thanks

**Comment by hughsando** [comment]
Good point.

**Comment by madrazo** [comment]
I am having this issue again when compiling iOS on release. On debug it is OK, but on release crashes (ipod 5th).
