### ISSUE TITLE
sys.net.waitForRead crashes on Windows

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/hxcpp#524]
waitForRead() crashes with a "Null Object Reference" on Windows.  (I did not test other platforms.  The problem stems from waitForRead calling select(), with nulls for the last three parameters, but in Socket.cpp, these nulls are not checked for, when preparing the return values.  Adding a `if(a == NULL) return null();` in the make_array_result() function fixes this, but I don't know if it's the right approach.

**Comment by thomasuster** [comment]
I think I had the same issue for neko after checkout out the latest. Does passing empty arrays work for you?
`var select:Dynamic = Socket.select([], [socket], [], timeout);`

**Comment by ckentgeorge** [comment]
I didn't try passing empty arrays, as it looks like nulls should be allowed, but that was going to be my next test.  Either way, the fix is a library change.

**Comment by thomasuster** [comment]
@ckentgeorge Ahh okay, yea I use to pass nulls as well. I wasn't sure what the API intended.

**Comment by hughsando** [comment]
The call should have a null-check in there now.
