### ISSUE TITLE
Do not quote Process argument when not necessary

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hxcpp#527]
Currently Process implementation quotes all arguments that passed to the process. While this is understandable, this results in sometimes broken behaviour.
Example:
```haxe
// This will return proper results, but not possible to catch stdout.
Sys.pritln(Sys.command("wmic", ["OS", "get", "Caption,Version", "/Value"]));
// This on the other hand will make quotes around all arguments, resulting in error.
var p:Process = new sys.io.Process("wmic", ["OS", "get", "Caption,Version", "/Value"]);
Sys.println(p.stdout.readAll().toString()); // Nothing
Sys.println(p.stderr.readAll().toString()); // Invalid GET switch.
// Quotes around "Caption,Version" makes them a single key, which makes it invalid query. 
// Quotes around "/Value" does not trigger that switch and returns error.
```
Expected command is `wmic OS get Caption,Version /Value`. But instead Process uses `"wmic" "OS" "get" "Caption,Version" "/Value"`.

**Comment by hughsando** [comment]
I think this is relying on the dos command  line to spit on the comma.
Perhaps the correct result here would be to split "Caption,Version" into two separate strings before passing to command, using your application specific knowledge.
ie, would this work:
```wmic OS get Caption Version /Value```

**Comment by Yanrishatum** [comment]
@hughsando 
Nope, it only accepts comma-separated values and if values can be quoted, comma sould be unquoted. And same goes to switches. `/Value` *should* be unquoted, otherwise it'll be not processed and will return an error. 
E.g.:
```cmd
wmic OS get "Caption","Version" /Value
REM OK
wmic OS get "Caption,Version" /Value
REM ERROR, comma is part of key so query is literally "Caption,Version" instead of 2 keys.
wmic OS get Caption Version /Value
REM ERROR, Invalid GET Expression because no comma and `Version` is processed
REM not as part of GET query.
wmic OS get Caption,Version "/Value"
REM ERROR, Invalid GET Expression because /Value switch is quoted.
```

**Comment by hughsando** [comment]
If I use a test prog:
```
#include <stdio.h>

int main(int argc, char **argv)
{
   for(int i=0;i<argc;i++)
      printf("%d] '%s'\n",i, argv[i]);
   return 0;
}
```

I get the results:
```
0] 'prog.exe'
1] 'OS'
2] 'get'
3] 'Caption,Version'
4] '/Value'
0
0] 'prog.exe'
1] 'OS'
2] 'get'
3] 'Caption,Version'
4] '/Value'
```
This is the best cpp can do I think.  Perhaps this was fixed in an update.

The difference could be the cmd shell.  In which case, your process might be like:  "cmd", ["/c","wmic",....]
