### ISSUE TITLE
Android setup? NDK r13b is failing to link. 

### ISSUE THREAD

**Issue by ex** [HaxeFoundation/hxcpp#529]
Can we have documentation about the latest stable SDK/JDK/NDK versions to use for Android? 
According to openFL [here](http://www.openfl.org/learn/docs/advanced-setup/android/) the supported versions are: API 16, JDK 1.6, NDK r8b. but these are for lime and kind of outdated. 
Trying the latest NDK r13b (x86 and x86) my build is failing with:
````
 - Link : libApplicationMain.so
arm-linux-androideabi-g++: error: C:\Development\ndk13b/toolchains/arm-linux-and
roideabi-4.9/prebuilt/windows/lib/gcc/arm-linux-androideabi/4.9/libgcc.a: No suc
h file or directory
Error: error running arm-linux-androideabi-g++ -olibApplicationMain.so -frtti -n
ostdlib -std=c++11 -Wl,-shared,-Bsymbolic -Wl,--no-undefined -Wl,-z,noexecstack
--sysroot=C:\Development\ndk13b/platforms/android-9/arch-arm -LC:\Development\nd
k13b/platforms/android-9/arch-arm/usr/lib @obj/android/all_objs -ldl -landroid -
lGLESv2 -lEGL -lz C:\Development\ndk13b/sources/cxx-stl/gnu-libstdc++/4.9/libs/a
rmeabi/libgnustl_static.a C:\Development\ndk13b/platforms/android-9/arch-arm/usr
/lib/crtbegin_so.o C:\Development\ndk13b/toolchains/arm-linux-androideabi-4.9/pr
ebuilt/windows/lib/gcc/arm-linux-androideabi/4.9/libgcc.a C:\Development\ndk13b/
platforms/android-9/arch-arm/usr/lib/libc.so C:\Development\ndk13b/platforms/and
roid-9/arch-arm/usr/lib/libm.so -llog -ldl
Error: Build failed
````
However the deprecated r12b and r13 versions work, but I'm not sure if it's OK to use these deprecated versions. I'm using APi 25 and JDK 1.8.

**Comment by madrazo** [comment]
The problem is that the directory name is "4.9.x" instead of "4.9" 

A workaround is just to make a copy of the directory (ndk-bundle/toolchains/arm-linux-and
roideabi-4.9/prebuilt/windows/lib/gcc/arm-linux-androideabi/4.9) to "4.9.x"

**Comment by madrazo** [comment]
Adding
`   <flag value="-I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/${TOOLCHAIN_VERSION}.x/include" />
`below
`   <flag value="-I${ANDROID_NDK_ROOT}/sources/cxx-stl/gnu-libstdc++/${TOOLCHAIN_VERSION}/include" />`
in android-toolchain.xml seems to be a better fix

**Comment by madrazo** [comment]
This:  https://github.com/HaxeFoundation/hxcpp/pull/530

**Comment by madrazo** [comment]
Seems that simply changing NDKV12 to NDKV12+ solves the issue

**Comment by madrazo** [comment]
It's not working for me because getNdkVersion in /tools/hxcpp/Setup.hx does not detect my NDK version. It only checks it if the directory name is android-ndk-r* , but it also should check the version in the androidndk/source.propertes file.  

 An alternative is to set the -DNDKV13 flag
