### ISSUE TITLE
bytes.toString() can create string with 0 byte

### ISSUE THREAD

**Issue by ckentgeorge** [HaxeFoundation/hxcpp#534]
On previous releases of Haxe, the following code would not hit the trace statement.  Is this a bug, or should expectations be adjusted?  Should the 0 byte be added to the string, or should the 0 demark where toString stops reading bytes?

```
var buffer = new BytesOutput();
buffer.writeString("Hello");
buffer.writeByte(0);
var bytes:Bytes = leBuffer.getBytes();
if(bytes.toString() != "Hello")
{
   trace("String behavior has changed.");
}
```

**Comment by ncannasse** [comment]
From a pure Haxe specification point of view, both results seems valid

**Comment by hughsando** [comment]
I think the strings should be different, and have different lengths, since haxe does not really have a concept of "null termination".
I did not realize it use to work the other way, so I guess this is a "change management" issue - sorry for the inconvenience.

You can also do this:
```
using cpp.NativeString;
...
if(bytes.toString().compare("Hello")==0)
{
   trace("But still compare to 0.");
}
```
