### ISSUE TITLE
Primitive not found : get_env__1 - in linked library

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/hxcpp#535]
Hello,

I successfully created a very simple static library using **hxcpp**. The resulting artifact is `libserver.a`.
Now I want to build a simple Qt application that links this library. Compilation is successful but at runtime I receive the following error: 
```
Primitive not found : get_env__1
```
A Dynamic object is also thrown: `terminate called after throwing an instance of 'Dynamic' `
This is how the main function is written:
```cpp
int main(int argc, char *argv[])
{
    __hxcpp_lib_main();
    return 0;
}
```
In the .pro file I have:
```
LIBS += -LC:\HaxeToolkit\haxe\lib\hxcpp\3,3,49\lib\Windows -lstd
```
Which should be enough, I think ...

**Comment by ovidiugabriel** [comment]
I already used  `QMAKE_CXXFLAGS += -m32` in my .pro file and `-D HXCPP_M32` in build.xml
So I came to think the problem is somewhere elese.

**Comment by ovidiugabriel** [comment]
Checking on a similar issue: https://github.com/openfl/lime/issues/142 but it is not my case because I am using only hxcpp.

```bash
$ haxelib upgrade
Checking hxcpp
All libraries are up-to-date

$ haxelib list
hxcpp: [3.3.49]
```
That's all I have.

```bash
$ haxelib remove hxcpp
Library hxcpp removed

$ haxelib -notimeout install hxcpp
Downloading hxcpp-3,3,49.zip...
Download complete : 49476374 bytes in 7.3s (6585.3KB/s)
...
Done

```

I am now running the compiler
```
g++ -c -pipe -fno-keep-inline-dllexport -m32 -static -Wl,-z,defs -Wall -Wl,-m32 -g \
    -std=gnu++11 -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG \
    -DQT_CORE_LIB -I..\Server -I. -IC:\Qt\5.7\mingw53_32\include \
    -IC:\Qt\5.7\mingw53_32\include\QtCore -Idebug -IC:\Qt\5.7\mingw53_32\mkspecs\win32-g++ \
    -o debug\main.o ..\Server\main.cpp

g++ -Wl,-subsystem,console -mthreads -o debug\Server.exe debug/main.o \
  -LC:\fcgi-haxe-extern\Server -lServer -LC:\HaxeToolkit\haxe\lib\hxcpp\3,3,49\lib\Windows \
  -static -lstd -LC:\Qt\5.7\mingw53_32\lib C:\Qt\5.7\mingw53_32\lib\libQt5Cored.a 

```
But with the same result: **Primitive not found : get_env__1**

**Comment by ovidiugabriel** [comment]
```bash
$ nm libstd.lib | grep get_env
00000000 t ??__E__reg_get_env@@YAXXZ
00000000 R ??_C@_0L@FECBBIOD@get_env__1?$AA@
00000038 B ?__reg_get_env@@3HA
00000000 t ?get_env@@YAPAU_value@@PAU1@@Z
00000000 r ___reg_get_env$initializer$
```

```
$ nm libstd.a | grep get_env
00000064 B ___reg_get_env
00000d60 t __ZL7get_envP6_value
```

So It is visible that there is no get_env__1 in libstd.a; What is wrong here?

**Comment by ovidiugabriel** [comment]
I solved it by rewriting the core API.
```haxe
@:coreApi 
extern class Sys
```

**Comment by hughsando** [comment]
I think this one was solved by https://github.com/haxenme/nme/commit/6a1d79b372e27801630110978247acc45d785cb8
