### ISSUE TITLE
CFFI Prime compiler error (minimal repro example included)

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/hxcpp#542]
Minimal reproduction case and instructions here:
https://gist.github.com/larsiusprime/7c96637c15111a2b6751df4287c7d9c0

Relevant error message:
```
Error: ./src/Stuff.cpp:83:54: error: ambiguous conversion for functional-style cast from '::cpp::Function<int (int, int)>' to 'hx::Val' (aka 'cpp::Variant')
                if (HX_FIELD_EQ(inName,"CFFI_TraceIII") ) { return hx::Val( CFFI_TraceIII); }
                                                                   ^~~~~~~~~~~~~~~~~~~~~~
/Users/larsdoucet/Development/git/hxcpp/include/cpp/Variant.h:64:14: note: candidate constructor
      inline Variant(bool inValue) : type(typeBool), valBool(inValue) { }
             ^
/Users/larsdoucet/Development/git/hxcpp/include/cpp/Variant.h:293:13: note: candidate constructor
   Variant::Variant(const Dynamic &inRHS) : type(typeObject), valObject(inRHS.mPtr) { }
            ^
```

First discovered it happening to my CI builds of Defender's Quest using [steamwrap](http://github.com/larsiusprime/steamwrap). I had been neglecting my CI for a while so I can't say exactly when it started, but sometime in the last few months for sure. It happens only on Mac and Linux, seems like a recent-ish regression. I was able to isolate the repro case and have tested it on mac, but not yet on linux, though I suspect it will get the same error there as well.

Cannot reproduce on Windows. Suspect it doesn't occur there.

Using latest version of haxe & hxcpp from git.

**Comment by hughsando** [comment]
I will look into it.  On windows I like to reproduce these things using the android gcc compiler.
Meanwhile, you could tag these fields "@:unreflective" to take them out of the get-by-name function.
It is probably not a bad idea to do this habitually, since it is unlikely you will need dynamic versions of these functions and it will make your exe size smaller.

**Comment by larsiusprime** [comment]
Thanks, I'll try that first thing tomorrow!

**Comment by hughsando** [comment]
I had not actually tested the member-variable version of these functions, so your example code was very helpful to work out what was going wrong.
Typically these would be static, unless you are using some kind of singleton pattern.

**Comment by larsiusprime** [comment]
Glad to hear it! Let me verify it's fixed on my end now...

**Comment by larsiusprime** [comment]
Just tried it on my Mac with my example -- compiles fine with no errors! Trying it in production now.
