### ISSUE TITLE
String concatenation crashes if it's used in a specific way?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#543]
This code always crashes on release mode but not on debug mode. Tested on VS2015, x86.

https://github.com/openfl/openfl/blob/549e6dcfed4d036458e75e51dde02e228cdd85ed/openfl/system/Capabilities.hx#L220

Specifically crashed inside memcpy here. inRHS's data was broken somehow.
https://github.com/HaxeFoundation/hxcpp/blob/master/src/String.cpp#L1164

**Comment by hughsando** [comment]
There does not appear to be too much wrong with this.  If I try:
```import haxe.macro.Compiler;
class Test
{
   public static function main()
   {
      var value = "WIN";
      if (Compiler.getDefine ("openfl") != null)
         value += " " + StringTools.replace (Compiler.getDefine ("openfl"), ".", ",") + ",0";
      trace(value);
   }
}
```
with
```haxe -main Test -cpp cpp -D openfl=openfl1.2.3```

It seems to work.  Maybe the value of the define?
But I suspect something else may have gone wrong before you get  to here.
Stepping a compiler though may help identify the issue (or a printf in the string add and array split/join).

**Comment by vroad** [comment]
```
class Main 
{	
	static function main() 
	{
		var value = "WIN";
		value += " " + StringTools.replace ("4.4.1", ".", ",") + ",0";
		
		trace(value);
	}
```
Strangely it only crashes when `StringTools.replace` is called. And first concatenation after replace will crash.

**Comment by vroad** [comment]
Doesn't crash if I assign version to a local variable first. I also inserted a trace call so that it won't get removed by Haxe compiler.

```
class Main 
{
	static function main() 
	{
		var value = "WIN";
		var version = StringTools.replace ("4.4.1", ".", ",");
		trace(version);
		value += " " + version + ",0";
		
		trace(value);
	}
}
```

**Comment by vroad** [comment]
Is something strange generated only on my environment?

without trace
```
void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_4_main)
HXLINE(   5)		HX_VARI( ::String,value) = HX_("WIN",fc,43,42,00);
HXLINE(   8)		value = (HX_("WIN",fc,43,42,00) + ((HX_(" ",20,00,00,00) + ::StringTools_obj::replace(HX_("4.4.1",3d,98,65,0f),HX_(".",2e,00,00,00),HX_(",",2c,00,00,00))) + HX_(",0",84,26,00,00)));
HXLINE(  10)		::haxe::Log_obj::trace(value,hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),10,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            	}
```

with trace:
```
void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_6_main)
HXLINE(   7)		HX_VARI( ::String,value) = HX_("WIN",fc,43,42,00);
HXLINE(   8)		HX_VARI( ::String,version) = ::StringTools_obj::replace(HX_("4.4.1",3d,98,65,0f),HX_(".",2e,00,00,00),HX_(",",2c,00,00,00));
HXLINE(   9)		::haxe::Log_obj::trace(version,hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),9,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
HXLINE(  10)		value = (HX_("WIN",fc,43,42,00) + ((HX_(" ",20,00,00,00) + version) + HX_(",0",84,26,00,00)));
HXLINE(  12)		::haxe::Log_obj::trace(value,hx::SourceInfo(HX_("Main.hx",05,5c,7e,08),12,HX_("Main",59,64,2f,33),HX_("main",39,38,56,48)));
            	}
```

StringTools_obj::replace
```
::String StringTools_obj::replace(::String s,::String sub,::String by){
            	HX_STACKFRAME(&_hx_pos_ae8d48bb73fd7d46_386_replace)
            	HX_STACK_ARG(s,"s")
            	HX_STACK_ARG(sub,"sub")
            	HX_STACK_ARG(by,"by")
HXLINE( 386)		return s.split(sub)->join(by);
            	}
```

**Comment by hughsando** [comment]
Does any of these crash for you?  It might be a version thing, because seems ok for me (just some simple testing).
You can get a more faithful match between haxe and cpp code if you use analyze meta:
```
   @:analyzer(ignore)
   static function main() ...
``` 
Here you will actually get a "AddEq" call.

**Comment by vroad** [comment]
"Without trace" version crashed for me.
Haxe version is 3.4.0. I built 3.4.0-rc1 by myself.
Doesn't crash either if I add that analyze meta.

**Comment by hughsando** [comment]
Ok, I got a crash on one of my other computers.  Will check it out.

**Comment by hughsando** [comment]
This really looks like a microsoft compiler issue to me.
Seems the inRHS is put at the wrong point in the stack when the calls are chained together like this, so the length member slips into the __s member.
The calls were probably never chained together like this before.
I can work around this by changing the signature of operator+ to take a "const String &" rather than just a String.  I will have a  think about whether this is the best solution - probably not bad.

**Comment by hughsando** [comment]
maybe vc2017 will fix it magically.

**Comment by vroad** [comment]
Thanks, issue seems to have gone. Should I close now?

**Comment by hughsando** [comment]
I will close it and see if the compiler fairies get upset.
