### ISSUE TITLE
Thread-safe val_id?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#544]
val_id doesn't seem to be thread-safe as it accesses global variables without locks. Is there any way to do this in a thread-safe manner?

I'm initializing all variable ids in single place to avoid race conditions, but this is not a very convenient way because I need to check every time ids are already initialized.
Is there a way to call initialization function when NDLL is loaded?

I'm not sure how this is handled on neko. Is val_id on neko thread-safe or not?

https://github.com/HaxeFoundation/hxcpp/blob/5d3f85072516e7a86968ae1c3b133981cf5b3811/src/hx/CFFI.cpp#L698
https://github.com/HaxeFoundation/hxcpp/blob/614069ffa0e2b60b54c64fbb20e2b04364ecad23/src/hx/StdLibs.cpp#L713
https://github.com/HaxeFoundation/hxcpp/blob/614069ffa0e2b60b54c64fbb20e2b04364ecad23/src/hx/StdLibs.cpp#L695-L699

Currently lime is checking if id is initialized with global bool variable in this way, but that may cause race conditions for another reason. If you call this from multiple threads on processor does out-of-order execution, init flag may get written first, and NDLL may pass uninitialized id to CFFI functions because it seems initialized. Couldn't that happen?

https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/graphics/ImageBuffer.cpp#L35

**Comment by hughsando** [comment]
You can use the 'entry point', like:
https://github.com/haxenme/nme/blob/master/project/src/common/ExternalInterface.cpp#L256

Or you could use a static c++ object, which will get initialized shortly
after the dll is loaded.

But it would make sense to make this routine thread-safe too.

**Comment by vroad** [comment]
Thanks, I will use entry point instead for initialization.

Can reading be made thread-safe as well?
Also, I cannot assume this thread-safe if val_id (and other related CFFI calls?) is not thread-safe on neko.
