### ISSUE TITLE
[cpp]EReg.matchSub and beginning anchor (^)

### ISSUE THREAD

**Issue by romamik** [HaxeFoundation/hxcpp#546]
```haxe
class Test {
    static function main() {
		trace((~/^abc/).match('abc'));
		trace((~/^abc/).matchSub('   abc', 3));
    }
}
```
This should output 
```
true 
true 
```
And it does at least on js and flash targets. But on cpp target it outputs
```
true
false
```

**Comment by thomasuster** [comment]
Would make a great test in ```https://github.com/HaxeFoundation/hxcpp/tree/master/test/haxe```

**Comment by Simn** [comment]
I came across this as well. Interestingly it seems to fail using PCRE with a position offset as well. Can't properly investigate right now because http://pcre.org/ is down.

**Comment by Simn** [comment]
Just double-checked with pcretest:

```
PCRE version 8.33 2013-05-28

  re> /^abc/
data> \>3   abc
No match
```

According to http://stackoverflow.com/questions/14006885/fast-way-to-match-anchored-regex-in-the-middle-of-the-string there's a `\G` anchor for this, which indeed works with PCRE:

```
  re> /\Gabc/
data> \>3   abc
 0: abc
```

If we want to specify that matchSub is equivalent to match(substr), this is going to require some work...

**Comment by hughsando** [comment]
We pass the length and offset to pcre_exec, but we could consume the offset
ourselves and prevent pcre from knowing its there.
In this case, what should the matchedPos be ? 0 or 3 - same for
matched(0)?  If we are saying its the same as match(substr), then I guess
the spec is easy.

**Comment by Simn** [comment]
I suppose it should be 0 in that case. That is going to cause other problems though, because [EReg stores the full string](https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/_std/EReg.hx#L70) and then [uses the match positions to index into it](https://github.com/HaxeFoundation/haxe/blob/development/std/cpp/_std/EReg.hx#L54). At the very least we would have to offset this.

**Comment by hughsando** [comment]
The wrapping is pretty simple in the hxcpp code, so should all be easy enough.

**Comment by ibilon** [comment]
I guess that doing a full haxe implementation of ereg isn't a realistic option? Would be crossplatform.
