### ISSUE TITLE
[Feature request] Support for selective debug symbols?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#547]
I think (for performance reasons) it may be valuable to be able to do builds that are compiled for release on certain class paths (such as a third-party library) while continuing to build for debug on the application code.

What do you think we would need in the HXCPP build tool in order to support this feature?

**Comment by hughsando** [comment]
This can be managed with 'tags', which can be on files or file groups and control which compiler flags get used with which files.

Here you can see the tags set to empty:
https://github.com/native-toolkit/sdl/blob/master/files.xml#L88

And then overridden according to the variable
https://github.com/native-toolkit/sdl/blob/master/files.xml#L91

So you can do a haxe debug build but with release toolkit like:
nme cpp -toolkit -debug -DNATIVE_TOOLKIT_OPTIM_TAG=release
If you do not give any tags, it will assume the the default one from the build (-debug in this case)

You  can see the compiler flags associated with the tags in the hxcpp output - the tag is printed in brackets by the hxcpp compiler.

So you might be able to achieve what you are trying to do with  -DNATIVE_TOOLKIT_OPTIM_TAG=release in your build scripts.

**Comment by jgranick** [comment]
If I edit the generated "Build.xml" that is provided from Haxe, then I might be able to accomplish this by doing two file sets (instead of one "haxe" set) and tagging one with release?

I just learned about @:noDebug, do you think that this should tag the file to be compiled for release, or would that at least improve the performance?

The issue is that we have files (such as aspects of our Haxe-based GL renderer) that run so slowly in debug, it makes testing difficult. Release builds run fast, but then there's no stack for application-level code. We need to tag Haxe-based files somehow (like doing NME in release and doing the application as debug). If this could be done using @:noDebug or a similar meta-data, then applying that to all the right files is solvable problem :smile:

Thanks

**Comment by hughsando** [comment]
I should have mentioned that you can also set per-file tags via meta, but I have not extensively tested this:
```
@:noDebug @:fileXml(' tags="haxe,release" ')
class OptimizedClass {...
```
This will put release on for the whole file (class).  Note, you can also use this in reverse, with the 'optim-std' tag to remove the -O2 flag in files that take a long time to compile (lots of 'if' statements), but do not really need optimizations.
So  you can choose "-O2" flags, but with full call-stack etc. with 'release' and no noDebug.
You can also just turn on the call-stack in release mode (except for noDebug routines) with some of the defines in http://gamehaxe.com/2012/09/14/hxcpp-built-in-debugging/ which may offer a better compromise.
I have a few ideas for making the call-stack stuff less expensive, which will make it more likely just to always put it on.

**Comment by jgranick** [comment]
Thank you! This is very helpful :smile:

Do you think `@:noDebug` should imply the "release" tag?

Do you think that `@:noDebug` or `@:fileXml` could work on abstract classes, so we can tag the "_Impl" files as well, or is that unnecessary?

**Comment by hughsando** [comment]
@:noDebug can be done per-routine, whereas release can not - it must be
applied to the whole file.  There is probably no a lot of use-cases where
you would want noDebug, but release - but maybe if you want to do native
debugging.  I am tempted to keep them separate, but maybe look at ways to
make it easier to apply both together.
I was trying to get meta into the "import.hx" file so that it can be
applied to all files in a directory.  Do you think this would help? We
could try bringing this up again.
As far as abstract impl is concerned, hxcpp just sees these a normal
classes because haxe generates them from the abstract.  There might be an
issue where the abstract-meta in not transferred to the implementation
class - this could be addressed.

**Comment by hughsando** [comment]
It seems the meta works on the _Impl abstract classes, so I'm closing this one now.  Maybe start a new issue if you want to discuss this more.
