### ISSUE TITLE
Enabling --gc-sections, -fno-rtti, -fno-exceptions with -O2 optimization for Android build?

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#548]
When I checked last time, it was not possible to enable --gc-sections without changing optimization to `-Os`.
I read that this still enables optimizations that doesn't typically increase code side, but I wonder if that turns off important optimizations.
Can you add something like `HXCPP_GC_SECTIONS`, which doesn't change optimization flags?

https://github.com/HaxeFoundation/hxcpp/pull/334

Is it safe to turn off RTTI and Exception support when I build NDLLs? I'd like to turn this off because supporting those features slightly increases binary size.
I think I've read somewhere that those flags are required for hxcpp runtime, but is this the same for NDLLs?

**Comment by madrazo** [comment]
Hi. Please help me to try -flto to reduce the APK size (and increase performance?), as here https://github.com/HaxeFoundation/hxcpp/issues/541

Also, I see that "-Wl,--strip-all" is missing (similar to "-Wl,--gc-sections") which furthers decrease my test APK size on 1.5 Mb. 

Thanks

**Comment by madrazo** [comment]
I think that compilation with "-fdata-sections" is needed if you want to use  "-Wl,--gc-sections" without Os

**Comment by hughsando** [comment]
I have added Carlos's change for the gc-sections.  See if this works for
you.
I think it should be safe to turn off rtti for ndlls if you know what you
are doing.  Nme uses dynamic_cast on some of its structures, so I guess it
depends what the ndlls are doing.  c-based ndlls will not be using rtti or
exceptions, so there should be no change there.
I'm not sure about exceptions - for example if the ndll had a c++ object
that had a destructor and you called a hxcpp function that threw an
exception, would the destructor get called?  You would need to test this,
or be sure that non of the hxcpp functions you called threw an exception.
