### ISSUE TITLE
3.4.x cpp.Callable<Void->Void> different?

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#549]
Haxe `3.4.0 (git build development @ 57948c9)`
hxcpp git `b2a1efc46e8dee75e630195646cc11da4964143c`

In previous code I had a function in [this library](https://github.com/snowkit/linc_sdl):

```haxe
@:native('linc::sdl::init_ios_callback')
private static function init_ios_callback(window:Window, interval:Int, func: cpp.Callable<Void->Void>):Void;
```

On the native side:
```c++
typedef ::cpp::Function < Void() > InternaliOSCallbackFN;
extern void init_ios_callback( SDL_Window* window, int interval, InternaliOSCallbackFN fn );
```

In 3.2.1 and prior this was working as intended. 
In 3.4

```
Error: ./src/sdl/_SDL/SDL_helper.cpp:130:61: error: no viable conversion from 'Function<void ()>' to 'Function<Void ()>'
HXLINE(1340)                    linc::sdl::init_ios_callback(window,interval,::cpp::Function< void ()>(hx::AnyCast(&::sdl::_SDL::SDL_helper_obj::iOS_callback_handler )));
```

Note the type is now `void` c type and not `Void` hxcpp type.
I think this isn't the first time this void/Void issue has come up for me since 3.2. 

Can we get a consistent type here because without it I have to have `#ifdef` in the c++ side try and guess the haxe version safely to support 3.2.1 :/

**Comment by hughsando** [comment]
Yes,  captital-V void is gone for good now.  Long-term, this should make things simpler.
Unfortunately, I neglected to bump the api level at exactly the same time I changed the generated code.
I think I need change null.h to: 
```
#if (HXCPP_API_LEVEL>=330)
typedef void Void;
#else
typedef null Void;
#endif
```
But this change now needs a fix I just put into haxe - so I might need to bump the api level again to fix this.

But you should be able to do this I think:
```
#if (HXCPP_API_LEVEL>=330)
typedef void LincVoid;
#else
typedef null LincVoid;
#endif
```
And then use LincVoid in your function typedef.

Also note that the "Int" and "Bool" typedefs are gone, so you should use the plain "int" and "bool" in your native code.  This change is backwards compatible, so not as big a drama.

**Comment by underscorediscovery** [comment]
thanks @hughsando I think it works for now. One thing I wonder if removing these though, what happens to something like [this](https://github.com/snowkit/linc_enet/blob/master/enet/ENet.hx#L33) - where `cpp.Pointer<Void>` is used (maybe even incorrectly? ignoring the duplicated code inside the `#if`). Will that matter I wonder?

**Comment by hughsando** [comment]
That should be fine, since it is in haxe code, and the haxe compiler can translate it to little-v void.
If you used @:native("Void...") it would be an issue, since the haxe compiler does not parse this type.
