### ISSUE TITLE
mega threads = GC race ?

### ISSUE THREAD

**Issue by dfadev** [HaxeFoundation/hxcpp#550]
```
class Main {
	static function main() {
		for (i in 0...200) {
			trace('creating thread#$i');
			cpp.vm.Thread.create(proc);
		}
		proc();
	}

	static function proc() {
		while (true) {
			var a = new Array<Int>();
			for (i in 0...100000) a.push(i);
		}
	}
}
```

The above code fails to create all 200 threads on my machine.  No core dump, no error message, just a silent hang with no cpu usage.  If I reduce the number of threads being created by half, it will finish creating them but CPU usage eventually goes to zero when it should not.  If I keep thread count low, say 10 or less, CPU stays pegged.

200 threads is not real world design, the high thread count and many local allocations is meant to increase the probability of triggering a race condition.  I also encounter this issue when using a more reasonable 32 threads, but it can take a while to happen.

This occurs using latest git versions of haxe and hxcpp on Ubuntu 16.10.

**Comment by hughsando** [comment]
So I found one issue with this, and it seems to run better now. See if this works for you.

**Comment by dfadev** [comment]
Works now.  Thanks!
