### ISSUE TITLE
Add support for `long` in CFFIPrime bindings

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#553]
Do you think we could support `long` in CFFI Prime bindings? Is it just a matter of adding `long` to the `AutoValue` type, or would there be problems with that?

**Comment by hughsando** [comment]
It should be ok to add to AutoValue.
However, on all systems supported by hxcpp, long=int as far as processing goes, but you can run into problems with function signatures if you do not explicitly cast.
So, if its your own code, you can take an "int" and pass it to a function that takes a "long" with a simple cast - unless it is some 16-bit console I'm not aware of.  It could be an issue if you are trying to take the address of a system function that uses long.

**Comment by jgranick** [comment]
Ah, so you can use `long` on the C++ side, and type it as "i" with CFFI prime? It does not assume it will be an `int`? Perhaps I misunderstood the API, that's helpful :smile:

**Comment by jgranick** [comment]
Nevermind, I misunderstood for a moment.

I tried adding `long` to `AutoValue`, but I'm getting bad numbers 😕

**Comment by jgranick** [comment]
Thanks

I have gotten it to work initially, please feel free to revise if there's a nicer way to do this. This should help with avoiding boxing when you need 32-bit integers :smile:
