### ISSUE TITLE
Single support

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#555]
I just noticed that hxcpp does not seem to support "Single" type:
http://api.haxe.org/v/dev/Single.html
It is nice when you want to write cross platform system apps.

**Comment by nadako** [comment]
There's `cpp.Float32`, but not sure if it has the same behaviour as `Single`.

**Comment by hughsando** [comment]
Yes, its the same thing.

**Comment by ncannasse** [comment]
Yes, it's just a matter of allowing a standardized name on platforms that
supports it

**Comment by Simn** [comment]
Float32 is so much more descriptive than Single... plus it's immune to dating site jokes.

**Comment by ncannasse** [comment]
Yes but Single have been there (alone) for years.
