### ISSUE TITLE
update related "bad cache name" errors

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#558]
When updating between git -> 3.4.43 -> git -> 3.4.49, upon every update or change to hxcpp version the following error happens:

```
Error: Error cleaning cache: bad cache name "1b2bd622bfb875a95db45b78a8c05e" found - aborting
```

The name obviously changes, but **this prevents any building from happening at all.**
I tried `haxelib run hxcpp cache clear` but the same error is triggered.

The only solution appears to be deleting all the files manually, which is far from ideal.
Am I missing anything? Can we make it resilient so that users aren't stonewalled completely?

**Comment by hughsando** [comment]
I have not seen this - at least for a while.
I'm wondering if some very old hxcpp code generated a funky file.  If you completely delete the cache, does that solve the problem for ever, or does it come back once it gets full again.
Any hints on where this file is, or is it just a normal .obj file?
I can look at not aborting in this case too.
What os are you using?

**Comment by underscorediscovery** [comment]
I usually have to run `rm -rf ~/.hxcpp_cache/*` to remove all files in order to build, so I doubt the file is hanging around. The problem comes back when updating.
The file seems to be a normal obj file, and I am testing on mac.
If I can get it to happen I'll try get more info. 

To me it seems that if it doesn't like the cache file for whatever reason, it should just invalidate/delete it and continue. Halting seems like telling the user about an internal state they don't care about. It seems reasonable to me that a hxcpp update might invalidate the cache naming or structure and I wouldn't be surprised on updating to have some rebuilds... as long as it can build that is.

**Comment by Gama11** [comment]
I have run into this issue at least two times as well. I think both times it happened I switched from Haxe 3.2.1 to latest.

**Comment by hughsando** [comment]
I'm going to close this one.  Please report again if you are still getting errors.
