### ISSUE TITLE
Enable C++11 on Mac

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/hxcpp#560]
Related to https://github.com/HaxeFoundation/hxcpp/issues/457

It would fix the following warning, but min target is macOS 10.9

> clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9

**Comment by ibilon** [comment]
You can change it that by adding:
```
@:buildXml('<target id="haxe" tool="linker" toolid="exe">
  <compilerflag value="-std=c++11" />
  <compilerflag value="-stdlib=libc++" />
  <lib name="-lc++" />
</target>
<files id="haxe">
  <compilerflag value="-mmacosx-version-min=10.9" />
  <compilerflag value="-std=c++11" />
</files>')
```
to your main class for instance.

**Comment by madrazo** [comment]
Thanks. I'm thinking on adding the HXCPP_CPP11 flag as in the iphone toolchain. Seems that `<lib name="-lc++" />` is not required for 10.9 target since it is the default lib.
