### ISSUE TITLE
Socket.cpp:361:56: error: 'inet_pton' was not declared in this scope

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hxcpp#569]
When compiling the [haxe-doctest](https://github.com/vegardit/haxe-doctest/) project to C++ using Haxe 3.4 and hxcpp 3,4,49 and GCC 5.1 or 6.1 I am getting the following exception:

```
 - Socket.cpp
Error: C:/apps/dev/haxe/haxe-3.4.0/lib/hxcpp/3,4,49/src/hx/libs/std/Socket.cpp: In function 'Array<unsigned char> _hx_std_host_resolve_ipv6(String, bool)':
C:/apps/dev/haxe/haxe-3.4.0/lib/hxcpp/3,4,49/src/hx/libs/std/Socket.cpp:361:56: error: 'inet_pton' was not declared in this scope
    int ok = inet_pton(AF_INET6, host.__s, (void *)&ipv6);
                                                        ^
C:/apps/dev/haxe/haxe-3.4.0/lib/hxcpp/3,4,49/src/hx/libs/std/Socket.cpp: In function 'String _hx_std_host_to_string_ipv6(Array<unsigned char>)':
C:/apps/dev/haxe/haxe-3.4.0/lib/hxcpp/3,4,49/src/hx/libs/std/Socket.cpp:427:55: error: 'inet_ntop' was not declared in this scope
    return String( inet_ntop(AF_INET6, &ip[0], buf, 100) );
                                                       ^
Error: Build failed
```

any ideas?

**Comment by sebthom** [comment]
Same with GCC6.3

**Comment by hughsando** [comment]
That's pretty odd.  Its is supposed to be in <arpa/inet.h> or  <netdb.h>
I wonder if there is some "enable ipv6" flag that is missing somewhere, or if one of the other net files is using a pre-processor to prevent the header being included.
I assume this is for linux - anything odd about the compiler setup?
I've seen gcc4 (android) and clang more so that gcc5/6 I guess.

**Comment by sebthom** [comment]
I am using Windows 10 and tried these GCC distributions:
GCC 5.1: https://sourceforge.net/projects/tdm-gcc/files/TDM-GCC%20Installer/
GCC 6.1: https://sourceforge.net/projects/mingw-w64/files/Multilib%20Toolchains%28Targetting%20Win32%20and%20Win64%29/ray_linn/gcc-6.X-with-ada/
GCC 6.3: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/6.3.0/threads-posix/seh/

GCC compilation used to work with earlier HXCPP versions on Windows. Last time I tried was Haxe 3.2.1 with GCC 5.1 and HXCPP 3,3,49 as far as I remember.

**Comment by sebthom** [comment]
Maybe related? http://stackoverflow.com/questions/15370033/how-to-use-inet-pton-with-the-mingw-compiler

**Comment by hughsando** [comment]
Ok gcc on windows.
I put in a compile fix for the mingw I have on my system (based on gcc 4.x I think), but have not really tested it (it compiles + links though)
See how this works for you.

**Comment by sebthom** [comment]
Works. thanks!
