### ISSUE TITLE
Strange for loop bug

### ISSUE THREAD

**Issue by musanek** [HaxeFoundation/hxcpp#57]
After upgrading to hxcpp 3.1.30, I run into weird issue using hxtea library. 
Here is the test code : https://gist.github.com/musanek/11333726

I did track it down to the following loop 

       for (i in 0...32)
        {
            v1 -= ((v0<<4) + k2) ^ (v0 + sum) ^ ((v0>>5) + k3);
            v0 -= ((v1<<4) + k0) ^ (v1 + sum) ^ ((v1>>5) + k1);
            sum -= delta;
        }
in
        static public function decrypt(v:Array<Int>, k:Array<Int>):Array<Int>

This loop translated to while in cpp goes forever. If I add trace as first statement in the loop it works. No problem on neko and swf.

gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

**Comment by thomasuster** [comment]
Tried on hxcpp master 7b0fd680d79f82e52130f59158aa99a4d0c18042, and hxtea: [1.2.0] / OSX. Seems to work.

thomasuster$ out/Test 
Test.hx:8: =wP=1LjZKcE
Test.hx:10: test

**Comment by thomasuster** [comment]
@musanek Are you still running into this issue?

**Comment by hughsando** [comment]
I'm going to close this one - feel free to reopen it if the problem still occurs.
