### ISSUE TITLE
HXCPP_CHECK_POINTER doesn't seem to work anymore

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hxcpp#571]
Even with "-D HXCPP_CHECK_POINTER" specified the current hxcpp release on Haxe 3.4 does not throw exceptions when invoking methods on null objects.

The following code prints `should never be reached` but should not.
```haxe
class Test {
   public static function main() {      
        try {
            var s = ""; 
            s = null;
            trace(s.length); // should throw NPE
            trace("should never be reached");
            Sys.exit(1);
        } catch (e:Dynamic) {
            // expected
        }
   }
}
```

**Comment by hughsando** [comment]
This is actually the designed behaviour.  Strings are a funny kind of "object" - although they can be null, you can still access the length in hxcpp.  If you use an object, you will get the desired behaviour: 
```haxe
class Test {
   static function createTest(): Test return null;
   public var length:Int;
   public static function main() {      
        try {
            var s = createTest();
            trace(s.length); // should throw NPE
            trace("should never be reached");
            Sys.exit(1);
        } catch (e:Dynamic) {
            // expected
        }
   }
}
```

**Comment by sebthom** [comment]
Interesting. Is that the desired behavior in Haxe as a language or on the CPP target? the NPE seems to be raised on all other targets and as far as I remember was also raised on CPP with Haxe 3.2.1.
