### ISSUE TITLE
Windows XP compatability issues.

### ISSUE THREAD

**Issue by Yanrishatum** [HaxeFoundation/hxcpp#574]
Currently HXCPP application crashes on Windows XP due to usage of functions that are not present in Window XP. Both app and libraries (std/zlib/etc) are built with `-DHXCPP_WINXP_COMPAT` flag.  
Identified at least two of them: `inet_pton` and `iten_ntop` in `winsocks2.h` / `WS2_32.dll`.
Additionally dll files that are bundled in Haxelib release is clearly broken for WinXP (`false` for `FileSystem.exists(Sys.getCwd())` is clearly something out of nightmares.)

**Comment by hughsando** [comment]
I have loaded these functions dynamically - hopefully should make this link for you.
Not sure about the other issues.  Hxcpp should no longer be using dlls - the Sys.getCwd should be coming from src/hx/libs/std/Sys.cpp now.  So that might be a place to start.

**Comment by Yanrishatum** [comment]
It seems that problem with MSVC runtime package. `stat` functions returns -1, which is apparently know issue. So far problem not with HXCPP directly on that problem.

**Comment by Yanrishatum** [comment]
Closing issue, as `inet_*` was fixed, and other issues were not directly HXCPP-related, and required updating Windows Kit.  Thanks.
