### ISSUE TITLE
Calling functions through Dynamic doesn't do anything

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/hxcpp#575]
This doesn't work, because when wrapped in Dynamic, the Function is stored in PointerData, which doesn't override the default `__Run` method, so it effectively does nothing.
```haxe
class Main {
    static function test() {
        return 1;
    }

    static function getFnDynamic():Dynamic {
        return cpp.Function.fromStaticFunction(test);
    }

    static function main() {
        var fn = getFnDynamic();
        if (fn() != 1)
            throw "oh no";
    }
}
```

This might be an issue @larsiusprime is currently fighting with.

**Comment by nadako** [comment]
Wrapping in Dynamic lime/openfl in the first place is caused by https://github.com/HaxeFoundation/haxe/issues/6074.

**Comment by hughsando** [comment]
Pointers wrapped in Dynamic are not designed to be callable Dynamically.
They must be unwrapped explicitly before calling, like:
```haxe
    static function main() {
        var fn:cpp.Callable<Void->Int> = getFnDynamic();
        if (fn() != 1)
            throw "oh no";
    }
```
The problem with the referring issue is that the Dynamic was created in the first place, not that it is not callable once it is created.
