### ISSUE TITLE
Cppia crash when calling interface functions

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/hxcpp#576]
For the purpose of this test case, everything here is located in "D:/haxe" on my computer.

Test.hx
``` haxe
import test.Script;

@:build(cpp.cppia.HostClasses.include())
class Test
{
	public static function main()
	{
		var source = sys.io.File.getContent("D:\\haxe\\MyScript.cppia");
		untyped __global__.__scriptable_load_cppia(source);
	}

	public static function runTest():Void
	{
		var myScriptClass = Type.resolveClass("MyScript");
		
		var myScript:Script = Type.createInstance(myScriptClass, []);
		myScript.doSomething();
	}
}
```

test/Script.hx
``` haxe
package test;

interface Script
{
	function doSomething():Void;
}
```

MyScript.hx
``` haxe
#if cppia
import test.Script;

class MyScript implements Script
{
	public static function main():Void
	{
		Test.runTest();
	}
	
	public function doSomething():Void
	{
		trace("MyScript.doSomething");
	}
}
#end
```

Compile host
`haxe -main Test.hx -cpp host -D scriptable -D dce=no -D dll_export=D:/haxe/export/export_classes.info`

Compile script
`haxe -main MyScript.hx --macro cpp.cppia.HostClasses.exclude() -D dce=no -D cppia -cpp MyScript.cppia -cp export`

The end result is a crash. However, it works when the interface is defined at the top level (e.g. `Script` instead of `test.Script`). It seems like it's due to the pre-computed interface name hashes using different delimiters (`::` in the host, `.` in the script).

**Comment by hughsando** [comment]
Nice explanation - I will look into it.

**Comment by justin-espedal** [comment]
Oh yeah, I've fixed this one in my own copy. As I said in my other issue though, not sure what else this might affect, but it seems to work okay for me.

[Fix interface hashing](https://github.com/Stencyl/hxcpp/commit/51b36e5e78bf6a84a8d206f3fcce4e38f17a3d2e)
