### ISSUE TITLE
Curious warning in null.h (3.4.64)

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#582]
Not yet sure what triggered the specific warning (first time seeing it on this version) but the warning looks like a valid concern.

```
Users/sven/dev/haxelib/hxcpp/3,4,64/include/null.h:132:61: warning: binding dereferenced null pointer to reference has undefined behavior [-Wnull-dereference]
        { hx::NullReference("Function Call", false); return *(Dynamic *)0; }
```

**Comment by hughsando** [comment]
Closed by https://github.com/HaxeFoundation/hxcpp/commit/e3bae04367c3abef166ad316de99b9c5feeaee02
