### ISSUE TITLE
Obscure error with inlined empty function

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/hxcpp#59]
[Error](http://pastebin.com/yr7jrBAa).

This happened in flixel without the [this fix](https://github.com/HaxeFlixel/flixel/commit/b3ebcf93925bb83b4c92591cdd7ed4ff26a92fad) when compiling with `FLX_NO_DEBUG`. Removing the `inline` from `add()` in that same class also seems to fix it.

**Comment by hughsando** [comment]
This case I think is where the null value gets inlined.  Some cases of this have been fixed, and the more general issues are in:
https://github.com/HaxeFoundation/haxe/issues/4072
I'm going to close this - if the problem does not look like this, and is not fixed, you can reopen the issue.
