### ISSUE TITLE
val_callN on mac. bad access error

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hxcpp#592]
I did experiment. Made hx function with few array arguments. This function has empty body. I call this function from cpp code frequently (60fps) passing few arrays (thousands rows) 
val_callN crash at random moment in time with bad error access on mac. other platforms work well so far. When I significantly reduce number of elements in array, val_callN work stable. Not sure what can be different on mac os.

**Comment by codeservice** [comment]
Checked test app for neko target on mac. Stable here. 
Issue only when I run it for cpp target. Problem some where in hxcpp.

**Comment by hughsando** [comment]
How are you storing the values that you are passing in the value* param?
A local variable or a heap variable?  I can see there might be GC issues if they are not on the stack.

**Comment by codeservice** [comment]
I think it could be it! Function args local variable not in stack

I am using it like:
*value *args* = new value[num_args];
for (int i = 0; i < num_args; ++i) {
   args[i] = get_random_array_value_for_function(i);//returns float array
}
value result = val_callN(value_function, args, num_args);
delete [] args;

array I am creating like:
value v = alloc_array(elemens_count);
val_array_set_i(v, i, random_float_value);//in cycle for i


*value *args* declared as local variable inside method.
How this global stack needs to be declared? Where can I look for example?
Is it just some kind of global static std::map<int, value> map?

**Comment by codeservice** [comment]
Now I see by local variables you mean not allocated by NEW, which is not my
case.

Maybe issue here, array not allocated by new in hxcpp:
hx::Object * alloc_array(int arg1)
{
   Array<Dynamic> array(arg1,arg1);
   return array.GetPtr();
}

**Comment by codeservice** [comment]
One more interesting moment. neko for allocation arrays using
GC_MALLOC_IGNORE_OFF_PAGE:
#define* gc_alloc_big*(n) (((n) > 256) ? GC_MALLOC_IGNORE_OFF_PAGE(n) :
GC_MALLOC(n))
and it works for me on mac with large arrays,

EXTERN value alloc_array( unsigned int n ) {
value v;
if( n == 0 )
return (value)(void*)&empty_array;
if( n > max_array_size )
failure("max_array_size reached");
v = (value)*gc_alloc_big*(sizeof(varray)+(n - 1)*sizeof(value));
if( v == NULL ) failure("out of memory");
v->t = VAL_ARRAY | (n << TAG_BITS);
return v;
}


I dont see the same on HXCPP, maybe that is the reason why array can be GC
from memory?

**Comment by hughsando** [comment]
Neko uses different gc scanning, and will probably work not matter what you do.

So the correct way would be if you knew the number of args in advance (or max number of args) would be to use stack mem:
```cpp
   value myArgs[MY_MAX_ARG_COUNT];
   for(int i=0;i<MY_ARGC_COUNT;i++)
       myArgs[i] = ....;
   val_callN(func, myArgs, MY_ARG_COUNT);
```

For an unknown number, you should be able allocate the args like you allocate your float array, ie:
```cpp
value myArgs = alloc_array(arg_count);
val_array_set_i(myArgs, i, arg[i]); //loop
```
Then the the "value *" from "val_array_value(myArgs)"
```cpp
   val_callN(func, val_array_value(myArgs), MY_ARG_COUNT);
```

This is the theory - I have not checked it works.

**Comment by codeservice** [comment]
It works rock solid on mac if I declare function arguments as: "value
args[num_args];" without "new".
I didnt check other platforms yet but issue was on mac only, so I am
closing this. Thank you!, now I know that values array declared with "new"
can be GC from memory on mac. Why its not happening on other platforms
still mystery to me.

**Comment by hughsando** [comment]
I think it is probably the luck of the conservative GC and where registers
fall on the stack.
You could probably reproduce elsewhere  by forcing a collect half way
through filling your argument list.

**Comment by codeservice** [comment]
I run this old test on ios for 10-15 min on ipad, never crash. windows the
same. Didnt force gc collect, theoretically for that long time must be
triggered automatically.
Also interesting "value args[num_args];" I can't compile this line on
windows
error:

error C2057: expected constant expression
error C2466: cannot allocate an array of constant size 0
error C2133: 'args' : unknown size

So for now, doing this only on mac:
#if defined(HX_MACOS)
value args[num_args];
...
#else
value *args = new value[num_args];
...
#endif

Maybe I need to try alloc_array for universal cross platform solution

**Comment by codeservice** [comment]
Ha, did test on windows with alloc_array. Compiled but crash, I think here:
val_array_value(args)

**Comment by hughsando** [comment]
Can you use "MAX_ARGS" as a smallish constant (less than 100 say), and only pass the first N?
Or could max-args be anything?  In this case, probably better to pass an array anyhow.

**Comment by codeservice** [comment]
Yes, now I can compile this on windows! Completely forget you mentioned
this max constant option before. Mac doesn't require fixed number for this.
Thanks!

const int MAX_ARGS = 99;
value args[MAX_ARGS];

**Comment by codeservice** [comment]
Best practice maybe make even different calls depending on how many
parameters, in this case no need to create args array every time.
I saw code close to this all over hxcpp and neko:
   if(num_args == 0)
       result = val_call0(val_fn);
   else if(num_args == 1)
       result = val_call1(val_fn, arg[0]);
   else if(num_args == 2)
       result = val_call2(val_fn, arg[0], arg[1]);
   else if(num_args == 3)
       result = val_call3(val_fn, arg[0], arg[1], arg[2]);
   else {
       value args[30];//hxcpp limit 25 parameters?
...

**Comment by hughsando** [comment]
There are quite a few limits here and there to the number of args and the
number of capture variables.
Not great, but seems to work in practice.
