### ISSUE TITLE
Lookup in Map is slower than Update 

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#596]
While doing some Map benchmarks and comparing HxCPP and HL I noticed the Map.set is 3 times faster than Map.get (using MSVC + latest Haxe)

You might want to look into it, here's the benchmark:

```haxe

class Main  {
	
	static function main() {
		var a = [for( i in 0...10000 ) null];
		var str = "Hello";
		
		var t = haxe.Timer.stamp();
		for( i in 0...10000 ) {
			var m = new Map();
			for( i in 0...100 )
				m.set(i,str);
			a[i] = m;
		}
		trace("INSERT", haxe.Timer.stamp() - t);

		var t = haxe.Timer.stamp();
		var tot = 0;
		var m = a[0];
		for( i in 0...100000 ) {
			for( i in 0...100 )
				tot += m.get((i*31)%100).length;
		}
		trace("LOOKUP", haxe.Timer.stamp() - t);

		var t = haxe.Timer.stamp();
		var tot = 0;
		var m = a[0];
		for( i in 0...100000 ) {
			for( i in 0...100 )
				m.set((i*31)%100, str);
		}
		trace("UPDATE", haxe.Timer.stamp() - t);

	}

}
```

**Comment by Simn** [comment]
You might want to check your zeroes there...

**Comment by ncannasse** [comment]
It's correct, I'm comparing LOOKUP/UPDATE, not INSERT/LOOKUP

**Comment by Simn** [comment]
Ah, now I get it. Alright then, carry on.

**Comment by hughsando** [comment]
The `get(key):Null<X>`  is pretty annoying.  Now I can change functions
based on expected return type in the cpp backend,  I might be able to do
something better about this.

**Comment by ncannasse** [comment]
@hughsando please not that in this case, it's `Null<String>` so this should be the same as `String` for hxcpp I guess

**Comment by hughsando** [comment]
The get function was still boxing the result, since I used the same map implementation for all value types.  I have now specialized the get routine, so the performance is about what you would expect.
