### ISSUE TITLE
[emscripten] Crash when using --js-library

### ISSUE THREAD

**Issue by gogoprog** [HaxeFoundation/hxcpp#599]
Hello,

I've tried to use the `--js-library` linker flag for emscripten but it always leads to a crash.

`Internal compiler error in src/compiler.js! Please raise a bug report at https://github.com/kripken/emscripten/issues/ with a log of the build and the input files used to run. Exception message: "Unclear preprocessor command: #nq�|�ǥ�A���&)^z�]�@�pN3��iG2���'~����;AR��/8�4E�0y�-L�܊'~����;A�Y��s���\Dm�`�nZ���_���DP��O �!��?��Y��/\ Um��/!����O�C�HS8�t�|�p{��$5��_M@���F��?��\�^:��	��\D��Z��wX0�����'i��	!L5�� 1q
                 I^eO�3
                       �AL�HF���I�ǥ�AS����<@Dx)�ҿ)��?��q�h��D5�J��
_p�|��q�h��T���E�P��U��������;A�KS�4��wX0�`" | undefined����!�a)�?��q�h��T��ς��-�$y�:���Ͱ^�%����'~����;AR��;"x+��S�4ƺwX0�p��U�i�<D4a� �d:�G�,��/LN$�����a
Traceback (most recent call last):
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emcc.py", line 2220, in <module>
    run()
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emcc.py", line 1558, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/tools/shared.py", line 1737, in emscripten
    call_emscripten(cmdline)
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emscripten.py", line 1775, in _main
    temp_files.run_and_clean(lambda: main(
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/tools/tempfiles.py", line 78, in run_and_clean
    return func()
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emscripten.py", line 1780, in <lambda>
    DEBUG=DEBUG,
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emscripten.py", line 1681, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emscripten.py", line 93, in emscript
    glue, forwarded_data = compiler_glue(metadata, settings, libraries, compiler_engine, temp_files, DEBUG)
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/emscripten.py", line 293, in compiler_glue
    cwd=path_from_root('src'), error_limit=300)
  File "/home/gogoprog/code/emsdk_portable/emscripten/incoming/tools/jsrun.py", line 122, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/home/gogoprog/code/emsdk_portable/node/4.1.1_64bit/bin/node', '/home/gogoprog/code/emsdk_portable/emscripten/incoming/src/compiler.js', '/tmp/tmp4h8Mjd.txt', '/home/gogoprog/code/hxcpp-issue/build/failing/obj/emscripten/926416c8_Log.o', '/home/gogoprog/code/emsdk_portable/emscripten/incoming/src/library_pthread_stub.js'] to finish with return code 0, but it returned with code 1 instead! Output: // The Module object: Our interface to the outside world. We import
// and export values on it, and do the work to get that through
// closure compiler if necessary. There are various ways Module can be used:
// 1. Not defined. We create it here
// 2. A function parameter, function(Module) { ..gener
Error: Build failed
`

If I copy-paste the generated `emcc` link command it succeeds without any error.

It seems that a .o file is still being written but that's my only guess right now...

I made a minimal test case here : https://github.com/gogoprog/hxcpp-issue

**Comment by gogoprog** [comment]
I just noticed that my generated command line was :
`emcc -o Test.js -O2 -s DISABLE_EXCEPTION_CATCHING=0 "--js-library /home/gogoprog/code/hxlibcanvas/src/../libcanvas/src/lib/libcanvas.js" @obj/emscripten/all_objs`

The problem appears because of the double-quotes around js-library.

So how could I use the --js-library flag ?

**Comment by gogoprog** [comment]
My current workaround is to write the flags on 2 lines:
```haxe
@:buildXml('<target id="haxe" tool="linker">
    <flag value="--js-library"/>
    <flag value="libdummy.js"/>
</target>')
class MyClass...

**Comment by hughsando** [comment]
Yes, that is the correct solution at the moment.
