### ISSUE TITLE
Runtime error Gc with BitmapData

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/hxcpp#61]
This will explode...

var leak:BitmapData = new BitmapData(1,1);
Gc.doNotKill(leak); //boom

This will also explode...

var leak:BitmapData;

somewhereElse {
  leak = new BitmapData(1,1);
  Gc.doNotKill(leak);
  leak = null;//boom
}

===== Try it ===== 
git clone git@github.com:thomasuster/limeGCError.git
cd limeGCError
lime test cpp

**Comment by hughsando** [comment]
I think the zombie issues have been fixed - can I close this one?

**Comment by thomasuster** [comment]
Yep, closed!
