### ISSUE TITLE
Compilation fails with glibc 2.26

### ISSUE THREAD

**Issue by guzzard** [HaxeFoundation/hxcpp#641]
Compilation failed for me with glibc 2.26. Error was that xlocale.h was not found.

From [glibc changelog](https://sourceware.org/git/?p=glibc.git;a=blob;f=ChangeLog;h=8dbfc7eaffad18cf01256f5b2c908437442665ce;hb=1c9a5c270d8b66f30dcfaf1cb2d6cf39d3e18369):
```
2017-06-20  Zack Weinberg  <zackw@panix.com>
2130 
2131         * locale/xlocale.h: Rename to...
2132         * locale/bits/types/__locale_t.h: ...here.  Adjust commentary.
2133         Only define struct __locale_struct and __locale_t, not locale_t.
2134         * locale/bits/types/locale_t.h: New file; define locale_t here.
```

I changed these lines, and after that it compiled again:
- [src/hx/libs/std/Sys.cpp#L34](https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/libs/std/Sys.cpp#L34)
- [src/hx/libs/std/Sys.cpp#L146](https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/libs/std/Sys.cpp#L146)
- [project/libs/std/Sys.cpp#L33](https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/std/Sys.cpp#L33)
- [project/libs/std/Sys.cpp#L149](https://github.com/HaxeFoundation/hxcpp/blob/master/project/libs/std/Sys.cpp#L149)

**Comment by ibilon** [comment]
What version of hxcpp did you use? One was released yesterday with a fix for that.

**Comment by guzzard** [comment]
ah ok perfect! I'm using [khacpp](https://github.com/Kode/khacpp) so I guess I just have to wait until that fix has been reflected there.
