### ISSUE TITLE
Another Immix Issue?

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/hxcpp#642]
Hey @hughsando 

Trying to get PPs test harness running, it's having some problems that feel like a GC issue. 

Here's the info when running it in lldb.

<img width="1550" alt="screen shot 2017-09-24 at 5 44 03 pm" src="https://user-images.githubusercontent.com/220965/30788374-38b570bc-a150-11e7-84e9-2342b5705f9d.png">

Some high level potentially useful info.
* Using munit so both tests are running in a child thread of the main thread
* Both tests reference an array in the same class they're in
* Both tests reallocate this array
* If I remove allocations inside the tests and instead make the allocation once at setup the runtime error doesn't occur
* It happens with and without <haxedef name="HXCPP_GC_MOVING" />

**Comment by hughsando** [comment]
I'm not sure.  I could be - but are 2 tests accessing the same hash or array at any point?  Because this would need mutex-locking.

**Comment by thomasuster** [comment]
@hughsando Both tests are run on the same thread, so no multi threading issues here.  There munit test runner runs everything inside a child thread, not but all tests will be in run the same thread. Not sure why they did this, but yea, might mean "multiThreadMode" is enabled.

**Comment by thomasuster** [comment]
Okay, commented out all of the multithreading completely and verified GCPrepareMultiThreaded never gets called, still occurs.

**Comment by thomasuster** [comment]
Going to have to throw in the towel tonight, if you have any ideas for me to try let me know :-). But so far very much feels like another bug in GC.

**Comment by thomasuster** [comment]
Just found out I'm using NativeArray and using unsafeSet/Get. I'm betting this means that the array members are intentionally not marked upon being added with unsafeSet, so they are getting swept  before I expect? Is NativeArray suppose to work with GC?
