### ISSUE TITLE
In ios 11 'system' removed.  

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hxcpp#643]
- Sys.cpp 
Error: /usr/local/lib/haxe/lib/hxcpp/3,4,188/project/libs/std/Sys.cpp:293:16: error: call to unavailable function 'system': not available on iOS
        int result =  system(val_string(cmd));
                      ^~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.0.sdk/usr/include/stdlib.h:195:6: note: candidate function has been explicitly made unavailable
int      system(const char *) __DARWIN_ALIAS_C(system);
         ^
1 error generated.
#### Error building neko -Diphoneos -DHXCPP_ARMV7S -Dstatic_link

**Comment by codeservice** [comment]
For quick fix can be excluded:

/**
	sys_command : string -> int
	<doc>Run the shell command and return exit code</doc>
**/
static value sys_command( value cmd ) {
   #if defined(HX_WINRT) || defined(EMSCRIPTEN) || defined(EPPC) || defined(APPLETV) **|| defined(IPHONE)**
...

**Comment by mastef** [comment]
Looks like this was fixed in 5f63d23768988ba2a4d4488843afab70d279a593
