### ISSUE TITLE
array.sort loses GC references

### ISSUE THREAD

**Issue by hughsando** [HaxeFoundation/hxcpp#65]
It appears that doing a gc collect from within array.sort may prematurely collect some objects. Maybe:
- use scratch area
- std::allocator
- non-std solution
Also, maybe allow cpp.Function for  non-dynamic sorting

**Comment by thomasuster** [comment]
Roger that, I use haxe.ds.ArraySort.sort instead of normal sort.

**Comment by thomasuster** [comment]
https://github.com/HaxeFoundation/hxcpp/pull/185

**Comment by hughsando** [comment]
I have added an extra level of indirect to ensure that the references are held.
The haxe.ds.ArraySort is not a bad option either.
