### ISSUE TITLE
Question, what to do about generated obj files?

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#652]
Hello,

Sorry to open a question as an issue, but I was wondering what the recommended path might be for dealing with generated source files and obj files on C++ projects.

As you switch to new Haxe, HXCPP and library versions, and as code changes, the hash identifier continues to update. The great thing is that you can perform debug, release and other forms of builds in the same obj directory and retain the cache. Long-term, however, I'm wondering whether old files are ever removed.

Is there a way to have an idea about which files might be old or no longer-needed, if an "autoclean" behavior were built in a set of tools?

Thanks :smile:

**Comment by ibilon** [comment]
By default the cache for obj files is limited to 1GB, so old files are removed by that.

To manually deal with it there's a couple of `haxelib run hxcpp cache` commands: clear/days/resize/list/details

**Comment by jgranick** [comment]
`haxelib run hxcpp cache list` appears to require `HXCPP_COMPILE_CACHE`, do these commands work for standard HXCPP projects, using the default obj directories?

Is this cache per platform + target, or global?

**Comment by ibilon** [comment]
Oh I thought you were talking about the cache, for the in place obj I don't think I've seen any get removed.

The cache limit is global afaik.

**Comment by hughsando** [comment]
Yes, the recommended way is to the the compile-cache, the obj dir should be
considered legact mode now.  Everything should be faster and smaller then,
and these concerns are addressed.
