### ISSUE TITLE
Can't compile application for armv7

### ISSUE THREAD

**Issue by r3d9u11** [HaxeFoundation/hxcpp#655]
Hi. I tried to compile my application for armv7 arch and have an exception of g++:
```
g++: error: unrecognized command line option `-m32`
Error: Could not create PCH
```
But this option is for x86 architecture, is'n it?

```
#uname -a
Linux imx6ul-var-dart 4.1.15-224577-gc6d2d28 #1 SMP PREEMPT Web Oct 11 12:33:22 +03 2017 armv71 GNU/Linux
#g++ --version
g++ (Debian 6.3.0.-18) 6.3.0 20170516
```

tested with Haxe 3.2.1 (stable debian repo) and Haxe 3.4.4 (unstable debian repo)

build-cpp.hxml:
```
-main Main
-cp Sources
-cpp Bin
-D HXCPP_ARMV7
-lib tink_json
```

tested on [Debian Jessie](http://variwiki.com/index.php?title=DART-6UL_Debian_Jessie_MX6UL).

What I'm doing wrong?
Thanks.

**Comment by hughsando** [comment]
There is a 'noM32' option in linux-toolchain.xml.
Ideally, this should be set from the HXCPP_ARMV7 setting.
But you could try "-D HXCPP_NO_M32" and see if this helps.

**Comment by r3d9u11** [comment]
@hughsando Many thanks!
