### ISSUE TITLE
Dynamic Float Caching

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/hxcpp#656]
I'm wondering about the caching of non-int number values when boxed in Dynamic. A small range of ints is cached, which is nice, but it looks like the same int cache is half-there for other values as well. Is there a reason that it's not utilized, or is this an oversight?

I'm talking about the three constructors, `Dynamic(double inVal)`, `Dynamic(cpp::Int64 inVal)`, `Dynamic(cpp::UInt64 inVal)`

https://github.com/HaxeFoundation/hxcpp/blob/b815a8aeffe4db844d4759eccc6c406253f7702e/src/Dynamic.cpp#L398

**Comment by hughsando** [comment]
There is an awful lot of floating point numbers, so I do not want to cache them all.
eg, getting a time stamp every frame would leak cached references.
These integers are permanently allocated and do not cause gc overhead - but I really have to draw a line somewhere.

**Comment by hughsando** [comment]
Oh, you mean a missing "else" statement - might be something in that.

**Comment by justin-espedal** [comment]
Right, I meant the missing else. I noticed this when I saw hundreds of thousands of floats being allocated all because a single value (10.0, which would coincidentally benefit from the cache) was being passed through a closure, which unfortunately requires the Dynamic boxing.
