### ISSUE TITLE
Function name includes "_dyn" suffix

### ISSUE THREAD

**Issue by ianharrigan** [HaxeFoundation/hxcpp#659]
Hi, when using code similar to this:

```haxe
untyped __cpp__ ('QObject::connect({0}->ptr, &{1}, [=](){ {2}; })', pushButtonRef, QPushButton.clicked, clickHandler);
```

The following cpp is generated:

```cpp
QObject::connect(this->get_pushButtonRef()->ptr, &QPushButton::clicked, [=](){ this->clickHandler_dyn(); });
```

The part that looks strange is that `clickHandler` has turned into `clickHandler_dyn` in the result cpp.

Is this a bug or is it something im doing incorrectly?

**Comment by hughsando** [comment]
clickHandler I assume is a haxe function.  clickHandler_dyn() creates a closure (of type Dynamic) that binds the 'this' instance pointer to the clickHandler, and is callable using the f(x) notation, but not suitable to pass to native function pointer.
You can use a static function with cpp.Pointer.addressOf( someStaticFunction), but you would need to make a static function wrapper.
You could also pass a fixed external (native) function that takes a dynamic and calls it - then bind the clickHandler_dyn() dynamic value to this fixed function.  You will need to think about GC here - perhaps storing things in and AutoGCRoot.
Finally, you could move the function name inside the quotes to avoid the closure translation.

**Comment by ianharrigan** [comment]
Ok, thanks for the clarification Hugh - so seems its not a bug and simply my wrong doing - will close this issue.

Thanks again!
