### ISSUE TITLE
Cppia, indexOf returns 0 when a float is expected

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/hxcpp#661]
```
class Main
{
	static public function main()
	{
		trace(Std.int("01".indexOf("1")));
	}
}
```

Run this on cppia and it'll print 0 instead of 1. I guess because runFloat is undefined for IndexOfExpr.

**Comment by robocoder** [comment]
Compiled with Haxe 3.4.4, this now prints 1.

**Comment by justin-espedal** [comment]
You sure you were testing in cppia? I just tried it and it still returns 0 for me.
