### ISSUE TITLE
stderr points to stdout. regression

### ISSUE THREAD

**Issue by oprudkyi** [HaxeFoundation/hxcpp#663]
haxe 3.4 Sys,stderr() points to stdout 
https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/libs/std/File.cpp#L396

in haxe 3.2 stderr works correctly 

this is really a blocking bug because in many cases stderr and stdout treated differently (console commands pipe-lining and many other stdio based APIs )

**Comment by hughsando** [comment]
I think the PR should take care of this.
