### ISSUE TITLE
CI stability

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/hxcpp#665]
Problem:
HXCPP CI breaks a lot, it seems like every dependency we're pulling from is bleeding edge meaning that HXCPP is very susceptible to software erosion. Software erosion makes hxcpp unfriendly to PRs, as authors cannot rely on CI for regression testing. Also because dependencies are changing if CI is working you never know what build configuration actually results in it working.

Solution:
I've love to start slowly changing HXCPP CI / build such that it's always pulling versioned dependencies. When Hugh or someone else wants to update HXCPP and haxe, they should be able to run some simple command to update the haxe dependency, check in that change to the repo, and push. Now if CI breaks, we should be able to trust that the change we just pushed broke it, and nothing else.

**Comment by thomasuster** [comment]
@andyli

**Comment by andyli** [comment]
I agree. Feel free to work on this direction and propose PR.

However, note that it is not easy at all. Especially, for Mac, homebrew itself always use the latest version and there is little to no effort of supporting a specific version.

For Haxe <-> hxcpp, they always depend on the latest development/master of each other.

For Linux, it is relatively easy and reliable to achieve with the use of Docker. But it seems I'm the only one in HF who are comfortable with Docker...

**Comment by hughsando** [comment]
Currently, hxcpp uses a script to build haxe.
The script haxe uses to set itself up is in the travis.tml file itself, which is not very helpful.  So one solution here would be to extract the ocaml+build phase from the haxe .tml and put it in a separate script, then hxcpp can use this script.  This means that if haxe can build then so can hxcpp.
We could also possibly have separate runs for hxcpp against "last release" and "git version".  This would be helpful in itself, but would also give more confidence in a PR that is green against "latest release" but might actually be failing on "git" for not fault of its own.
Might it also be possible to create some pre-bundled ocaml distos? opam is truly the worst package manager in the universe for this, but maybe some OS snapshot or similar can be used -  and shared between haxe and hxcpp.

**Comment by hughsando** [comment]
I'm closing this for now - the ocaml/opam dependency is one of the trickiest unsolved problems in computer science, and it is beyond me.
I have moved the script from the travis setup, but really I need to split something off from haxe and use that.
