### ISSUE TITLE
Building a Static Framework for iOS?

### ISSUE THREAD

**Issue by alastaircoote** [HaxeFoundation/hxcpp#668]
I've been reading up about using the `-D objc` flag to output Objective C++ instead of C++, and some initial testing has been successful. But I'd love to be able to bundle my project as a static framework for use in XCode, so that anyone using my library doesn't have to worry about including header files, etc. etc.

But I'm struggling to put it together (warning: I'm definitely a newbie here). I've tried making a 'fat' `.a` library then [manually creating a framework by renaming/moving files](https://stackoverflow.com/questions/12476750/manually-create-framework-from-static-library), as well as creating an XCode project and including the `.mm` and `.h` files, but neither was successful, and I realise I actually have no idea what I'm doing.

My ideal result is a totally self-contained framework that just drops in to a project without the target having to change anything. Is this possible, and if so, how would I go about doing it?

**Comment by hughsando** [comment]
This is a tricky one.  You are going to need to ship some header files - so it depends what these look like.
If they include "haxey" stuff, you are going to need to expose the hxcpp header files too.
It should be possible to build a fat library - nme has done this, where it builds all the haxe stuff into a .a file. 
You could also use libtool to join the lib files together with some kind of post-build step, so I think your approach is sound.  Mainly a matter of working out apple's convention for naming etc.

**Comment by hughsando** [comment]
This one is getting old, so I'm closing it.
