### ISSUE TITLE
unicode cppia unit tests fail because of global function __hxcpp_string_of_bytes

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/hxcpp#669]
The unit tests of my unicode branch are currently [failing](https://travis-ci.org/frabbit/haxe-1/jobs/296496052) with: 

```
Unknown function : __hxcpp_string_of_bytes(4)
Called from hxcpp::__hxcpp_main
Called from cpp.cppia.Host::main /home/travis/build/frabbit/haxe-1/std/cpp/cppia/Host.hx line 62
Error : Unknown global
```

I reused the code of Bytes.getString in my [ByteAccess](https://github.com/frabbit/haxe-1/blob/unicode_vector/std/haxe/i18n/ByteAccess.hx#L396) type but it fails even when i add those classes to the [host classes](https://github.com/frabbit/haxe-1/blob/unicode_vector/std/cpp/cppia/HostClasses.hx#L133)

**Comment by hughsando** [comment]
Putting it in the host should solve the problem - it could be that the cppia needs to be recompiled once it sees the new "export_classes.info".
This can also happen when functions are inlined - the code gets inlined into the cppia.
Using inline can then be slower on cppia - sometimes if use "#if !cppia inline #end"

Some functions can be builtin to cppia - see https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/cppia/GlobalBuiltin.cpp

But it is not very fun.

**Comment by frabbit** [comment]
My Problem was that the call to `__hxcpp_string_of_bytes` was inside of a private class, in that case adding the containing Module to the Host classes didn't help. Moving the appropriate class into it's own file solves the problem. Feel free to close this issue if you don't want to fix those cases.

**Comment by hughsando** [comment]
Closing this now because I think you solved it.  Please reopen if required.
