### ISSUE TITLE
cpp.Int64/UInt64 issues

### ISSUE THREAD

**Issue by Herschel** [HaxeFoundation/hxcpp#67]
```
var i : cpp.Int64 = 1;
trace( i ); // Error because Dynamic.cpp doesn't define the appropriate constructor -- can't box Int64?
i = i << 33; // Error because gencpp casts both operands to an `int`
```

**Comment by thomasuster** [comment]
var i:Int64 = 1;

**Comment by ncannasse** [comment]
Has this not been fixed already ?

**Comment by hughsando** [comment]
The cpp.Int64 is really only for native interactions, and not haxe.
However, the new haxe.Int64 wraps the cpp.Int64 and provides all the shift operators etc to haxe, so I suggest switching over to haxe.Int64 instead of cpp.Int64, unless you have some particular native interactions.
