### ISSUE TITLE
Base generic class goes to be Dynamic

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/hxcpp#670]
```
@:native('NativeObject.h')
extern class NativeObject 
{
    //...
    public function setValue(value:Int):Void;
}

class HaxeObject<T:NativeObject>
{
    private var ref:Pointer<T>; //generated as Pointer<Dynamic>. But I want to get Pointer<NativeObject>
    public function new()
    {
        //...
    }
    
    public function setValue(value:Int):Void
    {
        ref.setValue(value);
    }
}
```

Don’t know why, but it replace T with Dynamic type.
@:generic is not helped.

**Comment by dmitryhryppa** [comment]
Looks like it is not a generics with externs problem. Regular Haxe class gives the same result:
```
@:generic  // << this does not give any effect
class Ololo {
}

class HaxeObject<T:Ololo>
{
    private var ref:T; //generated as Dynamic. But Ololo expected.
}
```

**Comment by hughsando** [comment]
Did you try @:generic on the HaxeObject?
It is the "T" that is getting replaced with dynamic.

**Comment by dmitryhryppa** [comment]
Yes, I tried it. Nothing was changed.

**Comment by dmitryhryppa** [comment]
Any chance to get help with this? Is it even possible to fix that?
PS. If you don't have a time for it, maybe you can give an advice where to look for issue. Maybe I can help with it then.

**Comment by dmitryhryppa** [comment]
This can be closed. That's my fault. After cleaning build dir everything works fine now.
