### ISSUE TITLE
Question: Embedded hint for GPU driver

### ISSUE THREAD

**Issue by jgranick** [HaxeFoundation/hxcpp#676]
I need to embed a hint in the executable for a GPU driver

How do you think this should be done?

One way I could do this would be behind a define, such as `-DHXCPP_HINT_DISCRETE_GPU`, and put it in the standard HxcppMain.h

A second way to approach this would be to enable this always by default, though some applications may not want the extra battery draw of a discrete GPU if a low-powered GPU is available

Third, should I instead try and override HxcppMain.h somehow, with a custom version?

Trying to think what the cleanest/best approach for this would be long-term

Thank you :smile:

**Comment by hughsando** [comment]
What does this hint look like?  An exposed symbol, or something else?  and what OS?
Or is it something that would normally go in an executable?

**Comment by TerryCavanagh** [comment]
This technical document by Nvidia explains the issue in a bit more detail: http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf 

(See the section _Global Variable NvOptimusEnablement (new in Driver Release 302)_ on page 3.)

The solution talked about in the openfl slack was adding these lines to `include/hx/HxcppMain.h':

```
   #if defined(HX_WINDOWS) && defined(HXCPP_HINT_DISCRETE_GPU)
   extern "C" {
      _declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
      _declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
   }
   #endif
```
[(these lines would be added at this point in the file)](https://github.com/HaxeFoundation/hxcpp/blob/master/include/hx/HxcppMain.h#L61)

**Comment by hughsando** [comment]
You can add this with some inline @:cppFileCode into any haxe file - and use @:keep meta to ensure its linked, like:
```haxe
@:cppFileCode('
#if defined(HX_WINDOWS)
   extern "C" {
      _declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
      _declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
   }
   #endif
')
@:keep class HighPerformance { }

class Test
{
   public static function main() trace("hello");

}
```
```
dumpbin -exports cpp/Test.exe
          1    0 00065014 AmdPowerXpressRequestHighPerformance
          2    1 00065010 NvOptimusEnablement
```
So the developer would do "import lime.gpu.HighPerformance" and it should just work.
Main is a bit complicated in hxcpp, so one of the library files would probably be better if it *really* needs to be in hxcpp code.

**Comment by TerryCavanagh** [comment]
This works for me!

**Comment by jgranick** [comment]
Thanks Hugh :smile:
