### ISSUE TITLE
How can I link with XP version of msvcrt.dll while I am building on a Windows 10 machine?

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/hxcpp#678]
Hello, I have a HXCPP project that I build on a Windows 10 machine with MinGW option.
I was not expecting msvcrt.dll to be linked as long as I am using g++ and not msvc. Unfortunatelly the library (msvcrt.dll) is installed by the operating system in /cygdrive/c/Windows/system32/msvcrt.dll

The problem is when running my project on Windows XP, the symbol `_vsnprintf_s` could not be found in the msvcrt.dll version installed on the system. I think is is not legal to distribute my msvcrt.dll copy from my Windows 10 instance, and it might not work also.

How can avoid linking with msvcrt.dll, or how can I provide a custom implementation for vsnprintf_s, in case I am running on Windows XP? Requiring Redistributable C++ is out of question since I am linking with G++, it must be a bug somewhere.

**Comment by hughsando** [comment]
I'm not exactly sure why that symbol is needed - maybe from sqllite3?
However, you certainly can - and probably should - redistribute msvcrt.dll
with your app.  Just copy the one from your dev machine and put it next to
the .exe file.

**Comment by ovidiugabriel** [comment]
I added msvcrt.dll next to the executable in the bin folder but it is not working. It is still loading the one in c:\Windows\system32; I tried to replace that one but is not possible while the library is in use. Which version of Visual C++ Redistributable is required for HXCPP 3.4.188?

This issue appeared after I moved from haxe 3.2.1 to haxe 3.4.4 and I updated the hxcpp accordingly. I do not remember exactly my previous hxcpp version.

**Comment by hughsando** [comment]
I think this is to do with mingw, since the msvc uses statically linking to avoid such issues.  It might be possible to work out what needs this symbol - possible one of the libraries like sqlite or regexp - maybe mingw is #defining something - and then avoid the call.  Older versions linked these separately and that might be what has changed.
It might be worth using msvc is you are targeting xp, and avoid these problems.

**Comment by ovidiugabriel** [comment]
Yes, it is most probably because of mingw is #defining something. Thanks!
