### ISSUE TITLE
How to convert ::cpp::Function<int(::cpp::Pointer<lua_State>)> to and from int (*)(lua_State *)?

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/hxcpp#684]
How to convert `::cpp::Function<int(::cpp::Pointer<lua_State>)>` to and from `int (*)(lua_State *)`?

**Comment by hughsando** [comment]
With function pointer you really need the types to match exactly.  In this case "cpp::Pointer" is a wrapper an not exactly the same class as a normal pointer.
So you could try `cpp.Star<lua_State>` instead of cpp.Pointer

**Comment by kevinresol** [comment]
OK thanks!
