### ISSUE TITLE
linux64 .dso files missing on v3.4.18x

### ISSUE THREAD

**Issue by JonnyTech** [HaxeFoundation/hxcpp#693]
The last couple of versions fail on Linux64:

```
$  haxelib set hxcpp 3.4.188
Library hxcpp current version is now 3.4.188
$ lime test linux 
Error: Source path "/home/user/haxelib/hxcpp/3,4,188/bin/Linux64/std.dso" does not exist
$  haxelib set hxcpp 3.4.185
Library hxcpp current version is now 3.4.185
$ lime test linux 
Error: Source path "/home/user/haxelib/hxcpp/3,4,185/bin/Linux64/std.dso" does not exist
$ haxelib set hxcpp 3.4.64
Library hxcpp current version is now 3.4.64
$ lime test linux 
OK
$
```

As you can see, downgrading to v3.4.64 is fine - is there a fix?

My workaround is to manually copy the files:

```
$ ls ~/haxelib/hxcpp/3\,4\,188/bin/Linux64/
Cppia
$ ls ~/haxelib/hxcpp/3\,4\,185/bin/Linux64/
Cppia
$ ls ~/haxelib/hxcpp/3\,4\,64/bin/Linux64/
Cppia  mysql5.dso  regexp.dso  sqlite.dso  std.dso  zlib.dso
$ cp ~/haxelib/hxcpp/3\,4\,64/bin/Linux64/* ~/haxelib/hxcpp/3\,4\,188/bin/Linux64/
$  haxelib set hxcpp 3.4.188
Library hxcpp current version is now 3.4.188
$ lime test linux 
OK
$
```

**Comment by hughsando** [comment]
These dlls should no longer be needed (they re built into the generated
exe)- so lime might need an update to reflect this.  Or perhaps your
project file refers to these ndlls directly?  You might just be able to
delete the references.
Copying should be ok as a work-around, since the dlls will not be used any
way.

**Comment by JonnyTech** [comment]
Ah, I am using Haxeflixel which currently cannot use lime newer than v3.6.1 so that may explain it.
