### ISSUE TITLE
typo: IMPLEMNET

### ISSUE THREAD

**Issue by farteryhr** [HaxeFoundation/hxcpp#699]
HX_IMPLEMNET_INLINE_VARIANT_FUNCTIONS

haxe\lib\hxcpp\3,4,188\include\cpp\Variant.h
haxe\lib\hxcpp\3,4,188\include\hx\Macros.tpl

**Comment by robocoder** [comment]
There's also NOT_IMPLEMNETED in:

* include/hx/CFFINekoLoader.h
* project/libs/nekoapi/NekoAPI.cpp
