### ISSUE TITLE
Passing wrapped C++ struct as a parameter

### ISSUE THREAD

**Issue by luboslenco** [HaxeFoundation/hxcpp#700]
Heyho.

I am unifying the 'float array' usage in Kha, and we would like to map the array directly to the following c++ struct:

```cpp
struct float32array {
	float* data;
	int myLength;
	// ...
};
```

Haxe externs look like this:

```hx
@:unreflective
@:structAccess
@:include("cpp_float32array.h")
@:native("float32array")
extern class Float32ArrayData {
	@:native("float32array")
	public static function create(): Float32ArrayData;
}

abstract Float32Array(Float32ArrayData) {
	public inline function new(elements: Int = 0) {
		this = Float32ArrayData.create();
	}
}
```

This works almost perfectly, but there is one issue - when passing `Float32Array` as a function parameter in Haxe, the generated code ends up as `( ::Dynamic)(( (cpp::Struct<  float32array >)(fa)`, which throws `no suitable user-defined conversion from "Dynamic" to "float32array" exists`.

It seems to be caused because of `@:structAccess` on the `Float32Array`. But if I remove that, we end up with `.` and `->` misuse. Is there any way to prevent the `::Dynamic` wrap-up when passing the struct?

(Using Haxe 3.4.4, compiling on Windows 10 & Visual Studio 2017.)

**Comment by hughsando** [comment]
It's been a little while since I've looked at it.  There is a way to make a "Dynamic Handler" for your types - but I don't have the code in front of me.
Can you pass around (functions, member variables) `cpp.Star<Float32Array>` instead?
This would allow reflection and make a few other things work better is a more "haxey" way.

**Comment by luboslenco** [comment]
I changed the mapping from `abstract -> extern class` to  `abstract -> class -> extern class` which did the trick. Thanks for help!

(related: https://github.com/Kode/Kha/pull/760/commits/6c5b0c5e415382f89356278d1fe2ca470841c4aa and https://github.com/Kode/Kha/pull/760)
