### ISSUE TITLE
Feature request. Disabling GC

### ISSUE THREAD

**Issue by dmitryhryppa** [HaxeFoundation/hxcpp#710]
Hi, 
currently, Haxe generates classes without destructor, but Gc have a disable option which does not make a lot of sense. 
But it would be a very nice if Haxe could generate classes with destructors, if some compiler flag is enabled (-D HXCPP_NO_GC, for example), so then we could call it manually. 
Or it may be a metatag (which is even better, something like `@:noGc`) which will help to use manual memory management only for specific classes and which will generate `destructor()` function for them. 

This feature may be very useful for C++ programmers, who want to switch to the more highlevel language. Also, it is very useful if we want to create external C++ library with Haxe. 

The second thing which may be improved is memory allocations for local variables.
The idea is to initialize local objects in stack so they can be deleted automatically after function is done. 

HxCpp target mostly used by games where performance is important thing, so manual memory management may be a great feature for improving this direction. 

Thank you for your time :)

**Comment by delahee** [comment]
I can only warmly approve of this :)

**Comment by hughsando** [comment]
You can't really disable Gc without leaking objects everywhere.  I think what you are describing is some kind of reference-counting haxe target.  One problem with this is that it is very easy to create self-references like `this.me = this` which complicates reference counting.  Some languages use weak references and "programmer beware" to get around this (eg, c++ smart pointers this code would just leak), and others do proper ref-cycle-detection.  Either way, there would be a significant departure from the current hxcpp target which is unlikely to happen without someone else doing a large chunk of work.

Your current options are to add finalizers to hxcpp classes, eg:
https://github.com/HaxeFoundation/hxcpp/blob/master/test/haxe/native/TestFinalizer.hx
which can call your destructor explicitly  which achieves the same thing - eg being able to store std::string/std::vector in you haxe classes.

And to store your haxe classes in native c++ code or std::vectors using GCRoot wrappers.

There is also nativeGen, which creates interfaces that do not rely on  hxcpp header files when using the haxe generated classes externally.

**Comment by dmitryhryppa** [comment]
Thank you for your reply!

Oh, I didn't know that nativeGen available for cpp target. 
Can you please point me to the right direction on how to use it? 
![Image](https://image.ibb.co/eF4Kxo/image.png)

I've tried it on the main (just like for Java or C# targets) class and looks like cpp output is a pretty clean now (neat!), but it won't compile. So, is it my fault beacause of wrong usage of nativeGen or it is a possible bug in hxcpp?

_Haxe 4 preview 3, MSVC 2017, hxcpp 3.4.188_

**Comment by hughsando** [comment]
hmm, this might just be an issue with the 'main' class entry point.  Try some other class.
But it might also be an issue with static functions, because I was mainly thinking of interfaces when I designed it.

**Comment by dmitryhryppa** [comment]
Well. I'm closing this then... 
But here is an issue with nativeGen :)
https://github.com/HaxeFoundation/haxe/issues/7199
