### ISSUE TITLE
dll_link causes undefined reference errors

### ISSUE THREAD

**Issue by sierra-se** [HaxeFoundation/hxcpp#714]
When defining `dll_link`:
``` - Link: Test.dso: g++ -o Test.dso -shared -fpic -fPIC -m64 -Xlinker --no-undefined @obj/linux64/all_objs -lpthread -ldl
obj/linux64/8b62ea8c_RunLibs.o: In function `hxRunLibrary':
RunLibs.cpp:(.text+0x17): undefined reference to `std_register_prims'
RunLibs.cpp:(.text+0x1c): undefined reference to `regexp_register_prims'
RunLibs.cpp:(.text+0x21): undefined reference to `zlib_register_prims'
collect2: error: ld returned 1 exit status
Error: Error while running command
g++ -o Test.dso -shared -fpic -fPIC -m64 -Xlinker --no-undefined @obj/linux64/all_objs -lpthread -ldl
Error: Build failed
```

They disappear when `dll_link` is commented out or replaced with `static_link`.

**Comment by hughsando** [comment]
The need for these should be conditional on HXCPP_API_LEVEL<330
What version of haxe are you using?
There is code to fix older versions of haxe, but maybe only for exe_link, not dll_link.
Can you try a more recent version of haxe?

**Comment by sierra-se** [comment]
I was on Haxe 3.2.1 since I installed Haxe from the official Ubuntu repository. I upgraded to Haxe 3.4.7 now and dll_link no longer causes an error.
Thanks for your help.
