### ISSUE TITLE
hxcpp fails to retain null-ness of cast Array

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#746]
When a function is called and an Array instance is implictly cast, if the Array instance was null in the caller's frame, it is not null in the callee's frame, instead becoming an empty array.  Here is an example showing the problem:

```
class HxcppBug
{
    public static function main()
    {
        var a : Array<Int> = null;

        examine(a);
    }

    private static function examine(a : Array<Dynamic>)
    {
        if (a != null) {
            trace("TEST FAILED: a was null when passed in but is not null " +
                  "inside examine");
        }
    }
}
```

This bug is pretty egregious.

**Comment by bjitivo** [comment]
Oh yeah testing with haxe 3.4.7 and hxcpp 4.0.4.

**Comment by Simn** [comment]
This reproduces on current development as well.

**Comment by ncannasse** [comment]
In include/cpp/VirtualArray.h:563-565
```cpp
template<typename SOURCE_>
VirtualArray::VirtualArray( const Array<SOURCE_> &inRHS )
   : super( hx::IsNull(inRHS) ? 0 : new VirtualArray_obj( inRHS.mPtr, true) )
```

This fixes the issue, but then we fail other unit tests. looking into it to see how problematic that is.

**Comment by bjitivo** [comment]
Yes I tried exactly that but it caused other problems so I gave up on it.  Can't remember what the other problems were, this was a week ago ...

**Comment by ncannasse** [comment]
Sorry for the delay Bryan, I didn't immediately realize Hugh was not available. Here's a PR for you, it pass unit tests with Haxe 4.0, tell me if it works for you, we're currently looking into other issues
https://github.com/HaxeFoundation/hxcpp/pull/752

**Comment by bjitivo** [comment]
OK so it turns out that I already have exactly your change in my code base, I guess I hadn't given up on it and my memory was faulty.  Been working through so many issues ...
