### ISSUE TITLE
Reflect.setProperty issue

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hxcpp#750]
I have code:

        var s: Sprite = new Sprite();
        var p: Dynamic = Reflect.getProperty(s, "addChild");
        trace(p);
        Reflect.setProperty(s, "addChild", function(child:nme.display.DisplayObject):nme.display.DisplayObject {
            return null;
        } );
        trace(s.addChild(null));

It work on neko, I can see trace: 
#function:1
null

Error on cpp, with trace output:
addChild
Invalid field:addChild

For some reason I can get method addChild from Reflect.getProperty but can't do Reflect.setProperty on cpp target.
Works on neko.

I am using official haxe release and latest hxcpp from GitHub.

So is it bug, or class method not a class property and can have random behavior on different targets?

**Comment by Gama11** [comment]
I think that's to be expected, trying to change a method via `setProperty()` seems to fail on all statically typed Haxe targets: C++, C#, Java, HashLink, Flash...

**Comment by codeservice** [comment]
If setProperty works correctly (except neko), then we have issue with getProperty. It should return null for class methods to avoid confusion.

**Comment by codeservice** [comment]
>It is not true, it doesn't behaves like Reflect.field

Well I am wrong, it works like Reflect.field, and return class methods in strange way:
        trace(Reflect.hasField( s, "addChild" )); //return false
        trace(Reflect.field(s, "addChild")); //return class method

I think its something developers need to accept as it is. The sky is green but we really know its blue, but some time can be gray :) distorted reality. I think I am done, commenting this.

Description for Reflect.field:
	/**
		Returns the value of the field named `field` on object `o`.

		If `o` is not an object or has no field named `field`, the result is
		null.

		If the field is defined as a property, its accessors are ignored. Refer
		to `Reflect.getProperty` for a function supporting property accessors.

		If `field` is null, the result is unspecified.

		(As3) If used on a property field, the getter will be invoked. It is
		not possible to obtain the value directly.
	**/
