### ISSUE TITLE
GPL Licensed MySQL Libs

### ISSUE THREAD

**Issue by zicklag** [HaxeFoundation/hxcpp#757]
I was doing a license scan and noticed that there are 4 files in [src/hx/libs/mysql](https://github.com/Kode/khacpp/tree/master/src/hx/libs/mysql) that are licensed under the GPL:

* `my_api.cpp`
* `my_proto.cpp`
* `my_proto.h`
* `mysql.h`

This would prevent them from being used in commercial products. They should be replaced with implementations that have a license compatible with the rest of the codebase.

**Comment by ncannasse** [comment]
Yes, they are my own code, I agree with a MIT license change
