### ISSUE TITLE
static_link missing flag in msvc-toolchain.xml

### ISSUE THREAD

**Issue by intoxopox** [HaxeFoundation/hxcpp#766]
I'm trying to build 64 bit static libraries, but no matter what I do, they are always 32 bit. Is it possible that the reason is msvc-toolchain.xml is missing the -machine:${MACHINE} flag under the static_link linker node?

**Comment by yzkuang** [comment]
You can use -DHXCPP_M64

**Comment by intoxopox** [comment]
Thanks for the response. My mistake was not expecting that define to be case sensitive. Once I used it in all caps, everything worked as expected. Closing this issue now.
