### ISSUE TITLE
Memory leak in multithreading environment

### ISSUE THREAD

**Issue by nulld** [HaxeFoundation/hxcpp#767]
Run into memory leak. Trying to figure out what is going on, but without results atm. Will be thankful for any hints.

Haxe Compiler 4.0.0-rc.1+1fdd3d59b
hxcpp: 4.0.8

Here my minimal representative example:

```
import haxe.Timer;
import cpp.vm.Thread;

class AnotherThreadStruct
{
    public var prop1:Array<Float>;

    public function new(size:Int)
    {
        prop1 = [];
        prop1[size - 1] = 0;
        for (i in 0...size) {
            prop1[i] = 0.0;
        }
    }
}

class SomeDeepStructure
{
    public var prop1:Array<Float>;
    public var prop2:Array<Float>;
    public var childs:Array<AnotherThreadStruct>;

    public function new(size:Int)
    {
        prop1 = [];
        prop2 = [];
        prop1[size - 1] = 0;
        prop2[size - 1] = 0;
        for (i in 0...size) {
            prop1[i] = 0.0;
            prop2[i] = 0.0;
        }
    }

    public function addInnerNode(node:AnotherThreadStruct)
    {
        childs.push(node);
    }

    public function addNNodes(n:Int)
    {
        childs = [];
        childs[n-1] = null;
        for (i in 0...n) {
            var n = new AnotherThreadStruct(1000);
            addInnerNode(n);
        }
    }
}

class Main {
    static var size = 1000;
    static var handle:Thread;

    public static function main() {
        trace("it works!");

        var timer = new Timer(5000);
        timer.run = update;

        handle = Thread.create(worker);
    }

    static var iter = 0;

    public static function update()
    {
        trace('Iteration: $iter');
        iter++;
        for (i in 0...size) {
            var n = new SomeDeepStructure(size);
            //not reproduced if do not use another thread - do job in timer for e.g
            //haxe.Timer.delay(n.addNNodes.bind(size), 0);
            handle.sendMessage(n.addNNodes.bind(size));
        }
    }

    static function worker()
    {
        while (true)
        {
            var task = Thread.readMessage(true);
            task();
        }
    }
}
```

**Comment by hughsando** [comment]
Could it be that you are creating work faster than you can process it?

**Comment by nulld** [comment]
@hughsando, thanks for fast answer. 
I've try set update frequence to one minute - seems leak still there, but become much more slower.
var timer = new Timer(60000);
App crashed after about 5 hours working and 2Gb was alocated. (But windows fall into sleep mode and I run intoproblem after awake - will try with switched off sleep mode)

![image](https://user-images.githubusercontent.com/2820168/53643614-91522300-3c45-11e9-9531-8867921c4c13.png)

In heap analyzer I see a lot of objects with the same alocation stack
![image](https://user-images.githubusercontent.com/2820168/53644224-1be75200-3c47-11e9-8b79-b8c86da9c279.png)

Is it possible to alocate part of one object from another thread? (`addNNodes`)
Is it correct to do so?

**Comment by nulld** [comment]
@hughsando Hm.. seem - you are right. If pc not fall into sleep mode - consuming memory amount is stable. But can you clarify how to interpretate GC debug output. Why after collect "large size" never becomes zero?:
```
=== Collect === 034AF948
Mark conservative 00CFFAE8...00CFFB84 (39)
Mark conservative 00507A4C...00507A58 (3)
Mark conservative 034AF9A4...034AFAB8 (69)
Mark conservative 0050A66C...0050A678 (3)
Row use ratio:0.000659
Total memory : 992.00k
  reserved bytes : 13.50k
  large size   : 40.97mb
  empty blocks : 28 (90.3%)
Target memory 20.00mb, using 13.50k
Collect Done
Collect time total=34.67ms =47.3%
  setup=2.25
  mark=11.15(init=0.00/roots=0.01 18+1/loc=11.14*82 696+356/mark=0.00 0+0/fin=0.00*0/ids=0.00)
  reclaim=7.85
  large(5377->347, recyc 0)=10.08
  defrag=0.00
Where?  8184
```

**Comment by hughsando** [comment]
At any given instant, the GC is not perfect because it is 'conservative', and although some bytes may no longer be in use, they still might show up an the stack, and the GC will hang on to these "just in case".
The best way to try to prevent this accidental retention is to call the allocate/process/deallocate routines from a deep stack, then return, then collect.  Or, putting zeros on the stack before collecting, like https://github.com/HaxeFoundation/hxcpp/blob/master/test/haxe/gc/TestGC.hx#L27
