### ISSUE TITLE
How to remove XXX_obj suffix?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#769]
How to remove XXX_obj suffix?

![image](https://user-images.githubusercontent.com/748320/54211284-019d5600-451c-11e9-9a21-7ab489582bf3.png)

generate cpp

**UnityEngine::Vector3_obj** instead of  **UnityEngine::Vector3**

we don't need _obj behind  UnityEngine::Vector3**_obj** 

UnityEngine::Vector3

how to add some @:xxx to avoid generate XXX_obj

**Comment by hughsando** [comment]
The `@:native` meta should do this in general, although you may need additional `@:native` to rename each static function.
Is this coming from the 'new' call?  Because calling a native new call can confuse hxcpp.  You can get around this with something like:
```haxe
@native("new UnityEngine::Vector3")
public function create(x:Float, y:Float,z:Float) : Vectory3

...

myVec = Vector3.create(1,2,3);
```
