### ISSUE TITLE
StringTools.replace with unicode and smart_strings

### ISSUE THREAD

**Issue by RblSb** [HaxeFoundation/hxcpp#772]
```haxe
package;

class Main {

	static function main() {
		trace(StringTools.replace("абв [X36] где", "[X36]", "abc"));
	}

}
```
`haxe -main Main -cpp cpp -D hxcpp_smart_strings`

output is `Main.hx:6: 012`
haxe rc1/rc2, git hxcpp or from haxelib.

**Comment by Aurel300** [comment]
I don't think this is `StringTools` related.

On the latest haxe build (c586004af4e3ef7a064136afdb64dbb4fa0fbce3), git hxcpp:

```haxe
class Main {
	public static function main():Void {
		Sys.println("č");
	}
}
```

Just outputs an invalid character:

```bash
$ out.cpp/Main | xxd
0000000: 0d01 0a                                ....
```

Interestingly, the character `č` is `U+010D`, i.e. a byte swap of the bytes that get printed. The correct UTF-8 encoding would be different of course (`C4 8D`).

**Comment by RblSb** [comment]
Well, problem is with `split` anyway:
`trace("äbbä".split("bb").length) // is 1`

**Comment by ncannasse** [comment]
These are serious problems, can you look into it @hughsando ?

@Aurel300 can you create a PR with these tests ? we have some already in tests/unit/src/unistd/Unicode.unit.hx , but are these correctly run on hxcpp ?

**Comment by Aurel300** [comment]
Ok, #781 will fix `trace` and printing. As for the `split` (and by extension `StringTools.replace`) issue, I think it happens when the string is Unicode but the delimiter is not.

```haxe
trace("абв [X36] где".split("[X36]")); // [абв [X36] где]
trace("абв [ň36] где".split("[ň36]")); // [абв , где]
trace("äbnbä".split("bnb")); // [äbnbä]
trace("äbňbä".split("bňb")); // [ä,ä]
```
