### ISSUE TITLE
[question]what's the check_type_size in hxcpp build xml?

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#774]
what's the check_type_size in hxcpp build xml?

I can't find the same way in hxcpp like cmake .

such like 

check_type_size("socklen_t" HAS_SOCKLEN_T BUILTIN_TYPES_ONLY)

if(HAS_SOCKLEN_T)
    add_definitions(-DHAS_SOCKLEN_T=1)
endif()

**Comment by hughsando** [comment]
There is no real way to do this.  The hxcpp build system does not have a way to run test code.  Usually these defines can be worked out in the cpp code, or are known in advance because to the compiler being used.
