### ISSUE TITLE
check null equality

### ISSUE THREAD

**Issue by porfirioribeiro** [HaxeFoundation/hxcpp#78]
I have a extern class that has functions that can return a NULL value.
But i can't compare that value with null in haxe because it always gives false.

Could it be added to null.h some way to check if a pointer is NULL?

**Comment by hughsando** [comment]
I have adde quite a few ways of accessing external data now, and these can interact with Dynamic/null a bit better.  I this particular case, I suggest declaring the native type as:
@:native("cpp::Reference<gdImage>")
extern class Image

This object can then be compared with null, and passed via Dynamic.

**Comment by hughsando** [comment]
I'm closing this one now since the apis have changed quite a bit - please start a new issue if you are still having issues.
