### ISSUE TITLE
Math.random() not random on ARM64

### ISSUE THREAD

**Issue by pozirk** [HaxeFoundation/hxcpp#784]
Hello!
I believe it's HXCPP problem.

Basically, Math.random() returns not random results on Android ARM64 architecture:
Here is an example:
04-23 10:49:32.513 19263 19289 I trace : Main.hx:37: time(NULL)=1556009372
04-23 10:49:32.513 19263 19289 I trace : Main.hx:38: Std.random(1000)=266
04-23 10:49:32.513 19263 19289 I trace : Main.hx:39: Math.random()=0.647641502087936
…
04-23 10:49:54.143 19367 19393 I trace : Main.hx:37: time(NULL)=1556009394
04-23 10:49:54.143 19367 19393 I trace : Main.hx:38: Std.random(1000)=266
04-23 10:49:54.143 19367 19393 I trace : Main.hx:39: Math.random()=0.647641502087936

Any help with that?
Thank you!

**Comment by nanjizal** [comment]
You could try using https://github.com/Kode/Kha/blob/master/Sources/kha/math/Random.hx in the mean time.
I read a suggestion that it might be maxing out and just giving you seed for the max integer it expects. Also read that recommendations are for c++ not to use standard random generator.
Sorry don't feel up to trying to debug but hopefully the alternate random is helpful.

**Comment by pozirk** [comment]
Thanks @nanjizal, I'll try this different version.

**Comment by andrew-git** [comment]
Stably reproduced on Android ARM64 architecture.

**Comment by andrew-git** [comment]
Looks like for ARM64 srand64 should be used instead of srand

**Comment by pozirk** [comment]
Thank you guys, I believe I can close this ticket now.
