### ISSUE TITLE
Broken Sys class after hxcpp upgrade (NEKO_WINDOWS)

### ISSUE THREAD

**Issue by ovidiugabriel** [HaxeFoundation/hxcpp#785]
After upgrading to hxcpp 4.0.8 I encountered some issues while building my project on Windows with MinGW. All these issues seem to be caused by guarding with NEKO_WINDOWS.

For example, the following code(in std/Sys.cpp)  will give an error since `_wfopen` is not defined in GNU C++ Compiler (MinGW/g++).

```cpp
#ifdef NEKO_WINDOWS
    const wchar_t * wfname = fname.__WCStr();
    const wchar_t * wr = r.__WCStr();
    hx::EnterGCFreeZone();
    FILE *file = _wfopen(wfname,wr);
#else
   hx::EnterGCFreeZone();
   FILE *file = fopen(fname.__s,r.__s);
#endif
```

How can I disable `NEKO_WINDOWS` while building with MinGW on Windows? I am not using `wchar_t` anywhere in this project, so it is ok for me if there is a way to diasble widechar support and make the project compile again.

**Comment by hughsando** [comment]
Looks like I need to undefine `__STRICT_ANSI__`  to make these functions visible.
