### ISSUE TITLE
Invalid string comparison

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/hxcpp#797]
```haxe
class Main {
	static public function main() {
		var s = "𠜎zя";
		var s2 = "abя";
		trace(s > s2);
	}
}
```
That yields `false` on cpp, `true` on all other targets.

**Comment by ncannasse** [comment]
I guess CPP has the same issue HashLink had :) @hughsando you need to compare the 16 bit code points on UCS2 strings, not byte-by-byte ;)
