### ISSUE TITLE
GC related crash on Windows with Deque objects

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/hxcpp#801]
Using hxcpp 4.0.8 and haxe RC2

When executing a major collect, hxcpp  is calling a Deque's finalizer unexpectedly. This seems to happen at a random time interval each run, but usually after no more than a few seconds.

Minimal repro

**GcCrash.hx**
````haxe
import sys.thread.Deque;

class GcCrash {

    static var queue: Deque<String>;

    static public function main() {
        trace("Starting, give it a few seconds to crash");
        queue = new Deque();
        haxe.MainLoop.add(mainLoop);
    }

    static function mainLoop() {
        cpp.vm.Gc.run(true);
        queue.pop(false);
    }

}
````
**Build with**
`haxe -main GcCrash -cpp bin`

--
The crash itself happens in `EnterCriticalSection` when the Deque's mutex locks with a critical section that was invalidated by it's finalizer.

Also happens with `-D HXCPP_GC_GENERATIONAL` and running `Gc.doNotKill(queue)`. Not yet sure what is causing `queue` to be collected but I think it's related some sort of threading timing issue.

(I'm aware we don't need to explicitly call `Gc.run(true)` but I'm assuming the crash will still happen at major collections)

**Comment by haxiomic** [comment]
Thanks for such a quick fix @hughsando!

Is there some way I can donate / support? I'm really impressed by hxcpp and I'd love to support it somehow :)

**Comment by hughsando** [comment]
Thanks for the offer!  I don't really need financial support, but if you
could somehow manufacture more hours in my day for me, that would be nice.
