### ISSUE TITLE
Hxcpp failed to build to emscripten - Update

### ISSUE THREAD

**Issue by Fhalo48** [HaxeFoundation/hxcpp#808]
Hi

I'm getting the following error:-
python: can’t open file ‘/emcc’: [Errno 2] No such file or directory

["Compiling multiple Haxe code files to Emscripten via javascript"](https://community.haxe.org/t/compliling-multiple-haxe-code-files-to-emscripten-via-javascript/1796) on Haxe community will
give more detail of the problem.

Any ideas?

**Comment by Fhalo48** [comment]
Update:
`@:buildXml("
<linker id='exe' exe='emcc'>
	<flag value='-s' />
	<flag value='WASM=1' />
</linker>
")
`
It now failed on linking, unable to find user32.lib.

**Comment by hughsando** [comment]
Looks like you have found a solution, so I will close for now.

**Comment by Fhalo48** [comment]
I think I may have found a solution. I’m uploading the solution to the Haxe cookbook.
