### ISSUE TITLE
Converting Haxe class to void * and vice-versa

### ISSUE THREAD

**Issue by darmie** [HaxeFoundation/hxcpp#810]
I am working with a C++ library that requires storing an object in it, to be reused later. 

When I try to retrieve the object back, I get a segmentation fault. (EXC_BAD_ACCESS)

Example c++ library
```c++
  extern void* getObject();
  extern storeObject(void* context);
```
in Haxe 
```hx
     storeObject(RawPointer.addressOf(object));
     untyped __cpp__('::Dynamic* __ref = (::Dynamic*)(getObject())');
     var myObject = untyped __cpp__('*__ref');  // segmentation fault
```
is there something I might be missing?

**Comment by Gama11** [comment]
Did you figure out a solution, or why close the issue?

**Comment by darmie** [comment]
No I didn't, I just had a work around which involved not having to use this aspect of the c++ library.
