### ISSUE TITLE
Haxe 3.4.7 + hxcpp 4.0.19 = crash on Lime/OpenFL samples

### ISSUE THREAD

**Issue by larsiusprime** [HaxeFoundation/hxcpp#814]
I'm not sure what the underlying cause is, but this is extremely easy to reproduce.

See also:
https://github.com/openfl/lime/issues/1331

To reproduce:

0. Install haxe 3.4.7
1. Install a fresh version of openfl from haxelib, just "haxelib install openfl" (as of this writing this is 8.9.1)
2. Run "haxelib setup openfl" and install the recommended libraries (including hxcpp 4.0.19)
3. Run "openfl create DisplayingABitmap"
4. Enter the created directory, run, "lime test windows -debug -v"

It will crash on startup and give an error message:
![2019-06-20 13_59_12-Error](https://user-images.githubusercontent.com/739064/59874947-25670800-9365-11e9-80d2-b213792cb931.png)

Reverting to hxcpp 4.0.8 eliminates this crash. I've heard (but have not tested myself) that upgrading to haxe 4.0.0-rc.3 fixes it as well. It's specifically the 3.4.7 + hxcpp 4.0.19 that knocks something loose and causes this regression.

My haxelib list for clarity:

actuate: [1.8.9]
box2d: [1.2.3]
flixel-demos: [2.7.1]
flixel: [4.6.2]
format: [3.4.2]
hxcpp: [4.0.8] 4.0.19
hxp: [1.1.2]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: [7.5.0]
openfl-samples: [8.7.0]
openfl: [8.9.1]

This is a working config -- swapping hxcpp to 4.0.19 and leaving all else the same causes the bug. And the haxe version here is 3.4.7.

**Comment by Gama11** [comment]
>It's specifically the 3.4.7 + hxcpp 4.0.19 that knocks something loose and causes this regression.

Any Haxe version < rc.3 actually, it seems - also happens with rc.2.

**Comment by hughsando** [comment]
This fix might cover a few issues - thanks for reporting.  Might I also suggest that lime.utils.Assets not discard the message provided to 'onError' when showing this dialog box.

**Comment by emugel** [comment]
I was about reporting a similar 'problem', this time with recordmacro.
My title was going to be `haxe 3.4.7 + hxcpp 4,0,4 = recordmacro works,  hxcpp 4,0,19 does not`.

The symptom is while the rows and data are retrieved from db with a simple `ClassName.manager.get(<someid>)`, when trying to obtain the fields they are all null. However the bug does not appear when I revert to the version I was using before (4,0,4).

My guess after noticing that was that newer versions of hxcpp were developed for Haxe 4 and that it was my fault for using Haxe 3 with hxcpp 4. Thought I'd mention this.  
Keep up the good work!
