### ISSUE TITLE
cppia: setting instance dynamic array with reflection makes it un-iterable

### ISSUE THREAD

**Issue by justin-espedal** [HaxeFoundation/hxcpp#815]
```haxe
#if cppia
class MyScript
{
	public var _choices:Array<Dynamic>;
	
	public static function main()
	{
		new MyScript();
	}
	
	public function new()
	{
		Reflect.setField(this, "_choices", ["A", "B"]);
		
		trace("testing");
		trace(_choices);
		
		for(item in _choices) //this for-loop crashes
		{
			trace(item);
		}
	}
}
#end
```

Making `_choices` static and calling `Reflect.setField(MyScript, "_choices", ["A", "B"]);` works fine.

Making `_choices` `Array<String>` instead of `Array<Dynamic>` also makes it work.

**Comment by justin-espedal** [comment]
Not sure if it would help at all, but I've been doing some debugging to try to figure out the cause.

At [this line](https://github.com/HaxeFoundation/hxcpp/blob/bc2fc6ff62ea07a3e96b5530775c2632d45f0b59/src/hx/cppia/CppiaVars.cpp#L257), `inValue` is a `cpp::VirtualArray_obj`, but the `=` operator turns it into `hx:ArrayBase`.

Later, when we try to loop over the values, it crashes when [trying to return the length of the array](https://github.com/HaxeFoundation/hxcpp/blob/bc2fc6ff62ea07a3e96b5530775c2632d45f0b59/src/hx/cppia/Cppia.cpp#L4611), since it expects it to be `cpp::VirtualArray_obj`, but it's a `hx:ArrayBase` instead.

**Comment by hughsando** [comment]
Yes - that looks like the problem.  The code for arrObject and arrAny used to be the same, but now there is a difference.  I have pushed a fix here - see if it works for you.

**Comment by justin-espedal** [comment]
Yep, that works. Thanks!
