### ISSUE TITLE
[android] Use latest NDK

### ISSUE THREAD

**Issue by thomasuster** [HaxeFoundation/hxcpp#823]
I normally use NDK 11, but while trying to implement #813 I ran into a lot of issues. Going to use this ticket as a way of trying to get the existing targets working with the latest NDK. And then see if adding x86_86 then becomes easier.

**Comment by thomasuster** [comment]
* Got it compiling for armv7

**Comment by thomasuster** [comment]
https://github.com/android-ndk/ndk/issues/1030

**Comment by thomasuster** [comment]
- Got it linking for armv7

**Comment by thomasuster** [comment]
Go sample NME app building & running

**Comment by jgranick** [comment]
Is it working for you?

Here was my last attempt, I think we'd all appreciate a working clang toolchain for newer Android NDK versions

https://github.com/HaxeFoundation/hxcpp/pull/707

**Comment by thomasuster** [comment]
@jgranick Hey Joshua! Yes it's working. I'm just working to clean & polish the diff before submitting a PR.
