### ISSUE TITLE
terminate called after throwing an instance of 'Dynamic'

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#848]
random throw this error, there are none of regular  to find

**Comment by Simn** [comment]
Sorry, what? Please provide some code that reproduces the problem.

**Comment by sonygod** [comment]
Maybe there are some unknown error in Sqlite or Mysql ,I 'll try to find and provide  sample code to 

reproduce.

same code and difference  server got difference  error
