### ISSUE TITLE
Cyrillic text issue after updating to haxe 4.0.0-rc.5 (in openfl TextField)

### ISSUE THREAD

**Issue by www0z0k** [HaxeFoundation/hxcpp#850]
After upgrading haxe I get correct traces of Cyrillic strings’ lengths and values, but the TextField itself looks like:
![Screenshot 2019-09-21 at 20 21 43](https://user-images.githubusercontent.com/951595/65380577-d4a9d700-dce6-11e9-84aa-01ed95413eec.png)

However tracing the `textField.text` gives a correct result in the console.

This is on mac/ios targets. `toUpperCase()` and `length` work as expected for Cyrillic strings, but the text looks like:
![Screenshot 2019-09-22 at 03 15 47](https://user-images.githubusercontent.com/951595/65380601-5d287780-dce7-11e9-9aea-0f5ad424dc54.png)

On neko target `toUpperCase()` and length don't work correctly, but the text is displayed ok:
![Screenshot 2019-09-22 at 03 17 14](https://user-images.githubusercontent.com/951595/65380605-80532700-dce7-11e9-9e92-9b877d11ebe6.png)

Here is the full code to reproduce it:
```
	var _body:TextField = new TextField();
        addChild(_body);
	_body.text = 'фыва йцук';

```
Should I downgrade back to 3.4.7 version or there might be another way around?

**Comment by Simn** [comment]
I think you're looking for https://github.com/openfl/openfl

**Comment by www0z0k** [comment]
sorry, I was sure that I was posting it there
