### ISSUE TITLE
Old object access in generational mode

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/hxcpp#851]
Hey, I finally managed to condense my problems with the generational garbage collector down to a two lines sample project (albeit containing a 20 MiB json file from https://github.com/json-iterator/test-data/blob/master/large-file.json). Or at least one of the problems I suppose.

This is the project: [hxcpp_json_generational_test.zip](https://github.com/HaxeFoundation/hxcpp/files/3640435/hxcpp_json_generational_test.zip)
It crashes with an old object access, tested with Haxe 4rc5 (64bit Windows version) and hxcpp 4.0.52.

**Comment by hughsando** [comment]
Thanks for the test-case, very helpful.

**Comment by sonygod** [comment]
after update hxcpp and test this project hxcpp_json_generational_test.zip
Error: /usr/lib/haxe/lib/hxcpp/git/src/hx/gc/Immix.cpp: In function ‘void hx::GCCheckPointer(void*)’:
/usr/lib/haxe/lib/hxcpp/git/src/hx/gc/Immix.cpp:1459:7: error: ‘Sleep’ was not declared in this scope
       Sleep(10000);
       ^~~~~
/usr/lib/haxe/lib/hxcpp/git/src/hx/gc/Immix.cpp:1459:7: note: suggested alternative: ‘sleep’
       Sleep(10000);
       ^~~~~
       sleep

**Comment by RobDangerous** [comment]
I did some tests with your latest changes and now when I do a release build it sometimes crashes at different positions in the garbage collector and sometimes it runs to the end. When I disabled HXCPP_GC_DEBUG_ALWAYS_MOVE it always worked but I fear that just makes the crashes less likely.

**Comment by RobDangerous** [comment]
And indeed my big application has similar random crashes even without HXCPP_GC_DEBUG_ALWAYS_MOVE and even if I don't use any threads (and also set the marker threads to 1) it is random when and where the crash occurs.

**Comment by RobDangerous** [comment]
Extended the example project. This one crashes for me on every single run but it typically goes into the hundreds.
[hxcpp_test2.zip](https://github.com/HaxeFoundation/hxcpp/files/3694631/hxcpp_test2.zip)

**Comment by RobDangerous** [comment]
Latest fixes make my last test run reliably here. Big game still crashes at different places though. Trying to build the next test...

**Comment by RobDangerous** [comment]
No success so far in building anything small that crashes but I activated it by default in Kha now, accompanied by a big warning and a notice to contact me when running into any problem. That'll hopefully help. Will also continue trying to build a small crashing sample myself of course.

**Comment by RobDangerous** [comment]
Another small hint - when activating all the defines I could find big game now always crashes with the "Nursery object escaped generational collection" message albeit always at different points in the game, even with HX_GC_FIXED_BLOCKS and HX_WATCH.

**Comment by hughsando** [comment]
The fixed_blocks was very handy on the previous example because it made it deterministic, and always crashed a the same memory location. I could then add this location to the hxWatchList for more details (you can also set a data breakpoint in msvc). The game input timing, and any threads, would prevent this for a game generally.  Unless you can run in some emulation mode with fixed clock and inputs and threads.
If you use single-threaded collection, you might be able to trace the ownership of the escaped object to a common point, even on different crashes - some native object maybe? - by looking at the mark stack at that warning point.  I think it should be the direct owner of the escaped object that is the problem. This message suggests that a new object was stored in an old object, but  the old object did no run the write barrier (WB) code.

**Comment by RobDangerous** [comment]
No idea what it could be yet and it sometimes crashes before user interaction when things should still be deterministic. Will have a closer look at the addresses... thanks a lot for the hints!

**Comment by RobDangerous** [comment]
One type of thing that often escapes is a regular Haxe object that's assigned using some silly code which looks basically like
```data['bla'][i] = new Something(data['bla'][i]);```
Will investigate further when I'm back from work.

**Comment by hughsando** [comment]
Could *possibly* be a compiler optimization - does it happen in debug mode?
If you could post a generated-cpp snippet for this code, it might give me
some ideas too.

**Comment by RobDangerous** [comment]
Does happen in debug mode. Generated code is
```
::Dynamic _hx_tmp = ::_Dynamo::Dynamo_Impl__obj::getarr(data,HX_("behaviors",a1,ef,ab,35));
::Dynamic _hx_tmp1 = ::Globals_obj::_sc_BALL_BEHAVIOR->get(type);
::_Dynamo::Dynamo_Impl__obj::setarr(_hx_tmp,i1,::JS_obj::create(_hx_tmp1,::cpp::VirtualArray_obj::__new(1)->init(0,::_Dynamo::Dynamo_Impl__obj::getarr(::_Dynamo::Dynamo_Impl__obj::getarr(data,HX_("behaviors",a1,ef,ab,35)),i1))));
```
but I'll try to simplify that, getarr and setarr are rather complex.

**Comment by hughsando** [comment]
Following this logic though, I found a missing write-barrier on __SetItem.  See if the change helps.

**Comment by RobDangerous** [comment]
Hm, that didn't help, the same objects are still escaping.

**Comment by RobDangerous** [comment]
OK, I think I figured this one out. The actual type of _hx_tmp is a VirtualArray and that circumvents your fix. I sent a pull request which hopefully does the right thing.
That said, I have still more escapees. Trying to figure out where those come from next...

**Comment by RobDangerous** [comment]
My current escapee strangely is a local. The generated code looks like this:
```
::JSMapImpl this1 = this->tilesetIds;
::Array< Float > tilesetIds = ( (::Array< Float >)(this1->get(maps->__get(::Std_obj::_hx_int(i)).StaticCast<  ::ig::C_BackgroundMap >()->tilesetName)) );
```
It's the ::Array< Float > tilesetIds which then escapes. Don't know what's up with that guy. I'm still running in debug mode. The assignment causes a fancy conversion from an array of dynamics hidden in a dynamic if I see that correctly.

PS: Also noticed that Anon seems to need some love as well, even though that didn't seem to cause any issues for me so far. Will try to create a pull request for that tomorrow.

**Comment by hughsando** [comment]
Interesting.  Do you know if the collection is happening in the middle of the conversion? ie, in some partial conversion state - there might be an edge case there.  Also, is it the array itself that goes missing, or the contents pointer?  The array should be covered by the mark conservative code - but maybe the logic for write barriers on long-lived local objects is funky.
Given that the escape-detection code relies on conservative marking, I don't think it is a top of stack/bottom of stack issue - unless it is actually during creation of the temp object.

**Comment by hughsando** [comment]
Ok, I can get a crash with:
```haxe
class Main
{
   public static function sum(array:Array<Float>) : Float
   {
      var sum = 0.0;
      for(a in array)
         sum += a;
      return sum;
   }
   public static function main()
   {
      var str = '{ "vals":[0,1,2,3,4,5,6,7,8,9,10] }';
      var sumAll = 0.0;
      var keepBuf = new Array<Dynamic>();
      for(i in 0...100000000)
      {
         if ( (i%1000000)==0 )
            trace('$i ...');
         var obj = haxe.Json.parse(str);
         sumAll += sum( obj.vals );
         keepBuf.push(obj);
         if (keepBuf.length>1000)
            keepBuf.shift();
      }
      trace("Sum All: " + sumAll);
   }
}
```
so I can have a look

**Comment by hughsando** [comment]
Added a few more write barriers:
https://github.com/HaxeFoundation/hxcpp/commit/e5fb1c3f832b598ae3fc5c55a4097a98d8d456de

**Comment by hughsando** [comment]
also - shouldn't your tilesetIds be ints? Or is it an Opengl thing?

**Comment by RobDangerous** [comment]
Thank you very much! Will give it a spin this evening, right when I'm back from work.
The code is cross-compiled from JavaScript, so everything has to be doubles.

**Comment by RobDangerous** [comment]
Things are looking really good now.
Only thing still bothering me is that my hack to unregister the audio thread now causes trouble but that isn't necessarily unexpected (will have a closer look though and might have some questions about it later). But apart from that everything seems to run just wonderful now.
