### ISSUE TITLE
'typeinfo.h': No such file or directory ....is back ...visual studio 16.3.0 update removed typeinfo.h

### ISSUE THREAD

**Issue by hoseyjoe** [HaxeFoundation/hxcpp#852]
Sounds like updating to visual studio 16.3.0 will break hxcpp

https://developercommunity.visualstudio.com/content/problem/734566/msvc-142328019-is-missing-include-typeinfoh.html

**Comment by MSGhero** [comment]
Really glad you posted this. I updated VS today and thought I broke something. I removed the `.h` from typeinfo in `include/hxcpp.h` and I'm able to compile.

**Comment by hoseyjoe** [comment]
great, thanks.  I had not gone that far.

**Comment by Binklebonk** [comment]
> Really glad you posted this. I updated VS today and thought I broke something. I removed the `.h` from typeinfo in `include/hxcpp.h` and I'm able to compile.

Thank you @MSGhero!
