### ISSUE TITLE
Sqlite cnx.request return error!

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#859]
Sqlite cnx.request return error!

same code test between hashlink and hxcpp

hashlink return correct results and hxcpp throw error.

        import sys.db.Sqlite;

        class CustomTrace {
            public static function init() {
                var oldTrace = haxe.Log.trace;
                haxe.Log.trace = function(v:Dynamic, ?pos:haxe.PosInfos) {
                    oldTrace("[" + Date.now().toString() + "] " + Std.string(v), pos);
                };
            }
        }

        typedef Scroe = {
            var id:Int;
            var roomID:Int;
            var round:Int;
            var cards:Array<Int>;

            var earnMoney:Int;
            var loseMoney:Int;
            var fk:Int;
            var time:Date;
            var key:Int;
        }

        class TestSqlite {
            public static function main() {
                CustomTrace.init();
                var cnx = Sqlite.open("mybase.db");
                cnx.request("
                CREATE TABLE IF NOT EXISTS fa_game (
                    id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                    us_id integer  NOT NULL DEFAULT 0,
                    room_id integer  NOT NULL DEFAULT 1,
                    round integer NOT NULL DEFAULT 0,
                    coeds TEXT NOT NULL,
                    win integer NOT NULL DEFAULT 0,
                    lost integer NOT NULL DEFAULT 0,
                    fk integer NOT NULL DEFAULT 0,
                    time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
                    times integer  NOT NULL,
                    score integer NOT NULL DEFAULT 0,
                    money integer NOT NULL DEFAULT 0,
                    isBanker integer NOT NULL DEFAULT 0
                )
                ");

                var allScores:Array<Scroe> = [];

                for (i in 0...4) {
                    allScores.push({
                        id: i,
                        roomID: i,
                        fk: i,
                        round: i,
                        key: i,
                        time: Date.now(),
                        cards: [i, i + 1, i + 2],
                        loseMoney: i,
                        earnMoney: 1
                    });
                }

                trace(allScores.length);
                var arr = [];
                for (p in allScores) {
                    var q = 'INSERT INTO fa_game (us_id,room_id,round,coeds,win,lost,fk,time,times) VALUES(${p.id},${p.roomID},${p.round},${cnx.quote(p.cards.join(","))},${p.earnMoney},${p.loseMoney} ,${p.fk},${cnx.quote(Std.string(p.time))},${p.key})';
                    arr.push(q);
                
                }

                trace("now?");

                for (p in allScores) {
                    var q = 'INSERT INTO fa_game (us_id,room_id,round,coeds,win,lost,fk,time,times) VALUES(${p.id},${p.roomID},${p.round},${cnx.quote(p.cards.join(","))},${p.earnMoney},${p.loseMoney} ,${p.fk},${cnx.quote(Std.string(p.time))},${p.key})';

                    trace(q);
                var rs= cnx.request(q);

                    trace(rs.length);//here cpp will crash.

                }
                trace("finish");
            }
        }

@hughsando  could you take a look?

**Comment by sonygod** [comment]
BTW,,mysql and sqlite do not support UTF-8 .

LIKE : "中文"

**Comment by ncannasse** [comment]
Please submit a different issue with a reproducible sample.

**Comment by jonasmalacofilho** [comment]
Reduced to

```
import sys.db.Sqlite;

class TestSqlite {
	static function main() {
		var cnx = Sqlite.open(":memory:");
		trace(cnx.request("CREATE TABLE foo(bar TEXT)").length); // Error: Invalid sqlite result
}
```

The fix is fairly straightforward, I'll open a PR later.

**Comment by jonasmalacofilho** [comment]
See jonasmalacofilho/hxcpp@227fbe9.

_(not opening a PR yet because it also touches the MySQL code and thus depends on the fix and tests in #861)_

**Comment by sonygod** [comment]
@jonasmalacofilho  any progress?

**Comment by jonasmalacofilho** [comment]
See #862.
