### ISSUE TITLE
[QUESTION/ISSUE] sqlite binary blob in haxe 4.X

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hxcpp#864]
Before haxe 4.x it was possible read/write binary data using strings. In haxe 4 it doesn't work any more.
https://github.com/HaxeFoundation/hxcpp/blob/ae7b42d10456a712336218b0c8b152b1e27122a2/project/libs/sqlite/sqlite.cpp#L266
case SQLITE_BLOB:
int size = sqlite3_column_bytes(r->r,i);
f = alloc_string_len((const char *)sqlite3_column_blob(r->r,i),size);

alloc_string_len return not exact binary value of blob data
Before I was able load images from blob using NME code:
var result: ByteArray = new ByteArray();
result.writeUTFBytes(blobstring);

In haxe 4 its broken.  What new method for working with CFFI binary data in haxe 4?

**Comment by ibilon** [comment]
Not familiar with the code but what about `alloc_buffer`?
Using `alloc_string_len` for binary data doesn't seem right.

**Comment by codeservice** [comment]
Doesn't work, I tried it like:
f = buffer_val(alloc_buffer((char*)sqlite3_column_blob(r->r,i)));
or
f = buffer_val(alloc_buffer(alloc_string_data(char*)sqlite3_column_blob(r->r,i)), size));
Data corrupted by transformation some where and image not displaying

**Comment by ibilon** [comment]
Why are you passing by `char*` or `string_data`, BLOB is binary not text?

Anyway it seems I got it wrong and buffer is a stringbuf, not a binary buffer, so I don't know,
maybe it needs to alloc an array?

**Comment by codeservice** [comment]
In older haxe it was possible pass binary buffer in hxcpp string data. I was using it to store images in binary BLOB field. Basically old hxcpp use char* and string_data as it is, simply pointer to row of bytes. It can be text or it can by bytes. My guess that in haxe 4, hxcpp doing some kind of Unicode transformations and we cant use haxe strings for binary objects any more. Now question what we can use? I'll check array, maybe it will work. I think we need to replace in hxcpp code were we are using strings for binary objects. I think it not only in sqlite, mysql has same issue too.

**Comment by codeservice** [comment]
I am continuing my investigation and found strange issue with alloc_field
https://github.com/HaxeFoundation/hxcpp/blob/ae7b42d10456a712336218b0c8b152b1e27122a2/project/libs/sqlite/sqlite.cpp#L276

I printed data types for result set values
https://github.com/HaxeFoundation/haxe/blob/0d88c583b747836de9ef534a54a0153ac89ab210/std/cpp/_std/sys/db/Sqlite.hx#L148

With code like:

            var f = Reflect.fields (c);
            var i = 0;
            var l = f.length;
            while (i < l) {
                var v = Reflect.field (c, f[i]);
                trace(f[i] + ": ["+Type.getClassName (Type.getClass (v))+"] "+v);
...

All fields have "String" type. So alloc_field always creating string values, even if fields allocated with different types: alloc_bool, alloc_int etc. Is it bug? Maybe this breaking binary buffer?

**Comment by hughsando** [comment]
Yeah, alloc_string is not right anymore.
I think the alloc_buffer is almost right, but is should be alloc_buffer_len, and then memcpy the data in.
```c++
   buffer b = alloc_buffer_len(len);
   char *ptr = buffer_data(b);
   memcpy(ptr, ....., len );
   f = buffer_val(b);
```
This avoids the string encoding.  The result will be haxe.io.BytesData, which is usually ok to pass to NME-style functions.

**Comment by codeservice** [comment]
Buffer doesn't work. I changed code to:

               int size = sqlite3_column_bytes(r->r,i);
               buffer b = alloc_buffer_len(size);
               char *ptr = buffer_data(b);
               memcpy(ptr, (char*)sqlite3_column_blob(r->r,i), size );
               f = buffer_val(b);

Table exists and I have image here. I can see this image in other SQLite management tools.
CREATE TABLE IF NOT EXISTS TestTable (
    binaryBLOB BLOB }
Result set **row** from query: "SELECT binaryBLOB FROM TestTable"
trace(Type.typeof(**row**.binaryBLOB)); 
printed: TClass(String) 

This issue I was mentioned before: https://github.com/HaxeFoundation/hxcpp/issues/864#issuecomment-553620570
alloc_field(v,r->names[i],f);  for buffer still making strings

And it crashed with attempt to make ByteArray from **row**.binaryBLOB:
ByteArray.fromBytes( haxe.io.Bytes.ofData(**row**.binaryBLOB));

**Comment by hughsando** [comment]
So there are a few things going wrong here.
Firstly, hxcpp/project/libs is only for legacy stuff, the current versions are in src/hx/libs/.  I think I will remove the legacy stuff next version to avoid confusion.
The code in the haxe std lib will need to change, since 'getResult' forces the result to a string, which is no good - or at least should have another function that can get the blob result.
I have put a fix in to convert blobs to haxe.io.BytesData.  Mysql currently generates haxe.io.Bytes, but I will need an updated haxe std lib to fix this to make them match.
I think the best way of dealing with it is to use code like:  https://github.com/HaxeFoundation/hxcpp/commit/0a50f68337626a8a618443fc7a1fe4ec71df7d3a#diff-bf0afdc55182926de255dc022416109eR142
and eventually, it will always be haxe.io.Bytes.

**Comment by codeservice** [comment]
Yes, I am still using old sqlite because I need it as standalone library with custom modifications. 

Fix, https://github.com/HaxeFoundation/hxcpp/commit/0a50f68337626a8a618443fc7a1fe4ec71df7d3a#diff-22f73ab9d27c8658d5e67ae8dad73cf3R326, works only if your library part of hxcpp, so you can include  #include <hxcpp.h> in your code and use Array_obj,  String, etc.

Including hxcpp.h impossible in CFFI libraries and here we still have problems with alloc_field for dynamic object producing string field instead of buffer.

**Comment by codeservice** [comment]
If old sqlite not supported in hxcpp, its probably make sense open new issue for alloc_field https://github.com/HaxeFoundation/hxcpp/issues/866

**Comment by codeservice** [comment]
I can confirm buffer works, with few additional kicks.
