### ISSUE TITLE
CFFI aloc_field for empty object data type issue

### ISSUE THREAD

**Issue by codeservice** [HaxeFoundation/hxcpp#866]
In CFFI library I have code:

            value v = alloc_empty_object();
            alloc_field(v,val_id("number1"),alloc_int(7));
            alloc_field(v,val_id("number2"),alloc_float(7.2));
            alloc_field(v,val_id("bool"),alloc_bool(true));
            //other non string types including buffer
            return v;//pass to haxe

In haxe I have code:

            var f = Reflect.fields (v);//read CFFI returned object fields
            var i = 0;
            var l = f.length;
            while (i < l) {
                var value = Reflect.field (v, f[i]);
                trace(Type.typeof(value));
                i = i + 1;
            }

Printed result, all fields TClass(String)
Expected int, float, bool, etc

Its maybe issue with alloc_field, or Reflect.field. Somewhere in hxcpp Anon __SetField or__Field

**Comment by hughsando** [comment]
I have added test for this, and it seems to work ok.
One thing to watch out for, is that if you "trace" a dynamic the variable, haxe will type is as a String.
To avoid this, explicitly type your temps as Dynamic, eg `var value:Dynamic = Reflect.field(anon, f);`

**Comment by codeservice** [comment]
I can see in some libraries, it’s expecting result to get all fields as string:
https://github.com/jgranick/sqlite/blob/bf93fb313455af7a1db3ed3d4be046ea19dbe38d/cpp/db/Sqlite.hx#L166 from alloc_field
I am using similar code. Only difference, as you mentioned, variable declared “Dynamic”. And it did the trick! Now I have correct field types!
