### ISSUE TITLE
[sqlite] sqlite not support utf-8

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#877]
import sys.db.Sqlite;

	class TestSqlite {
		public static function main() {
			var cnx = Sqlite.open(":memory:");

			cnx.request("PRAGMA synchronous = OFF");
			cnx.request("PRAGMA locking_mode=EXCLUSIVE");
			cnx.request("PRAGMA journal_mode=WAL");

			cnx.request("
							CREATE TABLE IF NOT EXISTS fa_game (
								id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
								us_id integer  NOT NULL DEFAULT 0,
								name TEXT NOT NULL DEFAULT ''
							)
							");

			cnx.request("begin;");

			for (i in 0...10) {
				var q = 'INSERT INTO fa_game (us_id,name) VALUES(${i},${cnx.quote("中文")})';

				// trace(q);
				var rs = cnx.request(q);
			}
			cnx.request("commit;");
			trace("finish");
		}
	}

//---------------------
Error : Error while executing INSERT INTO fa_game (us_id,name) VALUES(0,'涓枃') (Sqlite error in INSERT INTO fa_game (us_id,name) VALUES(0,'涓枃') : unrecognized token: "'涓)

@ConstNW @hughsando

**Comment by sonygod** [comment]
@R32 would you look this?

**Comment by R32** [comment]
I don't have mysql, but i guess you need a String with forced UTF8 encoding.

For now, you can't create UTF8 String directly from haxe since `HX_SMART_STRINGS`

But it can be bypassed by some `c` code:

ForceUTF8.hx:
```hx
@:unreflective
@:cppFileCode("
    static unsigned int wcstoutf8(unsigned char* out, const wchar_t* src) {
        wchar_t c = 0;
        unsigned int i = 0;
        if (out == NULL) {
            while (c = *src++) {
                if (c < 0x80) {
                    i++;
                } else if (c < 0x800) {
                    i += 2;
                } else if (c >= 0xD800 && c <= 0xDFFF) { // surrogate pair
                    src ++;
                    i += 4;
                } else {
                    i += 3;
                }
            }
        } else {
            while (c = *src++) {
                if (c < 0x80) {
                    out[i++] = (unsigned char)c;
                } else if (c < 0x800) {
                    out[i++] = (unsigned char)(0xC0 | (c >> 6));
                    out[i++] = (unsigned char)(0x80 | (c & 63));
                } else if (c >= 0xD800 && c <= 0xDFFF) {
                    int k = ((((int)c - 0xD800) << 10) | (((int)*src++) - 0xDC00)) + 0x10000;
                    out[i++] = (unsigned char)(0xF0 |(k>>18));
                    out[i++] = (unsigned char)(0x80 | ((k >> 12) & 63));
                    out[i++] = (unsigned char)(0x80 | ((k >> 6) & 63));
                    out[i++] = (unsigned char)(0x80 | (k & 63));
                } else {
                    out[i++] = (unsigned char)(0xE0 | (c >> 12));
                    out[i++] = (unsigned char)(0x80 | ((c >> 6) & 63));
                    out[i++] = (unsigned char)(0x80 | (c & 63));
                }
            }
        }
        return i;
    }
")
class ForceUTF8 {
    static public function toUTF8(s: String) : String {
        if ((cast s).isUTF16Encoded()) {
            untyped __cpp__("
                unsigned int len = wcstoutf8(NULL, (wchar_t * ) s.__w);
                unsigned char* ptr = (unsigned char*) hx::InternalNew(len + 1, false);
                ptr[len] = 0;
                wcstoutf8(ptr, (wchar_t*) s.__w);
                return ::String((char*) ptr, len);
            ");
        }
        return s;
    }
}
```
Main.hx:
```hx
using ForceUTF8;
class Main {
    static function main() {
        cnx.quote("中文".toUTF8());
    }
}
```

**Comment by sonygod** [comment]
it's seem work and fixed .

**Comment by sonygod** [comment]
it's seem only work on windows ,but on ubuntu ,I got this 

    src/Main.hx:48: Hello, world!
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(0,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(1,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(2,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(3,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(4,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(5,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(6,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(7,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(8,'▒▒')
    src/Main.hx:26: INSERT INTO fa_game (us_id,name) VALUES(9,'▒▒')
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:40: v=�
    src/Main.hx:42: finish

**Comment by R32** [comment]
```hx
class ForceUTF8 {
    static public function toUTF8(s: String) : String {
        untyped __cpp__("
        #if defined(HX_SMART_STRINGS) && defined(HX_WINDOWS)
            if (s.isUTF16Encoded()) {
                unsigned int len = wcstoutf8(NULL, (wchar_t * ) s.__w);
                unsigned char* ptr = (unsigned char*) hx::InternalNew(len + 1, false);
                ptr[len] = 0;
                wcstoutf8(ptr, (wchar_t*) s.__w);
                return ::String((char*) ptr, len);
            }
        #endif
        ");
        return s;
    }
}
```

**Comment by sonygod** [comment]
Called from Main::main Main.hx line 51
Called from Main::testsql Main.hx line 29
Called from sys.db._Sqlite.SqliteConnection::request /root/haxe/versions/4.0.5/std/cpp/_std/sys/db/Sqlite.hx line 40
Error : Error while executing INSERT INTO fa_game (us_id,name) VALUES(0,'中文') (Sqlite error in INSERT INTO fa_game (us_id,name) VALUES(0,'中文') : unrecognized token: "'中梀)
root@ets-game:~/test/testcpp/cpp#



@R32

**Comment by R32** [comment]
I don't have ubuntu,  but I guess it maybe that some c compilers treat  `wchar_t` as 4 bytes.

my last change: just simply replaced `wchar_t` with `char16_t`

```hx
@:unreflective
@:cppFileCode("
    static unsigned int wcstoutf8(unsigned char* out, const char16_t* src) {
        char16_t c = 0;
        unsigned int i = 0;
        if (out == NULL) {
            while (c = *src++) {
                if (c < 0x80) {
                    i++;
                } else if (c < 0x800) {
                    i += 2;
                } else if (c >= 0xD800 && c <= 0xDFFF) { // surrogate pair
                    src ++;
                    i += 4;
                } else {
                    i += 3;
                }
            }
        } else {
            while (c = *src++) {
                if (c < 0x80) {
                    out[i++] = (unsigned char)c;
                } else if (c < 0x800) {
                    out[i++] = (unsigned char)(0xC0 | (c >> 6));
                    out[i++] = (unsigned char)(0x80 | (c & 63));
                } else if (c >= 0xD800 && c <= 0xDFFF) {
                    int k = ((((int)c - 0xD800) << 10) | (((int)*src++) - 0xDC00)) + 0x10000;
                    out[i++] = (unsigned char)(0xF0 |(k>>18));
                    out[i++] = (unsigned char)(0x80 | ((k >> 12) & 63));
                    out[i++] = (unsigned char)(0x80 | ((k >> 6) & 63));
                    out[i++] = (unsigned char)(0x80 | (k & 63));
                } else {
                    out[i++] = (unsigned char)(0xE0 | (c >> 12));
                    out[i++] = (unsigned char)(0x80 | ((c >> 6) & 63));
                    out[i++] = (unsigned char)(0x80 | (c & 63));
                }
            }
        }
        return i;
    }
")
class ForceUTF8 {
    static public function toUTF8(s: String) : String {
        untyped __cpp__("
        #if defined(HX_SMART_STRINGS)
            if (s.isUTF16Encoded()) {
                unsigned int len = wcstoutf8(NULL, s.__w);
                unsigned char* ptr = (unsigned char*) hx::InternalNew(len + 1, false);
                ptr[len] = 0;
                wcstoutf8(ptr, s.__w);
                return ::String((char*) ptr, len);
            }
        #endif
        ");
        return s;
    }
}
```

**Comment by sonygod** [comment]
work!

**Comment by sonygod** [comment]
hi @R32 

on windows ,use you code 

   trace("中文".toUTF8()); //got 涓枃 ,but on ubuntu it's ok.

**Comment by R32** [comment]
Windows Console is not UTF8 encoding by default, 

So don't do `trace("中文".toUTF8())`, Just `trace("中文")`

**Comment by sonygod** [comment]
@R32  

so I want to trace sql line 


   var q = 'INSERT INTO fa_game (us_id,name) VALUES(${i},${cnx.quote("中文".toUTF8())})';

   trace(q);

I can't get right result .


![}YAZ`NVHPCL~`NCDMRJ{P`E](https://user-images.githubusercontent.com/748320/73149054-75c3f680-40fa-11ea-81fb-0e627aed3482.png)
