### ISSUE TITLE
Pointer casting doesn't work with RawPointer<T> but does with Star<T>

### ISSUE THREAD

**Issue by haxiomic** [HaxeFoundation/hxcpp#889]
When casting between pointers, the correct output is generated if `Star<T>` is used but not if `RawPointer<T>` is used:

```haxe
import cpp.*;

var buffer: Star<cpp.Void>;
var floatBuffer: Star<Float32> = cast buffer;
// generates correct: float* floatBuffer = ( (float*) buffer ) 🎉

var buffer: RawPointer<cpp.Void>;
var floatBuffer: RawPointer<Float32> = cast buffer;
// generates incorrect: float* floatBuffer = buffer
// the lack of native casting means the compiler throws an error here
```

I think this is a `gencpp.ml` issue

---
\* I've opened a few issues without PRs recently which I feel like brings negativity but I want to add that I absolutely _love_ hxcpp and hope to be using it a lot more in the future! These issues help me keep track of things I want to make PRs for this year

**Comment by Gama11** [comment]
>I've opened a few issues without PRs recently

For most people that's the norm. 😄

**Comment by haxiomic** [comment]
Yeah, I imagine maintaining a popular free open source repo can be a thankless task sometimes – I hate to open issues which feel like saying "this is wrong – fix it for me" so I think it's better to at least try a fix first if you're able to
