### ISSUE TITLE
Dynamic Int64 addition treated as strings

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hxcpp#897]
It looks like the Dynamic Dynamic::operator+(const Dynamic &inRHS) const doesn't check for vtInt64 and assumes string.

`
var i:Int64 = 1;

trace(add(i, i)); // returns "11" instead of 2 on hxcpp

function add(v1:Dynamic, v2:Dynamic):Dynamic
{
return v1 + v2;
}

`

**Comment by hughsando** [comment]
Seems to be working now.  Please re-open if it is still an issue.
