### ISSUE TITLE
[cppia] not support  haxe.MainLoop

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/hxcpp#898]
import haxe.MainLoop;
		class Main {
			static function main() {
				

				MainLoop.addThread(function (){

					while (true){
						Math.sin( Math.PI);
						Sys.sleep(1);
					}
				
				});

				trace('hello? cppia');

			}
		}

Unknown function : __hxcpp_thread_current(0)
Error : Unknown global:__hxcpp_thread_current

haxe :git version 
hxcpp:git version

//---------------
hxcpp target work  fine.

**Comment by RealyUniqueName** [comment]
Are you sure you're using the latest haxe and hxcpp?
I can't reproduce it.

**Comment by sonygod** [comment]
Yes , it's cppia target instead of hxcpp .Both windows and Ubuntu test .

**Comment by RealyUniqueName** [comment]
Works fine on Ubuntu with the latest haxe and hxcpp and cppia target.
What are you compilation settings?
How do you run the cppia script?
Have you rebuilt cppia host as explained in https://github.com/HaxeFoundation/hxcpp#cppia ?

**Comment by sonygod** [comment]
No ,without host ,just run 

   haxelib run hxcpp test.cppia

**Comment by RealyUniqueName** [comment]
I think that command requires rebuilding cppia by following instructions I linked above. Please, try that.
