### ISSUE TITLE
Windows on ARM64 support?

### ISSUE THREAD

**Issue by bugtestes** [HaxeFoundation/hxcpp#909]
Hi, any chance we could donate to a dev towards a Surface Pro X or something so WOA support can be added to HXCPP?

**Comment by hughsando** [comment]
I would accept a Surface Pro X in exchange for getting WOA support going in hxcpp.
Not sure is there are others who would share to costs.

**Comment by otsono** [comment]
I'll put 500 in, seems like used ones go for about 700-800.

**Comment by jdonaldson** [comment]
I can do another $500

**Comment by jdonaldson** [comment]
Wait, what’s the exchange rate here?  ;)

**Comment by otsono** [comment]
I'm speaking in USD as well 😉. https://swappa.com/laptops/buy/microsoft-surface-pro-x

**Comment by otsono** [comment]
> I would accept a Surface Pro X in exchange for getting WOA support going in hxcpp.
> Not sure is there are others who would share to costs.

How can I get my share over to you?

**Comment by hughsando** [comment]
I see there is a bit of a sale on these now.  I think I can justify buying one for my business and can send a paypal link to those who want to chip in a bit once I know the price.

**Comment by jdonaldson** [comment]
Sounds good to me.

**Comment by hughsando** [comment]
I made a few changes - got a nice speedup of about 2x from x86 to arm64.  The compiler crashes sometimes and corrupts the obj.  It seems random (works the second time I try to compile).  Looks like some concurrent access issue maybe - I was compiling on the device, which uses x86 build tool (no native arm64 :( ) so maybe there are some issues microsoft has.
I have not tried cross-compiling yet, although I don't think I've done anything that would prevent this.
Let me know if it works for you - you can add `-D HXCPP_ARM64` to generate the exes.

**Comment by otsono** [comment]
Seems like compiling on x64 fails with `obj\msvc1964-nc\de27382f_IShape.obj : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'ARM64'` - hopefully this doesn't mean cross-compiling in this direction isn't possible

I'll try compiling on an ARM64 machine soon

**Comment by hughsando** [comment]
You main need to remove your 'obj' directory before you start.  Better yet, use the HXCPP_COMPILE_CACHE.
 I think I need to alter the name for arm objs.

**Comment by hughsando** [comment]
ok, hxcpp should be updated.

**Comment by otsono** [comment]
Works here! :)
