### ISSUE TITLE
Crash with generational GC on 64 bit only

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/hxcpp#911]
Hey Hugh, we found another one. Mr @ustance uncovered this one, I minimized his original sample at https://github.com/RobDangerous/gc_bug_sample but I couldn't figure out what's special about it.

I tested it with Haxe 4.1.1 and hxcpp 4.1.1. using the included build.hxml. I could only make it crash in 64bit mode - but whether the problem actually doesn't exist in 32bit mode or whether that just makes it less likely to happen I don't know. Typical time-to-crash for me is about half an hour.

Also tried with HXCPP_GC_CHECK_POINTER and HXCPP_GC_DEBUG_ALWAYS_MOVE but that didn't change the behaviour for me. Setting HXCPP_GC_DEBUG_LEVEL to 4 (only tried that with Kha but tried all previous tests with both and it was all the same) crashed it in MarkObjectAllocUnchecked at the inPtr->__Mark(__inCtx); line, all other crashes I think were in processMarkStack at the obj->__Mark(this); line with obj being bogus.

**Comment by RobDangerous** [comment]
PS: Did all of the testing so far on Windows using msvc 2019.

**Comment by sibest** [comment]
Try my fix at the bottom of issue #913

**Comment by RobDangerous** [comment]
Thanks, added those two inSize == 0 checks. But sadly that didn't help with this issue.

**Comment by sibest** [comment]
Try also my fix in Array.h, about at row 450 before inline const void *PointerOf(...) { return 0; }

```
template<typename T>
inline const void *PointerOf(::Array<T> &a) { return a.mPtr; }
```

**Comment by RobDangerous** [comment]
Thanks again! But, uhm, that also didn't make a difference.

**Comment by sibest** [comment]
Well, i've tried GC_MOVING many times and it always lead to crash. It's possible that your loop triggers the blocks moving and crashes. In my game i don't have it enabled for now, if I see that memory fragmentation is a problem I will try to take a look at it.

**Comment by sibest** [comment]
Please try my code #917

**Comment by hughsando** [comment]
This seems like a bit of a doozy.
It looks like a object is found on the stack in one generation collection but not stored in an object, then not found on the next and is partially overwritten and then found again on a third collection causing a crash.  There is some code in there to prevent this for non-generation collections but looks like i need to do some stuff to fix this in the generational case.

**Comment by sibest** [comment]
Hi @RobDangerous , can you try my pull at https://github.com/HaxeFoundation/hxcpp/pull/918 ?

**Comment by RobDangerous** [comment]
Hi @sibest, you can just do that yourself, I think that would be more efficient :) It's cool you're trying to help but I don't think we need to do a full round-trip like that for every change, I made it very easy to run the code. That could have the additional benefit of figuring out what exactly caused it instead of throwing a whole bunch of changes at it all at once.

**Comment by hughsando** [comment]
Here is a version that crashes consistently in the same spot, relatively quickly:

```haxe

class TestT {
	public var array: Array<Int>;
	public var _t: Int = 0;
   static var cycle = 0;

	public function new() {
		var size: Int = 6 + (cycle % 50);
      cycle = (cycle+17)%50;
		array = [for(i in 0...size) 256];
		_t = 0;
	}

	public function init() {
		for (i in 0...10) {
			array = [];
			array.push(1280);
			array.push(800);
		}
	}
}

class Main {
	public static function main() {
		//init a lot of data
		tests = [];
		for(i in 0...1400) {
			var a = new TestT();
			a.init();
			tests.push(a);
		}

		while (true) {
			update();
		}
	}

	static var array: Array<Float> = [];

	static function update(): Void {
		//just some random calculations and allocations to take some time
		array = [];
		for(i in 0...500) {
			array.push( (i*17312) % 1280 );
			array.push( (i*191919) % 800 );
		}

		allocate_bunch();
	}

	//simple array of poly object
	//I use something like that in my game so here it is
	static var tests: Array<TestT>;

	@:nativeStaticExtension
	extern static function removeAt<T>(ioDestArray:Array<T>, inIndex:Int):Void;


	static function allocate_bunch() {
		//bunch of allocations that we are not using
		for(i in 0...250) {
			var a = new TestT();
			a.init();
		}
		
		//a lot of remove and push
		// crashes on push() -> EnsureSize or something like that
		for(i in 0...1000) {
			removeAt(tests,  (i*1231) % tests.length);
			removeAt(tests,  (i*777) % tests.length);

			var n = new TestT();
			n.init();
			tests.push(n);

			var n2 = new TestT();
			n2.init();
			tests.push(n2);
		}
	}
}
```

**Comment by sibest** [comment]
To make it crash about instantly:

while (true) {
	update();
	cpp.vm.Gc.run(false);
}

**Comment by sibest** [comment]
To make it crash almost instantly open Immix.cpp and in GetFreeBlock
add a forced collect just after while (true)
      	
     ```
 	#ifndef HXCPP_SINGLE_THREADED_APP
         hx::EnterGCFreeZone();
         gThreadStateChangeLock->Lock();
         hx::ExitGCFreeZoneLocked();
         #endif
         
         Collect(false,false,true,true);
            
         #ifndef HXCPP_SINGLE_THREADED_APP
         gThreadStateChangeLock->Unlock();
         #endif
```

**Comment by sibest** [comment]
@hughsando To make it crash almost instantly add this block of code
```
      	if (mAllBlocks.size() > 0)
      	{
	      	#ifndef HXCPP_SINGLE_THREADED_APP
	         hx::EnterGCFreeZone();
	         gThreadStateChangeLock->Lock();
	         hx::ExitGCFreeZoneLocked();
	         #endif
	         
	         inAlloc->SetupStack();
	         Collect(false,false,true,true);
	            
	         #ifndef HXCPP_SINGLE_THREADED_APP
	         gThreadStateChangeLock->Unlock();
	         #endif
         } 
```

At the top of 
   BlockDataInfo *GetFreeBlock(int inRequiredBytes, hx::ImmixAllocator *inAlloc)
   {

**Comment by sibest** [comment]
Keeps crashing with my test code

**Comment by hughsando** [comment]
Are you saying the fix does not work? There was a follow-up for fix non-generational code.
If there is still an issue, can you post some test code?

**Comment by sibest** [comment]
Yes it doesn't work. To make it crash you have to open Immix.php and add the lines i've posted before then rebuild. As you will know, it forces a collection each time GetFreeBlock is called, just to stress-test the Garbage Collector.

It crashes here
array = [for(i in 0...size) 256];
which in cpp is expanded as:
```
HXLINE(  14)		::Array< int > _g = ::Array_obj< int >::__new(0);
HXDLIN(  14)		{
HXLINE(  14)			int _g2 = 0;
HXDLIN(  14)			int _g1 = size;
HXDLIN(  14)			while((_g2 < _g1)){
HXLINE(  14)				_g2 = (_g2 + 1);
HXDLIN(  14)				int i = (_g2 - 1);
HXDLIN(  14)				_g->push(256);
            			}
            		}
HXDLIN(  14)		this->_hx_set_array(HX_CTX, _g);
HXLINE(  15)		this->_t = 0;
```
It does crash because the array is in the stack until the elements are added into it. Infact, if you rewrite the code as this:
array = []; for (i in 0...size) array.push(256);

It doesn't crash. Because it sets the member variable "array" before the cycle.  

I strongly suggest that MarkConservative is not finding the ptr of the array in the stack.

**Comment by sibest** [comment]
Actually my game crashes almost instantly with those new changes

**Comment by RobDangerous** [comment]
Also super-thanks to sibest for the additional fix!
