### ISSUE TITLE
HXCPP_GC_GENERATIONAL crash with Arrays and new Objects not marked on local allocator

### ISSUE THREAD

**Issue by sibest** [HaxeFoundation/hxcpp#913]
public function test()
    {
         var atlasTexture : Array<String> = ['collection,mipmap:false,scalable:false',
        'graphics,scalable:false,mipmap:true',
        'fronts0,scalable:false,mipmap:true',
        'fronts1,scalable:false,mipmap:true',
        'theme,scalable:false,mipmap:true',
        'logo,scalable:false,mipmap:true',
        'bg,scalable:false,mipmap:true',
        'page,scalable:false,mipmap:true',
        'bgeffect,scalable:false,mipmap:true',
        'flags,scalable:false',
        'bigdisp,scalable:false,mipmap:false',
        'disp,scalable:false,mipmap:false',
        'transitions,scalable:false,mipmap:false',
        'home,mipmap:false,scalable:false',
        'perl1,mipmap:false,scalable:false',
        'fire,mipmap:false,scalable:false'];

        //var loaded : Int = atlasTexture.length;

        for (texData in atlasTexture)
        {

            trace(texData);
	    Gc.run (true);

        }
}

The array texData is disposed during the foreach, it should not. The program crashes because the Gc frees the array before the ending of the variable scope.

**Comment by sibest** [comment]
I'm trying to fix this, i've modified Object.hs
line 170 return ImmixAllocator::alloc(alloc, inSize, inContainer, inName); replaced with

`         hx::Object* obj = (hx::Object*)ImmixAllocator::alloc(alloc, inSize, inContainer, inName);
         ((unsigned char *)(obj))[ HX_ENDIAN_MARK_ID_BYTE] = hx::gByteMarkID;
         HX_OBJ_WB_NEW_MARKED_OBJECT(obj);`

**Comment by sibest** [comment]
var test = [];
       cpp.vm.Gc.run(false);
        trace(test);
        trace(test);
        
This simple code crashes with 
HXCPP_GC_GENERATIONAL

**Comment by sibest** [comment]
After a bit of debugging, the problem in my win64 environment is that MarkConservative doesn't catch the "test" pointer from stack. Any clue why this is happening ? I'm not familiar with your way to read the stack.

**Comment by hughsando** [comment]
So I am having trouble reproducing this.
I am trying:
```haxe
import cpp.vm.Gc;

class Test
{

   function new() {}

   public function test()
   {
        var atlasTexture : Array<String> = ['collection,mipmap:false,scalable:false',
       'graphics,scalable:false,mipmap:true',
       'fronts0,scalable:false,mipmap:true',
       'fronts1,scalable:false,mipmap:true',
       'theme,scalable:false,mipmap:true',
       'logo,scalable:false,mipmap:true',
       'bg,scalable:false,mipmap:true',
       'page,scalable:false,mipmap:true',
       'bgeffect,scalable:false,mipmap:true',
       'flags,scalable:false',
       'bigdisp,scalable:false,mipmap:false',
       'disp,scalable:false,mipmap:false',
       'transitions,scalable:false,mipmap:false',
       'home,mipmap:false,scalable:false',
       'perl1,mipmap:false,scalable:false',
       'fire,mipmap:false,scalable:false'];

       //var loaded : Int = atlasTexture.length;


       for (texData in atlasTexture)
       {
          trace(texData);
          Gc.run (true);
       }
   }

   public static function t2()
   {
      var test = [];
      cpp.vm.Gc.run(false);
      trace(test);
      trace(test);
   }

   public static function main()
   {
      var test = [];
      cpp.vm.Gc.run(false);
      trace(test);
      trace(test);

     t2();

     var t= new Test();
     t.test();
     trace("ok");
   }

}
```
with `haxe -main Test -cpp cpp -D HXCPP_GC_GENERATIONAL -D HXCPP_M64`

Using the git version of hxcpp and a recent version of haxe on windows.

Stack scanning can be a bit of a black art, and bugs can be a little tricky to pin down.  Generally I first determine if the pointer is actually in the stack.  If so, why did I miss it?  If not, what has the compiler generated, and what do I need to do to find the pointer I need?  There are some built-in debugging options I can enable in the code to help.

You can enable an alternate scanning technique by uncommenting the `#define HXCPP_CAPTURE_SETJMP` line in GcRegCapture.h and see if that fixes the problem.

Generally, a complete example that shows the problem is the best way forward.

**Comment by sibest** [comment]
Well i'm trying to debug this thing,
`  public function new ()
    {
        super();


        var r:String = 'stringhetta' + 'stringona';
        var s:String = 'stringhetta' + 'stringona';
        var t:String = 'stringhetta' + 'stringona';
        var u:String = 'stringhetta' + 'stringona';
        var v:String = 'stringhetta' + 'stringona';
        var z:String = 'stringhetta' + 'stringona';
        trace('R='+r);
        cpp.vm.Gc.run(false);
        trace(r);
        trace(r);
        trace(r);
        trace(r);
        trace(r);`

the output is
Main.hx:63: R=stringhettastringona
Main.hx:65: stringhe
Main.hx:66: stringhe
Main.hx:67: stringhe
Main.hx:68: stringhe
Main.hx:69: stringhe

As you can see **r** is released from the Gc, and then crashes. It's an empty project with openfl.

**Comment by sibest** [comment]
I've fixed the bug. It was happening because a 0 length alloc was on the nursery.

in GetEnclosingNurseryType
`               if (/*!size || */end > last)
                  return allocNone;`

Commenting the size check fixes the crash. Now I should debug what is asking for 0 bytes inside the nursery, since it probably causes high memory defrag which will lead to big memory leaks.

**Comment by sibest** [comment]
Adding `
      if (inSize == 0)
     	 return NULL;`

in CallAlloc fixes the bug and it seems NOT to cause any crash in my game.

**Comment by hughsando** [comment]
Yes, I guess it is sort-of legitimate to alloc zero bytes - would be interesting to see where this is happening though, and maybe fix that instead.  I think the best fix would be to make sure the size is at least 4 bytes - this way no null pointers and the loop will terminate correctly.  For normal haxe objects, this will happen because there will always be a vtable allocated, so the size will never be zero.

**Comment by sibest** [comment]
Is there any way to print the haxe stacktrace from Immx.cpp ?

**Comment by sibest** [comment]
I guess __hx_dump_stack

**Comment by sibest** [comment]
In your opinion, does HXCPP_GC_BIG_BLOCKS make the memory management worse with lot of fragmentation ?

**Comment by sibest** [comment]
Anyway i've fixed this issue with these changes:
`
   void *CallAlloc(int inSize,unsigned int inObjectFlags)
   {
       
      if (inSize == 0)
     	 return NULL;`

`void *InternalRealloc(void *inData,int inSize, bool inExpand)
{
   if (inData==0 || inSize == 0)
      return hx::InternalNew(inSize,false);`

Plus i've reduced IMMIX_LARGE_OBJ_SIZE to 1024 and disabled the large object recycle pool (i'm pretty sure OS can manage it better)

GENERATIONAL GC seems very stable now.

**Comment by sibest** [comment]
I've another question, 

```
         int scan = mRanges[h].start;
         if (inOffset<scan)
            break;
```

mRanges is ordered ? Shouldn't it be continue; instead of break? Thank you

**Comment by sibest** [comment]
One more question, if i change
`#define IMMIX_LINE_BITS    6`
to 6 bits (64byte per line) it crashes. Do I have to tweak any other define to make it working? Thank you
