### ISSUE TITLE
nonblocking mode of sockets is busted in many ways

### ISSUE THREAD

**Issue by bji** [HaxeFoundation/hxcpp#92]
nonblocking Sockets are nearly non-functional.  Looking just at the implementation in Socket.cpp:

- socket_send says that it will "Send up to [len] bytes ...", but if it is able to write less than that number of bytes because the write is partial and would block, it doesn't check for EWOULDBLOCK, it just immediately throws a blocking error.  Thus it can never actually send less than [len] bytes.

- socket_recv similarly says that it will "Read up to [len]" bytes, but similarly, it does not check for EWOULDBLOCK and throws an error if it can't read exactly [len] bytes.

This means that just about any read or write operation on nonblocking Sockets will always fail.

I haven't looked at the rest of the implementation but it's likely that it suffers from many other issues.

**Comment by TheSHEEEP** [comment]
Is this fixed by now or is this still a problem?

**Comment by kiroukou** [comment]
It would be great to improve the documentation about this.
It's quite hard to get into that API which currently has no documentation or examples, and which does have some shortcuts with specific behaviours... (read/write in non blocking mode).

Thomas

**Comment by hughsando** [comment]
I've shifted this over to the haxe repo, unless there is something I need to do on the hxcpp side.
https://github.com/HaxeFoundation/haxe/issues/5131
