### ISSUE TITLE
Bytes -> String -> Bytes conversion not repeatable result

### ISSUE THREAD

**Issue by lleqsnoom** [HaxeFoundation/hxcpp#923]
var data = new haxe.io.BytesBuffer();
        data.addByte(88);
        data.addByte(88);
        data.addByte(88);
        for(i in 0...1024){
            data.addByte(i%256);
        }
        data.addByte(88);
        data.addByte(88);
        data.addByte(88);
        var bytes0 = data.getBytes();
        var str1 = bytes0.toString();
        var bytes1 = Bytes.ofString(str1);
        trace(bytes0.length, bytes1.length);

bytes0.length and bytes1.length is not equal in haxe 4.x.x
the same code works fine in haxe 3.x.x

**Comment by RealyUniqueName** [comment]
Haxe 4 moved to unicode strings.
Since your Bytes instance does not contain a valid unicode string `Bytes.toString()` may return a string, which is not equivalent to the original bytes.
If you don't care about unicode, then you can try disabling unicode strings with `-D disable_unicode_strings`.

**Comment by RealyUniqueName** [comment]
Also, your bytes contain zero-byte, which may be treated as the end of string.

**Comment by hughsando** [comment]
This is now treating the bytes as a utf8 string, which then contains invalid characters (possibly in addition to the null character), so the cycle does not work.  Bytes and Strings are not logically interchangeable anymore.  If you are looking to pass the bytes off as an external string, you can get the pointer directly from the Bytes object. 
I will wait for haxe specification test to fix this one.
