### ISSUE TITLE
Memory allocate error when create array

### ISSUE THREAD

**Issue by maz-1** [HaxeFoundation/hxcpp#939]
Environment: VS 2019, haxe 4.1.4, hxcpp 4.1.15, x64 build
I compiled [verb](https://www.github.com/pboyer/verb) into static library, find out that I can't create any kind of array with given size.

code I tested:
```
    #include <chrono>
    #include <thread>
    #include <iostream>
    using namespace std;
    #define _USE_MATH_DEFINES 
    #include <math.h>
    #include <limits>
    #include <omp.h>
    #include <limits>
    #include <string>
    #include <sstream>
    #include <algorithm>  // std::sort, std::stable_sort
    #include <deque>
    
    // haxe and verb
    #ifdef WIN32
	    #define HX_WINDOWS
	    #ifdef _WIN64
		    #define HXCPP_M64
	    #endif
    #endif
    //#ifdef NDEBUG
	    #define NO_HXCPP_DEBUG
    //#else
    //#endif
    #include <HxcppConfig-19.h>
    //#include <hxcpp.h>
    #include <verb/Verb.h>
    #include <verb/geom/NurbsCurve.h>
    
    int main (int argc, char** argv)
    {
      auto arrPoints = Array<double>(4, 4);
      std::cout << "booyah" << std::endl;
      return(0);
    }
```
![scrshot](https://user-images.githubusercontent.com/5277060/102894226-bf00ff80-449d-11eb-9493-c88b4fa4f25a.PNG)

**Comment by maz-1** [comment]
I tried to create an empty array and the resize/reserve, crash as well

**Comment by Aurel300** [comment]
@maz-1 Why close? Was it an issue in your code?

**Comment by maz-1** [comment]
> @maz-1 Why close? Was it an issue in your code?

never mind, I do need to add some code to the beginning. Followed [this](https://github.com/HaxeFoundation/hxcpp/issues/585) and no more crash. Sorry if i made any confusion.
