### ISSUE TITLE
On Android HX_HAS_ATOMIC is missing ...

### ISSUE THREAD

**Issue by sibest** [HaxeFoundation/hxcpp#944]
in file include/hx/Thread.h

`#if defined(ANDROID)

#if (HXCPP_ANDROID_PLATFORM>=16)
// Nice one, google, no one was using that.
#define __ATOMIC_INLINE__ static __inline__ __attribute__((always_inline))
// returns 0=exchange took place, 1=not
__ATOMIC_INLINE__ int __atomic_cmpxchg(int old, int _new, volatile int *ptr)
   { return __sync_val_compare_and_swap(ptr, old, _new) != old; }
__ATOMIC_INLINE__ int __atomic_dec(volatile int *ptr) { return __sync_fetch_and_sub (ptr, 1); }
__ATOMIC_INLINE__ int __atomic_inc(volatile int *ptr) { return __sync_fetch_and_add (ptr, 1); }
#else
#include <sys/atomics.h>
#endif

#define HX_HAS_ATOMIC 1 // missing this line <-------------------
`

**Comment by hughsando** [comment]
This has been added.  Thanks.
