### ISSUE TITLE
can I generate c++ without compiling it? 

### ISSUE THREAD

**Issue by NQNStudios** [HaxeFoundation/hxcpp#955]
I'm having an especially hard time getting my program to compile through `hxcpp` because I need to build it with a toolchain that isn't built-in, and I'm struggling to figure out how to define my own toolchain with the sparse documentation on how to put together build.xml files.

Right now, it seems like I would have an easier time making Haxe just generate C++ files, and letting me compile them myself directly. Is that possible?

**Comment by Aurel300** [comment]
Does [`-D no-compilation`](https://haxe.org/manual/target-cpp-defines.html#code-generation) do the trick?

**Comment by NQNStudios** [comment]
yes! thanks

**Comment by hughsando** [comment]
That is correct.
Here is an example of defining a toolchain: https://github.com/hughsando/winrpi

The basic idea is to set the toolchain define, `-D toolchain=WinRPi`  and then have a toolchain file of the correct name in the toolchain path.  The toolchain path is the same as the haxe path, so all this is nicely accomplished by having a haxelib and an extraParms.hxml.  The developer can then just use `-lib mytoolchainlib` to use your toolchain.
