### ISSUE TITLE
Function types being converted to dynamic types?

### ISSUE THREAD

**Issue by paulsgcross** [HaxeFoundation/hxcpp#996]
Out of curiosity, why does Haxe transform function types into dynamics (shown [here](https://imgur.com/a/NxXJ7iM)) after compilation?

What are the performance implications of doing so and is there any way to avoid this?

I noticed while using [HxScout ](https://hxscout.com/) that when using function types for callbacks, i.e. `var func : Float -> Void;` and then calling `func(3.0);` that the memory footprint showed the creation of a 'Float' object each frame which then needed to be garbage collected which seemed odd to me given it is a primitive type. Something I am missing about function types?

**Comment by Simn** [comment]
Please refer to community.haxe.org for questions like this.
